# Week 10 — dSprites-only OOD Steering Notebook

## Goal
Test whether a local kNN latent steering recipe learned on **in-domain dSprites** generalizes to a small **out-of-distribution** split.

## Experimental design
We use dSprites factors:
- `shape ∈ {0,1,2}`
- `scale ∈ {0,...,5}`
- `orientation ∈ {0,...,39}`
- `posX ∈ {0,...,31}`
- `posY ∈ {0,...,31}`

We train on a subset of **orientations 0..19** and evaluate on:
- **ID test**: unseen groups, but still orientations `0..19`
- **OOD test**: unseen groups with held-out orientations `20..39`

In [1]:
%pip install -q torch torchvision matplotlib pandas tqdm scikit-learn scipy

Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import json
import math
import time
import random
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, TensorDataset
from tqdm import tqdm
from IPython.display import display, Image

In [3]:
import warnings
warnings.filterwarnings("ignore", message=".*can only test a child process.*")
warnings.filterwarnings("ignore", category=FutureWarning)

In [4]:
cfg: Dict[str, Any] = {
    "seed": 42,
    "device": "cuda",

    "paths": {
        "dsprites_npz_path": "/kaggle/input/datasets/galievilyas/dsprits/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz",
        "run_root": "runs",
    },

    "data": {
        # OOD split = held-out orientations
        "train_orientations": list(range(0, 20)),
        "ood_orientations": list(range(20, 40)),

        # group = (shape, orientation, posX, posY), each selected group contributes all 6 scales
        "train_groups": 3500,
        "val_groups": 600,
        "id_test_groups": 800,
        "ood_test_groups": 800,
    },

    "loader": {
        "batch_size": 128,
        "num_workers": 0,
        "pin_memory": True,
    },

    "vae": {
        "latent_dim": 24,
        "base_channels": 32,
        "epochs": 30,
        "lr": 8e-4,
        "beta": 0.7,
        "beta_warmup_epochs": 8,
        "free_bits": 0.02,
        "weight_decay": 1e-5,
        "grad_clip": 1.0,
        "recon": "bce",  # "bce" or "mse"
    },

    "heads": {
        "epochs": 12,
        "lr": 2e-3,
        "batch_size": 512,
    },

    "steering": {
        "method": "local_knn",
        "local_k": 64,
        "same_shape_only": True,
        "distance_eps": 1e-6,
        "alpha_grid": [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0],
        "tau_img_values": [3.0, 5.0, 7.0],
        "tau_shape_conf": 0.20,
        "lambda_img": 0.06,
        "lambda_shape": 0.80,
        "strict_shape_consistency": True,
    },

    "preview": {
        "n_samples": 8,
    },

    "notes": {
        "experiment_name": "week10_dsprites_ood_local_knn",
    },
}

cfg

{'seed': 42,
 'device': 'cuda',
 'paths': {'dsprites_npz_path': '/kaggle/input/datasets/galievilyas/dsprits/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz',
  'run_root': 'runs'},
 'data': {'train_orientations': [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19],
  'ood_orientations': [20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39],
  'train_groups': 3500,
  'val_groups': 600,
  'id_test_groups': 800,
  'ood_test_groups': 800},
 'loader': {'batch_size': 128, 'num_workers': 0, 'pin_memory': True},
 'vae': {'latent_dim': 24,
  'base_channels': 32,
  'epochs': 30,
  'lr': 0.0008,
  'beta': 0.7,
  'beta_warmup_epochs': 8,
  'free_bits': 0.02,
  'weight_decay': 1e-05,
  'grad_clip': 1.0,
  'recon': 'bce'},
 'heads': {'epochs': 12, 'lr': 0.002, 'batch_size': 512},
 'steering': {'method': 'local_knn',
  'local_k': 64,
  'same_shape_only': True,
  'distance_eps': 1e-06,
  'alpha_grid': [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0],
  'tau_img_values': [3.0, 5.0, 7.0],
  'tau_shape_conf': 0.2,
  'lambda_img': 0.06,
  'lambda_shape': 0.8,
  'strict_shape_consistency': True},
 'preview': {'n_samples': 8},
 'notes': {'experiment_name': 'week10_dsprites_ood_local_knn'}}

In [5]:
# helpers
def get_device(name: str) -> torch.device:
    if name == "cuda" and torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def seed_worker(worker_id: int) -> None:
    worker_seed = (torch.initial_seed() + worker_id) % (2**32)
    np.random.seed(worker_seed)
    random.seed(worker_seed)

def save_json(path: str, obj: dict) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)

def make_run_dir(root: str, tag: str) -> str:
    stamp = time.strftime("%Y%m%d_%H%M%S")
    path = Path(root) / f"{stamp}_{tag}"
    (path / "plots").mkdir(parents=True, exist_ok=True)
    (path / "tables").mkdir(parents=True, exist_ok=True)
    (path / "checkpoints").mkdir(parents=True, exist_ok=True)
    return str(path)

def require_manual_path(value: str, label: str) -> str:
    value = str(value).strip()
    if value == "" or value.upper().startswith("TODO"):
        raise ValueError(f"Fill the TODO path for {label} before running the notebook.")
    path = Path(value).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"Path for {label} does not exist: {path}")
    return str(path)

def normalize_direction(v: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    v = np.asarray(v, dtype=np.float32)
    n = float(np.linalg.norm(v))
    return v / max(n, eps)

def encode_mu(model: nn.Module, x: torch.Tensor) -> torch.Tensor:
    mu, _ = model.enc(x)
    return mu

def decode_sigmoid(model: nn.Module, z: torch.Tensor) -> torch.Tensor:
    return torch.sigmoid(model.dec(z))

def load_checkpoint_state(model: nn.Module, checkpoint_path: str, device: torch.device) -> nn.Module:
    payload = torch.load(checkpoint_path, map_location=device)
    state = payload["model"] if isinstance(payload, dict) and "model" in payload else payload
    model.load_state_dict(state)
    return model

#  dSprites dataset
class DSpritesSubset(Dataset):
    def __init__(self, npz_path: str, indices: np.ndarray):
        data = np.load(npz_path, allow_pickle=True, mmap_mode="r")
        self.imgs = data["imgs"]
        self.classes = data["latents_classes"]
        self.indices = np.asarray(indices, dtype=np.int64)

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, i: int):
        idx = int(self.indices[i])
        x = self.imgs[idx].astype(np.float32)[None, ...]
        c = self.classes[idx].astype(np.int64)
        return torch.from_numpy(x), torch.from_numpy(c)

def build_group_splits(
        npz_path: str,
        train_orientations: List[int],
        ood_orientations: List[int],
        train_groups: int,
        val_groups: int,
        id_test_groups: int,
        ood_test_groups: int,
        seed: int = 42,
    ) -> Dict[str, np.ndarray]:

    data = np.load(npz_path, allow_pickle=True, mmap_mode="r")
    classes = np.asarray(data["latents_classes"], dtype=np.int64)

    # factor order: color, shape, scale, orientation, posX, posY
    group_factors = classes[:, [1, 3, 4, 5]]   # shape, orientation, posX, posY
    uniq_groups, inverse = np.unique(group_factors, axis=0, return_inverse=True)

    train_mask = np.isin(uniq_groups[:, 1], np.asarray(train_orientations, dtype=np.int64))
    ood_mask = np.isin(uniq_groups[:, 1], np.asarray(ood_orientations, dtype=np.int64))

    train_pool = np.where(train_mask)[0]
    ood_pool = np.where(ood_mask)[0]

    rng = np.random.default_rng(seed)
    rng.shuffle(train_pool)
    rng.shuffle(ood_pool)

    need_train = int(train_groups) + int(val_groups) + int(id_test_groups)
    if need_train > len(train_pool):
        raise ValueError(f"Requested {need_train} ID groups, but only {len(train_pool)} are available.")
    if int(ood_test_groups) > len(ood_pool):
        raise ValueError(f"Requested {ood_test_groups} OOD groups, but only {len(ood_pool)} are available.")

    g_train = train_pool[: int(train_groups)]
    g_val = train_pool[int(train_groups): int(train_groups) + int(val_groups)]
    g_id_test = train_pool[int(train_groups) + int(val_groups): need_train]
    g_ood_test = ood_pool[: int(ood_test_groups)]

    def group_ids_to_indices(group_ids: np.ndarray) -> np.ndarray:
        return np.where(np.isin(inverse, group_ids))[0].astype(np.int64)

    out = {
        "train_idx": group_ids_to_indices(g_train),
        "val_idx": group_ids_to_indices(g_val),
        "id_test_idx": group_ids_to_indices(g_id_test),
        "ood_test_idx": group_ids_to_indices(g_ood_test),
        "meta": {
            "n_unique_groups": int(len(uniq_groups)),
            "n_train_pool_groups": int(len(train_pool)),
            "n_ood_pool_groups": int(len(ood_pool)),
        },
    }
    return out

def summarize_split(indices: np.ndarray, name: str) -> pd.DataFrame:
    return pd.DataFrame([{
        "split": name,
        "n_samples": int(len(indices)),
        "n_groups_approx": int(len(indices) // 6),
        }
    ]
    )

In [6]:
# models
class ResidualBlock(nn.Module):
    def __init__(self, channels: int, groups: int = 8):
        super().__init__()
        g = max(1, min(groups, channels))
        while channels % g != 0 and g > 1:
            g -= 1
        self.block = nn.Sequential(
            nn.Conv2d(channels, channels, 3, padding=1, bias=False),
            nn.GroupNorm(g, channels),
            nn.SiLU(inplace=True),
            nn.Conv2d(channels, channels, 3, padding=1, bias=False),
            nn.GroupNorm(g, channels),
        )
        self.act = nn.SiLU(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(x + self.block(x))

class DownBlock(nn.Module):
    def __init__(self, in_ch: int, out_ch: int):
        super().__init__()
        g = max(1, min(8, out_ch))
        while out_ch % g != 0 and g > 1:
            g -= 1
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 4, stride=2, padding=1, bias=False),
            nn.GroupNorm(g, out_ch),
            nn.SiLU(inplace=True),
            ResidualBlock(out_ch, groups=g),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)

class UpBlock(nn.Module):
    def __init__(self, in_ch: int, out_ch: int):
        super().__init__()
        g = max(1, min(8, out_ch))
        while out_ch % g != 0 and g > 1:
            g -= 1
        self.block = nn.Sequential(
            nn.Upsample(scale_factor=2, mode="nearest"),
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.GroupNorm(g, out_ch),
            nn.SiLU(inplace=True),
            ResidualBlock(out_ch, groups=g),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)

class DSpritesEncoder(nn.Module):
    def __init__(self, latent_dim: int, base_channels: int = 32):
        super().__init__()
        c1, c2, c3, c4 = base_channels, base_channels * 2, base_channels * 4, base_channels * 8
        self.stem = nn.Sequential(
            nn.Conv2d(1, c1, 3, padding=1, bias=False),
            nn.GroupNorm(8 if c1 % 8 == 0 else 4, c1),
            nn.SiLU(inplace=True),
            ResidualBlock(c1),
        )
        self.net = nn.Sequential(
            DownBlock(c1, c2),   # 64 -> 32
            DownBlock(c2, c3),   # 32 -> 16
            DownBlock(c3, c4),   # 16 -> 8
            DownBlock(c4, c4),   # 8 -> 4
        )
        self.fc_mu = nn.Linear(c4 * 4 * 4, latent_dim)
        self.fc_lv = nn.Linear(c4 * 4 * 4, latent_dim)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        h = self.net(self.stem(x)).flatten(1)
        return self.fc_mu(h), self.fc_lv(h)

class DSpritesDecoder(nn.Module):
    def __init__(self, latent_dim: int, base_channels: int = 32):
        super().__init__()
        c1, c2, c3, c4 = base_channels, base_channels * 2, base_channels * 4, base_channels * 8
        self.fc = nn.Linear(latent_dim, c4 * 4 * 4)
        self.net = nn.Sequential(
            ResidualBlock(c4),
            UpBlock(c4, c4),     # 4 -> 8
            UpBlock(c4, c3),     # 8 -> 16
            UpBlock(c3, c2),     # 16 -> 32
            UpBlock(c2, c1),     # 32 -> 64
            nn.Conv2d(c1, 1, 3, padding=1),
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        c4 = self.fc.out_features // (4 * 4)
        h = self.fc(z).view(z.size(0), c4, 4, 4)
        return self.net(h)

class DSpritesVAE(nn.Module):
    def __init__(self, latent_dim: int, base_channels: int = 32):
        super().__init__()
        self.enc = DSpritesEncoder(latent_dim, base_channels=base_channels)
        self.dec = DSpritesDecoder(latent_dim, base_channels=base_channels)

    def reparam(self, mu: torch.Tensor, lv: torch.Tensor) -> torch.Tensor:
        std = torch.exp(0.5 * lv)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x: torch.Tensor):
        mu, lv = self.enc(x)
        z = self.reparam(mu, lv)
        x_logits = self.dec(z)
        return x_logits, mu, lv

class ShapeHead(nn.Module):
    def __init__(self, in_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 128),
            nn.SiLU(inplace=True),
            nn.Dropout(0.10),
            nn.Linear(128, 64),
            nn.SiLU(inplace=True),
            nn.Linear(64, 3),
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.net(z)

class ScaleHead(nn.Module):
    def __init__(self, in_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, 128),
            nn.SiLU(inplace=True),
            nn.Dropout(0.10),
            nn.Linear(128, 64),
            nn.SiLU(inplace=True),
            nn.Linear(64, 6),
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.net(z)


def dsprites_vae_loss(
        x: torch.Tensor,
        x_logits: torch.Tensor,
        mu: torch.Tensor,
        lv: torch.Tensor,
        beta: float = 1.0,
        recon: str = "bce",
        free_bits: float = 0.0,
    ):
    if recon == "bce":
        rec = F.binary_cross_entropy_with_logits(x_logits, x, reduction="sum") / x.size(0)
    elif recon == "mse":
        rec = F.mse_loss(torch.sigmoid(x_logits), x, reduction="sum") / x.size(0)
    else:
        raise ValueError(f"unknown recon: {recon}")

    kl_per_dim = 0.5 * (mu.pow(2) + lv.exp() - 1.0 - lv)
    if free_bits > 0:
        kl = kl_per_dim.mean(dim=0).clamp_min(float(free_bits)).sum()
    else:
        kl = kl_per_dim.sum(dim=1).mean()

    return rec + beta * kl, rec, kl


@torch.no_grad()
def encode_dataset(model: nn.Module, loader: DataLoader, device: torch.device) -> Tuple[np.ndarray, np.ndarray]:
    zs, classes = [], []
    model.eval()
    for x, c in tqdm(loader, desc="encode split", leave=False):
        x = x.to(device, non_blocking=True)
        z = encode_mu(model, x)
        zs.append(z.cpu().numpy())
        classes.append(c.numpy())
    return np.concatenate(zs, axis=0), np.concatenate(classes, axis=0)


def build_latent_loader(z: np.ndarray, y: np.ndarray, batch_size: int, shuffle: bool) -> DataLoader:
    ds = TensorDataset(torch.from_numpy(z).float(), torch.from_numpy(y).long())
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)


def train_dsprites_vae(
        train_loader: DataLoader,
        val_loader: DataLoader,
        run_dir: str,
        latent_dim: int,
        base_channels: int,
        epochs: int,
        lr: float,
        beta: float,
        beta_warmup_epochs: int,
        free_bits: float,
        weight_decay: float,
        grad_clip: float,
        recon: str,
        device: torch.device,
    ) -> Tuple[nn.Module, pd.DataFrame]:

    model = DSpritesVAE(latent_dim, base_channels=base_channels).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=max(1, int(epochs)), eta_min=lr * 0.1)

    rows = []
    best_val = float("inf")
    best_path = str(Path(run_dir) / "checkpoints" / "dsprites_vae_best.pt")

    for ep in range(1, int(epochs) + 1):
        beta_t = float(beta) * min(1.0, ep / max(1, int(beta_warmup_epochs)))

        model.train()
        tr_loss = tr_rec = tr_kl = 0.0
        n_tr = 0

        for x, _ in tqdm(train_loader, desc=f"VAE train ep{ep}", leave=False):
            x = x.to(device, non_blocking=True)
            opt.zero_grad(set_to_none=True)
            x_logits, mu, lv = model(x)
            loss, rec, kl = dsprites_vae_loss(
                x, x_logits, mu, lv,
                beta=beta_t,
                recon=recon,
                free_bits=free_bits,
            )
            loss.backward()
            if grad_clip and grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()

            bs = x.size(0)
            n_tr += bs
            tr_loss += float(loss.item()) * bs
            tr_rec += float(rec.item()) * bs
            tr_kl += float(kl.item()) * bs

        model.eval()
        va_loss = va_rec = va_kl = 0.0
        n_va = 0
        with torch.no_grad():
            for x, _ in tqdm(val_loader, desc=f"VAE val ep{ep}", leave=False):
                x = x.to(device, non_blocking=True)
                x_logits, mu, lv = model(x)
                loss, rec, kl = dsprites_vae_loss(
                    x, x_logits, mu, lv,
                    beta=beta_t,
                    recon=recon,
                    free_bits=free_bits,
                )
                bs = x.size(0)
                n_va += bs
                va_loss += float(loss.item()) * bs
                va_rec += float(rec.item()) * bs
                va_kl += float(kl.item()) * bs

        current_lr = opt.param_groups[0]["lr"]
        row = {
            "epoch": ep,
            "beta_t": beta_t,
            "lr": current_lr,
            "train_loss": tr_loss / max(1, n_tr),
            "train_rec": tr_rec / max(1, n_tr),
            "train_kl": tr_kl / max(1, n_tr),
            "val_loss": va_loss / max(1, n_va),
            "val_rec": va_rec / max(1, n_va),
            "val_kl": va_kl / max(1, n_va),
        }
        rows.append(row)

        if row["val_loss"] < best_val:
            best_val = row["val_loss"]
            torch.save({"model": model.state_dict(), "epoch": ep}, best_path)

        sched.step()

    best_model = DSpritesVAE(latent_dim, base_channels=base_channels).to(device)
    best_model = load_checkpoint_state(best_model, best_path, device)
    return best_model, pd.DataFrame(rows)


def train_latent_head(
        model: nn.Module,
        train_loader: DataLoader,
        val_loader: DataLoader,
        run_dir: str,
        name: str,
        epochs: int,
        lr: float,
        device: torch.device,
    ) -> Tuple[nn.Module, pd.DataFrame]:
    
    model = model.to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
    rows = []
    best_acc = -1.0
    best_path = str(Path(run_dir) / "checkpoints" / f"{name}_best.pt")

    for ep in range(1, int(epochs) + 1):
        model.train()
        tr_loss = 0.0
        n_tr = 0
        for z, y in train_loader:
            z = z.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            opt.zero_grad(set_to_none=True)
            logits = model(z)
            loss = F.cross_entropy(logits, y)
            loss.backward()
            opt.step()

            bs = z.size(0)
            n_tr += bs
            tr_loss += float(loss.item()) * bs

        model.eval()
        va_loss = 0.0
        correct = 0.0
        n_va = 0
        with torch.no_grad():
            for z, y in val_loader:
                z = z.to(device, non_blocking=True)
                y = y.to(device, non_blocking=True)
                logits = model(z)
                loss = F.cross_entropy(logits, y)
                bs = z.size(0)
                n_va += bs
                va_loss += float(loss.item()) * bs
                correct += float((logits.argmax(dim=1) == y).float().sum().item())

        acc = correct / max(1, n_va)
        rows.append({
            "epoch": ep,
            "train_loss": tr_loss / max(1, n_tr),
            "val_loss": va_loss / max(1, n_va),
            "val_acc": acc,
        })

        if acc > best_acc:
            best_acc = acc
            torch.save({"model": model.state_dict(), "epoch": ep}, best_path)

    if isinstance(model, ShapeHead):
        fresh = ShapeHead(model.net[0].in_features).to(device)
    elif isinstance(model, ScaleHead):
        fresh = ScaleHead(model.net[0].in_features).to(device)
    else:
        raise TypeError("Unsupported head type.")
    fresh = load_checkpoint_state(fresh, best_path, device)
    return fresh, pd.DataFrame(rows)


@torch.no_grad()
def evaluate_head(model: nn.Module, loader: DataLoader, device: torch.device, label_name: str, split_name: str) -> pd.DataFrame:
    correct = 0.0
    n = 0
    rows = []
    for z, y in loader:
        z = z.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        logits = model(z)
        pred = logits.argmax(dim=1)
        correct += float((pred == y).float().sum().item())
        n += y.numel()
    rows.append({
        "split": split_name,
        "target": label_name,
        "acc": correct / max(1, n),
        "n": int(n),
    })
    return pd.DataFrame(rows)

In [7]:
# steering
def expected_scale_from_logits(logits: torch.Tensor) -> torch.Tensor:
    p = torch.softmax(logits, dim=1)
    vals = torch.arange(logits.size(1), device=logits.device, dtype=logits.dtype)
    return (p * vals.view(1, -1)).sum(dim=1)


def build_local_scale_bank(z_train: np.ndarray, classes_train: np.ndarray) -> Dict[str, Any]:
    """
    local bank of adjacent-scale deltas.
    Each bank element is:
      - anchor = midpoint between z(scale=s) and z(scale=s+1)
      - delta = z(scale=s+1) - z(scale=s)
      - shape = shape id, used for shape-conditioned local lookup
    """
    groups: Dict[Tuple[int, int, int, int], Dict[int, np.ndarray]] = {}
    for z, c in zip(z_train, classes_train):
        key = (int(c[1]), int(c[3]), int(c[4]), int(c[5]))  # shape, orientation, posX, posY
        scale = int(c[2])
        groups.setdefault(key, {})[scale] = np.asarray(z, dtype=np.float32)

    anchors: List[np.ndarray] = []
    deltas: List[np.ndarray] = []
    shapes: List[int] = []
    pair_scales: List[int] = []

    for (shape, _, _, _), g in groups.items():
        for s in range(5):
            if s in g and (s + 1) in g:
                z0 = g[s]
                z1 = g[s + 1]
                anchors.append(0.5 * (z0 + z1))
                deltas.append(z1 - z0)
                shapes.append(int(shape))
                pair_scales.append(int(s))

    if len(deltas) == 0:
        raise RuntimeError("No adjacent scale pairs found in the training split.")

    anchors_arr = np.stack(anchors, axis=0).astype(np.float32)
    deltas_arr = np.stack(deltas, axis=0).astype(np.float32)
    shapes_arr = np.asarray(shapes, dtype=np.int64)
    pair_scales_arr = np.asarray(pair_scales, dtype=np.int64)

    shape_to_indices = {
        int(s): np.where(shapes_arr == s)[0].astype(np.int64)
        for s in np.unique(shapes_arr)
    }

    return {
        "anchors": anchors_arr,
        "deltas": deltas_arr,
        "shapes": shapes_arr,
        "pair_scales": pair_scales_arr,
        "shape_to_indices": shape_to_indices,
        "n_pairs": int(len(deltas_arr)),
    }


def local_direction_batch(
        z_query: torch.Tensor,
        shape_query: torch.Tensor,
        local_bank: Dict[str, Any],
        k: int = 64,
        same_shape_only: bool = True,
        distance_eps: float = 1e-6,
    ) -> torch.Tensor:

    z_np = z_query.detach().cpu().numpy().astype(np.float32)
    shape_np = shape_query.detach().cpu().numpy().astype(np.int64)

    anchors = local_bank["anchors"]
    deltas = local_bank["deltas"]
    shape_to_indices = local_bank["shape_to_indices"]
    all_indices = np.arange(len(anchors), dtype=np.int64)

    out = np.zeros_like(z_np, dtype=np.float32)

    for i, (z_i, shp_i) in enumerate(zip(z_np, shape_np)):
        if same_shape_only:
            cand = shape_to_indices.get(int(shp_i), all_indices)
            if cand.size == 0:
                cand = all_indices
        else:
            cand = all_indices

        diffs = anchors[cand] - z_i[None, :]
        dist2 = np.sum(diffs * diffs, axis=1)

        k_eff = max(1, min(int(k), int(cand.size)))
        if cand.size > k_eff:
            top_local = np.argpartition(dist2, kth=k_eff - 1)[:k_eff]
            use_idx = cand[top_local]
            use_dist2 = dist2[top_local]
        else:
            use_idx = cand
            use_dist2 = dist2

        weights = 1.0 / np.sqrt(use_dist2 + float(distance_eps))
        delta = (weights[:, None] * deltas[use_idx]).sum(axis=0) / max(float(weights.sum()), float(distance_eps))
        out[i] = normalize_direction(delta, eps=float(distance_eps))

    return torch.from_numpy(out).to(device=z_query.device, dtype=z_query.dtype)


@torch.no_grad()
def sweep_fixed_alpha(
        vae: nn.Module,
        shape_head: nn.Module,
        scale_head: nn.Module,
        loader: DataLoader,
        local_bank: Dict[str, Any],
        alpha_grid: List[float],
        tau_shape_conf: float,
        lambda_img: float,
        lambda_shape: float,
        strict_shape_consistency: bool,
        split_name: str,
        device: torch.device,
        local_k: int = 64,
        same_shape_only: bool = True,
        distance_eps: float = 1e-6,
    ) -> pd.DataFrame:

    acc = {float(a): {
        "split": split_name,
        "alpha": float(a),
        "n": 0,
        "shape_acc_sum": 0.0,
        "shape_consistency_sum": 0.0,
        "scale_gain_sum": 0.0,
        "img_l2_sum": 0.0,
        "shape_conf_drop_sum": 0.0,
        "objective_sum": 0.0,
        "feasible_sum": 0.0,
    } for a in alpha_grid}

    for x, c in tqdm(loader, desc=f"fixed sweep [{split_name}]", leave=False):
        x = x.to(device, non_blocking=True)
        c = c.to(device, non_blocking=True)
        shape_true = c[:, 1]

        z = encode_mu(vae, x)
        x_rec = decode_sigmoid(vae, z)

        shape_logits_rec = shape_head(z)
        scale_logits_rec = scale_head(z)
        shape_pred_rec = shape_logits_rec.argmax(dim=1)
        shape_prob_rec = torch.softmax(shape_logits_rec, dim=1).gather(1, shape_pred_rec[:, None]).squeeze(1)
        exp_scale_rec = expected_scale_from_logits(scale_logits_rec)

        d_batch = local_direction_batch(
            z_query=z,
            shape_query=shape_pred_rec,
            local_bank=local_bank,
            k=local_k,
            same_shape_only=same_shape_only,
            distance_eps=distance_eps,
        )

        for alpha in alpha_grid:
            alpha = float(alpha)
            z_s = z + alpha * d_batch
            x_s = decode_sigmoid(vae, z_s)

            shape_logits_s = shape_head(z_s)
            scale_logits_s = scale_head(z_s)

            shape_pred_s = shape_logits_s.argmax(dim=1)
            shape_prob_s = torch.softmax(shape_logits_s, dim=1).gather(1, shape_pred_rec[:, None]).squeeze(1)
            exp_scale_s = expected_scale_from_logits(scale_logits_s)

            gain = exp_scale_s - exp_scale_rec
            img_l2 = torch.norm((x_s - x_rec).flatten(1), dim=1)
            conf_drop = (shape_prob_rec - shape_prob_s).clamp_min(0.0)

            shape_ok = shape_pred_s.eq(shape_true).float()
            shape_cons = shape_pred_s.eq(shape_pred_rec).float()
            feasible = (conf_drop <= float(tau_shape_conf))
            if strict_shape_consistency:
                feasible = feasible & shape_pred_s.eq(shape_pred_rec)

            objective = gain - float(lambda_img) * img_l2 - float(lambda_shape) * conf_drop

            row = acc[alpha]
            row["n"] += x.size(0)
            row["shape_acc_sum"] += float(shape_ok.sum().item())
            row["shape_consistency_sum"] += float(shape_cons.sum().item())
            row["scale_gain_sum"] += float(gain.sum().item())
            row["img_l2_sum"] += float(img_l2.sum().item())
            row["shape_conf_drop_sum"] += float(conf_drop.sum().item())
            row["objective_sum"] += float(objective.sum().item())
            row["feasible_sum"] += float(feasible.float().sum().item())

    rows = []
    for alpha in alpha_grid:
        row = dict(acc[float(alpha)])
        n = max(1, int(row.pop("n")))
        rows.append({
            "split": row["split"],
            "alpha": row["alpha"],
            "shape_acc": row["shape_acc_sum"] / n,
            "shape_consistency": row["shape_consistency_sum"] / n,
            "scale_gain": row["scale_gain_sum"] / n,
            "img_l2_to_recon": row["img_l2_sum"] / n,
            "shape_conf_drop": row["shape_conf_drop_sum"] / n,
            "objective": row["objective_sum"] / n,
            "feasible_rate": row["feasible_sum"] / n,
            "n": n,
        })
    return pd.DataFrame(rows)


@torch.no_grad()
def evaluate_auto_alpha(
        vae: nn.Module,
        shape_head: nn.Module,
        scale_head: nn.Module,
        loader: DataLoader,
        local_bank: Dict[str, Any],
        alpha_grid: List[float],
        tau_img_values: List[float],
        tau_shape_conf: float,
        lambda_img: float,
        lambda_shape: float,
        strict_shape_consistency: bool,
        split_name: str,
        device: torch.device,
        local_k: int = 64,
        same_shape_only: bool = True,
        distance_eps: float = 1e-6,
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:

    summary_rows = []
    sample_rows = []

    for tau_img in tau_img_values:
        summary_rows.append({
            "split": split_name,
            "tau_img": float(tau_img),
            "n": 0,
            "shape_acc_sum": 0.0,
            "shape_consistency_sum": 0.0,
            "scale_gain_sum": 0.0,
            "img_l2_sum": 0.0,
            "shape_conf_drop_sum": 0.0,
            "alpha_star_sum": 0.0,
            "nonzero_alpha_sum": 0.0,
            "objective_sum": 0.0,
        })

    tau_to_idx = {float(r["tau_img"]): i for i, r in enumerate(summary_rows)}
    global_idx = 0

    for x, c in tqdm(loader, desc=f"auto alpha [{split_name}]", leave=False):
        x = x.to(device, non_blocking=True)
        c = c.to(device, non_blocking=True)
        shape_true = c[:, 1]

        z = encode_mu(vae, x)
        x_rec = decode_sigmoid(vae, z)

        shape_logits_rec = shape_head(z)
        scale_logits_rec = scale_head(z)
        shape_pred_rec = shape_logits_rec.argmax(dim=1)
        shape_prob_rec = torch.softmax(shape_logits_rec, dim=1).gather(1, shape_pred_rec[:, None]).squeeze(1)
        exp_scale_rec = expected_scale_from_logits(scale_logits_rec)

        d_batch = local_direction_batch(
            z_query=z,
            shape_query=shape_pred_rec,
            local_bank=local_bank,
            k=local_k,
            same_shape_only=same_shape_only,
            distance_eps=distance_eps,
        )

        bs = x.size(0)

        for tau_img in tau_img_values:
            tau_img = float(tau_img)

            best_obj = torch.zeros(bs, device=device)
            best_alpha = torch.zeros(bs, device=device)
            best_shape_ok = shape_pred_rec.eq(shape_true).float()
            best_shape_cons = torch.ones(bs, device=device)
            best_gain = torch.zeros(bs, device=device)
            best_img_l2 = torch.zeros(bs, device=device)
            best_conf_drop = torch.zeros(bs, device=device)
            best_shape_pred = shape_pred_rec.clone()

            for alpha in alpha_grid:
                alpha = float(alpha)
                if alpha == 0.0:
                    continue

                z_s = z + alpha * d_batch
                x_s = decode_sigmoid(vae, z_s)

                shape_logits_s = shape_head(z_s)
                scale_logits_s = scale_head(z_s)

                shape_pred_s = shape_logits_s.argmax(dim=1)
                shape_prob_s = torch.softmax(shape_logits_s, dim=1).gather(1, shape_pred_rec[:, None]).squeeze(1)
                exp_scale_s = expected_scale_from_logits(scale_logits_s)

                gain = exp_scale_s - exp_scale_rec
                img_l2 = torch.norm((x_s - x_rec).flatten(1), dim=1)
                conf_drop = (shape_prob_rec - shape_prob_s).clamp_min(0.0)

                shape_ok = shape_pred_s.eq(shape_true)
                shape_cons = shape_pred_s.eq(shape_pred_rec)

                feasible = (img_l2 <= tau_img) & (conf_drop <= float(tau_shape_conf))
                if strict_shape_consistency:
                    feasible = feasible & shape_cons

                obj = gain - float(lambda_img) * img_l2 - float(lambda_shape) * conf_drop
                update = feasible & (obj > best_obj)

                best_obj = torch.where(update, obj, best_obj)
                best_alpha = torch.where(update, torch.full_like(best_alpha, alpha), best_alpha)
                best_shape_ok = torch.where(update, shape_ok.float(), best_shape_ok)
                best_shape_cons = torch.where(update, shape_cons.float(), best_shape_cons)
                best_gain = torch.where(update, gain, best_gain)
                best_img_l2 = torch.where(update, img_l2, best_img_l2)
                best_conf_drop = torch.where(update, conf_drop, best_conf_drop)
                best_shape_pred = torch.where(update, shape_pred_s, best_shape_pred)

            row = summary_rows[tau_to_idx[tau_img]]
            row["n"] += bs
            row["shape_acc_sum"] += float(best_shape_ok.sum().item())
            row["shape_consistency_sum"] += float(best_shape_cons.sum().item())
            row["scale_gain_sum"] += float(best_gain.sum().item())
            row["img_l2_sum"] += float(best_img_l2.sum().item())
            row["shape_conf_drop_sum"] += float(best_conf_drop.sum().item())
            row["alpha_star_sum"] += float(best_alpha.sum().item())
            row["nonzero_alpha_sum"] += float((best_alpha != 0).float().sum().item())
            row["objective_sum"] += float(best_obj.sum().item())

            for i in range(bs):
                sample_rows.append({
                    "split": split_name,
                    "sample_idx": int(global_idx + i),
                    "tau_img": tau_img,
                    "alpha_star": float(best_alpha[i].item()),
                    "shape_true": int(shape_true[i].item()),
                    "shape_rec": int(shape_pred_rec[i].item()),
                    "shape_edit": int(best_shape_pred[i].item()),
                    "shape_acc": float(best_shape_ok[i].item()),
                    "shape_consistency": float(best_shape_cons[i].item()),
                    "scale_gain": float(best_gain[i].item()),
                    "img_l2_to_recon": float(best_img_l2[i].item()),
                    "shape_conf_drop": float(best_conf_drop[i].item()),
                    "objective": float(best_obj[i].item()),
                })

        global_idx += bs

    summary_df = pd.DataFrame([{
        "split": r["split"],
        "tau_img": r["tau_img"],
        "shape_acc": r["shape_acc_sum"] / max(1, r["n"]),
        "shape_consistency": r["shape_consistency_sum"] / max(1, r["n"]),
        "scale_gain": r["scale_gain_sum"] / max(1, r["n"]),
        "img_l2_to_recon": r["img_l2_sum"] / max(1, r["n"]),
        "shape_conf_drop": r["shape_conf_drop_sum"] / max(1, r["n"]),
        "alpha_star_mean": r["alpha_star_sum"] / max(1, r["n"]),
        "alpha_nonzero_rate": r["nonzero_alpha_sum"] / max(1, r["n"]),
        "objective": r["objective_sum"] / max(1, r["n"]),
        "n": int(r["n"]),
    } for r in summary_rows])

    sample_df = pd.DataFrame(sample_rows)
    return summary_df, sample_df


def pick_best_fixed_alpha(df_fixed: pd.DataFrame, split_name: str) -> float:
    x = df_fixed[df_fixed["split"] == split_name].copy()
    if len(x) == 0:
        raise ValueError(f"No fixed-alpha rows for split={split_name}")
    x = x.sort_values(["objective", "shape_consistency", "scale_gain"], ascending=[False, False, False])
    return float(x.iloc[0]["alpha"])


def pick_best_tau(df_auto: pd.DataFrame, split_name: str) -> float:
    x = df_auto[df_auto["split"] == split_name].copy()
    if len(x) == 0:
        raise ValueError(f"No auto-alpha rows for split={split_name}")
    x = x.sort_values(["objective", "shape_consistency", "scale_gain"], ascending=[False, False, False])
    return float(x.iloc[0]["tau_img"])

In [8]:
# plots
def plot_vae_curves(df: pd.DataFrame, out_png: str) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(10, 7))

    axes[0, 0].plot(df["epoch"], df["train_loss"], label="train_loss")
    axes[0, 0].plot(df["epoch"], df["val_loss"], label="val_loss")
    axes[0, 0].set_title("Total loss")
    axes[0, 0].set_xlabel("epoch")
    axes[0, 0].grid(alpha=0.25)
    axes[0, 0].legend()

    axes[0, 1].plot(df["epoch"], df["train_rec"], label="train_rec")
    axes[0, 1].plot(df["epoch"], df["val_rec"], label="val_rec")
    axes[0, 1].plot(df["epoch"], df["train_kl"], label="train_kl")
    axes[0, 1].plot(df["epoch"], df["val_kl"], label="val_kl")
    axes[0, 1].set_title("Recon / KL")
    axes[0, 1].set_xlabel("epoch")
    axes[0, 1].grid(alpha=0.25)
    axes[0, 1].legend()

    if "beta_t" in df.columns:
        axes[1, 0].plot(df["epoch"], df["beta_t"], label="beta_t")
        axes[1, 0].set_title("KL warmup")
        axes[1, 0].set_xlabel("epoch")
        axes[1, 0].grid(alpha=0.25)

    if "lr" in df.columns:
        axes[1, 1].plot(df["epoch"], df["lr"], label="lr")
        axes[1, 1].set_title("Learning rate")
        axes[1, 1].set_xlabel("epoch")
        axes[1, 1].grid(alpha=0.25)

    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()

def plot_head_curves(df_shape: pd.DataFrame, df_scale: pd.DataFrame, out_png: str) -> None:
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(df_shape["epoch"], df_shape["val_acc"], label="shape val acc")
    ax.plot(df_scale["epoch"], df_scale["val_acc"], label="scale val acc")
    ax.set_xlabel("epoch")
    ax.set_ylabel("accuracy")
    ax.set_title("Latent head validation accuracy")
    ax.legend()
    ax.grid(alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()


def plot_fixed_tradeoff(df_fixed: pd.DataFrame, out_png: str) -> None:
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    for split_name in sorted(df_fixed["split"].unique()):
        x = df_fixed[df_fixed["split"] == split_name].sort_values("alpha")
        ax.plot(x["img_l2_to_recon"], x["scale_gain"], marker="o", label=split_name)
        for _, r in x.iterrows():
            ax.text(r["img_l2_to_recon"], r["scale_gain"], f"{r['alpha']:.1f}", fontsize=8)
    ax.set_xlabel("image drift to reconstruction")
    ax.set_ylabel("expected scale gain")
    ax.set_title("Fixed-alpha tradeoff")
    ax.legend()
    ax.grid(alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()

def plot_auto_summary(df_auto: pd.DataFrame, out_png: str) -> None:
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    markers = {"id_test": "o", "ood_test": "s"}
    for split_name in sorted(df_auto["split"].unique()):
        x = df_auto[df_auto["split"] == split_name].sort_values("tau_img")
        ax.plot(x["img_l2_to_recon"], x["scale_gain"], marker=markers.get(split_name, "o"), label=split_name)
        for _, r in x.iterrows():
            ax.text(r["img_l2_to_recon"], r["scale_gain"], f"τ={r['tau_img']:.0f}", fontsize=8)
    ax.set_xlabel("image drift to reconstruction")
    ax.set_ylabel("expected scale gain")
    ax.set_title("Auto-alpha tradeoff")
    ax.legend()
    ax.grid(alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()

def plot_auto_alpha_hist(df_samples: pd.DataFrame, tau_img: float, out_png: str) -> None:
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    bins = np.asarray(sorted(df_samples["alpha_star"].unique()), dtype=np.float32)
    if len(bins) <= 1:
        bins = np.array([-0.25, 0.25])
    else:
        step = float(np.min(np.diff(np.unique(bins))))
        bins = np.concatenate([[bins.min() - step / 2], bins + step / 2])

    for split_name in sorted(df_samples["split"].unique()):
        x = df_samples[(df_samples["split"] == split_name) & (df_samples["tau_img"] == tau_img)]["alpha_star"].values
        ax.hist(x, bins=bins, alpha=0.55, label=split_name)
    ax.set_xlabel("alpha*")
    ax.set_ylabel("count")
    ax.set_title(f"Auto-alpha histogram (tau_img={tau_img})")
    ax.legend()
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()

@torch.no_grad()
def render_preview_grid(
        dataset: Dataset,
        out_png: str,
        vae: nn.Module,
        local_bank: Dict[str, Any],
        selected_rows: pd.DataFrame,
        device: torch.device,
        local_k: int = 64,
        same_shape_only: bool = True,
        distance_eps: float = 1e-6,
    ) -> None:

    selected_rows = selected_rows.head(8).copy()
    if len(selected_rows) == 0:
        return

    fig, axes = plt.subplots(len(selected_rows), 3, figsize=(8, 2.2 * len(selected_rows)))
    if len(selected_rows) == 1:
        axes = np.expand_dims(axes, axis=0)

    for i, (_, r) in enumerate(selected_rows.iterrows()):
        x, _ = dataset[int(r["sample_idx"])]
        x = x.unsqueeze(0).to(device)
        z = encode_mu(vae, x)
        x_rec = decode_sigmoid(vae, z)

        shape_ref = torch.tensor([int(r["shape_rec"])], device=device, dtype=torch.long)
        d_local = local_direction_batch(
            z_query=z,
            shape_query=shape_ref,
            local_bank=local_bank,
            k=local_k,
            same_shape_only=same_shape_only,
            distance_eps=distance_eps,
        )
        z_s = z + float(r["alpha_star"]) * d_local
        x_s = decode_sigmoid(vae, z_s)

        imgs = [x.squeeze().cpu().numpy(), x_rec.squeeze().cpu().numpy(), x_s.squeeze().cpu().numpy()]
        titles = ["original", "recon", "steered"]
        for j in range(3):
            ax = axes[i, j]
            ax.imshow(imgs[j], cmap="gray")
            ax.axis("off")
            if i == 0:
                ax.set_title(titles[j], fontsize=11)

        axes[i, 0].set_ylabel(
            f"a*={r['alpha_star']:.2f}\n"
            f"gain={r['scale_gain']:.2f}\n"
            f"shape {int(r['shape_rec'])}->{int(r['shape_edit'])}",
            fontsize=9
        )

    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()


def write_memo(
        out_path: str,
        split_df: pd.DataFrame,
        probe_df: pd.DataFrame,
        fixed_df: pd.DataFrame,
        auto_df: pd.DataFrame,
    ) -> None:
    
    best_fixed_id = fixed_df[fixed_df["split"] == "id_test"].sort_values("objective", ascending=False).iloc[0]
    best_fixed_ood = fixed_df[(fixed_df["split"] == "ood_test") & (fixed_df["alpha"] == best_fixed_id["alpha"])].iloc[0]

    best_auto_id = auto_df[auto_df["split"] == "id_test"].sort_values("objective", ascending=False).iloc[0]
    best_auto_ood = auto_df[(auto_df["split"] == "ood_test") & (auto_df["tau_img"] == best_auto_id["tau_img"])].iloc[0]

    shape_id = probe_df[(probe_df["split"] == "id_test") & (probe_df["target"] == "shape")]["acc"].iloc[0]
    shape_ood = probe_df[(probe_df["split"] == "ood_test") & (probe_df["target"] == "shape")]["acc"].iloc[0]
    scale_id = probe_df[(probe_df["split"] == "id_test") & (probe_df["target"] == "scale")]["acc"].iloc[0]
    scale_ood = probe_df[(probe_df["split"] == "ood_test") & (probe_df["target"] == "scale")]["acc"].iloc[0]

    lines = [
        "# Weekly memo — dSprites OOD extension",
        "",
        "## What was done",
        "- Trained a compact dSprites VAE on ID orientations only.",
        "- Trained latent heads for shape and scale.",
        "- Built a local kNN latent direction bank for increasing scale.",
        "- Evaluated fixed-alpha and auto-alpha local steering on ID and OOD splits.",
        "",
        "## Dataset split",
        split_df.to_markdown(index=False),
        "",
        "## Probe quality",
        probe_df.to_markdown(index=False),
        "",
        "## Main observations",
        f"- Shape probe accuracy: ID = {shape_id:.4f}, OOD = {shape_ood:.4f}.",
        f"- Scale probe accuracy: ID = {scale_id:.4f}, OOD = {scale_ood:.4f}.",
        f"- Best fixed alpha on ID: alpha = {best_fixed_id['alpha']:.2f}, scale gain = {best_fixed_id['scale_gain']:.4f}, shape consistency = {best_fixed_id['shape_consistency']:.4f}, drift = {best_fixed_id['img_l2_to_recon']:.4f}.",
        f"- Same fixed alpha on OOD: scale gain = {best_fixed_ood['scale_gain']:.4f}, shape consistency = {best_fixed_ood['shape_consistency']:.4f}, drift = {best_fixed_ood['img_l2_to_recon']:.4f}.",
        f"- Best auto setting on ID: tau_img = {best_auto_id['tau_img']:.2f}, scale gain = {best_auto_id['scale_gain']:.4f}, shape consistency = {best_auto_id['shape_consistency']:.4f}, alpha_nonzero_rate = {best_auto_id['alpha_nonzero_rate']:.4f}.",
        f"- Same auto setting on OOD: scale gain = {best_auto_ood['scale_gain']:.4f}, shape consistency = {best_auto_ood['shape_consistency']:.4f}, alpha_nonzero_rate = {best_auto_ood['alpha_nonzero_rate']:.4f}.",
        "",
        "## Interpretation",
        "- If OOD shape consistency stays close to ID while scale gain remains positive, the local steering rule transfers beyond the training support.",
        "- If OOD gain collapses or shape consistency drops, failure is likely tied to representation shift across held-out orientations.",
        "",
        "## Risks",
        "- The result may depend strongly on VAE quality and latent disentanglement.",
        "- OOD here is small: only orientation support shifts, not a new dataset.",
        "- Fixed-alpha may over-edit on OOD even if it looks fine on ID.",
        "",
        "## Next step",
        "- Compare the same steering recipe against a stronger local direction or nearest-neighbor-conditioned direction on dSprites.",
    ]

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")

In [9]:
#  main
set_seed(int(cfg["seed"]))
device = get_device(cfg["device"])

dsprites_npz_path = require_manual_path(cfg["paths"]["dsprites_npz_path"], "paths.dsprites_npz_path")
run_dir = make_run_dir(cfg["paths"]["run_root"], cfg["notes"]["experiment_name"])
save_json(str(Path(run_dir) / "config_used.json"), cfg)

print("device:", device)
print("run_dir:", run_dir)
print("dsprites:", dsprites_npz_path)

splits = build_group_splits(
    npz_path=dsprites_npz_path,
    train_orientations=list(cfg["data"]["train_orientations"]),
    ood_orientations=list(cfg["data"]["ood_orientations"]),
    train_groups=int(cfg["data"]["train_groups"]),
    val_groups=int(cfg["data"]["val_groups"]),
    id_test_groups=int(cfg["data"]["id_test_groups"]),
    ood_test_groups=int(cfg["data"]["ood_test_groups"]),
    seed=int(cfg["seed"]),
)

split_df = pd.concat([
    summarize_split(splits["train_idx"], "train"),
    summarize_split(splits["val_idx"], "val"),
    summarize_split(splits["id_test_idx"], "id_test"),
    summarize_split(splits["ood_test_idx"], "ood_test"),
], ignore_index=True)
display(split_df)

train_ds = DSpritesSubset(dsprites_npz_path, splits["train_idx"])
val_ds = DSpritesSubset(dsprites_npz_path, splits["val_idx"])
id_test_ds = DSpritesSubset(dsprites_npz_path, splits["id_test_idx"])
ood_test_ds = DSpritesSubset(dsprites_npz_path, splits["ood_test_idx"])

loader_cfg = cfg["loader"]
common_loader_kwargs = dict(
    batch_size=int(loader_cfg["batch_size"]),
    num_workers=int(loader_cfg["num_workers"]),
    pin_memory=bool(loader_cfg.get("pin_memory", False)) and device.type == "cuda",
    worker_init_fn=None if int(loader_cfg["num_workers"]) == 0 else seed_worker,
)

train_loader = DataLoader(train_ds, shuffle=True, **common_loader_kwargs)
val_loader = DataLoader(val_ds, shuffle=False, **common_loader_kwargs)
id_test_loader = DataLoader(id_test_ds, shuffle=False, **common_loader_kwargs)
ood_test_loader = DataLoader(ood_test_ds, shuffle=False, **common_loader_kwargs)

# train VAE
vae, vae_curve = train_dsprites_vae(
    train_loader=train_loader,
    val_loader=val_loader,
    run_dir=run_dir,
    latent_dim=int(cfg["vae"]["latent_dim"]),
    base_channels=int(cfg["vae"]["base_channels"]),
    epochs=int(cfg["vae"]["epochs"]),
    lr=float(cfg["vae"]["lr"]),
    beta=float(cfg["vae"]["beta"]),
    beta_warmup_epochs=int(cfg["vae"]["beta_warmup_epochs"]),
    free_bits=float(cfg["vae"]["free_bits"]),
    weight_decay=float(cfg["vae"]["weight_decay"]),
    grad_clip=float(cfg["vae"]["grad_clip"]),
    recon=str(cfg["vae"]["recon"]),
    device=device,
)
vae_curve.to_csv(Path(run_dir) / "tables" / "vae_curve.csv", index=False)

# encoding splits
eval_batch_size = int(loader_cfg["batch_size"])
eval_loader_kwargs = dict(
    batch_size=eval_batch_size,
    shuffle=False,
    num_workers=0,
    pin_memory=bool(loader_cfg.get("pin_memory", False)) and device.type == "cuda",
)
train_eval_loader = DataLoader(train_ds, **eval_loader_kwargs)
val_eval_loader = DataLoader(val_ds, **eval_loader_kwargs)
id_eval_loader = DataLoader(id_test_ds, **eval_loader_kwargs)
ood_eval_loader = DataLoader(ood_test_ds, **eval_loader_kwargs)

z_train, c_train = encode_dataset(vae, train_eval_loader, device)
z_val, c_val = encode_dataset(vae, val_eval_loader, device)
z_id, c_id = encode_dataset(vae, id_eval_loader, device)
z_ood, c_ood = encode_dataset(vae, ood_eval_loader, device)

# factor order: color, shape, scale, orientation, posX, posY
y_shape_train, y_shape_val, y_shape_id, y_shape_ood = c_train[:, 1], c_val[:, 1], c_id[:, 1], c_ood[:, 1]
y_scale_train, y_scale_val, y_scale_id, y_scale_ood = c_train[:, 2], c_val[:, 2], c_id[:, 2], c_ood[:, 2]

# train latent heads
head_cfg = cfg["heads"]
shape_head, shape_curve = train_latent_head(
    ShapeHead(z_train.shape[1]),
    build_latent_loader(z_train, y_shape_train, batch_size=int(head_cfg["batch_size"]), shuffle=True),
    build_latent_loader(z_val, y_shape_val, batch_size=int(head_cfg["batch_size"]), shuffle=False),
    run_dir=run_dir,
    name="shape_head",
    epochs=int(head_cfg["epochs"]),
    lr=float(head_cfg["lr"]),
    device=device,
)

scale_head, scale_curve = train_latent_head(
    ScaleHead(z_train.shape[1]),
    build_latent_loader(z_train, y_scale_train, batch_size=int(head_cfg["batch_size"]), shuffle=True),
    build_latent_loader(z_val, y_scale_val, batch_size=int(head_cfg["batch_size"]), shuffle=False),
    run_dir=run_dir,
    name="scale_head",
    epochs=int(head_cfg["epochs"]),
    lr=float(head_cfg["lr"]),
    device=device,
)

shape_curve.to_csv(Path(run_dir) / "tables" / "shape_head_curve.csv", index=False)
scale_curve.to_csv(Path(run_dir) / "tables" / "scale_head_curve.csv", index=False)

probe_df = pd.concat([
    evaluate_head(shape_head, build_latent_loader(z_id, y_shape_id, batch_size=1024, shuffle=False), device, "shape", "id_test"),
    evaluate_head(shape_head, build_latent_loader(z_ood, y_shape_ood, batch_size=1024, shuffle=False), device, "shape", "ood_test"),
    evaluate_head(scale_head, build_latent_loader(z_id, y_scale_id, batch_size=1024, shuffle=False), device, "scale", "id_test"),
    evaluate_head(scale_head, build_latent_loader(z_ood, y_scale_ood, batch_size=1024, shuffle=False), device, "scale", "ood_test"),
], ignore_index=True)
probe_df.to_csv(Path(run_dir) / "tables" / "probe_eval.csv", index=False)
display(probe_df)

# build local scale bank
steer_cfg = cfg["steering"]
local_bank = build_local_scale_bank(z_train, c_train)
np.savez(
    Path(run_dir) / "tables" / "local_scale_bank.npz",
    anchors=local_bank["anchors"],
    deltas=local_bank["deltas"],
    shapes=local_bank["shapes"],
    pair_scales=local_bank["pair_scales"],
)
save_json(
    str(Path(run_dir) / "tables" / "local_scale_bank_meta.json"),
    {
        "n_pairs": int(local_bank["n_pairs"]),
        "local_k": int(steer_cfg["local_k"]),
        "same_shape_only": bool(steer_cfg["same_shape_only"]),
        "distance_eps": float(steer_cfg["distance_eps"]),
    },
)

# Fixed-alpha sweep
df_fixed_id = sweep_fixed_alpha(
    vae, shape_head, scale_head, id_test_loader, local_bank,
    alpha_grid=list(steer_cfg["alpha_grid"]),
    tau_shape_conf=float(steer_cfg["tau_shape_conf"]),
    lambda_img=float(steer_cfg["lambda_img"]),
    lambda_shape=float(steer_cfg["lambda_shape"]),
    strict_shape_consistency=bool(steer_cfg["strict_shape_consistency"]),
    split_name="id_test",
    device=device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)
df_fixed_ood = sweep_fixed_alpha(
    vae, shape_head, scale_head, ood_test_loader, local_bank,
    alpha_grid=list(steer_cfg["alpha_grid"]),
    tau_shape_conf=float(steer_cfg["tau_shape_conf"]),
    lambda_img=float(steer_cfg["lambda_img"]),
    lambda_shape=float(steer_cfg["lambda_shape"]),
    strict_shape_consistency=bool(steer_cfg["strict_shape_consistency"]),
    split_name="ood_test",
    device=device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)
df_fixed = pd.concat([df_fixed_id, df_fixed_ood], ignore_index=True)
df_fixed.to_csv(Path(run_dir) / "tables" / "fixed_alpha_sweep.csv", index=False)

# auto-alpha
df_auto_id, df_samples_id = evaluate_auto_alpha(
    vae, shape_head, scale_head, id_test_loader, local_bank,
    alpha_grid=list(steer_cfg["alpha_grid"]),
    tau_img_values=list(steer_cfg["tau_img_values"]),
    tau_shape_conf=float(steer_cfg["tau_shape_conf"]),
    lambda_img=float(steer_cfg["lambda_img"]),
    lambda_shape=float(steer_cfg["lambda_shape"]),
    strict_shape_consistency=bool(steer_cfg["strict_shape_consistency"]),
    split_name="id_test",
    device=device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)
df_auto_ood, df_samples_ood = evaluate_auto_alpha(
    vae, shape_head, scale_head, ood_test_loader, local_bank,
    alpha_grid=list(steer_cfg["alpha_grid"]),
    tau_img_values=list(steer_cfg["tau_img_values"]),
    tau_shape_conf=float(steer_cfg["tau_shape_conf"]),
    lambda_img=float(steer_cfg["lambda_img"]),
    lambda_shape=float(steer_cfg["lambda_shape"]),
    strict_shape_consistency=bool(steer_cfg["strict_shape_consistency"]),
    split_name="ood_test",
    device=device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)
df_auto = pd.concat([df_auto_id, df_auto_ood], ignore_index=True)
df_samples = pd.concat([df_samples_id, df_samples_ood], ignore_index=True)
df_auto.to_csv(Path(run_dir) / "tables" / "auto_alpha_summary.csv", index=False)
df_samples.to_csv(Path(run_dir) / "tables" / "auto_alpha_samples.csv", index=False)

# best-setting comparison
best_fixed_alpha = pick_best_fixed_alpha(df_fixed, "id_test")
best_tau = pick_best_tau(df_auto, "id_test")

comparison_df = pd.concat([
    df_fixed[(df_fixed["split"].isin(["id_test", "ood_test"])) & (df_fixed["alpha"] == best_fixed_alpha)].assign(method=f"fixed_alpha_{best_fixed_alpha:.2f}"),
    df_auto[(df_auto["split"].isin(["id_test", "ood_test"])) & (df_auto["tau_img"] == best_tau)].assign(method=f"auto_tau_{best_tau:.2f}"),
], ignore_index=True)
comparison_df.to_csv(Path(run_dir) / "tables" / "selected_comparison.csv", index=False)

# plots
plot_dir = Path(run_dir) / "plots"
plot_vae_curves(vae_curve, str(plot_dir / "vae_curves.png"))
plot_head_curves(shape_curve, scale_curve, str(plot_dir / "head_curves.png"))
plot_fixed_tradeoff(df_fixed, str(plot_dir / "fixed_tradeoff.png"))
plot_auto_summary(df_auto, str(plot_dir / "auto_tradeoff.png"))
plot_auto_alpha_hist(df_samples, tau_img=best_tau, out_png=str(plot_dir / "auto_alpha_hist.png"))

preview_id = (
    df_samples[(df_samples["split"] == "id_test") & (df_samples["tau_img"] == best_tau)]
    .sort_values(["objective", "scale_gain"], ascending=[False, False])
    .head(int(cfg["preview"]["n_samples"]))
)

preview_ood = (
    df_samples[(df_samples["split"] == "ood_test") & (df_samples["tau_img"] == best_tau)]
    .sort_values(["objective", "scale_gain"], ascending=[False, False])
    .head(int(cfg["preview"]["n_samples"]))
)

render_preview_grid(
    id_test_ds,
    str(plot_dir / "preview_id.png"),
    vae,
    local_bank,
    preview_id,
    device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)

render_preview_grid(
    ood_test_ds,
    str(plot_dir / "preview_ood.png"),
    vae,
    local_bank,
    preview_ood,
    device,
    local_k=int(steer_cfg["local_k"]),
    same_shape_only=bool(steer_cfg["same_shape_only"]),
    distance_eps=float(steer_cfg["distance_eps"]),
)

# memo
write_memo(
    out_path=str(Path(run_dir) / "memo.md"),
    split_df=split_df,
    probe_df=probe_df,
    fixed_df=df_fixed,
    auto_df=df_auto,
)

result = {
    "run_dir": run_dir,
    "best_fixed_alpha": best_fixed_alpha,
    "best_auto_tau_img": best_tau,
}

print("\nDone.")
print(json.dumps(result, indent=2))
display(comparison_df)

device: cpu
run_dir: runs/20260331_034745_week10_dsprites_ood_local_knn
dsprites: /kaggle/input/datasets/galievilyas/dsprits/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz

      split  n_samples  n_groups_approx
0     train      21000             3500
1       val       3600              600
2   id_test       4800              800
3  ood_test       4800              800

VAE train ep1:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep1:   1%|          | 1/165 [00:09<27:11,  9.95s/it]

VAE train ep1:   1%|          | 2/165 [00:19<25:43,  9.47s/it]

VAE train ep1:   2%|▏         | 3/165 [00:28<25:01,  9.27s/it]

VAE train ep1:   2%|▏         | 4/165 [00:37<24:36,  9.17s/it]

VAE train ep1:   3%|▎         | 5/165 [00:45<24:09,  9.06s/it]

VAE train ep1:   4%|▎         | 6/165 [00:54<23:36,  8.91s/it]

VAE train ep1:   4%|▍         | 7/165 [01:02<22:50,  8.68s/it]

VAE train ep1:   5%|▍         | 8/165 [01:10<22:14,  8.50s/it]

VAE train ep1:   5%|▌         | 9/165 [01:19<21:55,  8.43s/it]

VAE train ep1:   6%|▌         | 10/165 [01:27<21:32,  8.34s/it]

VAE train ep1:   7%|▋         | 11/165 [01:35<21:16,  8.29s/it]

VAE train ep1:   7%|▋         | 12/165 [01:43<21:15,  8.34s/it]

VAE train ep1:   8%|▊         | 13/165 [01:52<20:59,  8.29s/it]

VAE train ep1:   8%|▊         | 14/165 [02:00<20:47,  8.26s/it]

VAE train ep1:   9%|▉         | 15/165 [02:08<20:42,  8.29s/it]

VAE train ep1:  10%|▉         | 16/165 [02:16<20:30,  8.26s/it]

VAE train ep1:  10%|█         | 17/165 [02:25<20:23,  8.27s/it]

VAE train ep1:  11%|█         | 18/165 [02:33<20:13,  8.26s/it]

VAE train ep1:  12%|█▏        | 19/165 [02:41<19:58,  8.21s/it]

VAE train ep1:  12%|█▏        | 20/165 [02:49<19:42,  8.16s/it]

VAE train ep1:  13%|█▎        | 21/165 [02:57<19:30,  8.13s/it]

VAE train ep1:  13%|█▎        | 22/165 [03:05<19:19,  8.11s/it]

VAE train ep1:  14%|█▍        | 23/165 [03:13<19:00,  8.03s/it]

VAE train ep1:  15%|█▍        | 24/165 [03:21<18:56,  8.06s/it]

VAE train ep1:  15%|█▌        | 25/165 [03:29<18:48,  8.06s/it]

VAE train ep1:  16%|█▌        | 26/165 [03:37<18:45,  8.10s/it]

VAE train ep1:  16%|█▋        | 27/165 [03:45<18:33,  8.07s/it]

VAE train ep1:  17%|█▋        | 28/165 [03:53<18:24,  8.06s/it]

VAE train ep1:  18%|█▊        | 29/165 [04:02<18:19,  8.08s/it]

VAE train ep1:  18%|█▊        | 30/165 [04:09<18:03,  8.03s/it]

VAE train ep1:  19%|█▉        | 31/165 [04:18<17:58,  8.05s/it]

VAE train ep1:  19%|█▉        | 32/165 [04:26<17:50,  8.05s/it]

VAE train ep1:  20%|██        | 33/165 [04:34<17:46,  8.08s/it]

VAE train ep1:  21%|██        | 34/165 [04:42<17:35,  8.06s/it]

VAE train ep1:  21%|██        | 35/165 [04:50<17:23,  8.03s/it]

VAE train ep1:  22%|██▏       | 36/165 [04:58<17:14,  8.02s/it]

VAE train ep1:  22%|██▏       | 37/165 [05:06<17:02,  7.99s/it]

VAE train ep1:  23%|██▎       | 38/165 [05:14<16:52,  7.97s/it]

VAE train ep1:  24%|██▎       | 39/165 [05:22<16:45,  7.98s/it]

VAE train ep1:  24%|██▍       | 40/165 [05:30<16:37,  7.98s/it]

VAE train ep1:  25%|██▍       | 41/165 [05:38<16:30,  7.98s/it]

VAE train ep1:  25%|██▌       | 42/165 [05:45<16:20,  7.97s/it]

VAE train ep1:  26%|██▌       | 43/165 [05:54<16:14,  7.99s/it]

VAE train ep1:  27%|██▋       | 44/165 [06:02<16:09,  8.01s/it]

VAE train ep1:  27%|██▋       | 45/165 [06:10<16:00,  8.00s/it]

VAE train ep1:  28%|██▊       | 46/165 [06:18<15:53,  8.01s/it]

VAE train ep1:  28%|██▊       | 47/165 [06:26<15:54,  8.09s/it]

VAE train ep1:  29%|██▉       | 48/165 [06:34<15:42,  8.05s/it]

VAE train ep1:  30%|██▉       | 49/165 [06:42<15:31,  8.03s/it]

VAE train ep1:  30%|███       | 50/165 [06:50<15:19,  8.00s/it]

VAE train ep1:  31%|███       | 51/165 [06:58<15:14,  8.02s/it]

VAE train ep1:  32%|███▏      | 52/165 [07:06<15:01,  7.98s/it]

VAE train ep1:  32%|███▏      | 53/165 [07:14<14:57,  8.01s/it]

VAE train ep1:  33%|███▎      | 54/165 [07:22<14:49,  8.01s/it]

VAE train ep1:  33%|███▎      | 55/165 [07:30<14:48,  8.08s/it]

VAE train ep1:  34%|███▍      | 56/165 [07:38<14:42,  8.10s/it]

VAE train ep1:  35%|███▍      | 57/165 [07:46<14:35,  8.11s/it]

VAE train ep1:  35%|███▌      | 58/165 [07:54<14:22,  8.06s/it]

VAE train ep1:  36%|███▌      | 59/165 [08:02<14:13,  8.05s/it]

VAE train ep1:  36%|███▋      | 60/165 [08:10<14:09,  8.09s/it]

VAE train ep1:  37%|███▋      | 61/165 [08:19<14:02,  8.10s/it]

VAE train ep1:  38%|███▊      | 62/165 [08:27<13:58,  8.14s/it]

VAE train ep1:  38%|███▊      | 63/165 [08:35<13:50,  8.14s/it]

VAE train ep1:  39%|███▉      | 64/165 [08:43<13:41,  8.14s/it]

VAE train ep1:  39%|███▉      | 65/165 [08:51<13:34,  8.14s/it]

VAE train ep1:  40%|████      | 66/165 [08:59<13:24,  8.13s/it]

VAE train ep1:  41%|████      | 67/165 [09:07<13:14,  8.11s/it]

VAE train ep1:  41%|████      | 68/165 [09:16<13:08,  8.13s/it]

VAE train ep1:  42%|████▏     | 69/165 [09:24<12:58,  8.11s/it]

VAE train ep1:  42%|████▏     | 70/165 [09:32<12:51,  8.12s/it]

VAE train ep1:  43%|████▎     | 71/165 [09:40<12:45,  8.14s/it]

VAE train ep1:  44%|████▎     | 72/165 [09:48<12:40,  8.17s/it]

VAE train ep1:  44%|████▍     | 73/165 [09:56<12:30,  8.16s/it]

VAE train ep1:  45%|████▍     | 74/165 [10:04<12:17,  8.11s/it]

VAE train ep1:  45%|████▌     | 75/165 [10:12<12:04,  8.05s/it]

VAE train ep1:  46%|████▌     | 76/165 [10:20<11:56,  8.05s/it]

VAE train ep1:  47%|████▋     | 77/165 [10:29<11:55,  8.13s/it]

VAE train ep1:  47%|████▋     | 78/165 [10:37<11:46,  8.12s/it]

VAE train ep1:  48%|████▊     | 79/165 [10:45<11:38,  8.12s/it]

VAE train ep1:  48%|████▊     | 80/165 [10:53<11:27,  8.08s/it]

VAE train ep1:  49%|████▉     | 81/165 [11:01<11:17,  8.07s/it]

VAE train ep1:  50%|████▉     | 82/165 [11:09<11:12,  8.10s/it]

VAE train ep1:  50%|█████     | 83/165 [11:17<11:08,  8.16s/it]

VAE train ep1:  51%|█████     | 84/165 [11:26<11:01,  8.16s/it]

VAE train ep1:  52%|█████▏    | 85/165 [11:34<10:55,  8.19s/it]

VAE train ep1:  52%|█████▏    | 86/165 [11:42<10:44,  8.15s/it]

VAE train ep1:  53%|█████▎    | 87/165 [11:50<10:39,  8.19s/it]

VAE train ep1:  53%|█████▎    | 88/165 [11:58<10:29,  8.17s/it]

VAE train ep1:  54%|█████▍    | 89/165 [12:07<10:26,  8.24s/it]

VAE train ep1:  55%|█████▍    | 90/165 [12:15<10:18,  8.25s/it]

VAE train ep1:  55%|█████▌    | 91/165 [12:23<10:09,  8.24s/it]

VAE train ep1:  56%|█████▌    | 92/165 [12:32<10:04,  8.28s/it]

VAE train ep1:  56%|█████▋    | 93/165 [12:40<09:55,  8.27s/it]

VAE train ep1:  57%|█████▋    | 94/165 [12:48<09:42,  8.20s/it]

VAE train ep1:  58%|█████▊    | 95/165 [12:56<09:32,  8.18s/it]

VAE train ep1:  58%|█████▊    | 96/165 [13:04<09:24,  8.19s/it]

VAE train ep1:  59%|█████▉    | 97/165 [13:12<09:12,  8.13s/it]

VAE train ep1:  59%|█████▉    | 98/165 [13:20<09:04,  8.13s/it]

VAE train ep1:  60%|██████    | 99/165 [13:28<08:57,  8.14s/it]

VAE train ep1:  61%|██████    | 100/165 [13:37<08:49,  8.14s/it]

VAE train ep1:  61%|██████    | 101/165 [13:45<08:40,  8.14s/it]

VAE train ep1:  62%|██████▏   | 102/165 [13:53<08:35,  8.18s/it]

VAE train ep1:  62%|██████▏   | 103/165 [14:01<08:27,  8.19s/it]

VAE train ep1:  63%|██████▎   | 104/165 [14:09<08:17,  8.16s/it]

VAE train ep1:  64%|██████▎   | 105/165 [14:17<08:08,  8.15s/it]

VAE train ep1:  64%|██████▍   | 106/165 [14:26<08:01,  8.16s/it]

VAE train ep1:  65%|██████▍   | 107/165 [14:34<07:50,  8.12s/it]

VAE train ep1:  65%|██████▌   | 108/165 [14:42<07:46,  8.19s/it]

VAE train ep1:  66%|██████▌   | 109/165 [14:50<07:41,  8.24s/it]

VAE train ep1:  67%|██████▋   | 110/165 [14:58<07:28,  8.16s/it]

VAE train ep1:  67%|██████▋   | 111/165 [15:06<07:19,  8.13s/it]

VAE train ep1:  68%|██████▊   | 112/165 [15:14<07:10,  8.13s/it]

VAE train ep1:  68%|██████▊   | 113/165 [15:23<07:02,  8.13s/it]

VAE train ep1:  69%|██████▉   | 114/165 [15:31<06:54,  8.12s/it]

VAE train ep1:  70%|██████▉   | 115/165 [15:39<06:45,  8.11s/it]

VAE train ep1:  70%|███████   | 116/165 [15:47<06:38,  8.13s/it]

VAE train ep1:  71%|███████   | 117/165 [15:55<06:30,  8.13s/it]

VAE train ep1:  72%|███████▏  | 118/165 [16:03<06:22,  8.15s/it]

VAE train ep1:  72%|███████▏  | 119/165 [16:11<06:11,  8.08s/it]

VAE train ep1:  73%|███████▎  | 120/165 [16:19<06:03,  8.09s/it]

VAE train ep1:  73%|███████▎  | 121/165 [16:27<05:54,  8.06s/it]

VAE train ep1:  74%|███████▍  | 122/165 [16:35<05:46,  8.05s/it]

VAE train ep1:  75%|███████▍  | 123/165 [16:44<05:41,  8.12s/it]

VAE train ep1:  75%|███████▌  | 124/165 [16:52<05:30,  8.06s/it]

VAE train ep1:  76%|███████▌  | 125/165 [17:00<05:23,  8.09s/it]

VAE train ep1:  76%|███████▋  | 126/165 [17:08<05:16,  8.13s/it]

VAE train ep1:  77%|███████▋  | 127/165 [17:16<05:07,  8.09s/it]

VAE train ep1:  78%|███████▊  | 128/165 [17:24<04:59,  8.10s/it]

VAE train ep1:  78%|███████▊  | 129/165 [17:32<04:49,  8.05s/it]

VAE train ep1:  79%|███████▉  | 130/165 [17:40<04:40,  8.01s/it]

VAE train ep1:  79%|███████▉  | 131/165 [17:48<04:32,  8.01s/it]

VAE train ep1:  80%|████████  | 132/165 [17:56<04:24,  8.00s/it]

VAE train ep1:  81%|████████  | 133/165 [18:04<04:15,  7.99s/it]

VAE train ep1:  81%|████████  | 134/165 [18:12<04:07,  7.97s/it]

VAE train ep1:  82%|████████▏ | 135/165 [18:20<03:56,  7.90s/it]

VAE train ep1:  82%|████████▏ | 136/165 [18:28<03:50,  7.96s/it]

VAE train ep1:  83%|████████▎ | 137/165 [18:36<03:44,  8.03s/it]

VAE train ep1:  84%|████████▎ | 138/165 [18:44<03:37,  8.07s/it]

VAE train ep1:  84%|████████▍ | 139/165 [18:52<03:29,  8.06s/it]

VAE train ep1:  85%|████████▍ | 140/165 [19:00<03:21,  8.06s/it]

VAE train ep1:  85%|████████▌ | 141/165 [19:08<03:14,  8.08s/it]

VAE train ep1:  86%|████████▌ | 142/165 [19:16<03:05,  8.05s/it]

VAE train ep1:  87%|████████▋ | 143/165 [19:24<02:56,  8.02s/it]

VAE train ep1:  87%|████████▋ | 144/165 [19:32<02:49,  8.08s/it]

VAE train ep1:  88%|████████▊ | 145/165 [19:40<02:41,  8.06s/it]

VAE train ep1:  88%|████████▊ | 146/165 [19:48<02:33,  8.07s/it]

VAE train ep1:  89%|████████▉ | 147/165 [19:56<02:24,  8.02s/it]

VAE train ep1:  90%|████████▉ | 148/165 [20:04<02:15,  7.99s/it]

VAE train ep1:  90%|█████████ | 149/165 [20:12<02:07,  7.99s/it]

VAE train ep1:  91%|█████████ | 150/165 [20:20<02:00,  8.03s/it]

VAE train ep1:  92%|█████████▏| 151/165 [20:29<01:53,  8.07s/it]

VAE train ep1:  92%|█████████▏| 152/165 [20:37<01:44,  8.03s/it]

VAE train ep1:  93%|█████████▎| 153/165 [20:44<01:36,  8.01s/it]

VAE train ep1:  93%|█████████▎| 154/165 [20:52<01:27,  7.93s/it]

VAE train ep1:  94%|█████████▍| 155/165 [21:00<01:19,  7.93s/it]

VAE train ep1:  95%|█████████▍| 156/165 [21:08<01:11,  7.97s/it]

VAE train ep1:  95%|█████████▌| 157/165 [21:16<01:03,  7.92s/it]

VAE train ep1:  96%|█████████▌| 158/165 [21:24<00:55,  7.89s/it]

VAE train ep1:  96%|█████████▋| 159/165 [21:32<00:47,  7.93s/it]

VAE train ep1:  97%|█████████▋| 160/165 [21:40<00:39,  7.98s/it]

VAE train ep1:  98%|█████████▊| 161/165 [21:48<00:32,  8.03s/it]

VAE train ep1:  98%|█████████▊| 162/165 [21:56<00:24,  8.09s/it]

VAE train ep1:  99%|█████████▉| 163/165 [22:04<00:16,  8.10s/it]

VAE train ep1:  99%|█████████▉| 164/165 [22:12<00:08,  8.08s/it]

VAE train ep1: 100%|██████████| 165/165 [22:13<00:00,  5.81s/it]

VAE val ep1:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep1:   3%|▎         | 1/29 [00:02<01:01,  2.19s/it]

VAE val ep1:   7%|▋         | 2/29 [00:04<01:00,  2.24s/it]

VAE val ep1:  10%|█         | 3/29 [00:06<00:58,  2.24s/it]

VAE val ep1:  14%|█▍        | 4/29 [00:08<00:55,  2.21s/it]

VAE val ep1:  17%|█▋        | 5/29 [00:11<00:52,  2.19s/it]

VAE val ep1:  21%|██        | 6/29 [00:13<00:50,  2.19s/it]

VAE val ep1:  24%|██▍       | 7/29 [00:15<00:48,  2.19s/it]

VAE val ep1:  28%|██▊       | 8/29 [00:17<00:45,  2.18s/it]

VAE val ep1:  31%|███       | 9/29 [00:19<00:43,  2.18s/it]

VAE val ep1:  34%|███▍      | 10/29 [00:21<00:41,  2.17s/it]

VAE val ep1:  38%|███▊      | 11/29 [00:24<00:39,  2.19s/it]

VAE val ep1:  41%|████▏     | 12/29 [00:26<00:37,  2.18s/it]

VAE val ep1:  45%|████▍     | 13/29 [00:28<00:34,  2.18s/it]

VAE val ep1:  48%|████▊     | 14/29 [00:30<00:32,  2.18s/it]

VAE val ep1:  52%|█████▏    | 15/29 [00:32<00:30,  2.17s/it]

VAE val ep1:  55%|█████▌    | 16/29 [00:34<00:28,  2.18s/it]

VAE val ep1:  59%|█████▊    | 17/29 [00:37<00:26,  2.17s/it]

VAE val ep1:  62%|██████▏   | 18/29 [00:39<00:23,  2.16s/it]

VAE val ep1:  66%|██████▌   | 19/29 [00:41<00:21,  2.16s/it]

VAE val ep1:  69%|██████▉   | 20/29 [00:43<00:19,  2.16s/it]

VAE val ep1:  72%|███████▏  | 21/29 [00:45<00:17,  2.15s/it]

VAE val ep1:  76%|███████▌  | 22/29 [00:47<00:15,  2.15s/it]

VAE val ep1:  79%|███████▉  | 23/29 [00:50<00:12,  2.15s/it]

VAE val ep1:  83%|████████▎ | 24/29 [00:52<00:10,  2.15s/it]

VAE val ep1:  86%|████████▌ | 25/29 [00:54<00:08,  2.16s/it]

VAE val ep1:  90%|████████▉ | 26/29 [00:56<00:06,  2.16s/it]

VAE val ep1:  93%|█████████▎| 27/29 [00:58<00:04,  2.16s/it]

VAE val ep1:  97%|█████████▋| 28/29 [01:00<00:02,  2.16s/it]

VAE val ep1: 100%|██████████| 29/29 [01:01<00:00,  1.60s/it]

VAE train ep2:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep2:   1%|          | 1/165 [00:08<22:36,  8.27s/it]

VAE train ep2:   1%|          | 2/165 [00:16<22:13,  8.18s/it]

VAE train ep2:   2%|▏         | 3/165 [00:24<22:06,  8.19s/it]

VAE train ep2:   2%|▏         | 4/165 [00:32<21:55,  8.17s/it]

VAE train ep2:   3%|▎         | 5/165 [00:40<21:36,  8.10s/it]

VAE train ep2:   4%|▎         | 6/165 [00:48<21:14,  8.01s/it]

VAE train ep2:   4%|▍         | 7/165 [00:56<20:59,  7.97s/it]

VAE train ep2:   5%|▍         | 8/165 [01:04<20:46,  7.94s/it]

VAE train ep2:   5%|▌         | 9/165 [01:12<20:40,  7.95s/it]

VAE train ep2:   6%|▌         | 10/165 [01:20<20:42,  8.01s/it]

VAE train ep2:   7%|▋         | 11/165 [01:28<20:39,  8.05s/it]

VAE train ep2:   7%|▋         | 12/165 [01:37<20:49,  8.17s/it]

VAE train ep2:   8%|▊         | 13/165 [01:45<20:42,  8.17s/it]

VAE train ep2:   8%|▊         | 14/165 [01:53<20:22,  8.10s/it]

VAE train ep2:   9%|▉         | 15/165 [02:01<20:09,  8.06s/it]

VAE train ep2:  10%|▉         | 16/165 [02:09<20:00,  8.06s/it]

VAE train ep2:  10%|█         | 17/165 [02:17<19:49,  8.04s/it]

VAE train ep2:  11%|█         | 18/165 [02:25<19:39,  8.03s/it]

VAE train ep2:  12%|█▏        | 19/165 [02:33<19:26,  7.99s/it]

VAE train ep2:  12%|█▏        | 20/165 [02:41<19:17,  7.98s/it]

VAE train ep2:  13%|█▎        | 21/165 [02:49<19:09,  7.98s/it]

VAE train ep2:  13%|█▎        | 22/165 [02:56<19:00,  7.98s/it]

VAE train ep2:  14%|█▍        | 23/165 [03:04<18:51,  7.97s/it]

VAE train ep2:  15%|█▍        | 24/165 [03:13<18:54,  8.05s/it]

VAE train ep2:  15%|█▌        | 25/165 [03:21<18:48,  8.06s/it]

VAE train ep2:  16%|█▌        | 26/165 [03:29<18:40,  8.06s/it]

VAE train ep2:  16%|█▋        | 27/165 [03:37<18:32,  8.06s/it]

VAE train ep2:  17%|█▋        | 28/165 [03:45<18:22,  8.04s/it]

VAE train ep2:  18%|█▊        | 29/165 [03:53<18:12,  8.04s/it]

VAE train ep2:  18%|█▊        | 30/165 [04:01<18:10,  8.08s/it]

VAE train ep2:  19%|█▉        | 31/165 [04:09<18:08,  8.12s/it]

VAE train ep2:  19%|█▉        | 32/165 [04:17<17:53,  8.07s/it]

VAE train ep2:  20%|██        | 33/165 [04:25<17:46,  8.08s/it]

VAE train ep2:  21%|██        | 34/165 [04:33<17:29,  8.01s/it]

VAE train ep2:  21%|██        | 35/165 [04:41<17:22,  8.02s/it]

VAE train ep2:  22%|██▏       | 36/165 [04:49<17:03,  7.94s/it]

VAE train ep2:  22%|██▏       | 37/165 [04:57<16:53,  7.92s/it]

VAE train ep2:  23%|██▎       | 38/165 [05:05<16:46,  7.92s/it]

VAE train ep2:  24%|██▎       | 39/165 [05:13<16:37,  7.91s/it]

VAE train ep2:  24%|██▍       | 40/165 [05:21<16:32,  7.94s/it]

VAE train ep2:  25%|██▍       | 41/165 [05:29<16:23,  7.93s/it]

VAE train ep2:  25%|██▌       | 42/165 [05:36<16:09,  7.88s/it]

VAE train ep2:  26%|██▌       | 43/165 [05:44<16:01,  7.88s/it]

VAE train ep2:  27%|██▋       | 44/165 [05:52<15:58,  7.92s/it]

VAE train ep2:  27%|██▋       | 45/165 [06:00<15:51,  7.93s/it]

VAE train ep2:  28%|██▊       | 46/165 [06:08<15:41,  7.91s/it]

VAE train ep2:  28%|██▊       | 47/165 [06:16<15:39,  7.96s/it]

VAE train ep2:  29%|██▉       | 48/165 [06:24<15:32,  7.97s/it]

VAE train ep2:  30%|██▉       | 49/165 [06:32<15:37,  8.09s/it]

VAE train ep2:  30%|███       | 50/165 [06:40<15:24,  8.04s/it]

VAE train ep2:  31%|███       | 51/165 [06:48<15:13,  8.01s/it]

VAE train ep2:  32%|███▏      | 52/165 [06:56<15:05,  8.01s/it]

VAE train ep2:  32%|███▏      | 53/165 [07:04<14:59,  8.03s/it]

VAE train ep2:  33%|███▎      | 54/165 [07:12<14:50,  8.02s/it]

VAE train ep2:  33%|███▎      | 55/165 [07:20<14:34,  7.95s/it]

VAE train ep2:  34%|███▍      | 56/165 [07:28<14:27,  7.96s/it]

VAE train ep2:  35%|███▍      | 57/165 [07:36<14:21,  7.98s/it]

VAE train ep2:  35%|███▌      | 58/165 [07:44<14:13,  7.97s/it]

VAE train ep2:  36%|███▌      | 59/165 [07:52<14:02,  7.95s/it]

VAE train ep2:  36%|███▋      | 60/165 [08:00<13:51,  7.92s/it]

VAE train ep2:  37%|███▋      | 61/165 [08:08<13:49,  7.97s/it]

VAE train ep2:  38%|███▊      | 62/165 [08:16<13:43,  7.99s/it]

VAE train ep2:  38%|███▊      | 63/165 [08:24<13:40,  8.05s/it]

VAE train ep2:  39%|███▉      | 64/165 [08:32<13:34,  8.07s/it]

VAE train ep2:  39%|███▉      | 65/165 [08:40<13:24,  8.05s/it]

VAE train ep2:  40%|████      | 66/165 [08:48<13:18,  8.07s/it]

VAE train ep2:  41%|████      | 67/165 [08:57<13:16,  8.12s/it]

VAE train ep2:  41%|████      | 68/165 [09:05<13:10,  8.15s/it]

VAE train ep2:  42%|████▏     | 69/165 [09:13<13:02,  8.16s/it]

VAE train ep2:  42%|████▏     | 70/165 [09:21<12:59,  8.21s/it]

VAE train ep2:  43%|████▎     | 71/165 [09:30<12:53,  8.23s/it]

VAE train ep2:  44%|████▎     | 72/165 [09:38<12:40,  8.17s/it]

VAE train ep2:  44%|████▍     | 73/165 [09:46<12:27,  8.12s/it]

VAE train ep2:  45%|████▍     | 74/165 [09:54<12:17,  8.10s/it]

VAE train ep2:  45%|████▌     | 75/165 [10:02<12:16,  8.18s/it]

VAE train ep2:  46%|████▌     | 76/165 [10:10<12:05,  8.15s/it]

VAE train ep2:  47%|████▋     | 77/165 [10:18<11:53,  8.11s/it]

VAE train ep2:  47%|████▋     | 78/165 [10:26<11:40,  8.06s/it]

VAE train ep2:  48%|████▊     | 79/165 [10:34<11:29,  8.02s/it]

VAE train ep2:  48%|████▊     | 80/165 [10:42<11:14,  7.94s/it]

VAE train ep2:  49%|████▉     | 81/165 [10:50<11:11,  7.99s/it]

VAE train ep2:  50%|████▉     | 82/165 [10:58<11:01,  7.97s/it]

VAE train ep2:  50%|█████     | 83/165 [11:06<10:57,  8.02s/it]

VAE train ep2:  51%|█████     | 84/165 [11:14<10:54,  8.08s/it]

VAE train ep2:  52%|█████▏    | 85/165 [11:23<10:55,  8.20s/it]

VAE train ep2:  52%|█████▏    | 86/165 [11:31<10:56,  8.30s/it]

VAE train ep2:  53%|█████▎    | 87/165 [11:40<10:50,  8.34s/it]

VAE train ep2:  53%|█████▎    | 88/165 [11:48<10:38,  8.29s/it]

VAE train ep2:  54%|█████▍    | 89/165 [11:56<10:32,  8.32s/it]

VAE train ep2:  55%|█████▍    | 90/165 [12:05<10:23,  8.31s/it]

VAE train ep2:  55%|█████▌    | 91/165 [12:13<10:14,  8.30s/it]

VAE train ep2:  56%|█████▌    | 92/165 [12:21<10:02,  8.25s/it]

VAE train ep2:  56%|█████▋    | 93/165 [12:29<09:50,  8.21s/it]

VAE train ep2:  57%|█████▋    | 94/165 [12:37<09:40,  8.18s/it]

VAE train ep2:  58%|█████▊    | 95/165 [12:45<09:31,  8.16s/it]

VAE train ep2:  58%|█████▊    | 96/165 [12:53<09:20,  8.12s/it]

VAE train ep2:  59%|█████▉    | 97/165 [13:01<09:09,  8.08s/it]

VAE train ep2:  59%|█████▉    | 98/165 [13:09<08:59,  8.06s/it]

VAE train ep2:  60%|██████    | 99/165 [13:17<08:53,  8.08s/it]

VAE train ep2:  61%|██████    | 100/165 [13:26<08:44,  8.08s/it]

VAE train ep2:  61%|██████    | 101/165 [13:34<08:39,  8.11s/it]

VAE train ep2:  62%|██████▏   | 102/165 [13:42<08:29,  8.09s/it]

VAE train ep2:  62%|██████▏   | 103/165 [13:50<08:20,  8.08s/it]

VAE train ep2:  63%|██████▎   | 104/165 [13:58<08:14,  8.10s/it]

VAE train ep2:  64%|██████▎   | 105/165 [14:06<08:05,  8.08s/it]

VAE train ep2:  64%|██████▍   | 106/165 [14:14<07:57,  8.09s/it]

VAE train ep2:  65%|██████▍   | 107/165 [14:22<07:50,  8.11s/it]

VAE train ep2:  65%|██████▌   | 108/165 [14:30<07:42,  8.11s/it]

VAE train ep2:  66%|██████▌   | 109/165 [14:39<07:34,  8.12s/it]

VAE train ep2:  67%|██████▋   | 110/165 [14:47<07:25,  8.11s/it]

VAE train ep2:  67%|██████▋   | 111/165 [14:55<07:16,  8.09s/it]

VAE train ep2:  68%|██████▊   | 112/165 [15:03<07:07,  8.07s/it]

VAE train ep2:  68%|██████▊   | 113/165 [15:11<06:57,  8.03s/it]

VAE train ep2:  69%|██████▉   | 114/165 [15:19<06:49,  8.02s/it]

VAE train ep2:  70%|██████▉   | 115/165 [15:27<06:41,  8.04s/it]

VAE train ep2:  70%|███████   | 116/165 [15:35<06:34,  8.06s/it]

VAE train ep2:  71%|███████   | 117/165 [15:43<06:27,  8.07s/it]

VAE train ep2:  72%|███████▏  | 118/165 [15:51<06:19,  8.07s/it]

VAE train ep2:  72%|███████▏  | 119/165 [15:59<06:09,  8.04s/it]

VAE train ep2:  73%|███████▎  | 120/165 [16:07<06:01,  8.04s/it]

VAE train ep2:  73%|███████▎  | 121/165 [16:15<05:52,  8.01s/it]

VAE train ep2:  74%|███████▍  | 122/165 [16:23<05:47,  8.09s/it]

VAE train ep2:  75%|███████▍  | 123/165 [16:31<05:42,  8.15s/it]

VAE train ep2:  75%|███████▌  | 124/165 [16:40<05:32,  8.11s/it]

VAE train ep2:  76%|███████▌  | 125/165 [16:48<05:23,  8.08s/it]

VAE train ep2:  76%|███████▋  | 126/165 [16:56<05:15,  8.10s/it]

VAE train ep2:  77%|███████▋  | 127/165 [17:04<05:08,  8.13s/it]

VAE train ep2:  78%|███████▊  | 128/165 [17:12<05:02,  8.16s/it]

VAE train ep2:  78%|███████▊  | 129/165 [17:20<04:52,  8.12s/it]

VAE train ep2:  79%|███████▉  | 130/165 [17:28<04:44,  8.11s/it]

VAE train ep2:  79%|███████▉  | 131/165 [17:36<04:36,  8.12s/it]

VAE train ep2:  80%|████████  | 132/165 [17:45<04:29,  8.17s/it]

VAE train ep2:  81%|████████  | 133/165 [17:53<04:21,  8.17s/it]

VAE train ep2:  81%|████████  | 134/165 [18:01<04:11,  8.13s/it]

VAE train ep2:  82%|████████▏ | 135/165 [18:09<04:01,  8.05s/it]

VAE train ep2:  82%|████████▏ | 136/165 [18:17<03:53,  8.06s/it]

VAE train ep2:  83%|████████▎ | 137/165 [18:25<03:47,  8.14s/it]

VAE train ep2:  84%|████████▎ | 138/165 [18:33<03:41,  8.21s/it]

VAE train ep2:  84%|████████▍ | 139/165 [18:42<03:37,  8.36s/it]

VAE train ep2:  85%|████████▍ | 140/165 [18:51<03:32,  8.51s/it]

VAE train ep2:  85%|████████▌ | 141/165 [19:00<03:25,  8.55s/it]

VAE train ep2:  86%|████████▌ | 142/165 [19:09<03:19,  8.66s/it]

VAE train ep2:  87%|████████▋ | 143/165 [19:18<03:12,  8.75s/it]

VAE train ep2:  87%|████████▋ | 144/165 [19:26<03:02,  8.69s/it]

VAE train ep2:  88%|████████▊ | 145/165 [19:35<02:52,  8.63s/it]

VAE train ep2:  88%|████████▊ | 146/165 [19:43<02:42,  8.55s/it]

VAE train ep2:  89%|████████▉ | 147/165 [19:52<02:36,  8.67s/it]

VAE train ep2:  90%|████████▉ | 148/165 [20:01<02:27,  8.66s/it]

VAE train ep2:  90%|█████████ | 149/165 [20:09<02:17,  8.59s/it]

VAE train ep2:  91%|█████████ | 150/165 [20:18<02:08,  8.57s/it]

VAE train ep2:  92%|█████████▏| 151/165 [20:26<02:00,  8.58s/it]

VAE train ep2:  92%|█████████▏| 152/165 [20:35<01:51,  8.61s/it]

VAE train ep2:  93%|█████████▎| 153/165 [20:43<01:43,  8.60s/it]

VAE train ep2:  93%|█████████▎| 154/165 [20:52<01:33,  8.50s/it]

VAE train ep2:  94%|█████████▍| 155/165 [21:00<01:24,  8.49s/it]

VAE train ep2:  95%|█████████▍| 156/165 [21:08<01:15,  8.42s/it]

VAE train ep2:  95%|█████████▌| 157/165 [21:17<01:06,  8.34s/it]

VAE train ep2:  96%|█████████▌| 158/165 [21:25<00:58,  8.33s/it]

VAE train ep2:  96%|█████████▋| 159/165 [21:33<00:49,  8.32s/it]

VAE train ep2:  97%|█████████▋| 160/165 [21:41<00:41,  8.29s/it]

VAE train ep2:  98%|█████████▊| 161/165 [21:50<00:33,  8.28s/it]

VAE train ep2:  98%|█████████▊| 162/165 [21:58<00:24,  8.22s/it]

VAE train ep2:  99%|█████████▉| 163/165 [22:06<00:16,  8.17s/it]

VAE train ep2:  99%|█████████▉| 164/165 [22:14<00:08,  8.18s/it]

VAE train ep2: 100%|██████████| 165/165 [22:14<00:00,  5.87s/it]

VAE val ep2:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep2:   3%|▎         | 1/29 [00:02<01:02,  2.23s/it]

VAE val ep2:   7%|▋         | 2/29 [00:04<01:00,  2.23s/it]

VAE val ep2:  10%|█         | 3/29 [00:06<00:57,  2.22s/it]

VAE val ep2:  14%|█▍        | 4/29 [00:08<00:55,  2.23s/it]

VAE val ep2:  17%|█▋        | 5/29 [00:11<00:53,  2.22s/it]

VAE val ep2:  21%|██        | 6/29 [00:13<00:50,  2.21s/it]

VAE val ep2:  24%|██▍       | 7/29 [00:15<00:48,  2.19s/it]

VAE val ep2:  28%|██▊       | 8/29 [00:17<00:46,  2.20s/it]

VAE val ep2:  31%|███       | 9/29 [00:19<00:43,  2.19s/it]

VAE val ep2:  34%|███▍      | 10/29 [00:21<00:41,  2.18s/it]

VAE val ep2:  38%|███▊      | 11/29 [00:24<00:38,  2.17s/it]

VAE val ep2:  41%|████▏     | 12/29 [00:26<00:36,  2.16s/it]

VAE val ep2:  45%|████▍     | 13/29 [00:28<00:34,  2.18s/it]

VAE val ep2:  48%|████▊     | 14/29 [00:30<00:32,  2.18s/it]

VAE val ep2:  52%|█████▏    | 15/29 [00:32<00:30,  2.19s/it]

VAE val ep2:  55%|█████▌    | 16/29 [00:35<00:28,  2.19s/it]

VAE val ep2:  59%|█████▊    | 17/29 [00:37<00:26,  2.21s/it]

VAE val ep2:  62%|██████▏   | 18/29 [00:39<00:24,  2.19s/it]

VAE val ep2:  66%|██████▌   | 19/29 [00:41<00:21,  2.19s/it]

VAE val ep2:  69%|██████▉   | 20/29 [00:43<00:19,  2.18s/it]

VAE val ep2:  72%|███████▏  | 21/29 [00:46<00:17,  2.18s/it]

VAE val ep2:  76%|███████▌  | 22/29 [00:48<00:15,  2.18s/it]

VAE val ep2:  79%|███████▉  | 23/29 [00:50<00:13,  2.18s/it]

VAE val ep2:  83%|████████▎ | 24/29 [00:52<00:10,  2.17s/it]

VAE val ep2:  86%|████████▌ | 25/29 [00:54<00:08,  2.18s/it]

VAE val ep2:  90%|████████▉ | 26/29 [00:56<00:06,  2.18s/it]

VAE val ep2:  93%|█████████▎| 27/29 [00:59<00:04,  2.20s/it]

VAE val ep2:  97%|█████████▋| 28/29 [01:01<00:02,  2.20s/it]

VAE val ep2: 100%|██████████| 29/29 [01:01<00:00,  1.64s/it]

VAE train ep3:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep3:   1%|          | 1/165 [00:08<23:23,  8.56s/it]

VAE train ep3:   1%|          | 2/165 [00:17<23:04,  8.50s/it]

VAE train ep3:   2%|▏         | 3/165 [00:25<22:54,  8.48s/it]

VAE train ep3:   2%|▏         | 4/165 [00:33<22:22,  8.34s/it]

VAE train ep3:   3%|▎         | 5/165 [00:41<22:03,  8.27s/it]

VAE train ep3:   4%|▎         | 6/165 [00:49<21:49,  8.24s/it]

VAE train ep3:   4%|▍         | 7/165 [00:58<21:36,  8.21s/it]

VAE train ep3:   5%|▍         | 8/165 [01:06<21:32,  8.23s/it]

VAE train ep3:   5%|▌         | 9/165 [01:14<21:24,  8.24s/it]

VAE train ep3:   6%|▌         | 10/165 [01:22<21:14,  8.22s/it]

VAE train ep3:   7%|▋         | 11/165 [01:30<21:02,  8.19s/it]

VAE train ep3:   7%|▋         | 12/165 [01:38<20:48,  8.16s/it]

VAE train ep3:   8%|▊         | 13/165 [01:46<20:31,  8.10s/it]

VAE train ep3:   8%|▊         | 14/165 [01:54<20:15,  8.05s/it]

VAE train ep3:   9%|▉         | 15/165 [02:03<20:19,  8.13s/it]

VAE train ep3:  10%|▉         | 16/165 [02:11<20:16,  8.17s/it]

VAE train ep3:  10%|█         | 17/165 [02:19<20:15,  8.21s/it]

VAE train ep3:  11%|█         | 18/165 [02:27<20:06,  8.21s/it]

VAE train ep3:  12%|█▏        | 19/165 [02:36<19:59,  8.22s/it]

VAE train ep3:  12%|█▏        | 20/165 [02:44<19:39,  8.13s/it]

VAE train ep3:  13%|█▎        | 21/165 [02:52<19:25,  8.09s/it]

VAE train ep3:  13%|█▎        | 22/165 [03:00<19:17,  8.09s/it]

VAE train ep3:  14%|█▍        | 23/165 [03:08<19:22,  8.19s/it]

VAE train ep3:  15%|█▍        | 24/165 [03:16<19:20,  8.23s/it]

VAE train ep3:  15%|█▌        | 25/165 [03:25<19:06,  8.19s/it]

VAE train ep3:  16%|█▌        | 26/165 [03:33<18:57,  8.18s/it]

VAE train ep3:  16%|█▋        | 27/165 [03:41<18:43,  8.14s/it]

VAE train ep3:  17%|█▋        | 28/165 [03:49<18:38,  8.17s/it]

VAE train ep3:  18%|█▊        | 29/165 [03:58<18:56,  8.36s/it]

VAE train ep3:  18%|█▊        | 30/165 [04:06<18:41,  8.30s/it]

VAE train ep3:  19%|█▉        | 31/165 [04:14<18:22,  8.23s/it]

VAE train ep3:  19%|█▉        | 32/165 [04:22<18:11,  8.21s/it]

VAE train ep3:  20%|██        | 33/165 [04:30<18:05,  8.22s/it]

VAE train ep3:  21%|██        | 34/165 [04:39<18:03,  8.27s/it]

VAE train ep3:  21%|██        | 35/165 [04:47<18:05,  8.35s/it]

VAE train ep3:  22%|██▏       | 36/165 [04:56<18:16,  8.50s/it]

VAE train ep3:  22%|██▏       | 37/165 [05:05<18:09,  8.51s/it]

VAE train ep3:  23%|██▎       | 38/165 [05:13<17:53,  8.45s/it]

VAE train ep3:  24%|██▎       | 39/165 [05:22<17:46,  8.46s/it]

VAE train ep3:  24%|██▍       | 40/165 [05:30<17:28,  8.39s/it]

VAE train ep3:  25%|██▍       | 41/165 [05:38<17:06,  8.28s/it]

VAE train ep3:  25%|██▌       | 42/165 [05:46<16:50,  8.22s/it]

VAE train ep3:  26%|██▌       | 43/165 [05:54<16:36,  8.17s/it]

VAE train ep3:  27%|██▋       | 44/165 [06:02<16:26,  8.15s/it]

VAE train ep3:  27%|██▋       | 45/165 [06:10<16:16,  8.14s/it]

VAE train ep3:  28%|██▊       | 46/165 [06:18<16:05,  8.12s/it]

VAE train ep3:  28%|██▊       | 47/165 [06:26<15:57,  8.11s/it]

VAE train ep3:  29%|██▉       | 48/165 [06:35<15:52,  8.14s/it]

VAE train ep3:  30%|██▉       | 49/165 [06:43<15:47,  8.17s/it]

VAE train ep3:  30%|███       | 50/165 [06:51<15:40,  8.18s/it]

VAE train ep3:  31%|███       | 51/165 [06:59<15:32,  8.18s/it]

VAE train ep3:  32%|███▏      | 52/165 [07:07<15:28,  8.22s/it]

VAE train ep3:  32%|███▏      | 53/165 [07:16<15:20,  8.22s/it]

VAE train ep3:  33%|███▎      | 54/165 [07:24<15:12,  8.22s/it]

VAE train ep3:  33%|███▎      | 55/165 [07:32<14:59,  8.18s/it]

VAE train ep3:  34%|███▍      | 56/165 [07:40<14:43,  8.11s/it]

VAE train ep3:  35%|███▍      | 57/165 [07:48<14:31,  8.07s/it]

VAE train ep3:  35%|███▌      | 58/165 [07:56<14:16,  8.01s/it]

VAE train ep3:  36%|███▌      | 59/165 [08:04<14:06,  7.98s/it]

VAE train ep3:  36%|███▋      | 60/165 [08:12<13:58,  7.99s/it]

VAE train ep3:  37%|███▋      | 61/165 [08:20<13:47,  7.95s/it]

VAE train ep3:  38%|███▊      | 62/165 [08:27<13:36,  7.93s/it]

VAE train ep3:  38%|███▊      | 63/165 [08:36<13:34,  7.98s/it]

VAE train ep3:  39%|███▉      | 64/165 [08:44<13:27,  7.99s/it]

VAE train ep3:  39%|███▉      | 65/165 [08:52<13:21,  8.02s/it]

VAE train ep3:  40%|████      | 66/165 [09:00<13:13,  8.01s/it]

VAE train ep3:  41%|████      | 67/165 [09:07<13:00,  7.97s/it]

VAE train ep3:  41%|████      | 68/165 [09:15<12:52,  7.97s/it]

VAE train ep3:  42%|████▏     | 69/165 [09:23<12:43,  7.95s/it]

VAE train ep3:  42%|████▏     | 70/165 [09:31<12:32,  7.92s/it]

VAE train ep3:  43%|████▎     | 71/165 [09:39<12:22,  7.90s/it]

VAE train ep3:  44%|████▎     | 72/165 [09:47<12:16,  7.92s/it]

VAE train ep3:  44%|████▍     | 73/165 [09:55<12:11,  7.95s/it]

VAE train ep3:  45%|████▍     | 74/165 [10:03<12:01,  7.93s/it]

VAE train ep3:  45%|████▌     | 75/165 [10:11<11:50,  7.90s/it]

VAE train ep3:  46%|████▌     | 76/165 [10:19<11:39,  7.86s/it]

VAE train ep3:  47%|████▋     | 77/165 [10:26<11:31,  7.86s/it]

VAE train ep3:  47%|████▋     | 78/165 [10:34<11:22,  7.84s/it]

VAE train ep3:  48%|████▊     | 79/165 [10:42<11:17,  7.88s/it]

VAE train ep3:  48%|████▊     | 80/165 [10:50<11:06,  7.84s/it]

VAE train ep3:  49%|████▉     | 81/165 [10:58<10:55,  7.80s/it]

VAE train ep3:  50%|████▉     | 82/165 [11:06<10:53,  7.88s/it]

VAE train ep3:  50%|█████     | 83/165 [11:13<10:44,  7.86s/it]

VAE train ep3:  51%|█████     | 84/165 [11:21<10:37,  7.86s/it]

VAE train ep3:  52%|█████▏    | 85/165 [11:29<10:28,  7.85s/it]

VAE train ep3:  52%|█████▏    | 86/165 [11:37<10:17,  7.82s/it]

VAE train ep3:  53%|█████▎    | 87/165 [11:45<10:08,  7.80s/it]

VAE train ep3:  53%|█████▎    | 88/165 [11:53<10:01,  7.81s/it]

VAE train ep3:  54%|█████▍    | 89/165 [12:00<09:51,  7.78s/it]

VAE train ep3:  55%|█████▍    | 90/165 [12:08<09:42,  7.77s/it]

VAE train ep3:  55%|█████▌    | 91/165 [12:16<09:38,  7.81s/it]

VAE train ep3:  56%|█████▌    | 92/165 [12:23<09:24,  7.73s/it]

VAE train ep3:  56%|█████▋    | 93/165 [12:31<09:16,  7.72s/it]

VAE train ep3:  57%|█████▋    | 94/165 [12:39<09:09,  7.74s/it]

VAE train ep3:  58%|█████▊    | 95/165 [12:47<09:00,  7.73s/it]

VAE train ep3:  58%|█████▊    | 96/165 [12:54<08:53,  7.73s/it]

VAE train ep3:  59%|█████▉    | 97/165 [13:02<08:45,  7.72s/it]

VAE train ep3:  59%|█████▉    | 98/165 [13:10<08:37,  7.73s/it]

VAE train ep3:  60%|██████    | 99/165 [13:17<08:26,  7.68s/it]

VAE train ep3:  61%|██████    | 100/165 [13:25<08:21,  7.71s/it]

VAE train ep3:  61%|██████    | 101/165 [13:33<08:13,  7.71s/it]

VAE train ep3:  62%|██████▏   | 102/165 [13:41<08:07,  7.73s/it]

VAE train ep3:  62%|██████▏   | 103/165 [13:48<07:59,  7.74s/it]

VAE train ep3:  63%|██████▎   | 104/165 [13:56<07:47,  7.67s/it]

VAE train ep3:  64%|██████▎   | 105/165 [14:04<07:39,  7.66s/it]

VAE train ep3:  64%|██████▍   | 106/165 [14:11<07:35,  7.72s/it]

VAE train ep3:  65%|██████▍   | 107/165 [14:19<07:28,  7.73s/it]

VAE train ep3:  65%|██████▌   | 108/165 [14:27<07:19,  7.71s/it]

VAE train ep3:  66%|██████▌   | 109/165 [14:35<07:12,  7.73s/it]

VAE train ep3:  67%|██████▋   | 110/165 [14:42<07:04,  7.71s/it]

VAE train ep3:  67%|██████▋   | 111/165 [14:50<06:58,  7.75s/it]

VAE train ep3:  68%|██████▊   | 112/165 [14:58<06:50,  7.74s/it]

VAE train ep3:  68%|██████▊   | 113/165 [15:05<06:40,  7.70s/it]

VAE train ep3:  69%|██████▉   | 114/165 [15:13<06:34,  7.74s/it]

VAE train ep3:  70%|██████▉   | 115/165 [15:21<06:28,  7.78s/it]

VAE train ep3:  70%|███████   | 116/165 [15:29<06:21,  7.78s/it]

VAE train ep3:  71%|███████   | 117/165 [15:37<06:15,  7.83s/it]

VAE train ep3:  72%|███████▏  | 118/165 [15:45<06:06,  7.80s/it]

VAE train ep3:  72%|███████▏  | 119/165 [15:52<05:55,  7.74s/it]

VAE train ep3:  73%|███████▎  | 120/165 [16:00<05:48,  7.75s/it]

VAE train ep3:  73%|███████▎  | 121/165 [16:08<05:41,  7.76s/it]

VAE train ep3:  74%|███████▍  | 122/165 [16:16<05:34,  7.78s/it]

VAE train ep3:  75%|███████▍  | 123/165 [16:23<05:24,  7.72s/it]

VAE train ep3:  75%|███████▌  | 124/165 [16:31<05:16,  7.72s/it]

VAE train ep3:  76%|███████▌  | 125/165 [16:39<05:08,  7.70s/it]

VAE train ep3:  76%|███████▋  | 126/165 [16:46<05:00,  7.72s/it]

VAE train ep3:  77%|███████▋  | 127/165 [16:54<04:52,  7.71s/it]

VAE train ep3:  78%|███████▊  | 128/165 [17:02<04:44,  7.70s/it]

VAE train ep3:  78%|███████▊  | 129/165 [17:09<04:37,  7.70s/it]

VAE train ep3:  79%|███████▉  | 130/165 [17:17<04:29,  7.69s/it]

VAE train ep3:  79%|███████▉  | 131/165 [17:25<04:20,  7.67s/it]

VAE train ep3:  80%|████████  | 132/165 [17:33<04:16,  7.78s/it]

VAE train ep3:  81%|████████  | 133/165 [17:41<04:10,  7.82s/it]

VAE train ep3:  81%|████████  | 134/165 [17:48<04:03,  7.84s/it]

VAE train ep3:  82%|████████▏ | 135/165 [17:56<03:57,  7.90s/it]

VAE train ep3:  82%|████████▏ | 136/165 [18:04<03:49,  7.92s/it]

VAE train ep3:  83%|████████▎ | 137/165 [18:12<03:39,  7.85s/it]

VAE train ep3:  84%|████████▎ | 138/165 [18:20<03:31,  7.84s/it]

VAE train ep3:  84%|████████▍ | 139/165 [18:28<03:24,  7.88s/it]

VAE train ep3:  85%|████████▍ | 140/165 [18:36<03:16,  7.87s/it]

VAE train ep3:  85%|████████▌ | 141/165 [18:43<03:06,  7.78s/it]

VAE train ep3:  86%|████████▌ | 142/165 [18:51<02:58,  7.75s/it]

VAE train ep3:  87%|████████▋ | 143/165 [18:59<02:50,  7.74s/it]

VAE train ep3:  87%|████████▋ | 144/165 [19:07<02:43,  7.78s/it]

VAE train ep3:  88%|████████▊ | 145/165 [19:15<02:37,  7.87s/it]

VAE train ep3:  88%|████████▊ | 146/165 [19:23<02:30,  7.90s/it]

VAE train ep3:  89%|████████▉ | 147/165 [19:31<02:22,  7.89s/it]

VAE train ep3:  90%|████████▉ | 148/165 [19:38<02:14,  7.89s/it]

VAE train ep3:  90%|█████████ | 149/165 [19:46<02:06,  7.90s/it]

VAE train ep3:  91%|█████████ | 150/165 [19:54<01:57,  7.81s/it]

VAE train ep3:  92%|█████████▏| 151/165 [20:02<01:49,  7.80s/it]

VAE train ep3:  92%|█████████▏| 152/165 [20:10<01:41,  7.82s/it]

VAE train ep3:  93%|█████████▎| 153/165 [20:17<01:33,  7.83s/it]

VAE train ep3:  93%|█████████▎| 154/165 [20:25<01:26,  7.85s/it]

VAE train ep3:  94%|█████████▍| 155/165 [20:33<01:18,  7.84s/it]

VAE train ep3:  95%|█████████▍| 156/165 [20:41<01:10,  7.84s/it]

VAE train ep3:  95%|█████████▌| 157/165 [20:49<01:02,  7.82s/it]

VAE train ep3:  96%|█████████▌| 158/165 [20:57<00:54,  7.81s/it]

VAE train ep3:  96%|█████████▋| 159/165 [21:04<00:46,  7.81s/it]

VAE train ep3:  97%|█████████▋| 160/165 [21:12<00:39,  7.80s/it]

VAE train ep3:  98%|█████████▊| 161/165 [21:20<00:31,  7.78s/it]

VAE train ep3:  98%|█████████▊| 162/165 [21:28<00:23,  7.76s/it]

VAE train ep3:  99%|█████████▉| 163/165 [21:36<00:15,  7.83s/it]

VAE train ep3:  99%|█████████▉| 164/165 [21:43<00:07,  7.82s/it]

VAE train ep3: 100%|██████████| 165/165 [21:44<00:00,  5.61s/it]

VAE val ep3:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep3:   3%|▎         | 1/29 [00:02<00:59,  2.12s/it]

VAE val ep3:   7%|▋         | 2/29 [00:04<00:56,  2.11s/it]

VAE val ep3:  10%|█         | 3/29 [00:06<00:54,  2.11s/it]

VAE val ep3:  14%|█▍        | 4/29 [00:08<00:52,  2.11s/it]

VAE val ep3:  17%|█▋        | 5/29 [00:10<00:50,  2.10s/it]

VAE val ep3:  21%|██        | 6/29 [00:12<00:48,  2.11s/it]

VAE val ep3:  24%|██▍       | 7/29 [00:14<00:46,  2.11s/it]

VAE val ep3:  28%|██▊       | 8/29 [00:16<00:44,  2.11s/it]

VAE val ep3:  31%|███       | 9/29 [00:18<00:42,  2.10s/it]

VAE val ep3:  34%|███▍      | 10/29 [00:21<00:39,  2.10s/it]

VAE val ep3:  38%|███▊      | 11/29 [00:23<00:37,  2.10s/it]

VAE val ep3:  41%|████▏     | 12/29 [00:25<00:36,  2.13s/it]

VAE val ep3:  45%|████▍     | 13/29 [00:27<00:33,  2.12s/it]

VAE val ep3:  48%|████▊     | 14/29 [00:29<00:31,  2.12s/it]

VAE val ep3:  52%|█████▏    | 15/29 [00:31<00:29,  2.13s/it]

VAE val ep3:  55%|█████▌    | 16/29 [00:33<00:27,  2.14s/it]

VAE val ep3:  59%|█████▊    | 17/29 [00:36<00:25,  2.14s/it]

VAE val ep3:  62%|██████▏   | 18/29 [00:38<00:23,  2.13s/it]

VAE val ep3:  66%|██████▌   | 19/29 [00:40<00:21,  2.12s/it]

VAE val ep3:  69%|██████▉   | 20/29 [00:42<00:19,  2.13s/it]

VAE val ep3:  72%|███████▏  | 21/29 [00:44<00:16,  2.11s/it]

VAE val ep3:  76%|███████▌  | 22/29 [00:46<00:14,  2.11s/it]

VAE val ep3:  79%|███████▉  | 23/29 [00:48<00:12,  2.10s/it]

VAE val ep3:  83%|████████▎ | 24/29 [00:50<00:10,  2.09s/it]

VAE val ep3:  86%|████████▌ | 25/29 [00:52<00:08,  2.10s/it]

VAE val ep3:  90%|████████▉ | 26/29 [00:54<00:06,  2.10s/it]

VAE val ep3:  93%|█████████▎| 27/29 [00:56<00:04,  2.09s/it]

VAE val ep3:  97%|█████████▋| 28/29 [00:59<00:02,  2.08s/it]

VAE val ep3: 100%|██████████| 29/29 [00:59<00:00,  1.54s/it]

VAE train ep4:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep4:   1%|          | 1/165 [00:08<22:18,  8.16s/it]

VAE train ep4:   1%|          | 2/165 [00:16<21:41,  7.99s/it]

VAE train ep4:   2%|▏         | 3/165 [00:23<21:27,  7.95s/it]

VAE train ep4:   2%|▏         | 4/165 [00:31<21:10,  7.89s/it]

VAE train ep4:   3%|▎         | 5/165 [00:39<20:48,  7.80s/it]

VAE train ep4:   4%|▎         | 6/165 [00:47<20:40,  7.80s/it]

VAE train ep4:   4%|▍         | 7/165 [00:55<20:33,  7.81s/it]

VAE train ep4:   5%|▍         | 8/165 [01:02<20:21,  7.78s/it]

VAE train ep4:   5%|▌         | 9/165 [01:10<20:12,  7.77s/it]

VAE train ep4:   6%|▌         | 10/165 [01:18<20:16,  7.85s/it]

VAE train ep4:   7%|▋         | 11/165 [01:26<20:14,  7.88s/it]

VAE train ep4:   7%|▋         | 12/165 [01:34<20:03,  7.87s/it]

VAE train ep4:   8%|▊         | 13/165 [01:42<19:54,  7.86s/it]

VAE train ep4:   8%|▊         | 14/165 [01:49<19:40,  7.82s/it]

VAE train ep4:   9%|▉         | 15/165 [01:57<19:37,  7.85s/it]

VAE train ep4:  10%|▉         | 16/165 [02:05<19:30,  7.85s/it]

VAE train ep4:  10%|█         | 17/165 [02:13<19:20,  7.84s/it]

VAE train ep4:  11%|█         | 18/165 [02:21<19:13,  7.85s/it]

VAE train ep4:  12%|█▏        | 19/165 [02:29<19:06,  7.85s/it]

VAE train ep4:  12%|█▏        | 20/165 [02:37<19:08,  7.92s/it]

VAE train ep4:  13%|█▎        | 21/165 [02:45<18:58,  7.91s/it]

VAE train ep4:  13%|█▎        | 22/165 [02:53<18:55,  7.94s/it]

VAE train ep4:  14%|█▍        | 23/165 [03:01<18:50,  7.96s/it]

VAE train ep4:  15%|█▍        | 24/165 [03:09<18:40,  7.95s/it]

VAE train ep4:  15%|█▌        | 25/165 [03:17<18:35,  7.97s/it]

VAE train ep4:  16%|█▌        | 26/165 [03:25<18:31,  8.00s/it]

VAE train ep4:  16%|█▋        | 27/165 [03:33<18:22,  7.99s/it]

VAE train ep4:  17%|█▋        | 28/165 [03:41<18:14,  7.99s/it]

VAE train ep4:  18%|█▊        | 29/165 [03:49<18:09,  8.01s/it]

VAE train ep4:  18%|█▊        | 30/165 [03:57<18:01,  8.01s/it]

VAE train ep4:  19%|█▉        | 31/165 [04:05<17:58,  8.05s/it]

VAE train ep4:  19%|█▉        | 32/165 [04:13<17:48,  8.04s/it]

VAE train ep4:  20%|██        | 33/165 [04:21<17:37,  8.01s/it]

VAE train ep4:  21%|██        | 34/165 [04:29<17:22,  7.96s/it]

VAE train ep4:  21%|██        | 35/165 [04:37<17:15,  7.97s/it]

VAE train ep4:  22%|██▏       | 36/165 [04:45<17:08,  7.97s/it]

VAE train ep4:  22%|██▏       | 37/165 [04:53<17:00,  7.97s/it]

VAE train ep4:  23%|██▎       | 38/165 [05:00<16:46,  7.93s/it]

VAE train ep4:  24%|██▎       | 39/165 [05:08<16:35,  7.90s/it]

VAE train ep4:  24%|██▍       | 40/165 [05:16<16:27,  7.90s/it]

VAE train ep4:  25%|██▍       | 41/165 [05:24<16:21,  7.92s/it]

VAE train ep4:  25%|██▌       | 42/165 [05:32<16:11,  7.90s/it]

VAE train ep4:  26%|██▌       | 43/165 [05:40<16:04,  7.91s/it]

VAE train ep4:  27%|██▋       | 44/165 [05:48<15:53,  7.88s/it]

VAE train ep4:  27%|██▋       | 45/165 [05:56<15:48,  7.90s/it]

VAE train ep4:  28%|██▊       | 46/165 [06:04<15:41,  7.91s/it]

VAE train ep4:  28%|██▊       | 47/165 [06:12<15:36,  7.93s/it]

VAE train ep4:  29%|██▉       | 48/165 [06:19<15:25,  7.91s/it]

VAE train ep4:  30%|██▉       | 49/165 [06:27<15:16,  7.90s/it]

VAE train ep4:  30%|███       | 50/165 [06:35<15:14,  7.95s/it]

VAE train ep4:  31%|███       | 51/165 [06:43<15:03,  7.92s/it]

VAE train ep4:  32%|███▏      | 52/165 [06:51<14:54,  7.91s/it]

VAE train ep4:  32%|███▏      | 53/165 [06:59<14:45,  7.90s/it]

VAE train ep4:  33%|███▎      | 54/165 [07:07<14:37,  7.91s/it]

VAE train ep4:  33%|███▎      | 55/165 [07:15<14:34,  7.95s/it]

VAE train ep4:  34%|███▍      | 56/165 [07:23<14:24,  7.93s/it]

VAE train ep4:  35%|███▍      | 57/165 [07:31<14:12,  7.90s/it]

VAE train ep4:  35%|███▌      | 58/165 [07:39<14:04,  7.89s/it]

VAE train ep4:  36%|███▌      | 59/165 [07:47<14:01,  7.94s/it]

VAE train ep4:  36%|███▋      | 60/165 [07:55<13:54,  7.94s/it]

VAE train ep4:  37%|███▋      | 61/165 [08:02<13:46,  7.95s/it]

VAE train ep4:  38%|███▊      | 62/165 [08:10<13:35,  7.92s/it]

VAE train ep4:  38%|███▊      | 63/165 [08:18<13:26,  7.91s/it]

VAE train ep4:  39%|███▉      | 64/165 [08:26<13:21,  7.93s/it]

VAE train ep4:  39%|███▉      | 65/165 [08:34<13:10,  7.91s/it]

VAE train ep4:  40%|████      | 66/165 [08:42<12:59,  7.88s/it]

VAE train ep4:  41%|████      | 67/165 [08:50<12:48,  7.84s/it]

VAE train ep4:  41%|████      | 68/165 [08:57<12:40,  7.84s/it]

VAE train ep4:  42%|████▏     | 69/165 [09:05<12:35,  7.87s/it]

VAE train ep4:  42%|████▏     | 70/165 [09:13<12:31,  7.91s/it]

VAE train ep4:  43%|████▎     | 71/165 [09:21<12:21,  7.89s/it]

VAE train ep4:  44%|████▎     | 72/165 [09:29<12:12,  7.88s/it]

VAE train ep4:  44%|████▍     | 73/165 [09:37<12:04,  7.88s/it]

VAE train ep4:  45%|████▍     | 74/165 [09:45<11:56,  7.88s/it]

VAE train ep4:  45%|████▌     | 75/165 [09:53<11:47,  7.86s/it]

VAE train ep4:  46%|████▌     | 76/165 [10:01<11:44,  7.91s/it]

VAE train ep4:  47%|████▋     | 77/165 [10:09<11:33,  7.88s/it]

VAE train ep4:  47%|████▋     | 78/165 [10:16<11:27,  7.91s/it]

VAE train ep4:  48%|████▊     | 79/165 [10:24<11:18,  7.88s/it]

VAE train ep4:  48%|████▊     | 80/165 [10:32<11:10,  7.88s/it]

VAE train ep4:  49%|████▉     | 81/165 [10:40<11:00,  7.87s/it]

VAE train ep4:  50%|████▉     | 82/165 [10:48<10:55,  7.89s/it]

VAE train ep4:  50%|█████     | 83/165 [10:56<10:49,  7.92s/it]

VAE train ep4:  51%|█████     | 84/165 [11:04<10:43,  7.95s/it]

VAE train ep4:  52%|█████▏    | 85/165 [11:12<10:39,  7.99s/it]

VAE train ep4:  52%|█████▏    | 86/165 [11:20<10:24,  7.91s/it]

VAE train ep4:  53%|█████▎    | 87/165 [11:28<10:17,  7.92s/it]

VAE train ep4:  53%|█████▎    | 88/165 [11:36<10:10,  7.93s/it]

VAE train ep4:  54%|█████▍    | 89/165 [11:43<09:57,  7.86s/it]

VAE train ep4:  55%|█████▍    | 90/165 [11:51<09:48,  7.85s/it]

VAE train ep4:  55%|█████▌    | 91/165 [11:59<09:40,  7.84s/it]

VAE train ep4:  56%|█████▌    | 92/165 [12:07<09:31,  7.82s/it]

VAE train ep4:  56%|█████▋    | 93/165 [12:15<09:22,  7.82s/it]

VAE train ep4:  57%|█████▋    | 94/165 [12:22<09:16,  7.83s/it]

VAE train ep4:  58%|█████▊    | 95/165 [12:30<09:07,  7.83s/it]

VAE train ep4:  58%|█████▊    | 96/165 [12:38<09:01,  7.84s/it]

VAE train ep4:  59%|█████▉    | 97/165 [12:46<08:53,  7.84s/it]

VAE train ep4:  59%|█████▉    | 98/165 [12:54<08:48,  7.89s/it]

VAE train ep4:  60%|██████    | 99/165 [13:02<08:40,  7.89s/it]

VAE train ep4:  61%|██████    | 100/165 [13:10<08:34,  7.92s/it]

VAE train ep4:  61%|██████    | 101/165 [13:18<08:27,  7.94s/it]

VAE train ep4:  62%|██████▏   | 102/165 [13:26<08:20,  7.94s/it]

VAE train ep4:  62%|██████▏   | 103/165 [13:34<08:09,  7.89s/it]

VAE train ep4:  63%|██████▎   | 104/165 [13:42<08:02,  7.90s/it]

VAE train ep4:  64%|██████▎   | 105/165 [13:49<07:52,  7.88s/it]

VAE train ep4:  64%|██████▍   | 106/165 [13:57<07:44,  7.88s/it]

VAE train ep4:  65%|██████▍   | 107/165 [14:05<07:34,  7.84s/it]

VAE train ep4:  65%|██████▌   | 108/165 [14:13<07:27,  7.85s/it]

VAE train ep4:  66%|██████▌   | 109/165 [14:21<07:18,  7.82s/it]

VAE train ep4:  67%|██████▋   | 110/165 [14:28<07:09,  7.81s/it]

VAE train ep4:  67%|██████▋   | 111/165 [14:36<07:00,  7.79s/it]

VAE train ep4:  68%|██████▊   | 112/165 [14:44<06:53,  7.81s/it]

VAE train ep4:  68%|██████▊   | 113/165 [14:52<06:49,  7.88s/it]

VAE train ep4:  69%|██████▉   | 114/165 [15:00<06:41,  7.88s/it]

VAE train ep4:  70%|██████▉   | 115/165 [15:08<06:30,  7.82s/it]

VAE train ep4:  70%|███████   | 116/165 [15:16<06:25,  7.87s/it]

VAE train ep4:  71%|███████   | 117/165 [15:23<06:16,  7.83s/it]

VAE train ep4:  72%|███████▏  | 118/165 [15:31<06:07,  7.82s/it]

VAE train ep4:  72%|███████▏  | 119/165 [15:39<05:58,  7.80s/it]

VAE train ep4:  73%|███████▎  | 120/165 [15:47<05:49,  7.76s/it]

VAE train ep4:  73%|███████▎  | 121/165 [15:54<05:41,  7.76s/it]

VAE train ep4:  74%|███████▍  | 122/165 [16:02<05:35,  7.79s/it]

VAE train ep4:  75%|███████▍  | 123/165 [16:10<05:27,  7.79s/it]

VAE train ep4:  75%|███████▌  | 124/165 [16:18<05:23,  7.88s/it]

VAE train ep4:  76%|███████▌  | 125/165 [16:26<05:15,  7.89s/it]

VAE train ep4:  76%|███████▋  | 126/165 [16:34<05:07,  7.89s/it]

VAE train ep4:  77%|███████▋  | 127/165 [16:42<04:58,  7.86s/it]

VAE train ep4:  78%|███████▊  | 128/165 [16:49<04:48,  7.79s/it]

VAE train ep4:  78%|███████▊  | 129/165 [16:57<04:38,  7.75s/it]

VAE train ep4:  79%|███████▉  | 130/165 [17:05<04:31,  7.75s/it]

VAE train ep4:  79%|███████▉  | 131/165 [17:12<04:24,  7.77s/it]

VAE train ep4:  80%|████████  | 132/165 [17:20<04:15,  7.75s/it]

VAE train ep4:  81%|████████  | 133/165 [17:28<04:08,  7.75s/it]

VAE train ep4:  81%|████████  | 134/165 [17:36<04:01,  7.77s/it]

VAE train ep4:  82%|████████▏ | 135/165 [17:43<03:52,  7.75s/it]

VAE train ep4:  82%|████████▏ | 136/165 [17:51<03:44,  7.74s/it]

VAE train ep4:  83%|████████▎ | 137/165 [17:59<03:38,  7.80s/it]

VAE train ep4:  84%|████████▎ | 138/165 [18:07<03:31,  7.83s/it]

VAE train ep4:  84%|████████▍ | 139/165 [18:15<03:23,  7.84s/it]

VAE train ep4:  85%|████████▍ | 140/165 [18:23<03:15,  7.83s/it]

VAE train ep4:  85%|████████▌ | 141/165 [18:31<03:07,  7.82s/it]

VAE train ep4:  86%|████████▌ | 142/165 [18:39<03:01,  7.88s/it]

VAE train ep4:  87%|████████▋ | 143/165 [18:47<02:55,  7.96s/it]

VAE train ep4:  87%|████████▋ | 144/165 [18:54<02:45,  7.90s/it]

VAE train ep4:  88%|████████▊ | 145/165 [19:02<02:37,  7.90s/it]

VAE train ep4:  88%|████████▊ | 146/165 [19:10<02:30,  7.91s/it]

VAE train ep4:  89%|████████▉ | 147/165 [19:18<02:22,  7.93s/it]

VAE train ep4:  90%|████████▉ | 148/165 [19:27<02:16,  8.04s/it]

VAE train ep4:  90%|█████████ | 149/165 [19:35<02:09,  8.11s/it]

VAE train ep4:  91%|█████████ | 150/165 [19:43<02:03,  8.22s/it]

VAE train ep4:  92%|█████████▏| 151/165 [19:52<01:55,  8.23s/it]

VAE train ep4:  92%|█████████▏| 152/165 [20:00<01:47,  8.27s/it]

VAE train ep4:  93%|█████████▎| 153/165 [20:09<01:40,  8.39s/it]

VAE train ep4:  93%|█████████▎| 154/165 [20:17<01:33,  8.53s/it]

VAE train ep4:  94%|█████████▍| 155/165 [20:27<01:26,  8.69s/it]

VAE train ep4:  95%|█████████▍| 156/165 [20:35<01:18,  8.76s/it]

VAE train ep4:  95%|█████████▌| 157/165 [20:44<01:09,  8.70s/it]

VAE train ep4:  96%|█████████▌| 158/165 [20:52<01:00,  8.58s/it]

VAE train ep4:  96%|█████████▋| 159/165 [21:00<00:50,  8.40s/it]

VAE train ep4:  97%|█████████▋| 160/165 [21:08<00:41,  8.28s/it]

VAE train ep4:  98%|█████████▊| 161/165 [21:16<00:32,  8.24s/it]

VAE train ep4:  98%|█████████▊| 162/165 [21:24<00:24,  8.19s/it]

VAE train ep4:  99%|█████████▉| 163/165 [21:33<00:16,  8.16s/it]

VAE train ep4:  99%|█████████▉| 164/165 [21:41<00:08,  8.19s/it]

VAE train ep4: 100%|██████████| 165/165 [21:41<00:00,  5.89s/it]

VAE val ep4:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep4:   3%|▎         | 1/29 [00:02<01:02,  2.22s/it]

VAE val ep4:   7%|▋         | 2/29 [00:04<00:59,  2.21s/it]

VAE val ep4:  10%|█         | 3/29 [00:06<00:57,  2.22s/it]

VAE val ep4:  14%|█▍        | 4/29 [00:08<00:55,  2.23s/it]

VAE val ep4:  17%|█▋        | 5/29 [00:11<00:53,  2.25s/it]

VAE val ep4:  21%|██        | 6/29 [00:13<00:51,  2.23s/it]

VAE val ep4:  24%|██▍       | 7/29 [00:15<00:48,  2.22s/it]

VAE val ep4:  28%|██▊       | 8/29 [00:17<00:46,  2.22s/it]

VAE val ep4:  31%|███       | 9/29 [00:20<00:44,  2.23s/it]

VAE val ep4:  34%|███▍      | 10/29 [00:22<00:42,  2.23s/it]

VAE val ep4:  38%|███▊      | 11/29 [00:24<00:39,  2.20s/it]

VAE val ep4:  41%|████▏     | 12/29 [00:26<00:37,  2.19s/it]

VAE val ep4:  45%|████▍     | 13/29 [00:28<00:35,  2.19s/it]

VAE val ep4:  48%|████▊     | 14/29 [00:31<00:33,  2.21s/it]

VAE val ep4:  52%|█████▏    | 15/29 [00:33<00:30,  2.20s/it]

VAE val ep4:  55%|█████▌    | 16/29 [00:35<00:28,  2.21s/it]

VAE val ep4:  59%|█████▊    | 17/29 [00:37<00:26,  2.20s/it]

VAE val ep4:  62%|██████▏   | 18/29 [00:39<00:24,  2.20s/it]

VAE val ep4:  66%|██████▌   | 19/29 [00:42<00:22,  2.20s/it]

VAE val ep4:  69%|██████▉   | 20/29 [00:44<00:19,  2.20s/it]

VAE val ep4:  72%|███████▏  | 21/29 [00:46<00:17,  2.20s/it]

VAE val ep4:  76%|███████▌  | 22/29 [00:48<00:15,  2.20s/it]

VAE val ep4:  79%|███████▉  | 23/29 [00:50<00:13,  2.23s/it]

VAE val ep4:  83%|████████▎ | 24/29 [00:53<00:11,  2.23s/it]

VAE val ep4:  86%|████████▌ | 25/29 [00:55<00:08,  2.22s/it]

VAE val ep4:  90%|████████▉ | 26/29 [00:57<00:06,  2.21s/it]

VAE val ep4:  93%|█████████▎| 27/29 [00:59<00:04,  2.21s/it]

VAE val ep4:  97%|█████████▋| 28/29 [01:01<00:02,  2.20s/it]

VAE val ep4: 100%|██████████| 29/29 [01:02<00:00,  1.63s/it]

VAE train ep5:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep5:   1%|          | 1/165 [00:08<22:42,  8.31s/it]

VAE train ep5:   1%|          | 2/165 [00:16<22:27,  8.26s/it]

VAE train ep5:   2%|▏         | 3/165 [00:24<22:19,  8.27s/it]

VAE train ep5:   2%|▏         | 4/165 [00:33<22:10,  8.26s/it]

VAE train ep5:   3%|▎         | 5/165 [00:41<21:44,  8.15s/it]

VAE train ep5:   4%|▎         | 6/165 [00:49<21:30,  8.12s/it]

VAE train ep5:   4%|▍         | 7/165 [00:57<21:18,  8.09s/it]

VAE train ep5:   5%|▍         | 8/165 [01:05<21:08,  8.08s/it]

VAE train ep5:   5%|▌         | 9/165 [01:13<21:01,  8.09s/it]

VAE train ep5:   6%|▌         | 10/165 [01:21<20:47,  8.05s/it]

VAE train ep5:   7%|▋         | 11/165 [01:29<20:27,  7.97s/it]

VAE train ep5:   7%|▋         | 12/165 [01:36<20:12,  7.93s/it]

VAE train ep5:   8%|▊         | 13/165 [01:44<20:02,  7.91s/it]

VAE train ep5:   8%|▊         | 14/165 [01:52<19:56,  7.93s/it]

VAE train ep5:   9%|▉         | 15/165 [02:00<19:54,  7.97s/it]

VAE train ep5:  10%|▉         | 16/165 [02:08<19:46,  7.97s/it]

VAE train ep5:  10%|█         | 17/165 [02:16<19:51,  8.05s/it]

VAE train ep5:  11%|█         | 18/165 [02:25<19:50,  8.10s/it]

VAE train ep5:  12%|█▏        | 19/165 [02:33<19:42,  8.10s/it]

VAE train ep5:  12%|█▏        | 20/165 [02:41<19:37,  8.12s/it]

VAE train ep5:  13%|█▎        | 21/165 [02:49<19:32,  8.14s/it]

VAE train ep5:  13%|█▎        | 22/165 [02:58<19:50,  8.33s/it]

VAE train ep5:  14%|█▍        | 23/165 [03:06<19:40,  8.32s/it]

VAE train ep5:  15%|█▍        | 24/165 [03:14<19:19,  8.23s/it]

VAE train ep5:  15%|█▌        | 25/165 [03:22<19:02,  8.16s/it]

VAE train ep5:  16%|█▌        | 26/165 [03:30<18:50,  8.14s/it]

VAE train ep5:  16%|█▋        | 27/165 [03:38<18:40,  8.12s/it]

VAE train ep5:  17%|█▋        | 28/165 [03:46<18:23,  8.05s/it]

VAE train ep5:  18%|█▊        | 29/165 [03:54<18:11,  8.03s/it]

VAE train ep5:  18%|█▊        | 30/165 [04:02<18:02,  8.02s/it]

VAE train ep5:  19%|█▉        | 31/165 [04:10<17:52,  8.00s/it]

VAE train ep5:  19%|█▉        | 32/165 [04:19<17:56,  8.10s/it]

VAE train ep5:  20%|██        | 33/165 [04:26<17:42,  8.05s/it]

VAE train ep5:  21%|██        | 34/165 [04:35<17:42,  8.11s/it]

VAE train ep5:  21%|██        | 35/165 [04:43<17:40,  8.15s/it]

VAE train ep5:  22%|██▏       | 36/165 [04:51<17:32,  8.16s/it]

VAE train ep5:  22%|██▏       | 37/165 [04:59<17:29,  8.20s/it]

VAE train ep5:  23%|██▎       | 38/165 [05:08<17:18,  8.18s/it]

VAE train ep5:  24%|██▎       | 39/165 [05:16<17:14,  8.21s/it]

VAE train ep5:  24%|██▍       | 40/165 [05:24<17:04,  8.19s/it]

VAE train ep5:  25%|██▍       | 41/165 [05:32<16:59,  8.23s/it]

VAE train ep5:  25%|██▌       | 42/165 [05:41<16:56,  8.26s/it]

VAE train ep5:  26%|██▌       | 43/165 [05:49<16:44,  8.23s/it]

VAE train ep5:  27%|██▋       | 44/165 [05:57<16:31,  8.20s/it]

VAE train ep5:  27%|██▋       | 45/165 [06:05<16:24,  8.20s/it]

VAE train ep5:  28%|██▊       | 46/165 [06:13<16:14,  8.19s/it]

VAE train ep5:  28%|██▊       | 47/165 [06:22<16:18,  8.30s/it]

VAE train ep5:  29%|██▉       | 48/165 [06:30<16:13,  8.32s/it]

VAE train ep5:  30%|██▉       | 49/165 [06:39<16:03,  8.31s/it]

VAE train ep5:  30%|███       | 50/165 [06:47<16:01,  8.36s/it]

VAE train ep5:  31%|███       | 51/165 [06:55<15:46,  8.30s/it]

VAE train ep5:  32%|███▏      | 52/165 [07:04<15:51,  8.42s/it]

VAE train ep5:  32%|███▏      | 53/165 [07:13<15:52,  8.50s/it]

VAE train ep5:  33%|███▎      | 54/165 [07:21<15:46,  8.52s/it]

VAE train ep5:  33%|███▎      | 55/165 [07:30<15:37,  8.52s/it]

VAE train ep5:  34%|███▍      | 56/165 [07:38<15:31,  8.55s/it]

VAE train ep5:  35%|███▍      | 57/165 [07:47<15:27,  8.58s/it]

VAE train ep5:  35%|███▌      | 58/165 [07:56<15:29,  8.68s/it]

VAE train ep5:  36%|███▌      | 59/165 [08:04<15:19,  8.67s/it]

VAE train ep5:  36%|███▋      | 60/165 [08:13<14:54,  8.52s/it]

VAE train ep5:  37%|███▋      | 61/165 [08:21<14:40,  8.47s/it]

VAE train ep5:  38%|███▊      | 62/165 [08:29<14:24,  8.39s/it]

VAE train ep5:  38%|███▊      | 63/165 [08:37<14:05,  8.29s/it]

VAE train ep5:  39%|███▉      | 64/165 [08:46<13:56,  8.28s/it]

VAE train ep5:  39%|███▉      | 65/165 [08:54<13:40,  8.21s/it]

VAE train ep5:  40%|████      | 66/165 [09:02<13:35,  8.24s/it]

VAE train ep5:  41%|████      | 67/165 [09:10<13:18,  8.15s/it]

VAE train ep5:  41%|████      | 68/165 [09:18<13:09,  8.14s/it]

VAE train ep5:  42%|████▏     | 69/165 [09:26<12:57,  8.10s/it]

VAE train ep5:  42%|████▏     | 70/165 [09:34<12:53,  8.14s/it]

VAE train ep5:  43%|████▎     | 71/165 [09:42<12:44,  8.14s/it]

VAE train ep5:  44%|████▎     | 72/165 [09:50<12:33,  8.10s/it]

VAE train ep5:  44%|████▍     | 73/165 [09:58<12:19,  8.04s/it]

VAE train ep5:  45%|████▍     | 74/165 [10:06<12:09,  8.01s/it]

VAE train ep5:  45%|████▌     | 75/165 [10:14<12:04,  8.05s/it]

VAE train ep5:  46%|████▌     | 76/165 [10:22<11:55,  8.04s/it]

VAE train ep5:  47%|████▋     | 77/165 [10:30<11:43,  8.00s/it]

VAE train ep5:  47%|████▋     | 78/165 [10:38<11:33,  7.97s/it]

VAE train ep5:  48%|████▊     | 79/165 [10:46<11:31,  8.04s/it]

VAE train ep5:  48%|████▊     | 80/165 [10:54<11:24,  8.05s/it]

VAE train ep5:  49%|████▉     | 81/165 [11:02<11:15,  8.04s/it]

VAE train ep5:  50%|████▉     | 82/165 [11:10<11:07,  8.04s/it]

VAE train ep5:  50%|█████     | 83/165 [11:18<10:58,  8.03s/it]

VAE train ep5:  51%|█████     | 84/165 [11:26<10:49,  8.02s/it]

VAE train ep5:  52%|█████▏    | 85/165 [11:34<10:39,  7.99s/it]

VAE train ep5:  52%|█████▏    | 86/165 [11:42<10:28,  7.95s/it]

VAE train ep5:  53%|█████▎    | 87/165 [11:50<10:16,  7.90s/it]

VAE train ep5:  53%|█████▎    | 88/165 [11:58<10:06,  7.88s/it]

VAE train ep5:  54%|█████▍    | 89/165 [12:06<09:57,  7.86s/it]

VAE train ep5:  55%|█████▍    | 90/165 [12:14<09:54,  7.93s/it]

VAE train ep5:  55%|█████▌    | 91/165 [12:22<09:47,  7.94s/it]

VAE train ep5:  56%|█████▌    | 92/165 [12:30<09:37,  7.91s/it]

VAE train ep5:  56%|█████▋    | 93/165 [12:37<09:28,  7.89s/it]

VAE train ep5:  57%|█████▋    | 94/165 [12:45<09:18,  7.86s/it]

VAE train ep5:  58%|█████▊    | 95/165 [12:53<09:13,  7.90s/it]

VAE train ep5:  58%|█████▊    | 96/165 [13:01<09:04,  7.89s/it]

VAE train ep5:  59%|█████▉    | 97/165 [13:09<08:56,  7.89s/it]

VAE train ep5:  59%|█████▉    | 98/165 [13:17<08:47,  7.88s/it]

VAE train ep5:  60%|██████    | 99/165 [13:25<08:38,  7.86s/it]

VAE train ep5:  61%|██████    | 100/165 [13:32<08:30,  7.86s/it]

VAE train ep5:  61%|██████    | 101/165 [13:40<08:23,  7.86s/it]

VAE train ep5:  62%|██████▏   | 102/165 [13:48<08:17,  7.89s/it]

VAE train ep5:  62%|██████▏   | 103/165 [13:56<08:10,  7.92s/it]

VAE train ep5:  63%|██████▎   | 104/165 [14:04<08:01,  7.89s/it]

VAE train ep5:  64%|██████▎   | 105/165 [14:12<07:53,  7.89s/it]

VAE train ep5:  64%|██████▍   | 106/165 [14:20<07:43,  7.86s/it]

VAE train ep5:  65%|██████▍   | 107/165 [14:28<07:36,  7.87s/it]

VAE train ep5:  65%|██████▌   | 108/165 [14:35<07:27,  7.85s/it]

VAE train ep5:  66%|██████▌   | 109/165 [14:43<07:20,  7.87s/it]

VAE train ep5:  67%|██████▋   | 110/165 [14:51<07:11,  7.85s/it]

VAE train ep5:  67%|██████▋   | 111/165 [14:59<07:06,  7.90s/it]

VAE train ep5:  68%|██████▊   | 112/165 [15:07<06:58,  7.89s/it]

VAE train ep5:  68%|██████▊   | 113/165 [15:15<06:50,  7.89s/it]

VAE train ep5:  69%|██████▉   | 114/165 [15:23<06:40,  7.86s/it]

VAE train ep5:  70%|██████▉   | 115/165 [15:31<06:32,  7.84s/it]

VAE train ep5:  70%|███████   | 116/165 [15:38<06:24,  7.84s/it]

VAE train ep5:  71%|███████   | 117/165 [15:46<06:18,  7.88s/it]

VAE train ep5:  72%|███████▏  | 118/165 [15:54<06:09,  7.87s/it]

VAE train ep5:  72%|███████▏  | 119/165 [16:02<06:02,  7.87s/it]

VAE train ep5:  73%|███████▎  | 120/165 [16:10<05:53,  7.86s/it]

VAE train ep5:  73%|███████▎  | 121/165 [16:18<05:46,  7.87s/it]

VAE train ep5:  74%|███████▍  | 122/165 [16:26<05:37,  7.85s/it]

VAE train ep5:  75%|███████▍  | 123/165 [16:33<05:27,  7.81s/it]

VAE train ep5:  75%|███████▌  | 124/165 [16:41<05:19,  7.80s/it]

VAE train ep5:  76%|███████▌  | 125/165 [16:49<05:14,  7.86s/it]

VAE train ep5:  76%|███████▋  | 126/165 [16:57<05:07,  7.88s/it]

VAE train ep5:  77%|███████▋  | 127/165 [17:05<04:59,  7.88s/it]

VAE train ep5:  78%|███████▊  | 128/165 [17:13<04:51,  7.88s/it]

VAE train ep5:  78%|███████▊  | 129/165 [17:21<04:42,  7.86s/it]

VAE train ep5:  79%|███████▉  | 130/165 [17:28<04:34,  7.85s/it]

VAE train ep5:  79%|███████▉  | 131/165 [17:36<04:26,  7.83s/it]

VAE train ep5:  80%|████████  | 132/165 [17:44<04:18,  7.84s/it]

VAE train ep5:  81%|████████  | 133/165 [17:52<04:11,  7.84s/it]

VAE train ep5:  81%|████████  | 134/165 [18:00<04:02,  7.83s/it]

VAE train ep5:  82%|████████▏ | 135/165 [18:07<03:54,  7.81s/it]

VAE train ep5:  82%|████████▏ | 136/165 [18:15<03:46,  7.82s/it]

VAE train ep5:  83%|████████▎ | 137/165 [18:23<03:37,  7.78s/it]

VAE train ep5:  84%|████████▎ | 138/165 [18:31<03:31,  7.84s/it]

VAE train ep5:  84%|████████▍ | 139/165 [18:39<03:25,  7.90s/it]

VAE train ep5:  85%|████████▍ | 140/165 [18:47<03:18,  7.95s/it]

VAE train ep5:  85%|████████▌ | 141/165 [18:55<03:11,  7.97s/it]

VAE train ep5:  86%|████████▌ | 142/165 [19:03<03:02,  7.94s/it]

VAE train ep5:  87%|████████▋ | 143/165 [19:11<02:54,  7.95s/it]

VAE train ep5:  87%|████████▋ | 144/165 [19:19<02:46,  7.93s/it]

VAE train ep5:  88%|████████▊ | 145/165 [19:27<02:37,  7.89s/it]

VAE train ep5:  88%|████████▊ | 146/165 [19:34<02:29,  7.88s/it]

VAE train ep5:  89%|████████▉ | 147/165 [19:42<02:21,  7.88s/it]

VAE train ep5:  90%|████████▉ | 148/165 [19:50<02:13,  7.85s/it]

VAE train ep5:  90%|█████████ | 149/165 [19:58<02:05,  7.86s/it]

VAE train ep5:  91%|█████████ | 150/165 [20:06<01:58,  7.87s/it]

VAE train ep5:  92%|█████████▏| 151/165 [20:14<01:49,  7.84s/it]

VAE train ep5:  92%|█████████▏| 152/165 [20:22<01:41,  7.84s/it]

VAE train ep5:  93%|█████████▎| 153/165 [20:29<01:33,  7.77s/it]

VAE train ep5:  93%|█████████▎| 154/165 [20:37<01:25,  7.78s/it]

VAE train ep5:  94%|█████████▍| 155/165 [20:45<01:18,  7.81s/it]

VAE train ep5:  95%|█████████▍| 156/165 [20:53<01:10,  7.85s/it]

VAE train ep5:  95%|█████████▌| 157/165 [21:01<01:02,  7.84s/it]

VAE train ep5:  96%|█████████▌| 158/165 [21:08<00:54,  7.85s/it]

VAE train ep5:  96%|█████████▋| 159/165 [21:16<00:46,  7.81s/it]

VAE train ep5:  97%|█████████▋| 160/165 [21:24<00:39,  7.84s/it]

VAE train ep5:  98%|█████████▊| 161/165 [21:32<00:31,  7.88s/it]

VAE train ep5:  98%|█████████▊| 162/165 [21:40<00:23,  7.88s/it]

VAE train ep5:  99%|█████████▉| 163/165 [21:48<00:15,  7.91s/it]

VAE train ep5:  99%|█████████▉| 164/165 [21:56<00:07,  7.94s/it]

VAE train ep5: 100%|██████████| 165/165 [21:56<00:00,  5.71s/it]

VAE val ep5:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep5:   3%|▎         | 1/29 [00:02<01:01,  2.20s/it]

VAE val ep5:   7%|▋         | 2/29 [00:04<00:57,  2.15s/it]

VAE val ep5:  10%|█         | 3/29 [00:06<00:55,  2.13s/it]

VAE val ep5:  14%|█▍        | 4/29 [00:08<00:53,  2.14s/it]

VAE val ep5:  17%|█▋        | 5/29 [00:10<00:51,  2.14s/it]

VAE val ep5:  21%|██        | 6/29 [00:12<00:48,  2.13s/it]

VAE val ep5:  24%|██▍       | 7/29 [00:14<00:46,  2.13s/it]

VAE val ep5:  28%|██▊       | 8/29 [00:17<00:44,  2.13s/it]

VAE val ep5:  31%|███       | 9/29 [00:19<00:42,  2.14s/it]

VAE val ep5:  34%|███▍      | 10/29 [00:21<00:41,  2.16s/it]

VAE val ep5:  38%|███▊      | 11/29 [00:23<00:38,  2.15s/it]

VAE val ep5:  41%|████▏     | 12/29 [00:25<00:36,  2.14s/it]

VAE val ep5:  45%|████▍     | 13/29 [00:27<00:34,  2.13s/it]

VAE val ep5:  48%|████▊     | 14/29 [00:29<00:31,  2.13s/it]

VAE val ep5:  52%|█████▏    | 15/29 [00:32<00:29,  2.14s/it]

VAE val ep5:  55%|█████▌    | 16/29 [00:34<00:27,  2.14s/it]

VAE val ep5:  59%|█████▊    | 17/29 [00:36<00:25,  2.15s/it]

VAE val ep5:  62%|██████▏   | 18/29 [00:38<00:23,  2.14s/it]

VAE val ep5:  66%|██████▌   | 19/29 [00:40<00:21,  2.15s/it]

VAE val ep5:  69%|██████▉   | 20/29 [00:42<00:19,  2.14s/it]

VAE val ep5:  72%|███████▏  | 21/29 [00:44<00:17,  2.13s/it]

VAE val ep5:  76%|███████▌  | 22/29 [00:47<00:14,  2.14s/it]

VAE val ep5:  79%|███████▉  | 23/29 [00:49<00:12,  2.14s/it]

VAE val ep5:  83%|████████▎ | 24/29 [00:51<00:10,  2.15s/it]

VAE val ep5:  86%|████████▌ | 25/29 [00:53<00:08,  2.14s/it]

VAE val ep5:  90%|████████▉ | 26/29 [00:55<00:06,  2.14s/it]

VAE val ep5:  93%|█████████▎| 27/29 [00:57<00:04,  2.13s/it]

VAE val ep5:  97%|█████████▋| 28/29 [00:59<00:02,  2.12s/it]

VAE val ep5: 100%|██████████| 29/29 [01:00<00:00,  1.57s/it]

VAE train ep6:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep6:   1%|          | 1/165 [00:08<22:45,  8.33s/it]

VAE train ep6:   1%|          | 2/165 [00:16<22:34,  8.31s/it]

VAE train ep6:   2%|▏         | 3/165 [00:24<22:07,  8.20s/it]

VAE train ep6:   2%|▏         | 4/165 [00:32<21:53,  8.16s/it]

VAE train ep6:   3%|▎         | 5/165 [00:40<21:35,  8.10s/it]

VAE train ep6:   4%|▎         | 6/165 [00:48<21:30,  8.11s/it]

VAE train ep6:   4%|▍         | 7/165 [00:57<21:35,  8.20s/it]

VAE train ep6:   5%|▍         | 8/165 [01:05<21:38,  8.27s/it]

VAE train ep6:   5%|▌         | 9/165 [01:13<21:26,  8.25s/it]

VAE train ep6:   6%|▌         | 10/165 [01:22<21:19,  8.25s/it]

VAE train ep6:   7%|▋         | 11/165 [01:30<21:06,  8.23s/it]

VAE train ep6:   7%|▋         | 12/165 [01:38<20:57,  8.22s/it]

VAE train ep6:   8%|▊         | 13/165 [01:46<20:58,  8.28s/it]

VAE train ep6:   8%|▊         | 14/165 [01:55<20:45,  8.25s/it]

VAE train ep6:   9%|▉         | 15/165 [02:03<20:31,  8.21s/it]

VAE train ep6:  10%|▉         | 16/165 [02:12<20:47,  8.37s/it]

VAE train ep6:  10%|█         | 17/165 [02:20<20:28,  8.30s/it]

VAE train ep6:  11%|█         | 18/165 [02:28<20:15,  8.27s/it]

VAE train ep6:  12%|█▏        | 19/165 [02:36<20:16,  8.33s/it]

VAE train ep6:  12%|█▏        | 20/165 [02:45<20:05,  8.31s/it]

VAE train ep6:  13%|█▎        | 21/165 [02:53<19:52,  8.28s/it]

VAE train ep6:  13%|█▎        | 22/165 [03:01<19:43,  8.28s/it]

VAE train ep6:  14%|█▍        | 23/165 [03:09<19:30,  8.25s/it]

VAE train ep6:  15%|█▍        | 24/165 [03:17<19:20,  8.23s/it]

VAE train ep6:  15%|█▌        | 25/165 [03:25<19:01,  8.15s/it]

VAE train ep6:  16%|█▌        | 26/165 [03:33<18:49,  8.12s/it]

VAE train ep6:  16%|█▋        | 27/165 [03:42<18:40,  8.12s/it]

VAE train ep6:  17%|█▋        | 28/165 [03:50<18:38,  8.17s/it]

VAE train ep6:  18%|█▊        | 29/165 [03:58<18:27,  8.14s/it]

VAE train ep6:  18%|█▊        | 30/165 [04:06<18:21,  8.16s/it]

VAE train ep6:  19%|█▉        | 31/165 [04:14<18:14,  8.17s/it]

VAE train ep6:  19%|█▉        | 32/165 [04:22<18:06,  8.17s/it]

VAE train ep6:  20%|██        | 33/165 [04:30<17:51,  8.12s/it]

VAE train ep6:  21%|██        | 34/165 [04:39<17:42,  8.11s/it]

VAE train ep6:  21%|██        | 35/165 [04:47<17:37,  8.13s/it]

VAE train ep6:  22%|██▏       | 36/165 [04:55<17:21,  8.07s/it]

VAE train ep6:  22%|██▏       | 37/165 [05:03<17:14,  8.08s/it]

VAE train ep6:  23%|██▎       | 38/165 [05:11<17:14,  8.15s/it]

VAE train ep6:  24%|██▎       | 39/165 [05:19<17:05,  8.14s/it]

VAE train ep6:  24%|██▍       | 40/165 [05:27<16:59,  8.16s/it]

VAE train ep6:  25%|██▍       | 41/165 [05:36<16:50,  8.15s/it]

VAE train ep6:  25%|██▌       | 42/165 [05:44<16:38,  8.12s/it]

VAE train ep6:  26%|██▌       | 43/165 [05:52<16:33,  8.14s/it]

VAE train ep6:  27%|██▋       | 44/165 [06:00<16:14,  8.06s/it]

VAE train ep6:  27%|██▋       | 45/165 [06:08<16:04,  8.04s/it]

VAE train ep6:  28%|██▊       | 46/165 [06:16<15:55,  8.03s/it]

VAE train ep6:  28%|██▊       | 47/165 [06:24<15:48,  8.04s/it]

VAE train ep6:  29%|██▉       | 48/165 [06:32<15:46,  8.09s/it]

VAE train ep6:  30%|██▉       | 49/165 [06:40<15:35,  8.06s/it]

VAE train ep6:  30%|███       | 50/165 [06:48<15:20,  8.01s/it]

VAE train ep6:  31%|███       | 51/165 [06:56<15:12,  8.00s/it]

VAE train ep6:  32%|███▏      | 52/165 [07:04<15:02,  7.99s/it]

VAE train ep6:  32%|███▏      | 53/165 [07:12<14:54,  7.99s/it]

VAE train ep6:  33%|███▎      | 54/165 [07:20<14:43,  7.96s/it]

VAE train ep6:  33%|███▎      | 55/165 [07:28<14:35,  7.96s/it]

VAE train ep6:  34%|███▍      | 56/165 [07:36<14:32,  8.00s/it]

VAE train ep6:  35%|███▍      | 57/165 [07:44<14:27,  8.03s/it]

VAE train ep6:  35%|███▌      | 58/165 [07:52<14:26,  8.10s/it]

VAE train ep6:  36%|███▌      | 59/165 [08:00<14:13,  8.05s/it]

VAE train ep6:  36%|███▋      | 60/165 [08:08<14:01,  8.02s/it]

VAE train ep6:  37%|███▋      | 61/165 [08:16<13:53,  8.02s/it]

VAE train ep6:  38%|███▊      | 62/165 [08:24<13:41,  7.97s/it]

VAE train ep6:  38%|███▊      | 63/165 [08:32<13:31,  7.95s/it]

VAE train ep6:  39%|███▉      | 64/165 [08:39<13:17,  7.90s/it]

VAE train ep6:  39%|███▉      | 65/165 [08:47<13:09,  7.89s/it]

VAE train ep6:  40%|████      | 66/165 [08:55<13:01,  7.89s/it]

VAE train ep6:  41%|████      | 67/165 [09:03<12:56,  7.93s/it]

VAE train ep6:  41%|████      | 68/165 [09:11<12:49,  7.93s/it]

VAE train ep6:  42%|████▏     | 69/165 [09:19<12:38,  7.90s/it]

VAE train ep6:  42%|████▏     | 70/165 [09:27<12:29,  7.89s/it]

VAE train ep6:  43%|████▎     | 71/165 [09:35<12:21,  7.89s/it]

VAE train ep6:  44%|████▎     | 72/165 [09:43<12:17,  7.93s/it]

VAE train ep6:  44%|████▍     | 73/165 [09:51<12:08,  7.92s/it]

VAE train ep6:  45%|████▍     | 74/165 [09:59<11:59,  7.90s/it]

VAE train ep6:  45%|████▌     | 75/165 [10:06<11:51,  7.90s/it]

VAE train ep6:  46%|████▌     | 76/165 [10:14<11:39,  7.86s/it]

VAE train ep6:  47%|████▋     | 77/165 [10:22<11:33,  7.88s/it]

VAE train ep6:  47%|████▋     | 78/165 [10:30<11:23,  7.86s/it]

VAE train ep6:  48%|████▊     | 79/165 [10:38<11:15,  7.85s/it]

VAE train ep6:  48%|████▊     | 80/165 [10:46<11:09,  7.88s/it]

VAE train ep6:  49%|████▉     | 81/165 [10:54<10:59,  7.85s/it]

VAE train ep6:  50%|████▉     | 82/165 [11:01<10:51,  7.85s/it]

VAE train ep6:  50%|█████     | 83/165 [11:09<10:43,  7.84s/it]

VAE train ep6:  51%|█████     | 84/165 [11:17<10:33,  7.82s/it]

VAE train ep6:  52%|█████▏    | 85/165 [11:25<10:24,  7.80s/it]

VAE train ep6:  52%|█████▏    | 86/165 [11:33<10:20,  7.86s/it]

VAE train ep6:  53%|█████▎    | 87/165 [11:41<10:13,  7.86s/it]

VAE train ep6:  53%|█████▎    | 88/165 [11:48<10:03,  7.83s/it]

VAE train ep6:  54%|█████▍    | 89/165 [11:56<09:57,  7.86s/it]

VAE train ep6:  55%|█████▍    | 90/165 [12:04<09:51,  7.88s/it]

VAE train ep6:  55%|█████▌    | 91/165 [12:12<09:44,  7.89s/it]

VAE train ep6:  56%|█████▌    | 92/165 [12:20<09:37,  7.91s/it]

VAE train ep6:  56%|█████▋    | 93/165 [12:28<09:27,  7.88s/it]

VAE train ep6:  57%|█████▋    | 94/165 [12:36<09:18,  7.87s/it]

VAE train ep6:  58%|█████▊    | 95/165 [12:44<09:10,  7.87s/it]

VAE train ep6:  58%|█████▊    | 96/165 [12:52<09:06,  7.92s/it]

VAE train ep6:  59%|█████▉    | 97/165 [13:00<09:01,  7.96s/it]

VAE train ep6:  59%|█████▉    | 98/165 [13:08<08:53,  7.97s/it]

VAE train ep6:  60%|██████    | 99/165 [13:16<08:47,  7.99s/it]

VAE train ep6:  61%|██████    | 100/165 [13:24<08:42,  8.04s/it]

VAE train ep6:  61%|██████    | 101/165 [13:32<08:30,  7.98s/it]

VAE train ep6:  62%|██████▏   | 102/165 [13:40<08:24,  8.01s/it]

VAE train ep6:  62%|██████▏   | 103/165 [13:48<08:17,  8.03s/it]

VAE train ep6:  63%|██████▎   | 104/165 [13:56<08:09,  8.02s/it]

VAE train ep6:  64%|██████▎   | 105/165 [14:04<08:02,  8.04s/it]

VAE train ep6:  64%|██████▍   | 106/165 [14:12<07:55,  8.05s/it]

VAE train ep6:  65%|██████▍   | 107/165 [14:20<07:49,  8.09s/it]

VAE train ep6:  65%|██████▌   | 108/165 [14:28<07:39,  8.07s/it]

VAE train ep6:  66%|██████▌   | 109/165 [14:36<07:33,  8.09s/it]

VAE train ep6:  67%|██████▋   | 110/165 [14:45<07:30,  8.20s/it]

VAE train ep6:  67%|██████▋   | 111/165 [14:53<07:24,  8.23s/it]

VAE train ep6:  68%|██████▊   | 112/165 [15:01<07:13,  8.18s/it]

VAE train ep6:  68%|██████▊   | 113/165 [15:09<07:04,  8.16s/it]

VAE train ep6:  69%|██████▉   | 114/165 [15:17<06:55,  8.15s/it]

VAE train ep6:  70%|██████▉   | 115/165 [15:26<06:48,  8.18s/it]

VAE train ep6:  70%|███████   | 116/165 [15:34<06:43,  8.23s/it]

VAE train ep6:  71%|███████   | 117/165 [15:42<06:35,  8.25s/it]

VAE train ep6:  72%|███████▏  | 118/165 [15:51<06:33,  8.38s/it]

VAE train ep6:  72%|███████▏  | 119/165 [16:00<06:30,  8.50s/it]

VAE train ep6:  73%|███████▎  | 120/165 [16:09<06:28,  8.63s/it]

VAE train ep6:  73%|███████▎  | 121/165 [16:18<06:23,  8.71s/it]

VAE train ep6:  74%|███████▍  | 122/165 [16:27<06:21,  8.88s/it]

VAE train ep6:  75%|███████▍  | 123/165 [16:36<06:19,  9.04s/it]

VAE train ep6:  75%|███████▌  | 124/165 [16:46<06:13,  9.12s/it]

VAE train ep6:  76%|███████▌  | 125/165 [16:55<06:02,  9.07s/it]

VAE train ep6:  76%|███████▋  | 126/165 [17:03<05:49,  8.97s/it]

VAE train ep6:  77%|███████▋  | 127/165 [17:12<05:35,  8.83s/it]

VAE train ep6:  78%|███████▊  | 128/165 [17:20<05:22,  8.71s/it]

VAE train ep6:  78%|███████▊  | 129/165 [17:29<05:08,  8.58s/it]

VAE train ep6:  79%|███████▉  | 130/165 [17:37<04:56,  8.46s/it]

VAE train ep6:  79%|███████▉  | 131/165 [17:45<04:43,  8.33s/it]

VAE train ep6:  80%|████████  | 132/165 [17:53<04:33,  8.28s/it]

VAE train ep6:  81%|████████  | 133/165 [18:01<04:21,  8.18s/it]

VAE train ep6:  81%|████████  | 134/165 [18:09<04:11,  8.13s/it]

VAE train ep6:  82%|████████▏ | 135/165 [18:17<04:02,  8.09s/it]

VAE train ep6:  82%|████████▏ | 136/165 [18:25<03:54,  8.09s/it]

VAE train ep6:  83%|████████▎ | 137/165 [18:33<03:45,  8.07s/it]

VAE train ep6:  84%|████████▎ | 138/165 [18:41<03:37,  8.06s/it]

VAE train ep6:  84%|████████▍ | 139/165 [18:49<03:28,  8.02s/it]

VAE train ep6:  85%|████████▍ | 140/165 [18:57<03:19,  7.99s/it]

VAE train ep6:  85%|████████▌ | 141/165 [19:05<03:13,  8.06s/it]

VAE train ep6:  86%|████████▌ | 142/165 [19:13<03:04,  8.03s/it]

VAE train ep6:  87%|████████▋ | 143/165 [19:21<02:56,  8.03s/it]

VAE train ep6:  87%|████████▋ | 144/165 [19:29<02:48,  8.00s/it]

VAE train ep6:  88%|████████▊ | 145/165 [19:37<02:40,  8.02s/it]

VAE train ep6:  88%|████████▊ | 146/165 [19:45<02:34,  8.12s/it]

VAE train ep6:  89%|████████▉ | 147/165 [19:53<02:25,  8.11s/it]

VAE train ep6:  90%|████████▉ | 148/165 [20:01<02:17,  8.08s/it]

VAE train ep6:  90%|█████████ | 149/165 [20:09<02:08,  8.03s/it]

VAE train ep6:  91%|█████████ | 150/165 [20:17<01:59,  7.98s/it]

VAE train ep6:  92%|█████████▏| 151/165 [20:25<01:51,  7.97s/it]

VAE train ep6:  92%|█████████▏| 152/165 [20:33<01:43,  7.95s/it]

VAE train ep6:  93%|█████████▎| 153/165 [20:41<01:35,  7.92s/it]

VAE train ep6:  93%|█████████▎| 154/165 [20:49<01:26,  7.89s/it]

VAE train ep6:  94%|█████████▍| 155/165 [20:57<01:19,  7.95s/it]

VAE train ep6:  95%|█████████▍| 156/165 [21:05<01:10,  7.88s/it]

VAE train ep6:  95%|█████████▌| 157/165 [21:12<01:02,  7.87s/it]

VAE train ep6:  96%|█████████▌| 158/165 [21:20<00:55,  7.89s/it]

VAE train ep6:  96%|█████████▋| 159/165 [21:28<00:47,  7.90s/it]

VAE train ep6:  97%|█████████▋| 160/165 [21:36<00:39,  7.94s/it]

VAE train ep6:  98%|█████████▊| 161/165 [21:44<00:31,  7.94s/it]

VAE train ep6:  98%|█████████▊| 162/165 [21:52<00:23,  7.94s/it]

VAE train ep6:  99%|█████████▉| 163/165 [22:00<00:15,  7.93s/it]

VAE train ep6:  99%|█████████▉| 164/165 [22:08<00:07,  7.97s/it]

VAE train ep6: 100%|██████████| 165/165 [22:09<00:00,  5.73s/it]

VAE val ep6:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep6:   3%|▎         | 1/29 [00:02<01:03,  2.27s/it]

VAE val ep6:   7%|▋         | 2/29 [00:04<01:00,  2.24s/it]

VAE val ep6:  10%|█         | 3/29 [00:06<00:57,  2.21s/it]

VAE val ep6:  14%|█▍        | 4/29 [00:08<00:55,  2.21s/it]

VAE val ep6:  17%|█▋        | 5/29 [00:11<00:52,  2.19s/it]

VAE val ep6:  21%|██        | 6/29 [00:13<00:50,  2.19s/it]

VAE val ep6:  24%|██▍       | 7/29 [00:15<00:47,  2.16s/it]

VAE val ep6:  28%|██▊       | 8/29 [00:17<00:45,  2.16s/it]

VAE val ep6:  31%|███       | 9/29 [00:19<00:43,  2.17s/it]

VAE val ep6:  34%|███▍      | 10/29 [00:21<00:41,  2.19s/it]

VAE val ep6:  38%|███▊      | 11/29 [00:24<00:39,  2.19s/it]

VAE val ep6:  41%|████▏     | 12/29 [00:26<00:37,  2.19s/it]

VAE val ep6:  45%|████▍     | 13/29 [00:28<00:34,  2.17s/it]

VAE val ep6:  48%|████▊     | 14/29 [00:30<00:32,  2.16s/it]

VAE val ep6:  52%|█████▏    | 15/29 [00:32<00:30,  2.17s/it]

VAE val ep6:  55%|█████▌    | 16/29 [00:34<00:28,  2.17s/it]

VAE val ep6:  59%|█████▊    | 17/29 [00:37<00:25,  2.16s/it]

VAE val ep6:  62%|██████▏   | 18/29 [00:39<00:23,  2.16s/it]

VAE val ep6:  66%|██████▌   | 19/29 [00:41<00:21,  2.17s/it]

VAE val ep6:  69%|██████▉   | 20/29 [00:43<00:19,  2.17s/it]

VAE val ep6:  72%|███████▏  | 21/29 [00:45<00:17,  2.18s/it]

VAE val ep6:  76%|███████▌  | 22/29 [00:47<00:15,  2.18s/it]

VAE val ep6:  79%|███████▉  | 23/29 [00:50<00:12,  2.16s/it]

VAE val ep6:  83%|████████▎ | 24/29 [00:52<00:10,  2.18s/it]

VAE val ep6:  86%|████████▌ | 25/29 [00:54<00:08,  2.17s/it]

VAE val ep6:  90%|████████▉ | 26/29 [00:56<00:06,  2.17s/it]

VAE val ep6:  93%|█████████▎| 27/29 [00:58<00:04,  2.17s/it]

VAE val ep6:  97%|█████████▋| 28/29 [01:00<00:02,  2.16s/it]

VAE val ep6: 100%|██████████| 29/29 [01:01<00:00,  1.60s/it]

VAE train ep7:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep7:   1%|          | 1/165 [00:08<23:02,  8.43s/it]

VAE train ep7:   1%|          | 2/165 [00:16<22:28,  8.27s/it]

VAE train ep7:   2%|▏         | 3/165 [00:24<22:13,  8.23s/it]

VAE train ep7:   2%|▏         | 4/165 [00:32<21:59,  8.19s/it]

VAE train ep7:   3%|▎         | 5/165 [00:41<21:49,  8.19s/it]

VAE train ep7:   4%|▎         | 6/165 [00:48<21:24,  8.08s/it]

VAE train ep7:   4%|▍         | 7/165 [00:56<21:07,  8.03s/it]

VAE train ep7:   5%|▍         | 8/165 [01:04<20:59,  8.02s/it]

VAE train ep7:   5%|▌         | 9/165 [01:12<20:47,  8.00s/it]

VAE train ep7:   6%|▌         | 10/165 [01:20<20:36,  7.98s/it]

VAE train ep7:   7%|▋         | 11/165 [01:28<20:34,  8.02s/it]

VAE train ep7:   7%|▋         | 12/165 [01:37<20:36,  8.08s/it]

VAE train ep7:   8%|▊         | 13/165 [01:45<20:23,  8.05s/it]

VAE train ep7:   8%|▊         | 14/165 [01:52<20:08,  8.01s/it]

VAE train ep7:   9%|▉         | 15/165 [02:00<20:00,  8.00s/it]

VAE train ep7:  10%|▉         | 16/165 [02:09<19:55,  8.02s/it]

VAE train ep7:  10%|█         | 17/165 [02:17<19:52,  8.06s/it]

VAE train ep7:  11%|█         | 18/165 [02:25<19:57,  8.15s/it]

VAE train ep7:  12%|█▏        | 19/165 [02:33<19:44,  8.11s/it]

VAE train ep7:  12%|█▏        | 20/165 [02:41<19:31,  8.08s/it]

VAE train ep7:  13%|█▎        | 21/165 [02:49<19:14,  8.02s/it]

VAE train ep7:  13%|█▎        | 22/165 [02:57<19:03,  8.00s/it]

VAE train ep7:  14%|█▍        | 23/165 [03:05<18:56,  8.00s/it]

VAE train ep7:  15%|█▍        | 24/165 [03:13<18:46,  7.99s/it]

VAE train ep7:  15%|█▌        | 25/165 [03:21<18:43,  8.02s/it]

VAE train ep7:  16%|█▌        | 26/165 [03:29<18:32,  8.00s/it]

VAE train ep7:  16%|█▋        | 27/165 [03:37<18:19,  7.97s/it]

VAE train ep7:  17%|█▋        | 28/165 [03:45<18:07,  7.94s/it]

VAE train ep7:  18%|█▊        | 29/165 [03:53<17:58,  7.93s/it]

VAE train ep7:  18%|█▊        | 30/165 [04:00<17:48,  7.91s/it]

VAE train ep7:  19%|█▉        | 31/165 [04:08<17:43,  7.94s/it]

VAE train ep7:  19%|█▉        | 32/165 [04:16<17:25,  7.86s/it]

VAE train ep7:  20%|██        | 33/165 [04:24<17:20,  7.88s/it]

VAE train ep7:  21%|██        | 34/165 [04:32<17:07,  7.84s/it]

VAE train ep7:  21%|██        | 35/165 [04:40<16:57,  7.83s/it]

VAE train ep7:  22%|██▏       | 36/165 [04:47<16:48,  7.82s/it]

VAE train ep7:  22%|██▏       | 37/165 [04:55<16:42,  7.83s/it]

VAE train ep7:  23%|██▎       | 38/165 [05:03<16:35,  7.84s/it]

VAE train ep7:  24%|██▎       | 39/165 [05:11<16:26,  7.83s/it]

VAE train ep7:  24%|██▍       | 40/165 [05:19<16:14,  7.80s/it]

VAE train ep7:  25%|██▍       | 41/165 [05:27<16:11,  7.84s/it]

VAE train ep7:  25%|██▌       | 42/165 [05:34<16:00,  7.81s/it]

VAE train ep7:  26%|██▌       | 43/165 [05:42<15:54,  7.82s/it]

VAE train ep7:  27%|██▋       | 44/165 [05:50<15:46,  7.82s/it]

VAE train ep7:  27%|██▋       | 45/165 [05:58<15:35,  7.80s/it]

VAE train ep7:  28%|██▊       | 46/165 [06:06<15:33,  7.85s/it]

VAE train ep7:  28%|██▊       | 47/165 [06:14<15:26,  7.86s/it]

VAE train ep7:  29%|██▉       | 48/165 [06:21<15:15,  7.82s/it]

VAE train ep7:  30%|██▉       | 49/165 [06:29<15:06,  7.81s/it]

VAE train ep7:  30%|███       | 50/165 [06:37<15:00,  7.83s/it]

VAE train ep7:  31%|███       | 51/165 [06:45<14:57,  7.87s/it]

VAE train ep7:  32%|███▏      | 52/165 [06:53<14:47,  7.86s/it]

VAE train ep7:  32%|███▏      | 53/165 [07:00<14:34,  7.81s/it]

VAE train ep7:  33%|███▎      | 54/165 [07:08<14:22,  7.77s/it]

VAE train ep7:  33%|███▎      | 55/165 [07:16<14:16,  7.79s/it]

VAE train ep7:  34%|███▍      | 56/165 [07:24<14:08,  7.79s/it]

VAE train ep7:  35%|███▍      | 57/165 [07:31<13:53,  7.72s/it]

VAE train ep7:  35%|███▌      | 58/165 [07:39<13:47,  7.73s/it]

VAE train ep7:  36%|███▌      | 59/165 [07:47<13:39,  7.73s/it]

VAE train ep7:  36%|███▋      | 60/165 [07:55<13:38,  7.80s/it]

VAE train ep7:  37%|███▋      | 61/165 [08:02<13:28,  7.77s/it]

VAE train ep7:  38%|███▊      | 62/165 [08:10<13:21,  7.78s/it]

VAE train ep7:  38%|███▊      | 63/165 [08:18<13:14,  7.79s/it]

VAE train ep7:  39%|███▉      | 64/165 [08:26<13:07,  7.80s/it]

VAE train ep7:  39%|███▉      | 65/165 [08:34<13:03,  7.83s/it]

VAE train ep7:  40%|████      | 66/165 [08:42<12:54,  7.83s/it]

VAE train ep7:  41%|████      | 67/165 [08:50<12:48,  7.85s/it]

VAE train ep7:  41%|████      | 68/165 [08:57<12:35,  7.79s/it]

VAE train ep7:  42%|████▏     | 69/165 [09:05<12:27,  7.78s/it]

VAE train ep7:  42%|████▏     | 70/165 [09:13<12:23,  7.82s/it]

VAE train ep7:  43%|████▎     | 71/165 [09:21<12:14,  7.81s/it]

VAE train ep7:  44%|████▎     | 72/165 [09:28<12:02,  7.77s/it]

VAE train ep7:  44%|████▍     | 73/165 [09:36<11:50,  7.72s/it]

VAE train ep7:  45%|████▍     | 74/165 [09:44<11:46,  7.77s/it]

VAE train ep7:  45%|████▌     | 75/165 [09:52<11:39,  7.78s/it]

VAE train ep7:  46%|████▌     | 76/165 [09:59<11:30,  7.76s/it]

VAE train ep7:  47%|████▋     | 77/165 [10:07<11:24,  7.78s/it]

VAE train ep7:  47%|████▋     | 78/165 [10:15<11:13,  7.74s/it]

VAE train ep7:  48%|████▊     | 79/165 [10:23<11:07,  7.76s/it]

VAE train ep7:  48%|████▊     | 80/165 [10:30<11:03,  7.80s/it]

VAE train ep7:  49%|████▉     | 81/165 [10:38<10:55,  7.81s/it]

VAE train ep7:  50%|████▉     | 82/165 [10:46<10:51,  7.85s/it]

VAE train ep7:  50%|█████     | 83/165 [10:54<10:46,  7.88s/it]

VAE train ep7:  51%|█████     | 84/165 [11:02<10:35,  7.85s/it]

VAE train ep7:  52%|█████▏    | 85/165 [11:10<10:27,  7.84s/it]

VAE train ep7:  52%|█████▏    | 86/165 [11:18<10:18,  7.83s/it]

VAE train ep7:  53%|█████▎    | 87/165 [11:26<10:14,  7.87s/it]

VAE train ep7:  53%|█████▎    | 88/165 [11:33<10:05,  7.86s/it]

VAE train ep7:  54%|█████▍    | 89/165 [11:41<09:49,  7.76s/it]

VAE train ep7:  55%|█████▍    | 90/165 [11:49<09:38,  7.72s/it]

VAE train ep7:  55%|█████▌    | 91/165 [11:56<09:30,  7.71s/it]

VAE train ep7:  56%|█████▌    | 92/165 [12:04<09:22,  7.71s/it]

VAE train ep7:  56%|█████▋    | 93/165 [12:12<09:20,  7.79s/it]

VAE train ep7:  57%|█████▋    | 94/165 [12:20<09:13,  7.80s/it]

VAE train ep7:  58%|█████▊    | 95/165 [12:27<09:04,  7.78s/it]

VAE train ep7:  58%|█████▊    | 96/165 [12:35<08:59,  7.81s/it]

VAE train ep7:  59%|█████▉    | 97/165 [12:43<08:54,  7.86s/it]

VAE train ep7:  59%|█████▉    | 98/165 [12:51<08:47,  7.87s/it]

VAE train ep7:  60%|██████    | 99/165 [12:59<08:35,  7.82s/it]

VAE train ep7:  61%|██████    | 100/165 [13:07<08:29,  7.84s/it]

VAE train ep7:  61%|██████    | 101/165 [13:15<08:20,  7.83s/it]

VAE train ep7:  62%|██████▏   | 102/165 [13:23<08:14,  7.86s/it]

VAE train ep7:  62%|██████▏   | 103/165 [13:30<08:07,  7.86s/it]

VAE train ep7:  63%|██████▎   | 104/165 [13:38<07:58,  7.84s/it]

VAE train ep7:  64%|██████▎   | 105/165 [13:46<07:53,  7.89s/it]

VAE train ep7:  64%|██████▍   | 106/165 [13:54<07:44,  7.87s/it]

VAE train ep7:  65%|██████▍   | 107/165 [14:02<07:36,  7.87s/it]

VAE train ep7:  65%|██████▌   | 108/165 [14:10<07:27,  7.85s/it]

VAE train ep7:  66%|██████▌   | 109/165 [14:18<07:18,  7.83s/it]

VAE train ep7:  67%|██████▋   | 110/165 [14:25<07:10,  7.83s/it]

VAE train ep7:  67%|██████▋   | 111/165 [14:33<07:03,  7.85s/it]

VAE train ep7:  68%|██████▊   | 112/165 [14:41<06:58,  7.90s/it]

VAE train ep7:  68%|██████▊   | 113/165 [14:49<06:50,  7.89s/it]

VAE train ep7:  69%|██████▉   | 114/165 [14:57<06:42,  7.89s/it]

VAE train ep7:  70%|██████▉   | 115/165 [15:05<06:33,  7.88s/it]

VAE train ep7:  70%|███████   | 116/165 [15:13<06:26,  7.88s/it]

VAE train ep7:  71%|███████   | 117/165 [15:21<06:18,  7.88s/it]

VAE train ep7:  72%|███████▏  | 118/165 [15:29<06:11,  7.90s/it]

VAE train ep7:  72%|███████▏  | 119/165 [15:36<06:02,  7.89s/it]

VAE train ep7:  73%|███████▎  | 120/165 [15:44<05:53,  7.87s/it]

VAE train ep7:  73%|███████▎  | 121/165 [15:52<05:48,  7.93s/it]

VAE train ep7:  74%|███████▍  | 122/165 [16:00<05:41,  7.95s/it]

VAE train ep7:  75%|███████▍  | 123/165 [16:08<05:33,  7.95s/it]

VAE train ep7:  75%|███████▌  | 124/165 [16:16<05:24,  7.92s/it]

VAE train ep7:  76%|███████▌  | 125/165 [16:24<05:14,  7.87s/it]

VAE train ep7:  76%|███████▋  | 126/165 [16:32<05:05,  7.83s/it]

VAE train ep7:  77%|███████▋  | 127/165 [16:40<04:58,  7.86s/it]

VAE train ep7:  78%|███████▊  | 128/165 [16:47<04:50,  7.86s/it]

VAE train ep7:  78%|███████▊  | 129/165 [16:55<04:43,  7.88s/it]

VAE train ep7:  79%|███████▉  | 130/165 [17:03<04:36,  7.89s/it]

VAE train ep7:  79%|███████▉  | 131/165 [17:11<04:26,  7.85s/it]

VAE train ep7:  80%|████████  | 132/165 [17:19<04:19,  7.87s/it]

VAE train ep7:  81%|████████  | 133/165 [17:27<04:12,  7.88s/it]

VAE train ep7:  81%|████████  | 134/165 [17:34<04:02,  7.81s/it]

VAE train ep7:  82%|████████▏ | 135/165 [17:42<03:54,  7.82s/it]

VAE train ep7:  82%|████████▏ | 136/165 [17:50<03:45,  7.79s/it]

VAE train ep7:  83%|████████▎ | 137/165 [17:58<03:38,  7.79s/it]

VAE train ep7:  84%|████████▎ | 138/165 [18:06<03:29,  7.77s/it]

VAE train ep7:  84%|████████▍ | 139/165 [18:13<03:22,  7.78s/it]

VAE train ep7:  85%|████████▍ | 140/165 [18:21<03:15,  7.81s/it]

VAE train ep7:  85%|████████▌ | 141/165 [18:29<03:08,  7.87s/it]

VAE train ep7:  86%|████████▌ | 142/165 [18:37<03:02,  7.92s/it]

VAE train ep7:  87%|████████▋ | 143/165 [18:45<02:53,  7.88s/it]

VAE train ep7:  87%|████████▋ | 144/165 [18:53<02:45,  7.86s/it]

VAE train ep7:  88%|████████▊ | 145/165 [19:01<02:36,  7.85s/it]

VAE train ep7:  88%|████████▊ | 146/165 [19:09<02:30,  7.90s/it]

VAE train ep7:  89%|████████▉ | 147/165 [19:17<02:22,  7.92s/it]

VAE train ep7:  90%|████████▉ | 148/165 [19:25<02:14,  7.91s/it]

VAE train ep7:  90%|█████████ | 149/165 [19:32<02:06,  7.89s/it]

VAE train ep7:  91%|█████████ | 150/165 [19:40<01:58,  7.87s/it]

VAE train ep7:  92%|█████████▏| 151/165 [19:48<01:50,  7.91s/it]

VAE train ep7:  92%|█████████▏| 152/165 [19:56<01:42,  7.92s/it]

VAE train ep7:  93%|█████████▎| 153/165 [20:04<01:34,  7.84s/it]

VAE train ep7:  93%|█████████▎| 154/165 [20:11<01:25,  7.78s/it]

VAE train ep7:  94%|█████████▍| 155/165 [20:19<01:17,  7.78s/it]

VAE train ep7:  95%|█████████▍| 156/165 [20:27<01:10,  7.80s/it]

VAE train ep7:  95%|█████████▌| 157/165 [20:35<01:02,  7.82s/it]

VAE train ep7:  96%|█████████▌| 158/165 [20:43<00:54,  7.81s/it]

VAE train ep7:  96%|█████████▋| 159/165 [20:50<00:46,  7.78s/it]

VAE train ep7:  97%|█████████▋| 160/165 [20:58<00:38,  7.78s/it]

VAE train ep7:  98%|█████████▊| 161/165 [21:06<00:31,  7.83s/it]

VAE train ep7:  98%|█████████▊| 162/165 [21:14<00:23,  7.78s/it]

VAE train ep7:  99%|█████████▉| 163/165 [21:22<00:15,  7.76s/it]

VAE train ep7:  99%|█████████▉| 164/165 [21:29<00:07,  7.78s/it]

VAE train ep7: 100%|██████████| 165/165 [21:30<00:00,  5.59s/it]

VAE val ep7:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep7:   3%|▎         | 1/29 [00:02<00:58,  2.09s/it]

VAE val ep7:   7%|▋         | 2/29 [00:04<00:56,  2.10s/it]

VAE val ep7:  10%|█         | 3/29 [00:06<00:54,  2.10s/it]

VAE val ep7:  14%|█▍        | 4/29 [00:08<00:52,  2.10s/it]

VAE val ep7:  17%|█▋        | 5/29 [00:10<00:50,  2.11s/it]

VAE val ep7:  21%|██        | 6/29 [00:12<00:48,  2.10s/it]

VAE val ep7:  24%|██▍       | 7/29 [00:14<00:46,  2.09s/it]

VAE val ep7:  28%|██▊       | 8/29 [00:16<00:44,  2.10s/it]

VAE val ep7:  31%|███       | 9/29 [00:18<00:41,  2.10s/it]

VAE val ep7:  34%|███▍      | 10/29 [00:21<00:40,  2.11s/it]

VAE val ep7:  38%|███▊      | 11/29 [00:23<00:37,  2.10s/it]

VAE val ep7:  41%|████▏     | 12/29 [00:25<00:35,  2.12s/it]

VAE val ep7:  45%|████▍     | 13/29 [00:27<00:33,  2.11s/it]

VAE val ep7:  48%|████▊     | 14/29 [00:29<00:31,  2.09s/it]

VAE val ep7:  52%|█████▏    | 15/29 [00:31<00:29,  2.10s/it]

VAE val ep7:  55%|█████▌    | 16/29 [00:33<00:27,  2.10s/it]

VAE val ep7:  59%|█████▊    | 17/29 [00:35<00:25,  2.10s/it]

VAE val ep7:  62%|██████▏   | 18/29 [00:37<00:23,  2.10s/it]

VAE val ep7:  66%|██████▌   | 19/29 [00:39<00:21,  2.11s/it]

VAE val ep7:  69%|██████▉   | 20/29 [00:42<00:19,  2.12s/it]

VAE val ep7:  72%|███████▏  | 21/29 [00:44<00:17,  2.15s/it]

VAE val ep7:  76%|███████▌  | 22/29 [00:46<00:15,  2.16s/it]

VAE val ep7:  79%|███████▉  | 23/29 [00:48<00:12,  2.16s/it]

VAE val ep7:  83%|████████▎ | 24/29 [00:50<00:10,  2.17s/it]

VAE val ep7:  86%|████████▌ | 25/29 [00:52<00:08,  2.14s/it]

VAE val ep7:  90%|████████▉ | 26/29 [00:55<00:06,  2.12s/it]

VAE val ep7:  93%|█████████▎| 27/29 [00:57<00:04,  2.12s/it]

VAE val ep7:  97%|█████████▋| 28/29 [00:59<00:02,  2.12s/it]

VAE val ep7: 100%|██████████| 29/29 [00:59<00:00,  1.56s/it]

VAE train ep8:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep8:   1%|          | 1/165 [00:08<22:25,  8.21s/it]

VAE train ep8:   1%|          | 2/165 [00:16<21:55,  8.07s/it]

VAE train ep8:   2%|▏         | 3/165 [00:24<22:03,  8.17s/it]

VAE train ep8:   2%|▏         | 4/165 [00:32<22:10,  8.26s/it]

VAE train ep8:   3%|▎         | 5/165 [00:41<22:01,  8.26s/it]

VAE train ep8:   4%|▎         | 6/165 [00:49<21:39,  8.18s/it]

VAE train ep8:   4%|▍         | 7/165 [00:57<21:26,  8.14s/it]

VAE train ep8:   5%|▍         | 8/165 [01:05<21:03,  8.05s/it]

VAE train ep8:   5%|▌         | 9/165 [01:13<20:51,  8.02s/it]

VAE train ep8:   6%|▌         | 10/165 [01:20<20:37,  7.99s/it]

VAE train ep8:   7%|▋         | 11/165 [01:29<20:41,  8.06s/it]

VAE train ep8:   7%|▋         | 12/165 [01:37<20:23,  8.00s/it]

VAE train ep8:   8%|▊         | 13/165 [01:44<20:11,  7.97s/it]

VAE train ep8:   8%|▊         | 14/165 [01:52<20:06,  7.99s/it]

VAE train ep8:   9%|▉         | 15/165 [02:01<20:02,  8.01s/it]

VAE train ep8:  10%|▉         | 16/165 [02:08<19:49,  7.98s/it]

VAE train ep8:  10%|█         | 17/165 [02:17<19:46,  8.02s/it]

VAE train ep8:  11%|█         | 18/165 [02:24<19:35,  7.99s/it]

VAE train ep8:  12%|█▏        | 19/165 [02:32<19:24,  7.97s/it]

VAE train ep8:  12%|█▏        | 20/165 [02:40<19:13,  7.96s/it]

VAE train ep8:  13%|█▎        | 21/165 [02:48<18:45,  7.82s/it]

VAE train ep8:  13%|█▎        | 22/165 [02:56<18:40,  7.84s/it]

VAE train ep8:  14%|█▍        | 23/165 [03:03<18:29,  7.82s/it]

VAE train ep8:  15%|█▍        | 24/165 [03:11<18:27,  7.85s/it]

VAE train ep8:  15%|█▌        | 25/165 [03:19<18:21,  7.87s/it]

VAE train ep8:  16%|█▌        | 26/165 [03:27<18:12,  7.86s/it]

VAE train ep8:  16%|█▋        | 27/165 [03:35<18:02,  7.85s/it]

VAE train ep8:  17%|█▋        | 28/165 [03:43<17:54,  7.84s/it]

VAE train ep8:  18%|█▊        | 29/165 [03:51<17:47,  7.85s/it]

VAE train ep8:  18%|█▊        | 30/165 [03:59<17:42,  7.87s/it]

VAE train ep8:  19%|█▉        | 31/165 [04:06<17:35,  7.88s/it]

VAE train ep8:  19%|█▉        | 32/165 [04:14<17:19,  7.82s/it]

VAE train ep8:  20%|██        | 33/165 [04:22<17:11,  7.81s/it]

VAE train ep8:  21%|██        | 34/165 [04:30<17:01,  7.80s/it]

VAE train ep8:  21%|██        | 35/165 [04:37<16:51,  7.78s/it]

VAE train ep8:  22%|██▏       | 36/165 [04:45<16:43,  7.78s/it]

VAE train ep8:  22%|██▏       | 37/165 [04:53<16:36,  7.78s/it]

VAE train ep8:  23%|██▎       | 38/165 [05:01<16:36,  7.85s/it]

VAE train ep8:  24%|██▎       | 39/165 [05:09<16:36,  7.91s/it]

VAE train ep8:  24%|██▍       | 40/165 [05:17<16:25,  7.88s/it]

VAE train ep8:  25%|██▍       | 41/165 [05:25<16:20,  7.91s/it]

VAE train ep8:  25%|██▌       | 42/165 [05:33<16:10,  7.89s/it]

VAE train ep8:  26%|██▌       | 43/165 [05:41<16:07,  7.93s/it]

VAE train ep8:  27%|██▋       | 44/165 [05:49<16:01,  7.94s/it]

VAE train ep8:  27%|██▋       | 45/165 [05:57<15:48,  7.91s/it]

VAE train ep8:  28%|██▊       | 46/165 [06:04<15:39,  7.89s/it]

VAE train ep8:  28%|██▊       | 47/165 [06:12<15:31,  7.89s/it]

VAE train ep8:  29%|██▉       | 48/165 [06:20<15:26,  7.92s/it]

VAE train ep8:  30%|██▉       | 49/165 [06:28<15:15,  7.89s/it]

VAE train ep8:  30%|███       | 50/165 [06:36<15:02,  7.85s/it]

VAE train ep8:  31%|███       | 51/165 [06:44<14:50,  7.81s/it]

VAE train ep8:  32%|███▏      | 52/165 [06:51<14:43,  7.82s/it]

VAE train ep8:  32%|███▏      | 53/165 [06:59<14:35,  7.81s/it]

VAE train ep8:  33%|███▎      | 54/165 [07:07<14:34,  7.88s/it]

VAE train ep8:  33%|███▎      | 55/165 [07:15<14:21,  7.83s/it]

VAE train ep8:  34%|███▍      | 56/165 [07:23<14:23,  7.92s/it]

VAE train ep8:  35%|███▍      | 57/165 [07:31<14:11,  7.88s/it]

VAE train ep8:  35%|███▌      | 58/165 [07:39<13:56,  7.82s/it]

VAE train ep8:  36%|███▌      | 59/165 [07:46<13:50,  7.84s/it]

VAE train ep8:  36%|███▋      | 60/165 [07:54<13:45,  7.86s/it]

VAE train ep8:  37%|███▋      | 61/165 [08:02<13:37,  7.86s/it]

VAE train ep8:  38%|███▊      | 62/165 [08:10<13:24,  7.81s/it]

VAE train ep8:  38%|███▊      | 63/165 [08:17<13:10,  7.75s/it]

VAE train ep8:  39%|███▉      | 64/165 [08:25<13:10,  7.82s/it]

VAE train ep8:  39%|███▉      | 65/165 [08:33<13:01,  7.82s/it]

VAE train ep8:  40%|████      | 66/165 [08:41<12:53,  7.81s/it]

VAE train ep8:  41%|████      | 67/165 [08:49<12:40,  7.76s/it]

VAE train ep8:  41%|████      | 68/165 [08:57<12:36,  7.80s/it]

VAE train ep8:  42%|████▏     | 69/165 [09:04<12:28,  7.80s/it]

VAE train ep8:  42%|████▏     | 70/165 [09:12<12:18,  7.77s/it]

VAE train ep8:  43%|████▎     | 71/165 [09:20<12:11,  7.79s/it]

VAE train ep8:  44%|████▎     | 72/165 [09:28<12:05,  7.80s/it]

VAE train ep8:  44%|████▍     | 73/165 [09:35<11:54,  7.77s/it]

VAE train ep8:  45%|████▍     | 74/165 [09:43<11:52,  7.83s/it]

VAE train ep8:  45%|████▌     | 75/165 [09:51<11:46,  7.85s/it]

VAE train ep8:  46%|████▌     | 76/165 [09:59<11:34,  7.80s/it]

VAE train ep8:  47%|████▋     | 77/165 [10:07<11:24,  7.78s/it]

VAE train ep8:  47%|████▋     | 78/165 [10:15<11:16,  7.77s/it]

VAE train ep8:  48%|████▊     | 79/165 [10:22<11:06,  7.75s/it]

VAE train ep8:  48%|████▊     | 80/165 [10:30<10:56,  7.72s/it]

VAE train ep8:  49%|████▉     | 81/165 [10:38<10:48,  7.72s/it]

VAE train ep8:  50%|████▉     | 82/165 [10:45<10:35,  7.65s/it]

VAE train ep8:  50%|█████     | 83/165 [10:53<10:27,  7.65s/it]

VAE train ep8:  51%|█████     | 84/165 [11:00<10:21,  7.67s/it]

VAE train ep8:  52%|█████▏    | 85/165 [11:08<10:16,  7.70s/it]

VAE train ep8:  52%|█████▏    | 86/165 [11:16<10:06,  7.68s/it]

VAE train ep8:  53%|█████▎    | 87/165 [11:23<09:54,  7.62s/it]

VAE train ep8:  53%|█████▎    | 88/165 [11:31<09:45,  7.60s/it]

VAE train ep8:  54%|█████▍    | 89/165 [11:39<09:40,  7.64s/it]

VAE train ep8:  55%|█████▍    | 90/165 [11:46<09:37,  7.70s/it]

VAE train ep8:  55%|█████▌    | 91/165 [11:54<09:28,  7.68s/it]

VAE train ep8:  56%|█████▌    | 92/165 [12:02<09:28,  7.79s/it]

VAE train ep8:  56%|█████▋    | 93/165 [12:10<09:25,  7.85s/it]

VAE train ep8:  57%|█████▋    | 94/165 [12:18<09:14,  7.80s/it]

VAE train ep8:  58%|█████▊    | 95/165 [12:26<09:08,  7.83s/it]

VAE train ep8:  58%|█████▊    | 96/165 [12:33<08:56,  7.77s/it]

VAE train ep8:  59%|█████▉    | 97/165 [12:41<08:48,  7.77s/it]

VAE train ep8:  59%|█████▉    | 98/165 [12:49<08:39,  7.76s/it]

VAE train ep8:  60%|██████    | 99/165 [12:57<08:31,  7.75s/it]

VAE train ep8:  61%|██████    | 100/165 [13:04<08:24,  7.75s/it]

VAE train ep8:  61%|██████    | 101/165 [13:12<08:18,  7.78s/it]

VAE train ep8:  62%|██████▏   | 102/165 [13:20<08:14,  7.85s/it]

VAE train ep8:  62%|██████▏   | 103/165 [13:28<08:03,  7.80s/it]

VAE train ep8:  63%|██████▎   | 104/165 [13:36<07:57,  7.83s/it]

VAE train ep8:  64%|██████▎   | 105/165 [13:44<07:49,  7.82s/it]

VAE train ep8:  64%|██████▍   | 106/165 [13:52<07:43,  7.86s/it]

VAE train ep8:  65%|██████▍   | 107/165 [13:59<07:35,  7.85s/it]

VAE train ep8:  65%|██████▌   | 108/165 [14:07<07:26,  7.84s/it]

VAE train ep8:  66%|██████▌   | 109/165 [14:15<07:21,  7.88s/it]

VAE train ep8:  67%|██████▋   | 110/165 [14:23<07:11,  7.84s/it]

VAE train ep8:  67%|██████▋   | 111/165 [14:31<07:05,  7.87s/it]

VAE train ep8:  68%|██████▊   | 112/165 [14:39<06:59,  7.91s/it]

VAE train ep8:  68%|██████▊   | 113/165 [14:47<06:53,  7.95s/it]

VAE train ep8:  69%|██████▉   | 114/165 [14:55<06:47,  7.99s/it]

VAE train ep8:  70%|██████▉   | 115/165 [15:03<06:38,  7.97s/it]

VAE train ep8:  70%|███████   | 116/165 [15:11<06:28,  7.93s/it]

VAE train ep8:  71%|███████   | 117/165 [15:18<06:17,  7.86s/it]

VAE train ep8:  72%|███████▏  | 118/165 [15:27<06:12,  7.93s/it]

VAE train ep8:  72%|███████▏  | 119/165 [15:34<06:05,  7.94s/it]

VAE train ep8:  73%|███████▎  | 120/165 [15:43<05:58,  7.98s/it]

VAE train ep8:  73%|███████▎  | 121/165 [15:50<05:48,  7.93s/it]

VAE train ep8:  74%|███████▍  | 122/165 [15:58<05:39,  7.91s/it]

VAE train ep8:  75%|███████▍  | 123/165 [16:06<05:31,  7.90s/it]

VAE train ep8:  75%|███████▌  | 124/165 [16:14<05:21,  7.83s/it]

VAE train ep8:  76%|███████▌  | 125/165 [16:22<05:12,  7.81s/it]

VAE train ep8:  76%|███████▋  | 126/165 [16:29<05:04,  7.80s/it]

VAE train ep8:  77%|███████▋  | 127/165 [16:37<04:57,  7.84s/it]

VAE train ep8:  78%|███████▊  | 128/165 [16:45<04:50,  7.85s/it]

VAE train ep8:  78%|███████▊  | 129/165 [16:53<04:45,  7.92s/it]

VAE train ep8:  79%|███████▉  | 130/165 [17:01<04:38,  7.95s/it]

VAE train ep8:  79%|███████▉  | 131/165 [17:09<04:29,  7.94s/it]

VAE train ep8:  80%|████████  | 132/165 [17:17<04:23,  7.99s/it]

VAE train ep8:  81%|████████  | 133/165 [17:25<04:16,  8.01s/it]

VAE train ep8:  81%|████████  | 134/165 [17:33<04:09,  8.04s/it]

VAE train ep8:  82%|████████▏ | 135/165 [17:42<04:03,  8.10s/it]

VAE train ep8:  82%|████████▏ | 136/165 [17:51<04:01,  8.34s/it]

VAE train ep8:  83%|████████▎ | 137/165 [17:59<03:57,  8.48s/it]

VAE train ep8:  84%|████████▎ | 138/165 [18:08<03:51,  8.56s/it]

VAE train ep8:  84%|████████▍ | 139/165 [18:17<03:42,  8.57s/it]

VAE train ep8:  85%|████████▍ | 140/165 [18:25<03:32,  8.50s/it]

VAE train ep8:  85%|████████▌ | 141/165 [18:33<03:20,  8.37s/it]

VAE train ep8:  86%|████████▌ | 142/165 [18:41<03:09,  8.22s/it]

VAE train ep8:  87%|████████▋ | 143/165 [18:49<02:58,  8.11s/it]

VAE train ep8:  87%|████████▋ | 144/165 [18:57<02:51,  8.16s/it]

VAE train ep8:  88%|████████▊ | 145/165 [19:05<02:41,  8.08s/it]

VAE train ep8:  88%|████████▊ | 146/165 [19:13<02:32,  8.04s/it]

VAE train ep8:  89%|████████▉ | 147/165 [19:21<02:23,  7.98s/it]

VAE train ep8:  90%|████████▉ | 148/165 [19:29<02:15,  7.99s/it]

VAE train ep8:  90%|█████████ | 149/165 [19:37<02:08,  8.05s/it]

VAE train ep8:  91%|█████████ | 150/165 [19:45<01:59,  7.99s/it]

VAE train ep8:  92%|█████████▏| 151/165 [19:53<01:50,  7.91s/it]

VAE train ep8:  92%|█████████▏| 152/165 [20:00<01:42,  7.87s/it]

VAE train ep8:  93%|█████████▎| 153/165 [20:08<01:34,  7.87s/it]

VAE train ep8:  93%|█████████▎| 154/165 [20:16<01:26,  7.87s/it]

VAE train ep8:  94%|█████████▍| 155/165 [20:24<01:18,  7.82s/it]

VAE train ep8:  95%|█████████▍| 156/165 [20:32<01:10,  7.83s/it]

VAE train ep8:  95%|█████████▌| 157/165 [20:39<01:02,  7.81s/it]

VAE train ep8:  96%|█████████▌| 158/165 [20:48<00:55,  7.92s/it]

VAE train ep8:  96%|█████████▋| 159/165 [20:56<00:47,  7.95s/it]

VAE train ep8:  97%|█████████▋| 160/165 [21:04<00:39,  7.95s/it]

VAE train ep8:  98%|█████████▊| 161/165 [21:12<00:31,  7.95s/it]

VAE train ep8:  98%|█████████▊| 162/165 [21:19<00:23,  7.90s/it]

VAE train ep8:  99%|█████████▉| 163/165 [21:27<00:15,  7.87s/it]

VAE train ep8:  99%|█████████▉| 164/165 [21:35<00:07,  7.87s/it]

VAE train ep8: 100%|██████████| 165/165 [21:35<00:00,  5.65s/it]

VAE val ep8:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep8:   3%|▎         | 1/29 [00:02<00:59,  2.11s/it]

VAE val ep8:   7%|▋         | 2/29 [00:04<00:57,  2.13s/it]

VAE val ep8:  10%|█         | 3/29 [00:06<00:54,  2.11s/it]

VAE val ep8:  14%|█▍        | 4/29 [00:08<00:52,  2.10s/it]

VAE val ep8:  17%|█▋        | 5/29 [00:10<00:50,  2.10s/it]

VAE val ep8:  21%|██        | 6/29 [00:12<00:48,  2.09s/it]

VAE val ep8:  24%|██▍       | 7/29 [00:14<00:46,  2.10s/it]

VAE val ep8:  28%|██▊       | 8/29 [00:16<00:44,  2.10s/it]

VAE val ep8:  31%|███       | 9/29 [00:18<00:41,  2.08s/it]

VAE val ep8:  34%|███▍      | 10/29 [00:20<00:39,  2.08s/it]

VAE val ep8:  38%|███▊      | 11/29 [00:22<00:37,  2.07s/it]

VAE val ep8:  41%|████▏     | 12/29 [00:25<00:35,  2.10s/it]

VAE val ep8:  45%|████▍     | 13/29 [00:27<00:33,  2.11s/it]

VAE val ep8:  48%|████▊     | 14/29 [00:29<00:31,  2.12s/it]

VAE val ep8:  52%|█████▏    | 15/29 [00:31<00:29,  2.12s/it]

VAE val ep8:  55%|█████▌    | 16/29 [00:33<00:27,  2.14s/it]

VAE val ep8:  59%|█████▊    | 17/29 [00:35<00:25,  2.15s/it]

VAE val ep8:  62%|██████▏   | 18/29 [00:38<00:23,  2.14s/it]

VAE val ep8:  66%|██████▌   | 19/29 [00:40<00:21,  2.12s/it]

VAE val ep8:  69%|██████▉   | 20/29 [00:42<00:18,  2.10s/it]

VAE val ep8:  72%|███████▏  | 21/29 [00:44<00:16,  2.11s/it]

VAE val ep8:  76%|███████▌  | 22/29 [00:46<00:14,  2.12s/it]

VAE val ep8:  79%|███████▉  | 23/29 [00:48<00:12,  2.10s/it]

VAE val ep8:  83%|████████▎ | 24/29 [00:50<00:10,  2.11s/it]

VAE val ep8:  86%|████████▌ | 25/29 [00:52<00:08,  2.09s/it]

VAE val ep8:  90%|████████▉ | 26/29 [00:54<00:06,  2.09s/it]

VAE val ep8:  93%|█████████▎| 27/29 [00:56<00:04,  2.08s/it]

VAE val ep8:  97%|█████████▋| 28/29 [00:58<00:02,  2.07s/it]

VAE val ep8: 100%|██████████| 29/29 [00:59<00:00,  1.53s/it]

VAE train ep9:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep9:   1%|          | 1/165 [00:07<21:50,  7.99s/it]

VAE train ep9:   1%|          | 2/165 [00:15<21:41,  7.99s/it]

VAE train ep9:   2%|▏         | 3/165 [00:23<21:09,  7.84s/it]

VAE train ep9:   2%|▏         | 4/165 [00:31<20:55,  7.80s/it]

VAE train ep9:   3%|▎         | 5/165 [00:39<20:44,  7.78s/it]

VAE train ep9:   4%|▎         | 6/165 [00:46<20:27,  7.72s/it]

VAE train ep9:   4%|▍         | 7/165 [00:54<20:19,  7.72s/it]

VAE train ep9:   5%|▍         | 8/165 [01:02<20:08,  7.70s/it]

VAE train ep9:   5%|▌         | 9/165 [01:09<19:59,  7.69s/it]

VAE train ep9:   6%|▌         | 10/165 [01:17<19:50,  7.68s/it]

VAE train ep9:   7%|▋         | 11/165 [01:25<19:44,  7.69s/it]

VAE train ep9:   7%|▋         | 12/165 [01:32<19:42,  7.73s/it]

VAE train ep9:   8%|▊         | 13/165 [01:40<19:30,  7.70s/it]

VAE train ep9:   8%|▊         | 14/165 [01:48<19:22,  7.70s/it]

VAE train ep9:   9%|▉         | 15/165 [01:55<19:15,  7.70s/it]

VAE train ep9:  10%|▉         | 16/165 [02:03<19:00,  7.65s/it]

VAE train ep9:  10%|█         | 17/165 [02:11<18:55,  7.67s/it]

VAE train ep9:  11%|█         | 18/165 [02:19<18:54,  7.72s/it]

VAE train ep9:  12%|█▏        | 19/165 [02:26<18:45,  7.71s/it]

VAE train ep9:  12%|█▏        | 20/165 [02:34<18:27,  7.64s/it]

VAE train ep9:  13%|█▎        | 21/165 [02:41<18:19,  7.64s/it]

VAE train ep9:  13%|█▎        | 22/165 [02:49<18:17,  7.67s/it]

VAE train ep9:  14%|█▍        | 23/165 [02:57<18:09,  7.68s/it]

VAE train ep9:  15%|█▍        | 24/165 [03:04<18:02,  7.68s/it]

VAE train ep9:  15%|█▌        | 25/165 [03:12<17:54,  7.68s/it]

VAE train ep9:  16%|█▌        | 26/165 [03:20<17:44,  7.66s/it]

VAE train ep9:  16%|█▋        | 27/165 [03:28<17:39,  7.68s/it]

VAE train ep9:  17%|█▋        | 28/165 [03:35<17:34,  7.69s/it]

VAE train ep9:  18%|█▊        | 29/165 [03:43<17:32,  7.74s/it]

VAE train ep9:  18%|█▊        | 30/165 [03:51<17:24,  7.74s/it]

VAE train ep9:  19%|█▉        | 31/165 [03:58<17:13,  7.71s/it]

VAE train ep9:  19%|█▉        | 32/165 [04:06<17:04,  7.70s/it]

VAE train ep9:  20%|██        | 33/165 [04:14<16:52,  7.67s/it]

VAE train ep9:  21%|██        | 34/165 [04:22<16:50,  7.71s/it]

VAE train ep9:  21%|██        | 35/165 [04:29<16:50,  7.78s/it]

VAE train ep9:  22%|██▏       | 36/165 [04:37<16:41,  7.76s/it]

VAE train ep9:  22%|██▏       | 37/165 [04:45<16:37,  7.80s/it]

VAE train ep9:  23%|██▎       | 38/165 [04:53<16:24,  7.75s/it]

VAE train ep9:  24%|██▎       | 39/165 [05:00<16:12,  7.72s/it]

VAE train ep9:  24%|██▍       | 40/165 [05:08<16:03,  7.71s/it]

VAE train ep9:  25%|██▍       | 41/165 [05:16<15:56,  7.71s/it]

VAE train ep9:  25%|██▌       | 42/165 [05:23<15:45,  7.68s/it]

VAE train ep9:  26%|██▌       | 43/165 [05:31<15:38,  7.69s/it]

VAE train ep9:  27%|██▋       | 44/165 [05:39<15:25,  7.65s/it]

VAE train ep9:  27%|██▋       | 45/165 [05:46<15:14,  7.62s/it]

VAE train ep9:  28%|██▊       | 46/165 [05:54<15:11,  7.66s/it]

VAE train ep9:  28%|██▊       | 47/165 [06:02<15:07,  7.69s/it]

VAE train ep9:  29%|██▉       | 48/165 [06:09<15:00,  7.70s/it]

VAE train ep9:  30%|██▉       | 49/165 [06:17<14:54,  7.71s/it]

VAE train ep9:  30%|███       | 50/165 [06:25<14:44,  7.70s/it]

VAE train ep9:  31%|███       | 51/165 [06:32<14:33,  7.66s/it]

VAE train ep9:  32%|███▏      | 52/165 [06:40<14:25,  7.66s/it]

VAE train ep9:  32%|███▏      | 53/165 [06:48<14:19,  7.68s/it]

VAE train ep9:  33%|███▎      | 54/165 [06:55<14:12,  7.68s/it]

VAE train ep9:  33%|███▎      | 55/165 [07:03<14:10,  7.73s/it]

VAE train ep9:  34%|███▍      | 56/165 [07:11<14:12,  7.82s/it]

VAE train ep9:  35%|███▍      | 57/165 [07:19<14:12,  7.90s/it]

VAE train ep9:  35%|███▌      | 58/165 [07:27<14:06,  7.92s/it]

VAE train ep9:  36%|███▌      | 59/165 [07:36<14:12,  8.05s/it]

VAE train ep9:  36%|███▋      | 60/165 [07:44<14:07,  8.07s/it]

VAE train ep9:  37%|███▋      | 61/165 [07:52<13:55,  8.04s/it]

VAE train ep9:  38%|███▊      | 62/165 [08:00<13:38,  7.94s/it]

VAE train ep9:  38%|███▊      | 63/165 [08:07<13:22,  7.87s/it]

VAE train ep9:  39%|███▉      | 64/165 [08:15<13:11,  7.83s/it]

VAE train ep9:  39%|███▉      | 65/165 [08:23<13:01,  7.81s/it]

VAE train ep9:  40%|████      | 66/165 [08:30<12:50,  7.78s/it]

VAE train ep9:  41%|████      | 67/165 [08:38<12:42,  7.78s/it]

VAE train ep9:  41%|████      | 68/165 [08:46<12:30,  7.74s/it]

VAE train ep9:  42%|████▏     | 69/165 [08:54<12:25,  7.76s/it]

VAE train ep9:  42%|████▏     | 70/165 [09:02<12:20,  7.80s/it]

VAE train ep9:  43%|████▎     | 71/165 [09:09<12:11,  7.78s/it]

VAE train ep9:  44%|████▎     | 72/165 [09:17<12:02,  7.77s/it]

VAE train ep9:  44%|████▍     | 73/165 [09:25<11:52,  7.75s/it]

VAE train ep9:  45%|████▍     | 74/165 [09:33<11:48,  7.78s/it]

VAE train ep9:  45%|████▌     | 75/165 [09:40<11:40,  7.78s/it]

VAE train ep9:  46%|████▌     | 76/165 [09:48<11:31,  7.77s/it]

VAE train ep9:  47%|████▋     | 77/165 [09:56<11:23,  7.77s/it]

VAE train ep9:  47%|████▋     | 78/165 [10:04<11:21,  7.84s/it]

VAE train ep9:  48%|████▊     | 79/165 [10:12<11:13,  7.83s/it]

VAE train ep9:  48%|████▊     | 80/165 [10:20<11:08,  7.87s/it]

VAE train ep9:  49%|████▉     | 81/165 [10:28<11:05,  7.93s/it]

VAE train ep9:  50%|████▉     | 82/165 [10:36<10:58,  7.93s/it]

VAE train ep9:  50%|█████     | 83/165 [10:43<10:46,  7.89s/it]

VAE train ep9:  51%|█████     | 84/165 [10:51<10:38,  7.88s/it]

VAE train ep9:  52%|█████▏    | 85/165 [10:59<10:29,  7.87s/it]

VAE train ep9:  52%|█████▏    | 86/165 [11:07<10:18,  7.83s/it]

VAE train ep9:  53%|█████▎    | 87/165 [11:15<10:07,  7.78s/it]

VAE train ep9:  53%|█████▎    | 88/165 [11:22<09:55,  7.73s/it]

VAE train ep9:  54%|█████▍    | 89/165 [11:30<09:54,  7.82s/it]

VAE train ep9:  55%|█████▍    | 90/165 [11:38<09:46,  7.82s/it]

VAE train ep9:  55%|█████▌    | 91/165 [11:46<09:35,  7.77s/it]

VAE train ep9:  56%|█████▌    | 92/165 [11:53<09:24,  7.73s/it]

VAE train ep9:  56%|█████▋    | 93/165 [12:01<09:15,  7.72s/it]

VAE train ep9:  57%|█████▋    | 94/165 [12:09<09:08,  7.73s/it]

VAE train ep9:  58%|█████▊    | 95/165 [12:16<08:58,  7.70s/it]

VAE train ep9:  58%|█████▊    | 96/165 [12:24<08:47,  7.65s/it]

VAE train ep9:  59%|█████▉    | 97/165 [12:32<08:39,  7.64s/it]

VAE train ep9:  59%|█████▉    | 98/165 [12:39<08:29,  7.60s/it]

VAE train ep9:  60%|██████    | 99/165 [12:47<08:28,  7.70s/it]

VAE train ep9:  61%|██████    | 100/165 [12:55<08:19,  7.69s/it]

VAE train ep9:  61%|██████    | 101/165 [13:02<08:12,  7.69s/it]

VAE train ep9:  62%|██████▏   | 102/165 [13:10<08:07,  7.74s/it]

VAE train ep9:  62%|██████▏   | 103/165 [13:18<08:05,  7.83s/it]

VAE train ep9:  63%|██████▎   | 104/165 [13:26<07:59,  7.87s/it]

VAE train ep9:  64%|██████▎   | 105/165 [13:34<07:58,  7.98s/it]

VAE train ep9:  64%|██████▍   | 106/165 [13:42<07:50,  7.97s/it]

VAE train ep9:  65%|██████▍   | 107/165 [13:50<07:35,  7.85s/it]

VAE train ep9:  65%|██████▌   | 108/165 [13:58<07:24,  7.80s/it]

VAE train ep9:  66%|██████▌   | 109/165 [14:05<07:14,  7.76s/it]

VAE train ep9:  67%|██████▋   | 110/165 [14:13<07:06,  7.75s/it]

VAE train ep9:  67%|██████▋   | 111/165 [14:21<07:00,  7.78s/it]

VAE train ep9:  68%|██████▊   | 112/165 [14:29<06:53,  7.80s/it]

VAE train ep9:  68%|██████▊   | 113/165 [14:37<06:45,  7.80s/it]

VAE train ep9:  69%|██████▉   | 114/165 [14:44<06:35,  7.76s/it]

VAE train ep9:  70%|██████▉   | 115/165 [14:52<06:24,  7.69s/it]

VAE train ep9:  70%|███████   | 116/165 [15:00<06:18,  7.72s/it]

VAE train ep9:  71%|███████   | 117/165 [15:07<06:07,  7.66s/it]

VAE train ep9:  72%|███████▏  | 118/165 [15:15<05:58,  7.63s/it]

VAE train ep9:  72%|███████▏  | 119/165 [15:22<05:49,  7.60s/it]

VAE train ep9:  73%|███████▎  | 120/165 [15:30<05:42,  7.60s/it]

VAE train ep9:  73%|███████▎  | 121/165 [15:37<05:35,  7.62s/it]

VAE train ep9:  74%|███████▍  | 122/165 [15:45<05:28,  7.64s/it]

VAE train ep9:  75%|███████▍  | 123/165 [15:53<05:25,  7.74s/it]

VAE train ep9:  75%|███████▌  | 124/165 [16:01<05:18,  7.77s/it]

VAE train ep9:  76%|███████▌  | 125/165 [16:09<05:13,  7.85s/it]

VAE train ep9:  76%|███████▋  | 126/165 [16:17<05:09,  7.93s/it]

VAE train ep9:  77%|███████▋  | 127/165 [16:25<05:04,  8.01s/it]

VAE train ep9:  78%|███████▊  | 128/165 [16:33<04:54,  7.97s/it]

VAE train ep9:  78%|███████▊  | 129/165 [16:41<04:43,  7.87s/it]

VAE train ep9:  79%|███████▉  | 130/165 [16:48<04:33,  7.82s/it]

VAE train ep9:  79%|███████▉  | 131/165 [16:56<04:24,  7.79s/it]

VAE train ep9:  80%|████████  | 132/165 [17:04<04:16,  7.76s/it]

VAE train ep9:  81%|████████  | 133/165 [17:12<04:08,  7.76s/it]

VAE train ep9:  81%|████████  | 134/165 [17:19<03:59,  7.74s/it]

VAE train ep9:  82%|████████▏ | 135/165 [17:27<03:51,  7.70s/it]

VAE train ep9:  82%|████████▏ | 136/165 [17:35<03:42,  7.68s/it]

VAE train ep9:  83%|████████▎ | 137/165 [17:42<03:35,  7.68s/it]

VAE train ep9:  84%|████████▎ | 138/165 [17:50<03:26,  7.66s/it]

VAE train ep9:  84%|████████▍ | 139/165 [17:58<03:19,  7.66s/it]

VAE train ep9:  85%|████████▍ | 140/165 [18:05<03:11,  7.68s/it]

VAE train ep9:  85%|████████▌ | 141/165 [18:13<03:06,  7.75s/it]

VAE train ep9:  86%|████████▌ | 142/165 [18:21<02:58,  7.75s/it]

VAE train ep9:  87%|████████▋ | 143/165 [18:29<02:49,  7.71s/it]

VAE train ep9:  87%|████████▋ | 144/165 [18:36<02:40,  7.65s/it]

VAE train ep9:  88%|████████▊ | 145/165 [18:44<02:32,  7.62s/it]

VAE train ep9:  88%|████████▊ | 146/165 [18:52<02:26,  7.70s/it]

VAE train ep9:  89%|████████▉ | 147/165 [18:59<02:19,  7.72s/it]

VAE train ep9:  90%|████████▉ | 148/165 [19:07<02:12,  7.78s/it]

VAE train ep9:  90%|█████████ | 149/165 [19:15<02:04,  7.78s/it]

VAE train ep9:  91%|█████████ | 150/165 [19:23<01:56,  7.75s/it]

VAE train ep9:  92%|█████████▏| 151/165 [19:30<01:48,  7.76s/it]

VAE train ep9:  92%|█████████▏| 152/165 [19:38<01:40,  7.75s/it]

VAE train ep9:  93%|█████████▎| 153/165 [19:46<01:32,  7.70s/it]

VAE train ep9:  93%|█████████▎| 154/165 [19:53<01:23,  7.63s/it]

VAE train ep9:  94%|█████████▍| 155/165 [20:01<01:15,  7.58s/it]

VAE train ep9:  95%|█████████▍| 156/165 [20:08<01:08,  7.62s/it]

VAE train ep9:  95%|█████████▌| 157/165 [20:16<01:01,  7.65s/it]

VAE train ep9:  96%|█████████▌| 158/165 [20:24<00:53,  7.60s/it]

VAE train ep9:  96%|█████████▋| 159/165 [20:31<00:45,  7.58s/it]

VAE train ep9:  97%|█████████▋| 160/165 [20:39<00:37,  7.59s/it]

VAE train ep9:  98%|█████████▊| 161/165 [20:46<00:30,  7.61s/it]

VAE train ep9:  98%|█████████▊| 162/165 [20:54<00:22,  7.60s/it]

VAE train ep9:  99%|█████████▉| 163/165 [21:02<00:15,  7.63s/it]

VAE train ep9:  99%|█████████▉| 164/165 [21:09<00:07,  7.58s/it]

VAE train ep9: 100%|██████████| 165/165 [21:10<00:00,  5.45s/it]

VAE val ep9:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep9:   3%|▎         | 1/29 [00:02<00:57,  2.04s/it]

VAE val ep9:   7%|▋         | 2/29 [00:04<00:54,  2.04s/it]

VAE val ep9:  10%|█         | 3/29 [00:06<00:53,  2.04s/it]

VAE val ep9:  14%|█▍        | 4/29 [00:08<00:50,  2.03s/it]

VAE val ep9:  17%|█▋        | 5/29 [00:10<00:48,  2.03s/it]

VAE val ep9:  21%|██        | 6/29 [00:12<00:47,  2.05s/it]

VAE val ep9:  24%|██▍       | 7/29 [00:14<00:45,  2.06s/it]

VAE val ep9:  28%|██▊       | 8/29 [00:16<00:43,  2.08s/it]

VAE val ep9:  31%|███       | 9/29 [00:18<00:41,  2.07s/it]

VAE val ep9:  34%|███▍      | 10/29 [00:20<00:39,  2.07s/it]

VAE val ep9:  38%|███▊      | 11/29 [00:22<00:37,  2.06s/it]

VAE val ep9:  41%|████▏     | 12/29 [00:24<00:35,  2.07s/it]

VAE val ep9:  45%|████▍     | 13/29 [00:26<00:33,  2.08s/it]

VAE val ep9:  48%|████▊     | 14/29 [00:28<00:30,  2.07s/it]

VAE val ep9:  52%|█████▏    | 15/29 [00:30<00:28,  2.05s/it]

VAE val ep9:  55%|█████▌    | 16/29 [00:32<00:26,  2.06s/it]

VAE val ep9:  59%|█████▊    | 17/29 [00:34<00:24,  2.05s/it]

VAE val ep9:  62%|██████▏   | 18/29 [00:36<00:22,  2.05s/it]

VAE val ep9:  66%|██████▌   | 19/29 [00:39<00:20,  2.04s/it]

VAE val ep9:  69%|██████▉   | 20/29 [00:41<00:18,  2.05s/it]

VAE val ep9:  72%|███████▏  | 21/29 [00:43<00:16,  2.04s/it]

VAE val ep9:  76%|███████▌  | 22/29 [00:45<00:14,  2.04s/it]

VAE val ep9:  79%|███████▉  | 23/29 [00:47<00:12,  2.04s/it]

VAE val ep9:  83%|████████▎ | 24/29 [00:49<00:10,  2.04s/it]

VAE val ep9:  86%|████████▌ | 25/29 [00:51<00:08,  2.04s/it]

VAE val ep9:  90%|████████▉ | 26/29 [00:53<00:06,  2.05s/it]

VAE val ep9:  93%|█████████▎| 27/29 [00:55<00:04,  2.06s/it]

VAE val ep9:  97%|█████████▋| 28/29 [00:57<00:02,  2.06s/it]

VAE val ep9: 100%|██████████| 29/29 [00:57<00:00,  1.52s/it]

VAE train ep10:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep10:   1%|          | 1/165 [00:08<22:16,  8.15s/it]

VAE train ep10:   1%|          | 2/165 [00:16<21:41,  7.98s/it]

VAE train ep10:   2%|▏         | 3/165 [00:23<21:23,  7.92s/it]

VAE train ep10:   2%|▏         | 4/165 [00:31<20:58,  7.82s/it]

VAE train ep10:   3%|▎         | 5/165 [00:39<20:33,  7.71s/it]

VAE train ep10:   4%|▎         | 6/165 [00:46<20:17,  7.66s/it]

VAE train ep10:   4%|▍         | 7/165 [00:54<20:05,  7.63s/it]

VAE train ep10:   5%|▍         | 8/165 [01:01<19:52,  7.59s/it]

VAE train ep10:   5%|▌         | 9/165 [01:09<19:55,  7.67s/it]

VAE train ep10:   6%|▌         | 10/165 [01:17<20:02,  7.76s/it]

VAE train ep10:   7%|▋         | 11/165 [01:25<19:54,  7.76s/it]

VAE train ep10:   7%|▋         | 12/165 [01:32<19:41,  7.73s/it]

VAE train ep10:   8%|▊         | 13/165 [01:40<19:42,  7.78s/it]

VAE train ep10:   8%|▊         | 14/165 [01:48<19:25,  7.72s/it]

VAE train ep10:   9%|▉         | 15/165 [01:56<19:24,  7.76s/it]

VAE train ep10:  10%|▉         | 16/165 [02:03<19:12,  7.74s/it]

VAE train ep10:  10%|█         | 17/165 [02:11<19:03,  7.73s/it]

VAE train ep10:  11%|█         | 18/165 [02:19<18:51,  7.70s/it]

VAE train ep10:  12%|█▏        | 19/165 [02:26<18:43,  7.69s/it]

VAE train ep10:  12%|█▏        | 20/165 [02:34<18:34,  7.68s/it]

VAE train ep10:  13%|█▎        | 21/165 [02:42<18:30,  7.71s/it]

VAE train ep10:  13%|█▎        | 22/165 [02:50<18:30,  7.77s/it]

VAE train ep10:  14%|█▍        | 23/165 [02:58<18:38,  7.87s/it]

VAE train ep10:  15%|█▍        | 24/165 [03:06<18:45,  7.98s/it]

VAE train ep10:  15%|█▌        | 25/165 [03:15<19:06,  8.19s/it]

VAE train ep10:  16%|█▌        | 26/165 [03:24<19:22,  8.36s/it]

VAE train ep10:  16%|█▋        | 27/165 [03:32<19:16,  8.38s/it]

VAE train ep10:  17%|█▋        | 28/165 [03:40<19:11,  8.41s/it]

VAE train ep10:  18%|█▊        | 29/165 [03:48<18:37,  8.22s/it]

VAE train ep10:  18%|█▊        | 30/165 [03:56<18:12,  8.09s/it]

VAE train ep10:  19%|█▉        | 31/165 [04:04<17:50,  7.99s/it]

VAE train ep10:  19%|█▉        | 32/165 [04:12<17:41,  7.98s/it]

VAE train ep10:  20%|██        | 33/165 [04:20<17:25,  7.92s/it]

VAE train ep10:  21%|██        | 34/165 [04:27<17:13,  7.89s/it]

VAE train ep10:  21%|██        | 35/165 [04:35<17:02,  7.86s/it]

VAE train ep10:  22%|██▏       | 36/165 [04:43<16:48,  7.82s/it]

VAE train ep10:  22%|██▏       | 37/165 [04:50<16:33,  7.76s/it]

VAE train ep10:  23%|██▎       | 38/165 [04:58<16:21,  7.73s/it]

VAE train ep10:  24%|██▎       | 39/165 [05:06<16:11,  7.71s/it]

VAE train ep10:  24%|██▍       | 40/165 [05:13<15:54,  7.63s/it]

VAE train ep10:  25%|██▍       | 41/165 [05:21<15:46,  7.63s/it]

VAE train ep10:  25%|██▌       | 42/165 [05:29<15:40,  7.64s/it]

VAE train ep10:  26%|██▌       | 43/165 [05:36<15:41,  7.72s/it]

VAE train ep10:  27%|██▋       | 44/165 [05:44<15:30,  7.69s/it]

VAE train ep10:  27%|██▋       | 45/165 [05:52<15:19,  7.67s/it]

VAE train ep10:  28%|██▊       | 46/165 [05:59<15:15,  7.69s/it]

VAE train ep10:  28%|██▊       | 47/165 [06:07<15:04,  7.67s/it]

VAE train ep10:  29%|██▉       | 48/165 [06:15<15:03,  7.72s/it]

VAE train ep10:  30%|██▉       | 49/165 [06:23<14:57,  7.73s/it]

VAE train ep10:  30%|███       | 50/165 [06:30<14:46,  7.71s/it]

VAE train ep10:  31%|███       | 51/165 [06:38<14:34,  7.67s/it]

VAE train ep10:  32%|███▏      | 52/165 [06:46<14:26,  7.67s/it]

VAE train ep10:  32%|███▏      | 53/165 [06:53<14:20,  7.68s/it]

VAE train ep10:  33%|███▎      | 54/165 [07:01<14:13,  7.69s/it]

VAE train ep10:  33%|███▎      | 55/165 [07:09<14:04,  7.68s/it]

VAE train ep10:  34%|███▍      | 56/165 [07:16<13:59,  7.70s/it]

VAE train ep10:  35%|███▍      | 57/165 [07:24<13:49,  7.68s/it]

VAE train ep10:  35%|███▌      | 58/165 [07:32<13:41,  7.68s/it]

VAE train ep10:  36%|███▌      | 59/165 [07:39<13:35,  7.69s/it]

VAE train ep10:  36%|███▋      | 60/165 [07:47<13:27,  7.69s/it]

VAE train ep10:  37%|███▋      | 61/165 [07:55<13:16,  7.66s/it]

VAE train ep10:  38%|███▊      | 62/165 [08:02<13:09,  7.66s/it]

VAE train ep10:  38%|███▊      | 63/165 [08:10<13:05,  7.70s/it]

VAE train ep10:  39%|███▉      | 64/165 [08:18<13:03,  7.76s/it]

VAE train ep10:  39%|███▉      | 65/165 [08:26<12:57,  7.78s/it]

VAE train ep10:  40%|████      | 66/165 [08:34<12:48,  7.76s/it]

VAE train ep10:  41%|████      | 67/165 [08:41<12:36,  7.72s/it]

VAE train ep10:  41%|████      | 68/165 [08:49<12:26,  7.69s/it]

VAE train ep10:  42%|████▏     | 69/165 [08:57<12:23,  7.74s/it]

VAE train ep10:  42%|████▏     | 70/165 [09:04<12:11,  7.70s/it]

VAE train ep10:  43%|████▎     | 71/165 [09:12<11:59,  7.65s/it]

VAE train ep10:  44%|████▎     | 72/165 [09:19<11:51,  7.65s/it]

VAE train ep10:  44%|████▍     | 73/165 [09:27<11:43,  7.64s/it]

VAE train ep10:  45%|████▍     | 74/165 [09:35<11:34,  7.64s/it]

VAE train ep10:  45%|████▌     | 75/165 [09:42<11:25,  7.62s/it]

VAE train ep10:  46%|████▌     | 76/165 [09:50<11:22,  7.67s/it]

VAE train ep10:  47%|████▋     | 77/165 [09:58<11:17,  7.70s/it]

VAE train ep10:  47%|████▋     | 78/165 [10:05<11:07,  7.67s/it]

VAE train ep10:  48%|████▊     | 79/165 [10:13<11:02,  7.70s/it]

VAE train ep10:  48%|████▊     | 80/165 [10:21<10:56,  7.72s/it]

VAE train ep10:  49%|████▉     | 81/165 [10:29<10:51,  7.75s/it]

VAE train ep10:  50%|████▉     | 82/165 [10:37<10:46,  7.79s/it]

VAE train ep10:  50%|█████     | 83/165 [10:44<10:35,  7.75s/it]

VAE train ep10:  51%|█████     | 84/165 [10:52<10:30,  7.78s/it]

VAE train ep10:  52%|█████▏    | 85/165 [11:00<10:25,  7.82s/it]

VAE train ep10:  52%|█████▏    | 86/165 [11:08<10:21,  7.87s/it]

VAE train ep10:  53%|█████▎    | 87/165 [11:16<10:10,  7.83s/it]

VAE train ep10:  53%|█████▎    | 88/165 [11:24<10:02,  7.82s/it]

VAE train ep10:  54%|█████▍    | 89/165 [11:31<09:51,  7.78s/it]

VAE train ep10:  55%|█████▍    | 90/165 [11:39<09:43,  7.77s/it]

VAE train ep10:  55%|█████▌    | 91/165 [11:47<09:37,  7.81s/it]

VAE train ep10:  56%|█████▌    | 92/165 [11:55<09:26,  7.75s/it]

VAE train ep10:  56%|█████▋    | 93/165 [12:02<09:15,  7.72s/it]

VAE train ep10:  57%|█████▋    | 94/165 [12:10<09:10,  7.75s/it]

VAE train ep10:  58%|█████▊    | 95/165 [12:18<09:05,  7.80s/it]

VAE train ep10:  58%|█████▊    | 96/165 [12:26<09:01,  7.85s/it]

VAE train ep10:  59%|█████▉    | 97/165 [12:34<08:57,  7.90s/it]

VAE train ep10:  59%|█████▉    | 98/165 [12:42<08:51,  7.93s/it]

VAE train ep10:  60%|██████    | 99/165 [12:50<08:43,  7.93s/it]

VAE train ep10:  61%|██████    | 100/165 [12:58<08:34,  7.91s/it]

VAE train ep10:  61%|██████    | 101/165 [13:06<08:27,  7.93s/it]

VAE train ep10:  62%|██████▏   | 102/165 [13:14<08:27,  8.05s/it]

VAE train ep10:  62%|██████▏   | 103/165 [13:22<08:20,  8.07s/it]

VAE train ep10:  63%|██████▎   | 104/165 [13:30<08:11,  8.06s/it]

VAE train ep10:  64%|██████▎   | 105/165 [13:38<07:59,  7.99s/it]

VAE train ep10:  64%|██████▍   | 106/165 [13:46<07:51,  7.99s/it]

VAE train ep10:  65%|██████▍   | 107/165 [13:54<07:38,  7.91s/it]

VAE train ep10:  65%|██████▌   | 108/165 [14:02<07:28,  7.88s/it]

VAE train ep10:  66%|██████▌   | 109/165 [14:09<07:20,  7.87s/it]

VAE train ep10:  67%|██████▋   | 110/165 [14:17<07:09,  7.80s/it]

VAE train ep10:  67%|██████▋   | 111/165 [14:25<07:01,  7.81s/it]

VAE train ep10:  68%|██████▊   | 112/165 [14:33<06:53,  7.81s/it]

VAE train ep10:  68%|██████▊   | 113/165 [14:41<06:46,  7.83s/it]

VAE train ep10:  69%|██████▉   | 114/165 [14:48<06:38,  7.82s/it]

VAE train ep10:  70%|██████▉   | 115/165 [14:56<06:32,  7.85s/it]

VAE train ep10:  70%|███████   | 116/165 [15:04<06:26,  7.88s/it]

VAE train ep10:  71%|███████   | 117/165 [15:12<06:19,  7.90s/it]

VAE train ep10:  72%|███████▏  | 118/165 [15:20<06:07,  7.81s/it]

VAE train ep10:  72%|███████▏  | 119/165 [15:27<05:54,  7.70s/it]

VAE train ep10:  73%|███████▎  | 120/165 [15:35<05:44,  7.66s/it]

VAE train ep10:  73%|███████▎  | 121/165 [15:42<05:35,  7.62s/it]

VAE train ep10:  74%|███████▍  | 122/165 [15:50<05:30,  7.68s/it]

VAE train ep10:  75%|███████▍  | 123/165 [15:58<05:22,  7.68s/it]

VAE train ep10:  75%|███████▌  | 124/165 [16:06<05:18,  7.76s/it]

VAE train ep10:  76%|███████▌  | 125/165 [16:13<05:08,  7.70s/it]

VAE train ep10:  76%|███████▋  | 126/165 [16:21<04:59,  7.68s/it]

VAE train ep10:  77%|███████▋  | 127/165 [16:29<04:52,  7.69s/it]

VAE train ep10:  78%|███████▊  | 128/165 [16:36<04:42,  7.64s/it]

VAE train ep10:  78%|███████▊  | 129/165 [16:44<04:35,  7.64s/it]

VAE train ep10:  79%|███████▉  | 130/165 [16:52<04:28,  7.66s/it]

VAE train ep10:  79%|███████▉  | 131/165 [16:59<04:20,  7.66s/it]

VAE train ep10:  80%|████████  | 132/165 [17:07<04:13,  7.68s/it]

VAE train ep10:  81%|████████  | 133/165 [17:15<04:05,  7.67s/it]

VAE train ep10:  81%|████████  | 134/165 [17:22<03:58,  7.70s/it]

VAE train ep10:  82%|████████▏ | 135/165 [17:30<03:50,  7.68s/it]

VAE train ep10:  82%|████████▏ | 136/165 [17:38<03:41,  7.65s/it]

VAE train ep10:  83%|████████▎ | 137/165 [17:45<03:34,  7.65s/it]

VAE train ep10:  84%|████████▎ | 138/165 [17:53<03:28,  7.71s/it]

VAE train ep10:  84%|████████▍ | 139/165 [18:01<03:22,  7.79s/it]

VAE train ep10:  85%|████████▍ | 140/165 [18:09<03:15,  7.80s/it]

VAE train ep10:  85%|████████▌ | 141/165 [18:17<03:07,  7.81s/it]

VAE train ep10:  86%|████████▌ | 142/165 [18:25<03:01,  7.88s/it]

VAE train ep10:  87%|████████▋ | 143/165 [18:33<02:56,  8.01s/it]

VAE train ep10:  87%|████████▋ | 144/165 [18:41<02:49,  8.09s/it]

VAE train ep10:  88%|████████▊ | 145/165 [18:50<02:44,  8.20s/it]

VAE train ep10:  88%|████████▊ | 146/165 [18:58<02:35,  8.19s/it]

VAE train ep10:  89%|████████▉ | 147/165 [19:06<02:27,  8.17s/it]

VAE train ep10:  90%|████████▉ | 148/165 [19:14<02:17,  8.08s/it]

VAE train ep10:  90%|█████████ | 149/165 [19:22<02:08,  8.06s/it]

VAE train ep10:  91%|█████████ | 150/165 [19:30<02:00,  8.02s/it]

VAE train ep10:  92%|█████████▏| 151/165 [19:38<01:51,  7.98s/it]

VAE train ep10:  92%|█████████▏| 152/165 [19:46<01:43,  7.93s/it]

VAE train ep10:  93%|█████████▎| 153/165 [19:54<01:35,  7.93s/it]

VAE train ep10:  93%|█████████▎| 154/165 [20:01<01:27,  7.93s/it]

VAE train ep10:  94%|█████████▍| 155/165 [20:09<01:19,  7.91s/it]

VAE train ep10:  95%|█████████▍| 156/165 [20:17<01:11,  7.95s/it]

VAE train ep10:  95%|█████████▌| 157/165 [20:25<01:03,  7.93s/it]

VAE train ep10:  96%|█████████▌| 158/165 [20:33<00:55,  7.94s/it]

VAE train ep10:  96%|█████████▋| 159/165 [20:41<00:47,  7.92s/it]

VAE train ep10:  97%|█████████▋| 160/165 [20:49<00:39,  7.86s/it]

VAE train ep10:  98%|█████████▊| 161/165 [20:57<00:31,  7.97s/it]

VAE train ep10:  98%|█████████▊| 162/165 [21:05<00:23,  7.94s/it]

VAE train ep10:  99%|█████████▉| 163/165 [21:13<00:15,  7.91s/it]

VAE train ep10:  99%|█████████▉| 164/165 [21:21<00:07,  7.89s/it]

VAE train ep10: 100%|██████████| 165/165 [21:21<00:00,  5.67s/it]

VAE val ep10:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep10:   3%|▎         | 1/29 [00:02<00:58,  2.09s/it]

VAE val ep10:   7%|▋         | 2/29 [00:04<00:56,  2.08s/it]

VAE val ep10:  10%|█         | 3/29 [00:06<00:54,  2.10s/it]

VAE val ep10:  14%|█▍        | 4/29 [00:08<00:52,  2.12s/it]

VAE val ep10:  17%|█▋        | 5/29 [00:10<00:50,  2.12s/it]

VAE val ep10:  21%|██        | 6/29 [00:12<00:48,  2.13s/it]

VAE val ep10:  24%|██▍       | 7/29 [00:14<00:47,  2.14s/it]

VAE val ep10:  28%|██▊       | 8/29 [00:17<00:45,  2.16s/it]

VAE val ep10:  31%|███       | 9/29 [00:19<00:43,  2.16s/it]

VAE val ep10:  34%|███▍      | 10/29 [00:21<00:41,  2.16s/it]

VAE val ep10:  38%|███▊      | 11/29 [00:23<00:38,  2.14s/it]

VAE val ep10:  41%|████▏     | 12/29 [00:25<00:36,  2.13s/it]

VAE val ep10:  45%|████▍     | 13/29 [00:27<00:33,  2.12s/it]

VAE val ep10:  48%|████▊     | 14/29 [00:29<00:31,  2.11s/it]

VAE val ep10:  52%|█████▏    | 15/29 [00:31<00:29,  2.11s/it]

VAE val ep10:  55%|█████▌    | 16/29 [00:33<00:27,  2.10s/it]

VAE val ep10:  59%|█████▊    | 17/29 [00:36<00:25,  2.10s/it]

VAE val ep10:  62%|██████▏   | 18/29 [00:38<00:23,  2.11s/it]

VAE val ep10:  66%|██████▌   | 19/29 [00:40<00:21,  2.12s/it]

VAE val ep10:  69%|██████▉   | 20/29 [00:42<00:18,  2.11s/it]

VAE val ep10:  72%|███████▏  | 21/29 [00:44<00:16,  2.10s/it]

VAE val ep10:  76%|███████▌  | 22/29 [00:46<00:14,  2.11s/it]

VAE val ep10:  79%|███████▉  | 23/29 [00:48<00:12,  2.09s/it]

VAE val ep10:  83%|████████▎ | 24/29 [00:50<00:10,  2.08s/it]

VAE val ep10:  86%|████████▌ | 25/29 [00:52<00:08,  2.07s/it]

VAE val ep10:  90%|████████▉ | 26/29 [00:54<00:06,  2.07s/it]

VAE val ep10:  93%|█████████▎| 27/29 [00:57<00:04,  2.10s/it]

VAE val ep10:  97%|█████████▋| 28/29 [00:59<00:02,  2.12s/it]

VAE val ep10: 100%|██████████| 29/29 [00:59<00:00,  1.56s/it]

VAE train ep11:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep11:   1%|          | 1/165 [00:08<22:43,  8.31s/it]

VAE train ep11:   1%|          | 2/165 [00:16<21:58,  8.09s/it]

VAE train ep11:   2%|▏         | 3/165 [00:24<21:48,  8.08s/it]

VAE train ep11:   2%|▏         | 4/165 [00:32<21:34,  8.04s/it]

VAE train ep11:   3%|▎         | 5/165 [00:40<21:23,  8.02s/it]

VAE train ep11:   4%|▎         | 6/165 [00:48<21:29,  8.11s/it]

VAE train ep11:   4%|▍         | 7/165 [00:56<21:26,  8.14s/it]

VAE train ep11:   5%|▍         | 8/165 [01:04<21:12,  8.11s/it]

VAE train ep11:   5%|▌         | 9/165 [01:12<21:03,  8.10s/it]

VAE train ep11:   6%|▌         | 10/165 [01:20<20:51,  8.08s/it]

VAE train ep11:   7%|▋         | 11/165 [01:28<20:42,  8.07s/it]

VAE train ep11:   7%|▋         | 12/165 [01:37<20:35,  8.07s/it]

VAE train ep11:   8%|▊         | 13/165 [01:45<20:33,  8.11s/it]

VAE train ep11:   8%|▊         | 14/165 [01:53<20:25,  8.12s/it]

VAE train ep11:   9%|▉         | 15/165 [02:01<20:18,  8.12s/it]

VAE train ep11:  10%|▉         | 16/165 [02:09<20:06,  8.10s/it]

VAE train ep11:  10%|█         | 17/165 [02:17<19:55,  8.08s/it]

VAE train ep11:  11%|█         | 18/165 [02:25<19:51,  8.11s/it]

VAE train ep11:  12%|█▏        | 19/165 [02:33<19:37,  8.07s/it]

VAE train ep11:  12%|█▏        | 20/165 [02:41<19:27,  8.05s/it]

VAE train ep11:  13%|█▎        | 21/165 [02:49<19:21,  8.06s/it]

VAE train ep11:  13%|█▎        | 22/165 [02:57<19:08,  8.03s/it]

VAE train ep11:  14%|█▍        | 23/165 [03:06<19:09,  8.09s/it]

VAE train ep11:  15%|█▍        | 24/165 [03:14<19:09,  8.15s/it]

VAE train ep11:  15%|█▌        | 25/165 [03:22<18:59,  8.14s/it]

VAE train ep11:  16%|█▌        | 26/165 [03:30<18:44,  8.09s/it]

VAE train ep11:  16%|█▋        | 27/165 [03:38<18:30,  8.05s/it]

VAE train ep11:  17%|█▋        | 28/165 [03:46<18:16,  8.01s/it]

VAE train ep11:  18%|█▊        | 29/165 [03:54<18:06,  7.99s/it]

VAE train ep11:  18%|█▊        | 30/165 [04:02<17:54,  7.96s/it]

VAE train ep11:  19%|█▉        | 31/165 [04:09<17:38,  7.90s/it]

VAE train ep11:  19%|█▉        | 32/165 [04:17<17:22,  7.84s/it]

VAE train ep11:  20%|██        | 33/165 [04:25<17:08,  7.79s/it]

VAE train ep11:  21%|██        | 34/165 [04:33<16:59,  7.78s/it]

VAE train ep11:  21%|██        | 35/165 [04:40<16:51,  7.78s/it]

VAE train ep11:  22%|██▏       | 36/165 [04:48<16:41,  7.76s/it]

VAE train ep11:  22%|██▏       | 37/165 [04:56<16:25,  7.70s/it]

VAE train ep11:  23%|██▎       | 38/165 [05:03<16:10,  7.64s/it]

VAE train ep11:  24%|██▎       | 39/165 [05:11<16:02,  7.64s/it]

VAE train ep11:  24%|██▍       | 40/165 [05:18<15:53,  7.63s/it]

VAE train ep11:  25%|██▍       | 41/165 [05:26<15:46,  7.63s/it]

VAE train ep11:  25%|██▌       | 42/165 [05:34<15:38,  7.63s/it]

VAE train ep11:  26%|██▌       | 43/165 [05:41<15:32,  7.64s/it]

VAE train ep11:  27%|██▋       | 44/165 [05:49<15:26,  7.65s/it]

VAE train ep11:  27%|██▋       | 45/165 [05:57<15:17,  7.65s/it]

VAE train ep11:  28%|██▊       | 46/165 [06:04<15:07,  7.63s/it]

VAE train ep11:  28%|██▊       | 47/165 [06:12<15:01,  7.64s/it]

VAE train ep11:  29%|██▉       | 48/165 [06:19<14:54,  7.64s/it]

VAE train ep11:  30%|██▉       | 49/165 [06:27<14:47,  7.65s/it]

VAE train ep11:  30%|███       | 50/165 [06:35<14:42,  7.68s/it]

VAE train ep11:  31%|███       | 51/165 [06:42<14:29,  7.63s/it]

VAE train ep11:  32%|███▏      | 52/165 [06:50<14:30,  7.70s/it]

VAE train ep11:  32%|███▏      | 53/165 [06:58<14:22,  7.71s/it]

VAE train ep11:  33%|███▎      | 54/165 [07:06<14:18,  7.74s/it]

VAE train ep11:  33%|███▎      | 55/165 [07:13<14:10,  7.73s/it]

VAE train ep11:  34%|███▍      | 56/165 [07:21<13:57,  7.68s/it]

VAE train ep11:  35%|███▍      | 57/165 [07:29<13:46,  7.65s/it]

VAE train ep11:  35%|███▌      | 58/165 [07:36<13:38,  7.65s/it]

VAE train ep11:  36%|███▌      | 59/165 [07:44<13:31,  7.65s/it]

VAE train ep11:  36%|███▋      | 60/165 [07:52<13:32,  7.74s/it]

VAE train ep11:  37%|███▋      | 61/165 [08:00<13:26,  7.76s/it]

VAE train ep11:  38%|███▊      | 62/165 [08:07<13:18,  7.75s/it]

VAE train ep11:  38%|███▊      | 63/165 [08:15<13:07,  7.72s/it]

VAE train ep11:  39%|███▉      | 64/165 [08:23<12:57,  7.70s/it]

VAE train ep11:  39%|███▉      | 65/165 [08:30<12:48,  7.68s/it]

VAE train ep11:  40%|████      | 66/165 [08:38<12:38,  7.66s/it]

VAE train ep11:  41%|████      | 67/165 [08:46<12:33,  7.69s/it]

VAE train ep11:  41%|████      | 68/165 [08:53<12:22,  7.66s/it]

VAE train ep11:  42%|████▏     | 69/165 [09:01<12:11,  7.62s/it]

VAE train ep11:  42%|████▏     | 70/165 [09:09<12:05,  7.64s/it]

VAE train ep11:  43%|████▎     | 71/165 [09:16<11:56,  7.63s/it]

VAE train ep11:  44%|████▎     | 72/165 [09:24<11:44,  7.57s/it]

VAE train ep11:  44%|████▍     | 73/165 [09:31<11:36,  7.57s/it]

VAE train ep11:  45%|████▍     | 74/165 [09:39<11:31,  7.60s/it]

VAE train ep11:  45%|████▌     | 75/165 [09:46<11:25,  7.62s/it]

VAE train ep11:  46%|████▌     | 76/165 [09:54<11:15,  7.59s/it]

VAE train ep11:  47%|████▋     | 77/165 [10:02<11:07,  7.58s/it]

VAE train ep11:  47%|████▋     | 78/165 [10:09<10:59,  7.58s/it]

VAE train ep11:  48%|████▊     | 79/165 [10:17<10:53,  7.60s/it]

VAE train ep11:  48%|████▊     | 80/165 [10:24<10:45,  7.59s/it]

VAE train ep11:  49%|████▉     | 81/165 [10:32<10:38,  7.60s/it]

VAE train ep11:  50%|████▉     | 82/165 [10:40<10:29,  7.59s/it]

VAE train ep11:  50%|█████     | 83/165 [10:47<10:22,  7.59s/it]

VAE train ep11:  51%|█████     | 84/165 [10:55<10:16,  7.61s/it]

VAE train ep11:  52%|█████▏    | 85/165 [11:02<10:10,  7.63s/it]

VAE train ep11:  52%|█████▏    | 86/165 [11:10<10:02,  7.63s/it]

VAE train ep11:  53%|█████▎    | 87/165 [11:18<09:55,  7.63s/it]

VAE train ep11:  53%|█████▎    | 88/165 [11:25<09:50,  7.67s/it]

VAE train ep11:  54%|█████▍    | 89/165 [11:33<09:41,  7.66s/it]

VAE train ep11:  55%|█████▍    | 90/165 [11:41<09:32,  7.64s/it]

VAE train ep11:  55%|█████▌    | 91/165 [11:48<09:23,  7.61s/it]

VAE train ep11:  56%|█████▌    | 92/165 [11:56<09:13,  7.58s/it]

VAE train ep11:  56%|█████▋    | 93/165 [12:03<09:09,  7.63s/it]

VAE train ep11:  57%|█████▋    | 94/165 [12:11<09:00,  7.62s/it]

VAE train ep11:  58%|█████▊    | 95/165 [12:19<08:55,  7.64s/it]

VAE train ep11:  58%|█████▊    | 96/165 [12:26<08:47,  7.65s/it]

VAE train ep11:  59%|█████▉    | 97/165 [12:34<08:41,  7.67s/it]

VAE train ep11:  59%|█████▉    | 98/165 [12:42<08:33,  7.66s/it]

VAE train ep11:  60%|██████    | 99/165 [12:49<08:24,  7.65s/it]

VAE train ep11:  61%|██████    | 100/165 [12:57<08:19,  7.68s/it]

VAE train ep11:  61%|██████    | 101/165 [13:05<08:14,  7.72s/it]

VAE train ep11:  62%|██████▏   | 102/165 [13:13<08:05,  7.71s/it]

VAE train ep11:  62%|██████▏   | 103/165 [13:20<07:59,  7.74s/it]

VAE train ep11:  63%|██████▎   | 104/165 [13:28<07:52,  7.74s/it]

VAE train ep11:  64%|██████▎   | 105/165 [13:36<07:45,  7.76s/it]

VAE train ep11:  64%|██████▍   | 106/165 [13:44<07:38,  7.77s/it]

VAE train ep11:  65%|██████▍   | 107/165 [13:52<07:33,  7.82s/it]

VAE train ep11:  65%|██████▌   | 108/165 [14:00<07:26,  7.84s/it]

VAE train ep11:  66%|██████▌   | 109/165 [14:07<07:19,  7.84s/it]

VAE train ep11:  67%|██████▋   | 110/165 [14:15<07:10,  7.83s/it]

VAE train ep11:  67%|██████▋   | 111/165 [14:23<07:02,  7.82s/it]

VAE train ep11:  68%|██████▊   | 112/165 [14:31<06:54,  7.82s/it]

VAE train ep11:  68%|██████▊   | 113/165 [14:39<06:47,  7.84s/it]

VAE train ep11:  69%|██████▉   | 114/165 [14:47<06:40,  7.84s/it]

VAE train ep11:  70%|██████▉   | 115/165 [14:54<06:30,  7.81s/it]

VAE train ep11:  70%|███████   | 116/165 [15:02<06:20,  7.77s/it]

VAE train ep11:  71%|███████   | 117/165 [15:10<06:14,  7.80s/it]

VAE train ep11:  72%|███████▏  | 118/165 [15:18<06:07,  7.82s/it]

VAE train ep11:  72%|███████▏  | 119/165 [15:26<05:59,  7.82s/it]

VAE train ep11:  73%|███████▎  | 120/165 [15:33<05:49,  7.77s/it]

VAE train ep11:  73%|███████▎  | 121/165 [15:41<05:40,  7.75s/it]

VAE train ep11:  74%|███████▍  | 122/165 [15:49<05:34,  7.79s/it]

VAE train ep11:  75%|███████▍  | 123/165 [15:57<05:30,  7.86s/it]

VAE train ep11:  75%|███████▌  | 124/165 [16:05<05:21,  7.83s/it]

VAE train ep11:  76%|███████▌  | 125/165 [16:12<05:12,  7.81s/it]

VAE train ep11:  76%|███████▋  | 126/165 [16:20<05:03,  7.79s/it]

VAE train ep11:  77%|███████▋  | 127/165 [16:28<04:54,  7.76s/it]

VAE train ep11:  78%|███████▊  | 128/165 [16:36<04:46,  7.75s/it]

VAE train ep11:  78%|███████▊  | 129/165 [16:43<04:38,  7.74s/it]

VAE train ep11:  79%|███████▉  | 130/165 [16:51<04:29,  7.71s/it]

VAE train ep11:  79%|███████▉  | 131/165 [16:58<04:20,  7.67s/it]

VAE train ep11:  80%|████████  | 132/165 [17:06<04:14,  7.70s/it]

VAE train ep11:  81%|████████  | 133/165 [17:14<04:08,  7.76s/it]

VAE train ep11:  81%|████████  | 134/165 [17:22<04:01,  7.78s/it]

VAE train ep11:  82%|████████▏ | 135/165 [17:30<03:52,  7.75s/it]

VAE train ep11:  82%|████████▏ | 136/165 [17:37<03:43,  7.70s/it]

VAE train ep11:  83%|████████▎ | 137/165 [17:45<03:38,  7.79s/it]

VAE train ep11:  84%|████████▎ | 138/165 [17:53<03:30,  7.78s/it]

VAE train ep11:  84%|████████▍ | 139/165 [18:01<03:22,  7.80s/it]

VAE train ep11:  85%|████████▍ | 140/165 [18:08<03:13,  7.75s/it]

VAE train ep11:  85%|████████▌ | 141/165 [18:16<03:04,  7.68s/it]

VAE train ep11:  86%|████████▌ | 142/165 [18:24<02:55,  7.64s/it]

VAE train ep11:  87%|████████▋ | 143/165 [18:31<02:48,  7.67s/it]

VAE train ep11:  87%|████████▋ | 144/165 [18:39<02:41,  7.67s/it]

VAE train ep11:  88%|████████▊ | 145/165 [18:47<02:33,  7.67s/it]

VAE train ep11:  88%|████████▊ | 146/165 [18:54<02:25,  7.67s/it]

VAE train ep11:  89%|████████▉ | 147/165 [19:02<02:18,  7.68s/it]

VAE train ep11:  90%|████████▉ | 148/165 [19:10<02:10,  7.70s/it]

VAE train ep11:  90%|█████████ | 149/165 [19:18<02:04,  7.76s/it]

VAE train ep11:  91%|█████████ | 150/165 [19:26<01:57,  7.85s/it]

VAE train ep11:  92%|█████████▏| 151/165 [19:34<01:49,  7.85s/it]

VAE train ep11:  92%|█████████▏| 152/165 [19:41<01:41,  7.80s/it]

VAE train ep11:  93%|█████████▎| 153/165 [19:49<01:34,  7.88s/it]

VAE train ep11:  93%|█████████▎| 154/165 [19:57<01:27,  7.92s/it]

VAE train ep11:  94%|█████████▍| 155/165 [20:06<01:20,  8.05s/it]

VAE train ep11:  95%|█████████▍| 156/165 [20:14<01:13,  8.13s/it]

VAE train ep11:  95%|█████████▌| 157/165 [20:22<01:05,  8.24s/it]

VAE train ep11:  96%|█████████▌| 158/165 [20:31<00:57,  8.19s/it]

VAE train ep11:  96%|█████████▋| 159/165 [20:38<00:48,  8.11s/it]

VAE train ep11:  97%|█████████▋| 160/165 [20:46<00:40,  8.03s/it]

VAE train ep11:  98%|█████████▊| 161/165 [20:54<00:32,  8.01s/it]

VAE train ep11:  98%|█████████▊| 162/165 [21:02<00:23,  7.97s/it]

VAE train ep11:  99%|█████████▉| 163/165 [21:10<00:16,  8.00s/it]

VAE train ep11:  99%|█████████▉| 164/165 [21:18<00:08,  8.03s/it]

VAE train ep11: 100%|██████████| 165/165 [21:19<00:00,  5.76s/it]

VAE val ep11:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep11:   3%|▎         | 1/29 [00:02<00:59,  2.13s/it]

VAE val ep11:   7%|▋         | 2/29 [00:04<00:58,  2.15s/it]

VAE val ep11:  10%|█         | 3/29 [00:06<00:55,  2.15s/it]

VAE val ep11:  14%|█▍        | 4/29 [00:08<00:53,  2.15s/it]

VAE val ep11:  17%|█▋        | 5/29 [00:10<00:51,  2.13s/it]

VAE val ep11:  21%|██        | 6/29 [00:12<00:48,  2.12s/it]

VAE val ep11:  24%|██▍       | 7/29 [00:14<00:46,  2.13s/it]

VAE val ep11:  28%|██▊       | 8/29 [00:17<00:44,  2.13s/it]

VAE val ep11:  31%|███       | 9/29 [00:19<00:42,  2.11s/it]

VAE val ep11:  34%|███▍      | 10/29 [00:21<00:40,  2.11s/it]

VAE val ep11:  38%|███▊      | 11/29 [00:23<00:37,  2.11s/it]

VAE val ep11:  41%|████▏     | 12/29 [00:25<00:35,  2.11s/it]

VAE val ep11:  45%|████▍     | 13/29 [00:27<00:34,  2.15s/it]

VAE val ep11:  48%|████▊     | 14/29 [00:29<00:32,  2.16s/it]

VAE val ep11:  52%|█████▏    | 15/29 [00:32<00:30,  2.16s/it]

VAE val ep11:  55%|█████▌    | 16/29 [00:34<00:28,  2.17s/it]

VAE val ep11:  59%|█████▊    | 17/29 [00:36<00:25,  2.16s/it]

VAE val ep11:  62%|██████▏   | 18/29 [00:38<00:23,  2.15s/it]

VAE val ep11:  66%|██████▌   | 19/29 [00:40<00:21,  2.16s/it]

VAE val ep11:  69%|██████▉   | 20/29 [00:42<00:19,  2.14s/it]

VAE val ep11:  72%|███████▏  | 21/29 [00:44<00:17,  2.13s/it]

VAE val ep11:  76%|███████▌  | 22/29 [00:46<00:14,  2.12s/it]

VAE val ep11:  79%|███████▉  | 23/29 [00:49<00:12,  2.11s/it]

VAE val ep11:  83%|████████▎ | 24/29 [00:51<00:10,  2.10s/it]

VAE val ep11:  86%|████████▌ | 25/29 [00:53<00:08,  2.09s/it]

VAE val ep11:  90%|████████▉ | 26/29 [00:55<00:06,  2.08s/it]

VAE val ep11:  93%|█████████▎| 27/29 [00:57<00:04,  2.09s/it]

VAE val ep11:  97%|█████████▋| 28/29 [00:59<00:02,  2.10s/it]

VAE val ep11: 100%|██████████| 29/29 [00:59<00:00,  1.55s/it]

VAE train ep12:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep12:   1%|          | 1/165 [00:08<22:07,  8.10s/it]

VAE train ep12:   1%|          | 2/165 [00:16<22:06,  8.14s/it]

VAE train ep12:   2%|▏         | 3/165 [00:24<21:53,  8.11s/it]

VAE train ep12:   2%|▏         | 4/165 [00:32<21:43,  8.10s/it]

VAE train ep12:   3%|▎         | 5/165 [00:40<21:22,  8.01s/it]

VAE train ep12:   4%|▎         | 6/165 [00:48<21:05,  7.96s/it]

VAE train ep12:   4%|▍         | 7/165 [00:56<20:58,  7.96s/it]

VAE train ep12:   5%|▍         | 8/165 [01:04<21:06,  8.07s/it]

VAE train ep12:   5%|▌         | 9/165 [01:12<20:41,  7.96s/it]

VAE train ep12:   6%|▌         | 10/165 [01:19<20:22,  7.89s/it]

VAE train ep12:   7%|▋         | 11/165 [01:27<20:11,  7.87s/it]

VAE train ep12:   7%|▋         | 12/165 [01:35<20:04,  7.87s/it]

VAE train ep12:   8%|▊         | 13/165 [01:43<19:59,  7.89s/it]

VAE train ep12:   8%|▊         | 14/165 [01:51<19:54,  7.91s/it]

VAE train ep12:   9%|▉         | 15/165 [01:59<19:41,  7.87s/it]

VAE train ep12:  10%|▉         | 16/165 [02:06<19:27,  7.84s/it]

VAE train ep12:  10%|█         | 17/165 [02:14<19:17,  7.82s/it]

VAE train ep12:  11%|█         | 18/165 [02:22<19:16,  7.87s/it]

VAE train ep12:  12%|█▏        | 19/165 [02:31<19:41,  8.09s/it]

VAE train ep12:  12%|█▏        | 20/165 [02:39<19:19,  8.00s/it]

VAE train ep12:  13%|█▎        | 21/165 [02:46<19:05,  7.96s/it]

VAE train ep12:  13%|█▎        | 22/165 [02:54<18:49,  7.90s/it]

VAE train ep12:  14%|█▍        | 23/165 [03:02<18:39,  7.88s/it]

VAE train ep12:  15%|█▍        | 24/165 [03:10<18:31,  7.88s/it]

VAE train ep12:  15%|█▌        | 25/165 [03:18<18:12,  7.81s/it]

VAE train ep12:  16%|█▌        | 26/165 [03:25<17:57,  7.75s/it]

VAE train ep12:  16%|█▋        | 27/165 [03:33<17:44,  7.72s/it]

VAE train ep12:  17%|█▋        | 28/165 [03:41<17:37,  7.72s/it]

VAE train ep12:  18%|█▊        | 29/165 [03:48<17:33,  7.75s/it]

VAE train ep12:  18%|█▊        | 30/165 [03:56<17:19,  7.70s/it]

VAE train ep12:  19%|█▉        | 31/165 [04:04<17:11,  7.69s/it]

VAE train ep12:  19%|█▉        | 32/165 [04:11<17:02,  7.68s/it]

VAE train ep12:  20%|██        | 33/165 [04:19<17:02,  7.75s/it]

VAE train ep12:  21%|██        | 34/165 [04:27<17:07,  7.84s/it]

VAE train ep12:  21%|██        | 35/165 [04:35<17:03,  7.87s/it]

VAE train ep12:  22%|██▏       | 36/165 [04:43<16:54,  7.87s/it]

VAE train ep12:  22%|██▏       | 37/165 [04:51<16:34,  7.77s/it]

VAE train ep12:  23%|██▎       | 38/165 [04:58<16:17,  7.70s/it]

VAE train ep12:  24%|██▎       | 39/165 [05:06<16:03,  7.65s/it]

VAE train ep12:  24%|██▍       | 40/165 [05:13<15:57,  7.66s/it]

VAE train ep12:  25%|██▍       | 41/165 [05:21<15:45,  7.63s/it]

VAE train ep12:  25%|██▌       | 42/165 [05:28<15:32,  7.58s/it]

VAE train ep12:  26%|██▌       | 43/165 [05:36<15:20,  7.55s/it]

VAE train ep12:  27%|██▋       | 44/165 [05:43<15:14,  7.56s/it]

VAE train ep12:  27%|██▋       | 45/165 [05:51<15:10,  7.58s/it]

VAE train ep12:  28%|██▊       | 46/165 [05:59<15:04,  7.60s/it]

VAE train ep12:  28%|██▊       | 47/165 [06:06<14:55,  7.59s/it]

VAE train ep12:  29%|██▉       | 48/165 [06:14<14:46,  7.57s/it]

VAE train ep12:  30%|██▉       | 49/165 [06:21<14:36,  7.56s/it]

VAE train ep12:  30%|███       | 50/165 [06:29<14:29,  7.56s/it]

VAE train ep12:  31%|███       | 51/165 [06:37<14:23,  7.58s/it]

VAE train ep12:  32%|███▏      | 52/165 [06:44<14:18,  7.59s/it]

VAE train ep12:  32%|███▏      | 53/165 [06:52<14:10,  7.60s/it]

VAE train ep12:  33%|███▎      | 54/165 [07:00<14:09,  7.65s/it]

VAE train ep12:  33%|███▎      | 55/165 [07:07<14:08,  7.72s/it]

VAE train ep12:  34%|███▍      | 56/165 [07:15<13:55,  7.67s/it]

VAE train ep12:  35%|███▍      | 57/165 [07:23<13:48,  7.67s/it]

VAE train ep12:  35%|███▌      | 58/165 [07:30<13:39,  7.66s/it]

VAE train ep12:  36%|███▌      | 59/165 [07:38<13:29,  7.63s/it]

VAE train ep12:  36%|███▋      | 60/165 [07:45<13:17,  7.60s/it]

VAE train ep12:  37%|███▋      | 61/165 [07:53<13:06,  7.57s/it]

VAE train ep12:  38%|███▊      | 62/165 [08:00<12:57,  7.55s/it]

VAE train ep12:  38%|███▊      | 63/165 [08:08<12:44,  7.50s/it]

VAE train ep12:  39%|███▉      | 64/165 [08:15<12:35,  7.48s/it]

VAE train ep12:  39%|███▉      | 65/165 [08:23<12:30,  7.50s/it]

VAE train ep12:  40%|████      | 66/165 [08:31<12:30,  7.59s/it]

VAE train ep12:  41%|████      | 67/165 [08:38<12:22,  7.58s/it]

VAE train ep12:  41%|████      | 68/165 [08:46<12:14,  7.58s/it]

VAE train ep12:  42%|████▏     | 69/165 [08:53<12:06,  7.57s/it]

VAE train ep12:  42%|████▏     | 70/165 [09:01<11:56,  7.54s/it]

VAE train ep12:  43%|████▎     | 71/165 [09:08<11:51,  7.57s/it]

VAE train ep12:  44%|████▎     | 72/165 [09:16<11:42,  7.55s/it]

VAE train ep12:  44%|████▍     | 73/165 [09:23<11:31,  7.52s/it]

VAE train ep12:  45%|████▍     | 74/165 [09:31<11:24,  7.52s/it]

VAE train ep12:  45%|████▌     | 75/165 [09:38<11:18,  7.54s/it]

VAE train ep12:  46%|████▌     | 76/165 [09:46<11:14,  7.58s/it]

VAE train ep12:  47%|████▋     | 77/165 [09:54<11:09,  7.61s/it]

VAE train ep12:  47%|████▋     | 78/165 [10:01<11:00,  7.59s/it]

VAE train ep12:  48%|████▊     | 79/165 [10:09<10:53,  7.60s/it]

VAE train ep12:  48%|████▊     | 80/165 [10:16<10:45,  7.59s/it]

VAE train ep12:  49%|████▉     | 81/165 [10:24<10:41,  7.64s/it]

VAE train ep12:  50%|████▉     | 82/165 [10:32<10:37,  7.68s/it]

VAE train ep12:  50%|█████     | 83/165 [10:39<10:23,  7.61s/it]

VAE train ep12:  51%|█████     | 84/165 [10:47<10:12,  7.56s/it]

VAE train ep12:  52%|█████▏    | 85/165 [10:54<10:02,  7.54s/it]

VAE train ep12:  52%|█████▏    | 86/165 [11:02<09:57,  7.57s/it]

VAE train ep12:  53%|█████▎    | 87/165 [11:10<09:49,  7.56s/it]

VAE train ep12:  53%|█████▎    | 88/165 [11:17<09:43,  7.57s/it]

VAE train ep12:  54%|█████▍    | 89/165 [11:25<09:36,  7.59s/it]

VAE train ep12:  55%|█████▍    | 90/165 [11:33<09:33,  7.64s/it]

VAE train ep12:  55%|█████▌    | 91/165 [11:40<09:25,  7.64s/it]

VAE train ep12:  56%|█████▌    | 92/165 [11:48<09:14,  7.60s/it]

VAE train ep12:  56%|█████▋    | 93/165 [11:55<09:05,  7.58s/it]

VAE train ep12:  57%|█████▋    | 94/165 [12:03<08:57,  7.57s/it]

VAE train ep12:  58%|█████▊    | 95/165 [12:10<08:46,  7.51s/it]

VAE train ep12:  58%|█████▊    | 96/165 [12:18<08:37,  7.50s/it]

VAE train ep12:  59%|█████▉    | 97/165 [12:25<08:31,  7.52s/it]

VAE train ep12:  59%|█████▉    | 98/165 [12:33<08:21,  7.48s/it]

VAE train ep12:  60%|██████    | 99/165 [12:40<08:15,  7.51s/it]

VAE train ep12:  61%|██████    | 100/165 [12:48<08:13,  7.59s/it]

VAE train ep12:  61%|██████    | 101/165 [12:56<08:07,  7.61s/it]

VAE train ep12:  62%|██████▏   | 102/165 [13:03<08:00,  7.63s/it]

VAE train ep12:  62%|██████▏   | 103/165 [13:11<07:54,  7.65s/it]

VAE train ep12:  63%|██████▎   | 104/165 [13:18<07:43,  7.59s/it]

VAE train ep12:  64%|██████▎   | 105/165 [13:26<07:34,  7.57s/it]

VAE train ep12:  64%|██████▍   | 106/165 [13:33<07:25,  7.55s/it]

VAE train ep12:  65%|██████▍   | 107/165 [13:41<07:20,  7.59s/it]

VAE train ep12:  65%|██████▌   | 108/165 [13:49<07:12,  7.59s/it]

VAE train ep12:  66%|██████▌   | 109/165 [13:56<07:03,  7.55s/it]

VAE train ep12:  67%|██████▋   | 110/165 [14:04<06:55,  7.56s/it]

VAE train ep12:  67%|██████▋   | 111/165 [14:11<06:48,  7.57s/it]

VAE train ep12:  68%|██████▊   | 112/165 [14:19<06:39,  7.54s/it]

VAE train ep12:  68%|██████▊   | 113/165 [14:26<06:32,  7.56s/it]

VAE train ep12:  69%|██████▉   | 114/165 [14:34<06:26,  7.57s/it]

VAE train ep12:  70%|██████▉   | 115/165 [14:42<06:19,  7.59s/it]

VAE train ep12:  70%|███████   | 116/165 [14:49<06:11,  7.58s/it]

VAE train ep12:  71%|███████   | 117/165 [14:57<06:04,  7.59s/it]

VAE train ep12:  72%|███████▏  | 118/165 [15:04<05:54,  7.55s/it]

VAE train ep12:  72%|███████▏  | 119/165 [15:12<05:46,  7.53s/it]

VAE train ep12:  73%|███████▎  | 120/165 [15:19<05:38,  7.53s/it]

VAE train ep12:  73%|███████▎  | 121/165 [15:27<05:32,  7.57s/it]

VAE train ep12:  74%|███████▍  | 122/165 [15:34<05:24,  7.54s/it]

VAE train ep12:  75%|███████▍  | 123/165 [15:42<05:17,  7.55s/it]

VAE train ep12:  75%|███████▌  | 124/165 [15:49<05:07,  7.51s/it]

VAE train ep12:  76%|███████▌  | 125/165 [15:57<05:00,  7.51s/it]

VAE train ep12:  76%|███████▋  | 126/165 [16:04<04:52,  7.51s/it]

VAE train ep12:  77%|███████▋  | 127/165 [16:12<04:45,  7.52s/it]

VAE train ep12:  78%|███████▊  | 128/165 [16:20<04:39,  7.55s/it]

VAE train ep12:  78%|███████▊  | 129/165 [16:27<04:31,  7.53s/it]

VAE train ep12:  79%|███████▉  | 130/165 [16:35<04:22,  7.49s/it]

VAE train ep12:  79%|███████▉  | 131/165 [16:42<04:17,  7.58s/it]

VAE train ep12:  80%|████████  | 132/165 [16:50<04:11,  7.63s/it]

VAE train ep12:  81%|████████  | 133/165 [16:58<04:03,  7.61s/it]

VAE train ep12:  81%|████████  | 134/165 [17:05<03:55,  7.59s/it]

VAE train ep12:  82%|████████▏ | 135/165 [17:13<03:47,  7.59s/it]

VAE train ep12:  82%|████████▏ | 136/165 [17:20<03:40,  7.61s/it]

VAE train ep12:  83%|████████▎ | 137/165 [17:28<03:33,  7.61s/it]

VAE train ep12:  84%|████████▎ | 138/165 [17:35<03:23,  7.54s/it]

VAE train ep12:  84%|████████▍ | 139/165 [17:43<03:16,  7.55s/it]

VAE train ep12:  85%|████████▍ | 140/165 [17:51<03:09,  7.59s/it]

VAE train ep12:  85%|████████▌ | 141/165 [17:58<03:01,  7.57s/it]

VAE train ep12:  86%|████████▌ | 142/165 [18:06<02:54,  7.60s/it]

VAE train ep12:  87%|████████▋ | 143/165 [18:13<02:47,  7.59s/it]

VAE train ep12:  87%|████████▋ | 144/165 [18:21<02:40,  7.64s/it]

VAE train ep12:  88%|████████▊ | 145/165 [18:29<02:33,  7.65s/it]

VAE train ep12:  88%|████████▊ | 146/165 [18:36<02:24,  7.62s/it]

VAE train ep12:  89%|████████▉ | 147/165 [18:44<02:17,  7.61s/it]

VAE train ep12:  90%|████████▉ | 148/165 [18:52<02:09,  7.60s/it]

VAE train ep12:  90%|█████████ | 149/165 [18:59<02:01,  7.59s/it]

VAE train ep12:  91%|█████████ | 150/165 [19:07<01:53,  7.58s/it]

VAE train ep12:  92%|█████████▏| 151/165 [19:14<01:46,  7.58s/it]

VAE train ep12:  92%|█████████▏| 152/165 [19:22<01:38,  7.59s/it]

VAE train ep12:  93%|█████████▎| 153/165 [19:30<01:32,  7.67s/it]

VAE train ep12:  93%|█████████▎| 154/165 [19:38<01:24,  7.70s/it]

VAE train ep12:  94%|█████████▍| 155/165 [19:45<01:16,  7.69s/it]

VAE train ep12:  95%|█████████▍| 156/165 [19:53<01:09,  7.71s/it]

VAE train ep12:  95%|█████████▌| 157/165 [20:01<01:01,  7.73s/it]

VAE train ep12:  96%|█████████▌| 158/165 [20:08<00:54,  7.73s/it]

VAE train ep12:  96%|█████████▋| 159/165 [20:16<00:46,  7.74s/it]

VAE train ep12:  97%|█████████▋| 160/165 [20:24<00:38,  7.79s/it]

VAE train ep12:  98%|█████████▊| 161/165 [20:32<00:31,  7.82s/it]

VAE train ep12:  98%|█████████▊| 162/165 [20:40<00:23,  7.84s/it]

VAE train ep12:  99%|█████████▉| 163/165 [20:48<00:15,  7.80s/it]

VAE train ep12:  99%|█████████▉| 164/165 [20:55<00:07,  7.72s/it]

VAE train ep12: 100%|██████████| 165/165 [20:56<00:00,  5.54s/it]

VAE val ep12:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep12:   3%|▎         | 1/29 [00:02<00:58,  2.09s/it]

VAE val ep12:   7%|▋         | 2/29 [00:04<00:55,  2.05s/it]

VAE val ep12:  10%|█         | 3/29 [00:06<00:52,  2.03s/it]

VAE val ep12:  14%|█▍        | 4/29 [00:08<00:50,  2.02s/it]

VAE val ep12:  17%|█▋        | 5/29 [00:10<00:48,  2.01s/it]

VAE val ep12:  21%|██        | 6/29 [00:12<00:46,  2.03s/it]

VAE val ep12:  24%|██▍       | 7/29 [00:14<00:44,  2.03s/it]

VAE val ep12:  28%|██▊       | 8/29 [00:16<00:42,  2.03s/it]

VAE val ep12:  31%|███       | 9/29 [00:18<00:40,  2.03s/it]

VAE val ep12:  34%|███▍      | 10/29 [00:20<00:38,  2.02s/it]

VAE val ep12:  38%|███▊      | 11/29 [00:22<00:36,  2.04s/it]

VAE val ep12:  41%|████▏     | 12/29 [00:24<00:34,  2.06s/it]

VAE val ep12:  45%|████▍     | 13/29 [00:26<00:32,  2.05s/it]

VAE val ep12:  48%|████▊     | 14/29 [00:28<00:30,  2.05s/it]

VAE val ep12:  52%|█████▏    | 15/29 [00:30<00:28,  2.04s/it]

VAE val ep12:  55%|█████▌    | 16/29 [00:32<00:26,  2.04s/it]

VAE val ep12:  59%|█████▊    | 17/29 [00:34<00:24,  2.03s/it]

VAE val ep12:  62%|██████▏   | 18/29 [00:36<00:22,  2.03s/it]

VAE val ep12:  66%|██████▌   | 19/29 [00:38<00:20,  2.03s/it]

VAE val ep12:  69%|██████▉   | 20/29 [00:40<00:18,  2.03s/it]

VAE val ep12:  72%|███████▏  | 21/29 [00:42<00:16,  2.03s/it]

VAE val ep12:  76%|███████▌  | 22/29 [00:44<00:14,  2.02s/it]

VAE val ep12:  79%|███████▉  | 23/29 [00:46<00:12,  2.02s/it]

VAE val ep12:  83%|████████▎ | 24/29 [00:48<00:10,  2.02s/it]

VAE val ep12:  86%|████████▌ | 25/29 [00:50<00:08,  2.03s/it]

VAE val ep12:  90%|████████▉ | 26/29 [00:52<00:06,  2.02s/it]

VAE val ep12:  93%|█████████▎| 27/29 [00:54<00:04,  2.02s/it]

VAE val ep12:  97%|█████████▋| 28/29 [00:56<00:02,  2.02s/it]

VAE val ep12: 100%|██████████| 29/29 [00:57<00:00,  1.50s/it]

VAE train ep13:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep13:   1%|          | 1/165 [00:08<22:11,  8.12s/it]

VAE train ep13:   1%|          | 2/165 [00:16<21:40,  7.98s/it]

VAE train ep13:   2%|▏         | 3/165 [00:23<21:16,  7.88s/it]

VAE train ep13:   2%|▏         | 4/165 [00:31<20:51,  7.77s/it]

VAE train ep13:   3%|▎         | 5/165 [00:39<20:36,  7.73s/it]

VAE train ep13:   4%|▎         | 6/165 [00:46<20:31,  7.75s/it]

VAE train ep13:   4%|▍         | 7/165 [00:54<20:21,  7.73s/it]

VAE train ep13:   5%|▍         | 8/165 [01:02<20:15,  7.74s/it]

VAE train ep13:   5%|▌         | 9/165 [01:09<20:05,  7.73s/it]

VAE train ep13:   6%|▌         | 10/165 [01:17<19:54,  7.71s/it]

VAE train ep13:   7%|▋         | 11/165 [01:25<19:43,  7.68s/it]

VAE train ep13:   7%|▋         | 12/165 [01:32<19:37,  7.70s/it]

VAE train ep13:   8%|▊         | 13/165 [01:40<19:23,  7.66s/it]

VAE train ep13:   8%|▊         | 14/165 [01:48<19:09,  7.61s/it]

VAE train ep13:   9%|▉         | 15/165 [01:55<18:56,  7.57s/it]

VAE train ep13:  10%|▉         | 16/165 [02:03<18:59,  7.65s/it]

VAE train ep13:  10%|█         | 17/165 [02:10<18:51,  7.64s/it]

VAE train ep13:  11%|█         | 18/165 [02:18<18:40,  7.62s/it]

VAE train ep13:  12%|█▏        | 19/165 [02:26<18:29,  7.60s/it]

VAE train ep13:  12%|█▏        | 20/165 [02:33<18:21,  7.59s/it]

VAE train ep13:  13%|█▎        | 21/165 [02:41<18:15,  7.61s/it]

VAE train ep13:  13%|█▎        | 22/165 [02:49<18:18,  7.68s/it]

VAE train ep13:  14%|█▍        | 23/165 [02:56<18:13,  7.70s/it]

VAE train ep13:  15%|█▍        | 24/165 [03:04<18:02,  7.68s/it]

VAE train ep13:  15%|█▌        | 25/165 [03:12<17:56,  7.69s/it]

VAE train ep13:  16%|█▌        | 26/165 [03:19<17:42,  7.64s/it]

VAE train ep13:  16%|█▋        | 27/165 [03:27<17:32,  7.63s/it]

VAE train ep13:  17%|█▋        | 28/165 [03:34<17:21,  7.60s/it]

VAE train ep13:  18%|█▊        | 29/165 [03:42<17:06,  7.55s/it]

VAE train ep13:  18%|█▊        | 30/165 [03:49<16:57,  7.53s/it]

VAE train ep13:  19%|█▉        | 31/165 [03:57<16:55,  7.58s/it]

VAE train ep13:  19%|█▉        | 32/165 [04:05<16:46,  7.57s/it]

VAE train ep13:  20%|██        | 33/165 [04:12<16:40,  7.58s/it]

VAE train ep13:  21%|██        | 34/165 [04:20<16:32,  7.57s/it]

VAE train ep13:  21%|██        | 35/165 [04:27<16:21,  7.55s/it]

VAE train ep13:  22%|██▏       | 36/165 [04:35<16:10,  7.52s/it]

VAE train ep13:  22%|██▏       | 37/165 [04:42<16:00,  7.50s/it]

VAE train ep13:  23%|██▎       | 38/165 [04:50<15:48,  7.47s/it]

VAE train ep13:  24%|██▎       | 39/165 [04:57<15:39,  7.46s/it]

VAE train ep13:  24%|██▍       | 40/165 [05:04<15:27,  7.42s/it]

VAE train ep13:  25%|██▍       | 41/165 [05:12<15:21,  7.43s/it]

VAE train ep13:  25%|██▌       | 42/165 [05:19<15:24,  7.51s/it]

VAE train ep13:  26%|██▌       | 43/165 [05:27<15:19,  7.54s/it]

VAE train ep13:  27%|██▋       | 44/165 [05:35<15:15,  7.56s/it]

VAE train ep13:  27%|██▋       | 45/165 [05:42<15:09,  7.58s/it]

VAE train ep13:  28%|██▊       | 46/165 [05:50<15:01,  7.58s/it]

VAE train ep13:  28%|██▊       | 47/165 [05:57<14:55,  7.59s/it]

VAE train ep13:  29%|██▉       | 48/165 [06:05<14:42,  7.55s/it]

VAE train ep13:  30%|██▉       | 49/165 [06:12<14:31,  7.51s/it]

VAE train ep13:  30%|███       | 50/165 [06:20<14:29,  7.56s/it]

VAE train ep13:  31%|███       | 51/165 [06:28<14:21,  7.56s/it]

VAE train ep13:  32%|███▏      | 52/165 [06:35<14:14,  7.56s/it]

VAE train ep13:  32%|███▏      | 53/165 [06:43<14:08,  7.58s/it]

VAE train ep13:  33%|███▎      | 54/165 [06:50<14:03,  7.60s/it]

VAE train ep13:  33%|███▎      | 55/165 [06:58<14:00,  7.64s/it]

VAE train ep13:  34%|███▍      | 56/165 [07:06<13:52,  7.63s/it]

VAE train ep13:  35%|███▍      | 57/165 [07:13<13:43,  7.62s/it]

VAE train ep13:  35%|███▌      | 58/165 [07:21<13:31,  7.59s/it]

VAE train ep13:  36%|███▌      | 59/165 [07:29<13:27,  7.62s/it]

VAE train ep13:  36%|███▋      | 60/165 [07:36<13:19,  7.61s/it]

VAE train ep13:  37%|███▋      | 61/165 [07:44<13:09,  7.59s/it]

VAE train ep13:  38%|███▊      | 62/165 [07:52<13:15,  7.73s/it]

VAE train ep13:  38%|███▊      | 63/165 [08:00<13:13,  7.78s/it]

VAE train ep13:  39%|███▉      | 64/165 [08:07<13:00,  7.72s/it]

VAE train ep13:  39%|███▉      | 65/165 [08:15<12:52,  7.73s/it]

VAE train ep13:  40%|████      | 66/165 [08:23<12:48,  7.77s/it]

VAE train ep13:  41%|████      | 67/165 [08:30<12:36,  7.72s/it]

VAE train ep13:  41%|████      | 68/165 [08:38<12:30,  7.73s/it]

VAE train ep13:  42%|████▏     | 69/165 [08:46<12:20,  7.72s/it]

VAE train ep13:  42%|████▏     | 70/165 [08:54<12:09,  7.68s/it]

VAE train ep13:  43%|████▎     | 71/165 [09:01<12:01,  7.67s/it]

VAE train ep13:  44%|████▎     | 72/165 [09:09<12:00,  7.75s/it]

VAE train ep13:  44%|████▍     | 73/165 [09:17<11:59,  7.82s/it]

VAE train ep13:  45%|████▍     | 74/165 [09:25<11:54,  7.85s/it]

VAE train ep13:  45%|████▌     | 75/165 [09:33<11:50,  7.89s/it]

VAE train ep13:  46%|████▌     | 76/165 [09:41<11:38,  7.85s/it]

VAE train ep13:  47%|████▋     | 77/165 [09:49<11:29,  7.84s/it]

VAE train ep13:  47%|████▋     | 78/165 [09:56<11:23,  7.86s/it]

VAE train ep13:  48%|████▊     | 79/165 [10:04<11:09,  7.79s/it]

VAE train ep13:  48%|████▊     | 80/165 [10:12<10:58,  7.75s/it]

VAE train ep13:  49%|████▉     | 81/165 [10:19<10:48,  7.72s/it]

VAE train ep13:  50%|████▉     | 82/165 [10:27<10:36,  7.67s/it]

VAE train ep13:  50%|█████     | 83/165 [10:35<10:29,  7.67s/it]

VAE train ep13:  51%|█████     | 84/165 [10:42<10:19,  7.64s/it]

VAE train ep13:  52%|█████▏    | 85/165 [10:50<10:15,  7.69s/it]

VAE train ep13:  52%|█████▏    | 86/165 [10:58<10:04,  7.65s/it]

VAE train ep13:  53%|█████▎    | 87/165 [11:05<09:55,  7.64s/it]

VAE train ep13:  53%|█████▎    | 88/165 [11:13<09:45,  7.60s/it]

VAE train ep13:  54%|█████▍    | 89/165 [11:20<09:36,  7.58s/it]

VAE train ep13:  55%|█████▍    | 90/165 [11:28<09:27,  7.57s/it]

VAE train ep13:  55%|█████▌    | 91/165 [11:35<09:23,  7.61s/it]

VAE train ep13:  56%|█████▌    | 92/165 [11:43<09:11,  7.55s/it]

VAE train ep13:  56%|█████▋    | 93/165 [11:50<09:04,  7.56s/it]

VAE train ep13:  57%|█████▋    | 94/165 [11:58<08:56,  7.56s/it]

VAE train ep13:  58%|█████▊    | 95/165 [12:06<08:49,  7.57s/it]

VAE train ep13:  58%|█████▊    | 96/165 [12:13<08:44,  7.59s/it]

VAE train ep13:  59%|█████▉    | 97/165 [12:21<08:35,  7.58s/it]

VAE train ep13:  59%|█████▉    | 98/165 [12:28<08:26,  7.56s/it]

VAE train ep13:  60%|██████    | 99/165 [12:36<08:20,  7.59s/it]

VAE train ep13:  61%|██████    | 100/165 [12:43<08:10,  7.55s/it]

VAE train ep13:  61%|██████    | 101/165 [12:51<08:00,  7.51s/it]

VAE train ep13:  62%|██████▏   | 102/165 [12:58<07:55,  7.54s/it]

VAE train ep13:  62%|██████▏   | 103/165 [13:06<07:51,  7.60s/it]

VAE train ep13:  63%|██████▎   | 104/165 [13:14<07:42,  7.57s/it]

VAE train ep13:  64%|██████▎   | 105/165 [13:21<07:34,  7.58s/it]

VAE train ep13:  64%|██████▍   | 106/165 [13:29<07:24,  7.53s/it]

VAE train ep13:  65%|██████▍   | 107/165 [13:36<07:17,  7.54s/it]

VAE train ep13:  65%|██████▌   | 108/165 [13:44<07:10,  7.56s/it]

VAE train ep13:  66%|██████▌   | 109/165 [13:51<07:03,  7.55s/it]

VAE train ep13:  67%|██████▋   | 110/165 [13:59<06:52,  7.51s/it]

VAE train ep13:  67%|██████▋   | 111/165 [14:06<06:43,  7.48s/it]

VAE train ep13:  68%|██████▊   | 112/165 [14:14<06:37,  7.50s/it]

VAE train ep13:  68%|██████▊   | 113/165 [14:21<06:29,  7.49s/it]

VAE train ep13:  69%|██████▉   | 114/165 [14:29<06:24,  7.54s/it]

VAE train ep13:  70%|██████▉   | 115/165 [14:36<06:16,  7.53s/it]

VAE train ep13:  70%|███████   | 116/165 [14:44<06:10,  7.57s/it]

VAE train ep13:  71%|███████   | 117/165 [14:52<06:02,  7.54s/it]

VAE train ep13:  72%|███████▏  | 118/165 [14:59<05:54,  7.53s/it]

VAE train ep13:  72%|███████▏  | 119/165 [15:07<05:47,  7.54s/it]

VAE train ep13:  73%|███████▎  | 120/165 [15:14<05:38,  7.51s/it]

VAE train ep13:  73%|███████▎  | 121/165 [15:22<05:30,  7.50s/it]

VAE train ep13:  74%|███████▍  | 122/165 [15:29<05:23,  7.52s/it]

VAE train ep13:  75%|███████▍  | 123/165 [15:37<05:16,  7.52s/it]

VAE train ep13:  75%|███████▌  | 124/165 [15:44<05:09,  7.56s/it]

VAE train ep13:  76%|███████▌  | 125/165 [15:52<05:04,  7.61s/it]

VAE train ep13:  76%|███████▋  | 126/165 [16:00<04:58,  7.65s/it]

VAE train ep13:  77%|███████▋  | 127/165 [16:08<04:57,  7.83s/it]

VAE train ep13:  78%|███████▊  | 128/165 [16:16<04:53,  7.93s/it]

VAE train ep13:  78%|███████▊  | 129/165 [16:24<04:49,  8.03s/it]

VAE train ep13:  79%|███████▉  | 130/165 [16:32<04:41,  8.04s/it]

VAE train ep13:  79%|███████▉  | 131/165 [16:40<04:31,  8.00s/it]

VAE train ep13:  80%|████████  | 132/165 [16:48<04:23,  7.98s/it]

VAE train ep13:  81%|████████  | 133/165 [16:57<04:18,  8.06s/it]

VAE train ep13:  81%|████████  | 134/165 [17:05<04:10,  8.09s/it]

VAE train ep13:  82%|████████▏ | 135/165 [17:13<04:06,  8.21s/it]

VAE train ep13:  82%|████████▏ | 136/165 [17:22<04:00,  8.30s/it]

VAE train ep13:  83%|████████▎ | 137/165 [17:30<03:53,  8.35s/it]

VAE train ep13:  84%|████████▎ | 138/165 [17:39<03:46,  8.40s/it]

VAE train ep13:  84%|████████▍ | 139/165 [17:47<03:41,  8.51s/it]

VAE train ep13:  85%|████████▍ | 140/165 [17:56<03:34,  8.57s/it]

VAE train ep13:  85%|████████▌ | 141/165 [18:05<03:27,  8.63s/it]

VAE train ep13:  86%|████████▌ | 142/165 [18:13<03:16,  8.56s/it]

VAE train ep13:  87%|████████▋ | 143/165 [18:21<03:05,  8.43s/it]

VAE train ep13:  87%|████████▋ | 144/165 [18:30<02:55,  8.34s/it]

VAE train ep13:  88%|████████▊ | 145/165 [18:38<02:46,  8.33s/it]

VAE train ep13:  88%|████████▊ | 146/165 [18:46<02:37,  8.29s/it]

VAE train ep13:  89%|████████▉ | 147/165 [18:54<02:29,  8.30s/it]

VAE train ep13:  90%|████████▉ | 148/165 [19:02<02:19,  8.19s/it]

VAE train ep13:  90%|█████████ | 149/165 [19:10<02:09,  8.12s/it]

VAE train ep13:  91%|█████████ | 150/165 [19:18<02:00,  8.00s/it]

VAE train ep13:  92%|█████████▏| 151/165 [19:26<01:51,  7.96s/it]

VAE train ep13:  92%|█████████▏| 152/165 [19:34<01:43,  7.94s/it]

VAE train ep13:  93%|█████████▎| 153/165 [19:42<01:35,  7.94s/it]

VAE train ep13:  93%|█████████▎| 154/165 [19:50<01:27,  7.93s/it]

VAE train ep13:  94%|█████████▍| 155/165 [19:57<01:18,  7.89s/it]

VAE train ep13:  95%|█████████▍| 156/165 [20:05<01:11,  7.93s/it]

VAE train ep13:  95%|█████████▌| 157/165 [20:14<01:03,  8.00s/it]

VAE train ep13:  96%|█████████▌| 158/165 [20:22<00:56,  8.01s/it]

VAE train ep13:  96%|█████████▋| 159/165 [20:30<00:47,  7.99s/it]

VAE train ep13:  97%|█████████▋| 160/165 [20:37<00:39,  7.94s/it]

VAE train ep13:  98%|█████████▊| 161/165 [20:45<00:31,  7.88s/it]

VAE train ep13:  98%|█████████▊| 162/165 [20:53<00:23,  7.84s/it]

VAE train ep13:  99%|█████████▉| 163/165 [21:01<00:15,  7.83s/it]

VAE train ep13:  99%|█████████▉| 164/165 [21:09<00:07,  7.85s/it]

VAE train ep13: 100%|██████████| 165/165 [21:09<00:00,  5.65s/it]

VAE val ep13:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep13:   3%|▎         | 1/29 [00:02<01:00,  2.16s/it]

VAE val ep13:   7%|▋         | 2/29 [00:04<00:58,  2.16s/it]

VAE val ep13:  10%|█         | 3/29 [00:06<00:55,  2.14s/it]

VAE val ep13:  14%|█▍        | 4/29 [00:08<00:53,  2.14s/it]

VAE val ep13:  17%|█▋        | 5/29 [00:10<00:51,  2.13s/it]

VAE val ep13:  21%|██        | 6/29 [00:12<00:49,  2.14s/it]

VAE val ep13:  24%|██▍       | 7/29 [00:14<00:46,  2.13s/it]

VAE val ep13:  28%|██▊       | 8/29 [00:17<00:44,  2.13s/it]

VAE val ep13:  31%|███       | 9/29 [00:19<00:42,  2.12s/it]

VAE val ep13:  34%|███▍      | 10/29 [00:21<00:39,  2.10s/it]

VAE val ep13:  38%|███▊      | 11/29 [00:23<00:37,  2.10s/it]

VAE val ep13:  41%|████▏     | 12/29 [00:25<00:36,  2.12s/it]

VAE val ep13:  45%|████▍     | 13/29 [00:27<00:33,  2.12s/it]

VAE val ep13:  48%|████▊     | 14/29 [00:29<00:31,  2.12s/it]

VAE val ep13:  52%|█████▏    | 15/29 [00:31<00:29,  2.12s/it]

VAE val ep13:  55%|█████▌    | 16/29 [00:33<00:27,  2.12s/it]

VAE val ep13:  59%|█████▊    | 17/29 [00:36<00:25,  2.12s/it]

VAE val ep13:  62%|██████▏   | 18/29 [00:38<00:23,  2.11s/it]

VAE val ep13:  66%|██████▌   | 19/29 [00:40<00:20,  2.10s/it]

VAE val ep13:  69%|██████▉   | 20/29 [00:42<00:18,  2.10s/it]

VAE val ep13:  72%|███████▏  | 21/29 [00:44<00:16,  2.12s/it]

VAE val ep13:  76%|███████▌  | 22/29 [00:46<00:14,  2.11s/it]

VAE val ep13:  79%|███████▉  | 23/29 [00:48<00:12,  2.11s/it]

VAE val ep13:  83%|████████▎ | 24/29 [00:50<00:10,  2.09s/it]

VAE val ep13:  86%|████████▌ | 25/29 [00:52<00:08,  2.08s/it]

VAE val ep13:  90%|████████▉ | 26/29 [00:54<00:06,  2.09s/it]

VAE val ep13:  93%|█████████▎| 27/29 [00:56<00:04,  2.08s/it]

VAE val ep13:  97%|█████████▋| 28/29 [00:59<00:02,  2.07s/it]

VAE val ep13: 100%|██████████| 29/29 [00:59<00:00,  1.53s/it]

VAE train ep14:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep14:   1%|          | 1/165 [00:08<22:31,  8.24s/it]

VAE train ep14:   1%|          | 2/165 [00:16<22:02,  8.11s/it]

VAE train ep14:   2%|▏         | 3/165 [00:24<21:32,  7.98s/it]

VAE train ep14:   2%|▏         | 4/165 [00:31<21:20,  7.95s/it]

VAE train ep14:   3%|▎         | 5/165 [00:39<21:00,  7.88s/it]

VAE train ep14:   4%|▎         | 6/165 [00:47<20:46,  7.84s/it]

VAE train ep14:   4%|▍         | 7/165 [00:55<20:31,  7.79s/it]

VAE train ep14:   5%|▍         | 8/165 [01:02<20:18,  7.76s/it]

VAE train ep14:   5%|▌         | 9/165 [01:10<20:05,  7.73s/it]

VAE train ep14:   6%|▌         | 10/165 [01:18<20:01,  7.75s/it]

VAE train ep14:   7%|▋         | 11/165 [01:26<20:00,  7.80s/it]

VAE train ep14:   7%|▋         | 12/165 [01:34<19:55,  7.82s/it]

VAE train ep14:   8%|▊         | 13/165 [01:41<19:42,  7.78s/it]

VAE train ep14:   8%|▊         | 14/165 [01:49<19:23,  7.70s/it]

VAE train ep14:   9%|▉         | 15/165 [01:56<19:07,  7.65s/it]

VAE train ep14:  10%|▉         | 16/165 [02:04<19:02,  7.67s/it]

VAE train ep14:  10%|█         | 17/165 [02:12<18:49,  7.63s/it]

VAE train ep14:  11%|█         | 18/165 [02:19<18:42,  7.63s/it]

VAE train ep14:  12%|█▏        | 19/165 [02:27<18:33,  7.63s/it]

VAE train ep14:  12%|█▏        | 20/165 [02:35<18:30,  7.66s/it]

VAE train ep14:  13%|█▎        | 21/165 [02:42<18:30,  7.71s/it]

VAE train ep14:  13%|█▎        | 22/165 [02:50<18:23,  7.72s/it]

VAE train ep14:  14%|█▍        | 23/165 [02:58<18:09,  7.67s/it]

VAE train ep14:  15%|█▍        | 24/165 [03:06<18:07,  7.71s/it]

VAE train ep14:  15%|█▌        | 25/165 [03:13<17:59,  7.71s/it]

VAE train ep14:  16%|█▌        | 26/165 [03:21<18:02,  7.79s/it]

VAE train ep14:  16%|█▋        | 27/165 [03:29<17:55,  7.79s/it]

VAE train ep14:  17%|█▋        | 28/165 [03:37<17:50,  7.81s/it]

VAE train ep14:  18%|█▊        | 29/165 [03:45<17:42,  7.81s/it]

VAE train ep14:  18%|█▊        | 30/165 [03:53<17:37,  7.83s/it]

VAE train ep14:  19%|█▉        | 31/165 [04:00<17:28,  7.82s/it]

VAE train ep14:  19%|█▉        | 32/165 [04:08<17:13,  7.77s/it]

VAE train ep14:  20%|██        | 33/165 [04:16<17:02,  7.75s/it]

VAE train ep14:  21%|██        | 34/165 [04:24<16:59,  7.78s/it]

VAE train ep14:  21%|██        | 35/165 [04:31<16:51,  7.78s/it]

VAE train ep14:  22%|██▏       | 36/165 [04:40<16:57,  7.89s/it]

VAE train ep14:  22%|██▏       | 37/165 [04:48<16:57,  7.95s/it]

VAE train ep14:  23%|██▎       | 38/165 [04:55<16:43,  7.90s/it]

VAE train ep14:  24%|██▎       | 39/165 [05:03<16:24,  7.81s/it]

VAE train ep14:  24%|██▍       | 40/165 [05:11<16:06,  7.73s/it]

VAE train ep14:  25%|██▍       | 41/165 [05:18<16:02,  7.76s/it]

VAE train ep14:  25%|██▌       | 42/165 [05:26<15:54,  7.76s/it]

VAE train ep14:  26%|██▌       | 43/165 [05:34<15:41,  7.71s/it]

VAE train ep14:  27%|██▋       | 44/165 [05:41<15:28,  7.68s/it]

VAE train ep14:  27%|██▋       | 45/165 [05:49<15:19,  7.66s/it]

VAE train ep14:  28%|██▊       | 46/165 [05:57<15:11,  7.66s/it]

VAE train ep14:  28%|██▊       | 47/165 [06:04<15:05,  7.67s/it]

VAE train ep14:  29%|██▉       | 48/165 [06:12<14:54,  7.65s/it]

VAE train ep14:  30%|██▉       | 49/165 [06:20<14:48,  7.66s/it]

VAE train ep14:  30%|███       | 50/165 [06:28<14:51,  7.75s/it]

VAE train ep14:  31%|███       | 51/165 [06:35<14:48,  7.79s/it]

VAE train ep14:  32%|███▏      | 52/165 [06:43<14:44,  7.82s/it]

VAE train ep14:  32%|███▏      | 53/165 [06:51<14:36,  7.83s/it]

VAE train ep14:  33%|███▎      | 54/165 [06:59<14:26,  7.81s/it]

VAE train ep14:  33%|███▎      | 55/165 [07:07<14:19,  7.82s/it]

VAE train ep14:  34%|███▍      | 56/165 [07:15<14:16,  7.86s/it]

VAE train ep14:  35%|███▍      | 57/165 [07:22<14:04,  7.82s/it]

VAE train ep14:  35%|███▌      | 58/165 [07:30<13:55,  7.81s/it]

VAE train ep14:  36%|███▌      | 59/165 [07:38<13:42,  7.76s/it]

VAE train ep14:  36%|███▋      | 60/165 [07:46<13:31,  7.73s/it]

VAE train ep14:  37%|███▋      | 61/165 [07:53<13:24,  7.74s/it]

VAE train ep14:  38%|███▊      | 62/165 [08:01<13:17,  7.74s/it]

VAE train ep14:  38%|███▊      | 63/165 [08:09<13:11,  7.76s/it]

VAE train ep14:  39%|███▉      | 64/165 [08:17<13:04,  7.77s/it]

VAE train ep14:  39%|███▉      | 65/165 [08:24<12:56,  7.77s/it]

VAE train ep14:  40%|████      | 66/165 [08:32<12:46,  7.75s/it]

VAE train ep14:  41%|████      | 67/165 [08:40<12:38,  7.74s/it]

VAE train ep14:  41%|████      | 68/165 [08:48<12:35,  7.79s/it]

VAE train ep14:  42%|████▏     | 69/165 [08:55<12:22,  7.73s/it]

VAE train ep14:  42%|████▏     | 70/165 [09:03<12:04,  7.63s/it]

VAE train ep14:  43%|████▎     | 71/165 [09:10<12:01,  7.67s/it]

VAE train ep14:  44%|████▎     | 72/165 [09:18<11:54,  7.68s/it]

VAE train ep14:  44%|████▍     | 73/165 [09:26<11:47,  7.69s/it]

VAE train ep14:  45%|████▍     | 74/165 [09:34<11:39,  7.69s/it]

VAE train ep14:  45%|████▌     | 75/165 [09:41<11:30,  7.67s/it]

VAE train ep14:  46%|████▌     | 76/165 [09:49<11:24,  7.69s/it]

VAE train ep14:  47%|████▋     | 77/165 [09:57<11:15,  7.68s/it]

VAE train ep14:  47%|████▋     | 78/165 [10:04<11:08,  7.68s/it]

VAE train ep14:  48%|████▊     | 79/165 [10:12<11:04,  7.73s/it]

VAE train ep14:  48%|████▊     | 80/165 [10:20<10:57,  7.73s/it]

VAE train ep14:  49%|████▉     | 81/165 [10:28<10:49,  7.73s/it]

VAE train ep14:  50%|████▉     | 82/165 [10:35<10:39,  7.70s/it]

VAE train ep14:  50%|█████     | 83/165 [10:43<10:32,  7.71s/it]

VAE train ep14:  51%|█████     | 84/165 [10:51<10:27,  7.75s/it]

VAE train ep14:  52%|█████▏    | 85/165 [10:59<10:21,  7.77s/it]

VAE train ep14:  52%|█████▏    | 86/165 [11:06<10:11,  7.74s/it]

VAE train ep14:  53%|█████▎    | 87/165 [11:14<10:04,  7.75s/it]

VAE train ep14:  53%|█████▎    | 88/165 [11:22<09:54,  7.72s/it]

VAE train ep14:  54%|█████▍    | 89/165 [11:29<09:46,  7.72s/it]

VAE train ep14:  55%|█████▍    | 90/165 [11:37<09:40,  7.74s/it]

VAE train ep14:  55%|█████▌    | 91/165 [11:45<09:32,  7.74s/it]

VAE train ep14:  56%|█████▌    | 92/165 [11:53<09:26,  7.77s/it]

VAE train ep14:  56%|█████▋    | 93/165 [12:00<09:17,  7.74s/it]

VAE train ep14:  57%|█████▋    | 94/165 [12:08<09:07,  7.71s/it]

VAE train ep14:  58%|█████▊    | 95/165 [12:16<08:56,  7.67s/it]

VAE train ep14:  58%|█████▊    | 96/165 [12:23<08:48,  7.66s/it]

VAE train ep14:  59%|█████▉    | 97/165 [12:31<08:43,  7.69s/it]

VAE train ep14:  59%|█████▉    | 98/165 [12:39<08:36,  7.71s/it]

VAE train ep14:  60%|██████    | 99/165 [12:46<08:27,  7.69s/it]

VAE train ep14:  61%|██████    | 100/165 [12:54<08:19,  7.69s/it]

VAE train ep14:  61%|██████    | 101/165 [13:02<08:12,  7.70s/it]

VAE train ep14:  62%|██████▏   | 102/165 [13:10<08:05,  7.71s/it]

VAE train ep14:  62%|██████▏   | 103/165 [13:18<08:02,  7.78s/it]

VAE train ep14:  63%|██████▎   | 104/165 [13:25<07:53,  7.77s/it]

VAE train ep14:  64%|██████▎   | 105/165 [13:33<07:48,  7.80s/it]

VAE train ep14:  64%|██████▍   | 106/165 [13:41<07:43,  7.86s/it]

VAE train ep14:  65%|██████▍   | 107/165 [13:49<07:34,  7.84s/it]

VAE train ep14:  65%|██████▌   | 108/165 [13:57<07:33,  7.95s/it]

VAE train ep14:  66%|██████▌   | 109/165 [14:05<07:26,  7.97s/it]

VAE train ep14:  67%|██████▋   | 110/165 [14:13<07:18,  7.98s/it]

VAE train ep14:  67%|██████▋   | 111/165 [14:21<07:09,  7.95s/it]

VAE train ep14:  68%|██████▊   | 112/165 [14:29<07:03,  8.00s/it]

VAE train ep14:  68%|██████▊   | 113/165 [14:37<07:00,  8.08s/it]

VAE train ep14:  69%|██████▉   | 114/165 [14:46<06:58,  8.21s/it]

VAE train ep14:  70%|██████▉   | 115/165 [14:54<06:53,  8.26s/it]

VAE train ep14:  70%|███████   | 116/165 [15:03<06:45,  8.28s/it]

VAE train ep14:  71%|███████   | 117/165 [15:11<06:33,  8.19s/it]

VAE train ep14:  72%|███████▏  | 118/165 [15:19<06:21,  8.12s/it]

VAE train ep14:  72%|███████▏  | 119/165 [15:27<06:16,  8.18s/it]

VAE train ep14:  73%|███████▎  | 120/165 [15:35<06:08,  8.20s/it]

VAE train ep14:  73%|███████▎  | 121/165 [15:43<06:00,  8.19s/it]

VAE train ep14:  74%|███████▍  | 122/165 [15:51<05:50,  8.16s/it]

VAE train ep14:  75%|███████▍  | 123/165 [16:00<05:41,  8.13s/it]

VAE train ep14:  75%|███████▌  | 124/165 [16:08<05:32,  8.10s/it]

VAE train ep14:  76%|███████▌  | 125/165 [16:16<05:22,  8.06s/it]

VAE train ep14:  76%|███████▋  | 126/165 [16:23<05:12,  8.01s/it]

VAE train ep14:  77%|███████▋  | 127/165 [16:31<05:01,  7.94s/it]

VAE train ep14:  78%|███████▊  | 128/165 [16:39<04:53,  7.92s/it]

VAE train ep14:  78%|███████▊  | 129/165 [16:47<04:45,  7.93s/it]

VAE train ep14:  79%|███████▉  | 130/165 [16:55<04:38,  7.94s/it]

VAE train ep14:  79%|███████▉  | 131/165 [17:03<04:29,  7.93s/it]

VAE train ep14:  80%|████████  | 132/165 [17:11<04:21,  7.92s/it]

VAE train ep14:  81%|████████  | 133/165 [17:18<04:11,  7.85s/it]

VAE train ep14:  81%|████████  | 134/165 [17:26<04:03,  7.86s/it]

VAE train ep14:  82%|████████▏ | 135/165 [17:34<03:57,  7.93s/it]

VAE train ep14:  82%|████████▏ | 136/165 [17:42<03:48,  7.86s/it]

VAE train ep14:  83%|████████▎ | 137/165 [17:50<03:40,  7.87s/it]

VAE train ep14:  84%|████████▎ | 138/165 [17:58<03:31,  7.85s/it]

VAE train ep14:  84%|████████▍ | 139/165 [18:06<03:23,  7.82s/it]

VAE train ep14:  85%|████████▍ | 140/165 [18:13<03:16,  7.84s/it]

VAE train ep14:  85%|████████▌ | 141/165 [18:21<03:06,  7.78s/it]

VAE train ep14:  86%|████████▌ | 142/165 [18:29<02:58,  7.77s/it]

VAE train ep14:  87%|████████▋ | 143/165 [18:37<02:51,  7.79s/it]

VAE train ep14:  87%|████████▋ | 144/165 [18:45<02:45,  7.86s/it]

VAE train ep14:  88%|████████▊ | 145/165 [18:53<02:37,  7.85s/it]

VAE train ep14:  88%|████████▊ | 146/165 [19:00<02:28,  7.82s/it]

VAE train ep14:  89%|████████▉ | 147/165 [19:08<02:19,  7.76s/it]

VAE train ep14:  90%|████████▉ | 148/165 [19:16<02:11,  7.76s/it]

VAE train ep14:  90%|█████████ | 149/165 [19:23<02:03,  7.72s/it]

VAE train ep14:  91%|█████████ | 150/165 [19:31<01:56,  7.75s/it]

VAE train ep14:  92%|█████████▏| 151/165 [19:39<01:48,  7.75s/it]

VAE train ep14:  92%|█████████▏| 152/165 [19:47<01:41,  7.78s/it]

VAE train ep14:  93%|█████████▎| 153/165 [19:54<01:33,  7.75s/it]

VAE train ep14:  93%|█████████▎| 154/165 [20:02<01:25,  7.76s/it]

VAE train ep14:  94%|█████████▍| 155/165 [20:10<01:18,  7.84s/it]

VAE train ep14:  95%|█████████▍| 156/165 [20:18<01:11,  7.92s/it]

VAE train ep14:  95%|█████████▌| 157/165 [20:26<01:03,  7.91s/it]

VAE train ep14:  96%|█████████▌| 158/165 [20:34<00:55,  7.91s/it]

VAE train ep14:  96%|█████████▋| 159/165 [20:42<00:47,  7.97s/it]

VAE train ep14:  97%|█████████▋| 160/165 [20:50<00:40,  8.05s/it]

VAE train ep14:  98%|█████████▊| 161/165 [20:59<00:32,  8.07s/it]

VAE train ep14:  98%|█████████▊| 162/165 [21:06<00:23,  7.97s/it]

VAE train ep14:  99%|█████████▉| 163/165 [21:14<00:15,  7.95s/it]

VAE train ep14:  99%|█████████▉| 164/165 [21:22<00:07,  7.99s/it]

VAE train ep14: 100%|██████████| 165/165 [21:23<00:00,  5.75s/it]

VAE val ep14:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep14:   3%|▎         | 1/29 [00:02<00:59,  2.13s/it]

VAE val ep14:   7%|▋         | 2/29 [00:04<00:56,  2.11s/it]

VAE val ep14:  10%|█         | 3/29 [00:06<00:55,  2.15s/it]

VAE val ep14:  14%|█▍        | 4/29 [00:08<00:54,  2.17s/it]

VAE val ep14:  17%|█▋        | 5/29 [00:10<00:52,  2.19s/it]

VAE val ep14:  21%|██        | 6/29 [00:13<00:50,  2.19s/it]

VAE val ep14:  24%|██▍       | 7/29 [00:15<00:48,  2.21s/it]

VAE val ep14:  28%|██▊       | 8/29 [00:17<00:46,  2.22s/it]

VAE val ep14:  31%|███       | 9/29 [00:19<00:44,  2.22s/it]

VAE val ep14:  34%|███▍      | 10/29 [00:22<00:42,  2.23s/it]

VAE val ep14:  38%|███▊      | 11/29 [00:24<00:39,  2.22s/it]

VAE val ep14:  41%|████▏     | 12/29 [00:26<00:37,  2.22s/it]

VAE val ep14:  45%|████▍     | 13/29 [00:28<00:35,  2.22s/it]

VAE val ep14:  48%|████▊     | 14/29 [00:30<00:32,  2.20s/it]

VAE val ep14:  52%|█████▏    | 15/29 [00:33<00:30,  2.21s/it]

VAE val ep14:  55%|█████▌    | 16/29 [00:35<00:28,  2.18s/it]

VAE val ep14:  59%|█████▊    | 17/29 [00:37<00:25,  2.16s/it]

VAE val ep14:  62%|██████▏   | 18/29 [00:39<00:23,  2.13s/it]

VAE val ep14:  66%|██████▌   | 19/29 [00:41<00:21,  2.11s/it]

VAE val ep14:  69%|██████▉   | 20/29 [00:43<00:18,  2.11s/it]

VAE val ep14:  72%|███████▏  | 21/29 [00:45<00:16,  2.10s/it]

VAE val ep14:  76%|███████▌  | 22/29 [00:47<00:14,  2.08s/it]

VAE val ep14:  79%|███████▉  | 23/29 [00:49<00:12,  2.08s/it]

VAE val ep14:  83%|████████▎ | 24/29 [00:51<00:10,  2.08s/it]

VAE val ep14:  86%|████████▌ | 25/29 [00:53<00:08,  2.09s/it]

VAE val ep14:  90%|████████▉ | 26/29 [00:56<00:06,  2.11s/it]

VAE val ep14:  93%|█████████▎| 27/29 [00:58<00:04,  2.11s/it]

VAE val ep14:  97%|█████████▋| 28/29 [01:00<00:02,  2.10s/it]

VAE val ep14: 100%|██████████| 29/29 [01:00<00:00,  1.55s/it]

VAE train ep15:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep15:   1%|          | 1/165 [00:08<22:43,  8.32s/it]

VAE train ep15:   1%|          | 2/165 [00:16<22:04,  8.13s/it]

VAE train ep15:   2%|▏         | 3/165 [00:24<21:42,  8.04s/it]

VAE train ep15:   2%|▏         | 4/165 [00:32<21:21,  7.96s/it]

VAE train ep15:   3%|▎         | 5/165 [00:40<21:29,  8.06s/it]

VAE train ep15:   4%|▎         | 6/165 [00:48<21:16,  8.03s/it]

VAE train ep15:   4%|▍         | 7/165 [00:56<20:56,  7.95s/it]

VAE train ep15:   5%|▍         | 8/165 [01:03<20:43,  7.92s/it]

VAE train ep15:   5%|▌         | 9/165 [01:11<20:40,  7.95s/it]

VAE train ep15:   6%|▌         | 10/165 [01:19<20:21,  7.88s/it]

VAE train ep15:   7%|▋         | 11/165 [01:27<20:05,  7.83s/it]

VAE train ep15:   7%|▋         | 12/165 [01:35<20:01,  7.85s/it]

VAE train ep15:   8%|▊         | 13/165 [01:42<19:46,  7.81s/it]

VAE train ep15:   8%|▊         | 14/165 [01:50<19:36,  7.79s/it]

VAE train ep15:   9%|▉         | 15/165 [01:58<19:21,  7.74s/it]

VAE train ep15:  10%|▉         | 16/165 [02:06<19:10,  7.72s/it]

VAE train ep15:  10%|█         | 17/165 [02:13<19:01,  7.71s/it]

VAE train ep15:  11%|█         | 18/165 [02:21<18:53,  7.71s/it]

VAE train ep15:  12%|█▏        | 19/165 [02:29<18:47,  7.72s/it]

VAE train ep15:  12%|█▏        | 20/165 [02:37<18:44,  7.76s/it]

VAE train ep15:  13%|█▎        | 21/165 [02:44<18:29,  7.70s/it]

VAE train ep15:  13%|█▎        | 22/165 [02:52<18:17,  7.67s/it]

VAE train ep15:  14%|█▍        | 23/165 [02:59<18:03,  7.63s/it]

VAE train ep15:  15%|█▍        | 24/165 [03:07<18:01,  7.67s/it]

VAE train ep15:  15%|█▌        | 25/165 [03:15<17:54,  7.67s/it]

VAE train ep15:  16%|█▌        | 26/165 [03:22<17:41,  7.64s/it]

VAE train ep15:  16%|█▋        | 27/165 [03:30<17:31,  7.62s/it]

VAE train ep15:  17%|█▋        | 28/165 [03:38<17:29,  7.66s/it]

VAE train ep15:  18%|█▊        | 29/165 [03:45<17:31,  7.73s/it]

VAE train ep15:  18%|█▊        | 30/165 [03:53<17:26,  7.75s/it]

VAE train ep15:  19%|█▉        | 31/165 [04:01<17:13,  7.71s/it]

VAE train ep15:  19%|█▉        | 32/165 [04:09<17:05,  7.71s/it]

VAE train ep15:  20%|██        | 33/165 [04:16<16:55,  7.69s/it]

VAE train ep15:  21%|██        | 34/165 [04:24<16:46,  7.68s/it]

VAE train ep15:  21%|██        | 35/165 [04:32<16:38,  7.68s/it]

VAE train ep15:  22%|██▏       | 36/165 [04:39<16:24,  7.63s/it]

VAE train ep15:  22%|██▏       | 37/165 [04:47<16:13,  7.60s/it]

VAE train ep15:  23%|██▎       | 38/165 [04:54<15:59,  7.55s/it]

VAE train ep15:  24%|██▎       | 39/165 [05:02<16:02,  7.64s/it]

VAE train ep15:  24%|██▍       | 40/165 [05:10<16:01,  7.69s/it]

VAE train ep15:  25%|██▍       | 41/165 [05:17<15:53,  7.69s/it]

VAE train ep15:  25%|██▌       | 42/165 [05:25<15:39,  7.64s/it]

VAE train ep15:  26%|██▌       | 43/165 [05:33<15:32,  7.64s/it]

VAE train ep15:  27%|██▋       | 44/165 [05:40<15:26,  7.66s/it]

VAE train ep15:  27%|██▋       | 45/165 [05:48<15:15,  7.63s/it]

VAE train ep15:  28%|██▊       | 46/165 [05:55<15:07,  7.63s/it]

VAE train ep15:  28%|██▊       | 47/165 [06:03<14:59,  7.63s/it]

VAE train ep15:  29%|██▉       | 48/165 [06:11<14:57,  7.67s/it]

VAE train ep15:  30%|██▉       | 49/165 [06:19<14:51,  7.69s/it]

VAE train ep15:  30%|███       | 50/165 [06:26<14:44,  7.69s/it]

VAE train ep15:  31%|███       | 51/165 [06:34<14:38,  7.71s/it]

VAE train ep15:  32%|███▏      | 52/165 [06:42<14:26,  7.67s/it]

VAE train ep15:  32%|███▏      | 53/165 [06:49<14:24,  7.71s/it]

VAE train ep15:  33%|███▎      | 54/165 [06:57<14:11,  7.67s/it]

VAE train ep15:  33%|███▎      | 55/165 [07:05<14:01,  7.65s/it]

VAE train ep15:  34%|███▍      | 56/165 [07:12<13:52,  7.64s/it]

VAE train ep15:  35%|███▍      | 57/165 [07:20<13:43,  7.62s/it]

VAE train ep15:  35%|███▌      | 58/165 [07:28<13:39,  7.65s/it]

VAE train ep15:  36%|███▌      | 59/165 [07:35<13:32,  7.67s/it]

VAE train ep15:  36%|███▋      | 60/165 [07:43<13:25,  7.67s/it]

VAE train ep15:  37%|███▋      | 61/165 [07:51<13:16,  7.66s/it]

VAE train ep15:  38%|███▊      | 62/165 [07:58<13:07,  7.64s/it]

VAE train ep15:  38%|███▊      | 63/165 [08:06<12:58,  7.63s/it]

VAE train ep15:  39%|███▉      | 64/165 [08:14<12:56,  7.69s/it]

VAE train ep15:  39%|███▉      | 65/165 [08:21<12:48,  7.68s/it]

VAE train ep15:  40%|████      | 66/165 [08:29<12:38,  7.66s/it]

VAE train ep15:  41%|████      | 67/165 [08:36<12:29,  7.64s/it]

VAE train ep15:  41%|████      | 68/165 [08:44<12:19,  7.63s/it]

VAE train ep15:  42%|████▏     | 69/165 [08:52<12:17,  7.68s/it]

VAE train ep15:  42%|████▏     | 70/165 [09:00<12:09,  7.68s/it]

VAE train ep15:  43%|████▎     | 71/165 [09:07<12:00,  7.66s/it]

VAE train ep15:  44%|████▎     | 72/165 [09:15<11:52,  7.66s/it]

VAE train ep15:  44%|████▍     | 73/165 [09:22<11:43,  7.65s/it]

VAE train ep15:  45%|████▍     | 74/165 [09:30<11:36,  7.65s/it]

VAE train ep15:  45%|████▌     | 75/165 [09:38<11:26,  7.63s/it]

VAE train ep15:  46%|████▌     | 76/165 [09:45<11:19,  7.63s/it]

VAE train ep15:  47%|████▋     | 77/165 [09:53<11:11,  7.63s/it]

VAE train ep15:  47%|████▋     | 78/165 [10:01<11:05,  7.65s/it]

VAE train ep15:  48%|████▊     | 79/165 [10:08<10:57,  7.64s/it]

VAE train ep15:  48%|████▊     | 80/165 [10:16<10:49,  7.64s/it]

VAE train ep15:  49%|████▉     | 81/165 [10:23<10:39,  7.62s/it]

VAE train ep15:  50%|████▉     | 82/165 [10:31<10:33,  7.63s/it]

VAE train ep15:  50%|█████     | 83/165 [10:39<10:24,  7.61s/it]

VAE train ep15:  51%|█████     | 84/165 [10:46<10:16,  7.62s/it]

VAE train ep15:  52%|█████▏    | 85/165 [10:54<10:07,  7.59s/it]

VAE train ep15:  52%|█████▏    | 86/165 [11:02<10:02,  7.62s/it]

VAE train ep15:  53%|█████▎    | 87/165 [11:09<09:54,  7.63s/it]

VAE train ep15:  53%|█████▎    | 88/165 [11:17<09:46,  7.62s/it]

VAE train ep15:  54%|█████▍    | 89/165 [11:24<09:37,  7.60s/it]

VAE train ep15:  55%|█████▍    | 90/165 [11:32<09:32,  7.64s/it]

VAE train ep15:  55%|█████▌    | 91/165 [11:40<09:27,  7.67s/it]

VAE train ep15:  56%|█████▌    | 92/165 [11:47<09:16,  7.62s/it]

VAE train ep15:  56%|█████▋    | 93/165 [11:55<09:11,  7.66s/it]

VAE train ep15:  57%|█████▋    | 94/165 [12:03<09:01,  7.62s/it]

VAE train ep15:  58%|█████▊    | 95/165 [12:10<08:53,  7.63s/it]

VAE train ep15:  58%|█████▊    | 96/165 [12:18<08:47,  7.64s/it]

VAE train ep15:  59%|█████▉    | 97/165 [12:26<08:40,  7.65s/it]

VAE train ep15:  59%|█████▉    | 98/165 [12:33<08:31,  7.63s/it]

VAE train ep15:  60%|██████    | 99/165 [12:41<08:25,  7.66s/it]

VAE train ep15:  61%|██████    | 100/165 [12:49<08:21,  7.71s/it]

VAE train ep15:  61%|██████    | 101/165 [12:56<08:14,  7.72s/it]

VAE train ep15:  62%|██████▏   | 102/165 [13:04<08:05,  7.71s/it]

VAE train ep15:  62%|██████▏   | 103/165 [13:12<07:58,  7.72s/it]

VAE train ep15:  63%|██████▎   | 104/165 [13:20<07:53,  7.76s/it]

VAE train ep15:  64%|██████▎   | 105/165 [13:27<07:45,  7.76s/it]

VAE train ep15:  64%|██████▍   | 106/165 [13:35<07:36,  7.74s/it]

VAE train ep15:  65%|██████▍   | 107/165 [13:43<07:27,  7.72s/it]

VAE train ep15:  65%|██████▌   | 108/165 [13:51<07:27,  7.84s/it]

VAE train ep15:  66%|██████▌   | 109/165 [13:59<07:22,  7.90s/it]

VAE train ep15:  67%|██████▋   | 110/165 [14:07<07:17,  7.96s/it]

VAE train ep15:  67%|██████▋   | 111/165 [14:16<07:18,  8.12s/it]

VAE train ep15:  68%|██████▊   | 112/165 [14:24<07:12,  8.16s/it]

VAE train ep15:  68%|██████▊   | 113/165 [14:32<07:03,  8.14s/it]

VAE train ep15:  69%|██████▉   | 114/165 [14:40<06:53,  8.11s/it]

VAE train ep15:  70%|██████▉   | 115/165 [14:48<06:43,  8.08s/it]

VAE train ep15:  70%|███████   | 116/165 [14:56<06:34,  8.04s/it]

VAE train ep15:  71%|███████   | 117/165 [15:04<06:21,  7.96s/it]

VAE train ep15:  72%|███████▏  | 118/165 [15:12<06:13,  7.95s/it]

VAE train ep15:  72%|███████▏  | 119/165 [15:20<06:05,  7.95s/it]

VAE train ep15:  73%|███████▎  | 120/165 [15:28<05:58,  7.96s/it]

VAE train ep15:  73%|███████▎  | 121/165 [15:35<05:48,  7.91s/it]

VAE train ep15:  74%|███████▍  | 122/165 [15:43<05:35,  7.81s/it]

VAE train ep15:  75%|███████▍  | 123/165 [15:51<05:27,  7.80s/it]

VAE train ep15:  75%|███████▌  | 124/165 [15:59<05:19,  7.80s/it]

VAE train ep15:  76%|███████▌  | 125/165 [16:06<05:13,  7.85s/it]

VAE train ep15:  76%|███████▋  | 126/165 [16:14<05:06,  7.86s/it]

VAE train ep15:  77%|███████▋  | 127/165 [16:22<04:57,  7.83s/it]

VAE train ep15:  78%|███████▊  | 128/165 [16:30<04:47,  7.77s/it]

VAE train ep15:  78%|███████▊  | 129/165 [16:38<04:40,  7.79s/it]

VAE train ep15:  79%|███████▉  | 130/165 [16:45<04:33,  7.81s/it]

VAE train ep15:  79%|███████▉  | 131/165 [16:53<04:25,  7.80s/it]

VAE train ep15:  80%|████████  | 132/165 [17:01<04:20,  7.89s/it]

VAE train ep15:  81%|████████  | 133/165 [17:09<04:09,  7.80s/it]

VAE train ep15:  81%|████████  | 134/165 [17:17<04:03,  7.86s/it]

VAE train ep15:  82%|████████▏ | 135/165 [17:25<03:56,  7.88s/it]

VAE train ep15:  82%|████████▏ | 136/165 [17:33<03:49,  7.91s/it]

VAE train ep15:  83%|████████▎ | 137/165 [17:41<03:41,  7.92s/it]

VAE train ep15:  84%|████████▎ | 138/165 [17:49<03:32,  7.87s/it]

VAE train ep15:  84%|████████▍ | 139/165 [17:56<03:25,  7.90s/it]

VAE train ep15:  85%|████████▍ | 140/165 [18:04<03:17,  7.89s/it]

VAE train ep15:  85%|████████▌ | 141/165 [18:12<03:08,  7.86s/it]

VAE train ep15:  86%|████████▌ | 142/165 [18:20<03:00,  7.85s/it]

VAE train ep15:  87%|████████▋ | 143/165 [18:28<02:51,  7.81s/it]

VAE train ep15:  87%|████████▋ | 144/165 [18:36<02:44,  7.85s/it]

VAE train ep15:  88%|████████▊ | 145/165 [18:43<02:36,  7.83s/it]

VAE train ep15:  88%|████████▊ | 146/165 [18:51<02:28,  7.82s/it]

VAE train ep15:  89%|████████▉ | 147/165 [18:59<02:19,  7.75s/it]

VAE train ep15:  90%|████████▉ | 148/165 [19:07<02:12,  7.79s/it]

VAE train ep15:  90%|█████████ | 149/165 [19:15<02:05,  7.85s/it]

VAE train ep15:  91%|█████████ | 150/165 [19:23<01:57,  7.87s/it]

VAE train ep15:  92%|█████████▏| 151/165 [19:30<01:50,  7.86s/it]

VAE train ep15:  92%|█████████▏| 152/165 [19:38<01:42,  7.88s/it]

VAE train ep15:  93%|█████████▎| 153/165 [19:46<01:34,  7.88s/it]

VAE train ep15:  93%|█████████▎| 154/165 [19:54<01:26,  7.90s/it]

VAE train ep15:  94%|█████████▍| 155/165 [20:02<01:19,  7.90s/it]

VAE train ep15:  95%|█████████▍| 156/165 [20:10<01:11,  7.89s/it]

VAE train ep15:  95%|█████████▌| 157/165 [20:18<01:02,  7.87s/it]

VAE train ep15:  96%|█████████▌| 158/165 [20:25<00:54,  7.83s/it]

VAE train ep15:  96%|█████████▋| 159/165 [20:33<00:46,  7.83s/it]

VAE train ep15:  97%|█████████▋| 160/165 [20:41<00:39,  7.81s/it]

VAE train ep15:  98%|█████████▊| 161/165 [20:49<00:31,  7.78s/it]

VAE train ep15:  98%|█████████▊| 162/165 [20:57<00:23,  7.87s/it]

VAE train ep15:  99%|█████████▉| 163/165 [21:05<00:15,  7.92s/it]

VAE train ep15:  99%|█████████▉| 164/165 [21:13<00:07,  7.91s/it]

VAE train ep15: 100%|██████████| 165/165 [21:13<00:00,  5.68s/it]

VAE val ep15:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep15:   3%|▎         | 1/29 [00:02<00:59,  2.12s/it]

VAE val ep15:   7%|▋         | 2/29 [00:04<00:56,  2.09s/it]

VAE val ep15:  10%|█         | 3/29 [00:06<00:54,  2.10s/it]

VAE val ep15:  14%|█▍        | 4/29 [00:08<00:52,  2.10s/it]

VAE val ep15:  17%|█▋        | 5/29 [00:10<00:49,  2.08s/it]

VAE val ep15:  21%|██        | 6/29 [00:12<00:47,  2.07s/it]

VAE val ep15:  24%|██▍       | 7/29 [00:14<00:45,  2.07s/it]

VAE val ep15:  28%|██▊       | 8/29 [00:16<00:43,  2.07s/it]

VAE val ep15:  31%|███       | 9/29 [00:18<00:41,  2.07s/it]

VAE val ep15:  34%|███▍      | 10/29 [00:20<00:39,  2.08s/it]

VAE val ep15:  38%|███▊      | 11/29 [00:22<00:37,  2.08s/it]

VAE val ep15:  41%|████▏     | 12/29 [00:24<00:35,  2.09s/it]

VAE val ep15:  45%|████▍     | 13/29 [00:27<00:33,  2.09s/it]

VAE val ep15:  48%|████▊     | 14/29 [00:29<00:31,  2.07s/it]

VAE val ep15:  52%|█████▏    | 15/29 [00:31<00:28,  2.07s/it]

VAE val ep15:  55%|█████▌    | 16/29 [00:33<00:26,  2.07s/it]

VAE val ep15:  59%|█████▊    | 17/29 [00:35<00:25,  2.09s/it]

VAE val ep15:  62%|██████▏   | 18/29 [00:37<00:23,  2.10s/it]

VAE val ep15:  66%|██████▌   | 19/29 [00:39<00:21,  2.11s/it]

VAE val ep15:  69%|██████▉   | 20/29 [00:41<00:18,  2.09s/it]

VAE val ep15:  72%|███████▏  | 21/29 [00:43<00:16,  2.08s/it]

VAE val ep15:  76%|███████▌  | 22/29 [00:45<00:14,  2.08s/it]

VAE val ep15:  79%|███████▉  | 23/29 [00:47<00:12,  2.09s/it]

VAE val ep15:  83%|████████▎ | 24/29 [00:50<00:10,  2.09s/it]

VAE val ep15:  86%|████████▌ | 25/29 [00:52<00:08,  2.09s/it]

VAE val ep15:  90%|████████▉ | 26/29 [00:54<00:06,  2.10s/it]

VAE val ep15:  93%|█████████▎| 27/29 [00:56<00:04,  2.11s/it]

VAE val ep15:  97%|█████████▋| 28/29 [00:58<00:02,  2.10s/it]

VAE val ep15: 100%|██████████| 29/29 [00:58<00:00,  1.55s/it]

VAE train ep16:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep16:   1%|          | 1/165 [00:08<22:21,  8.18s/it]

VAE train ep16:   1%|          | 2/165 [00:16<22:11,  8.17s/it]

VAE train ep16:   2%|▏         | 3/165 [00:24<21:36,  8.00s/it]

VAE train ep16:   2%|▏         | 4/165 [00:31<21:13,  7.91s/it]

VAE train ep16:   3%|▎         | 5/165 [00:39<20:55,  7.85s/it]

VAE train ep16:   4%|▎         | 6/165 [00:47<20:39,  7.80s/it]

VAE train ep16:   4%|▍         | 7/165 [00:55<20:33,  7.81s/it]

VAE train ep16:   5%|▍         | 8/165 [01:02<20:18,  7.76s/it]

VAE train ep16:   5%|▌         | 9/165 [01:10<20:10,  7.76s/it]

VAE train ep16:   6%|▌         | 10/165 [01:18<19:55,  7.71s/it]

VAE train ep16:   7%|▋         | 11/165 [01:25<19:44,  7.69s/it]

VAE train ep16:   7%|▋         | 12/165 [01:33<19:33,  7.67s/it]

VAE train ep16:   8%|▊         | 13/165 [01:41<19:27,  7.68s/it]

VAE train ep16:   8%|▊         | 14/165 [01:48<19:19,  7.68s/it]

VAE train ep16:   9%|▉         | 15/165 [01:56<19:15,  7.70s/it]

VAE train ep16:  10%|▉         | 16/165 [02:04<19:11,  7.73s/it]

VAE train ep16:  10%|█         | 17/165 [02:12<19:06,  7.75s/it]

VAE train ep16:  11%|█         | 18/165 [02:19<18:59,  7.75s/it]

VAE train ep16:  12%|█▏        | 19/165 [02:27<18:45,  7.71s/it]

VAE train ep16:  12%|█▏        | 20/165 [02:35<18:41,  7.73s/it]

VAE train ep16:  13%|█▎        | 21/165 [02:43<18:35,  7.75s/it]

VAE train ep16:  13%|█▎        | 22/165 [02:50<18:27,  7.74s/it]

VAE train ep16:  14%|█▍        | 23/165 [02:58<18:27,  7.80s/it]

VAE train ep16:  15%|█▍        | 24/165 [03:06<18:14,  7.76s/it]

VAE train ep16:  15%|█▌        | 25/165 [03:14<18:03,  7.74s/it]

VAE train ep16:  16%|█▌        | 26/165 [03:21<17:57,  7.75s/it]

VAE train ep16:  16%|█▋        | 27/165 [03:29<17:38,  7.67s/it]

VAE train ep16:  17%|█▋        | 28/165 [03:37<17:29,  7.66s/it]

VAE train ep16:  18%|█▊        | 29/165 [03:44<17:19,  7.64s/it]

VAE train ep16:  18%|█▊        | 30/165 [03:52<17:11,  7.64s/it]

VAE train ep16:  19%|█▉        | 31/165 [03:59<17:05,  7.65s/it]

VAE train ep16:  19%|█▉        | 32/165 [04:07<16:59,  7.67s/it]

VAE train ep16:  20%|██        | 33/165 [04:15<16:59,  7.72s/it]

VAE train ep16:  21%|██        | 34/165 [04:23<16:55,  7.75s/it]

VAE train ep16:  21%|██        | 35/165 [04:31<16:51,  7.78s/it]

VAE train ep16:  22%|██▏       | 36/165 [04:38<16:44,  7.79s/it]

VAE train ep16:  22%|██▏       | 37/165 [04:46<16:32,  7.75s/it]

VAE train ep16:  23%|██▎       | 38/165 [04:54<16:28,  7.78s/it]

VAE train ep16:  24%|██▎       | 39/165 [05:02<16:24,  7.81s/it]

VAE train ep16:  24%|██▍       | 40/165 [05:10<16:21,  7.85s/it]

VAE train ep16:  25%|██▍       | 41/165 [05:18<16:10,  7.82s/it]

VAE train ep16:  25%|██▌       | 42/165 [05:25<15:59,  7.80s/it]

VAE train ep16:  26%|██▌       | 43/165 [05:33<15:54,  7.83s/it]

VAE train ep16:  27%|██▋       | 44/165 [05:41<15:43,  7.80s/it]

VAE train ep16:  27%|██▋       | 45/165 [05:49<15:47,  7.90s/it]

VAE train ep16:  28%|██▊       | 46/165 [05:57<15:37,  7.88s/it]

VAE train ep16:  28%|██▊       | 47/165 [06:05<15:27,  7.86s/it]

VAE train ep16:  29%|██▉       | 48/165 [06:12<15:14,  7.82s/it]

VAE train ep16:  30%|██▉       | 49/165 [06:20<15:07,  7.82s/it]

VAE train ep16:  30%|███       | 50/165 [06:28<14:55,  7.79s/it]

VAE train ep16:  31%|███       | 51/165 [06:36<14:49,  7.80s/it]

VAE train ep16:  32%|███▏      | 52/165 [06:44<14:39,  7.78s/it]

VAE train ep16:  32%|███▏      | 53/165 [06:51<14:33,  7.80s/it]

VAE train ep16:  33%|███▎      | 54/165 [06:59<14:22,  7.77s/it]

VAE train ep16:  33%|███▎      | 55/165 [07:07<14:14,  7.77s/it]

VAE train ep16:  34%|███▍      | 56/165 [07:15<14:08,  7.79s/it]

VAE train ep16:  35%|███▍      | 57/165 [07:22<13:59,  7.77s/it]

VAE train ep16:  35%|███▌      | 58/165 [07:30<13:52,  7.78s/it]

VAE train ep16:  36%|███▌      | 59/165 [07:38<13:52,  7.85s/it]

VAE train ep16:  36%|███▋      | 60/165 [07:46<13:50,  7.91s/it]

VAE train ep16:  37%|███▋      | 61/165 [07:55<13:55,  8.04s/it]

VAE train ep16:  38%|███▊      | 62/165 [08:03<13:55,  8.11s/it]

VAE train ep16:  38%|███▊      | 63/165 [08:11<13:43,  8.07s/it]

VAE train ep16:  39%|███▉      | 64/165 [08:19<13:35,  8.07s/it]

VAE train ep16:  39%|███▉      | 65/165 [08:27<13:25,  8.05s/it]

VAE train ep16:  40%|████      | 66/165 [08:35<13:24,  8.13s/it]

VAE train ep16:  41%|████      | 67/165 [08:44<13:31,  8.28s/it]

VAE train ep16:  41%|████      | 68/165 [08:53<13:37,  8.43s/it]

VAE train ep16:  42%|████▏     | 69/165 [09:01<13:35,  8.50s/it]

VAE train ep16:  42%|████▏     | 70/165 [09:10<13:24,  8.47s/it]

VAE train ep16:  43%|████▎     | 71/165 [09:18<13:04,  8.35s/it]

VAE train ep16:  44%|████▎     | 72/165 [09:26<12:41,  8.19s/it]

VAE train ep16:  44%|████▍     | 73/165 [09:34<12:30,  8.16s/it]

VAE train ep16:  45%|████▍     | 74/165 [09:42<12:18,  8.11s/it]

VAE train ep16:  45%|████▌     | 75/165 [09:50<12:11,  8.13s/it]

VAE train ep16:  46%|████▌     | 76/165 [09:58<12:03,  8.13s/it]

VAE train ep16:  47%|████▋     | 77/165 [10:06<11:51,  8.09s/it]

VAE train ep16:  47%|████▋     | 78/165 [10:14<11:47,  8.13s/it]

VAE train ep16:  48%|████▊     | 79/165 [10:22<11:36,  8.10s/it]

VAE train ep16:  48%|████▊     | 80/165 [10:30<11:22,  8.03s/it]

VAE train ep16:  49%|████▉     | 81/165 [10:38<11:14,  8.03s/it]

VAE train ep16:  50%|████▉     | 82/165 [10:46<11:06,  8.03s/it]

VAE train ep16:  50%|█████     | 83/165 [10:54<11:00,  8.05s/it]

VAE train ep16:  51%|█████     | 84/165 [11:02<10:54,  8.09s/it]

VAE train ep16:  52%|█████▏    | 85/165 [11:11<10:50,  8.13s/it]

VAE train ep16:  52%|█████▏    | 86/165 [11:19<10:42,  8.13s/it]

VAE train ep16:  53%|█████▎    | 87/165 [11:27<10:31,  8.10s/it]

VAE train ep16:  53%|█████▎    | 88/165 [11:35<10:24,  8.11s/it]

VAE train ep16:  54%|█████▍    | 89/165 [11:43<10:16,  8.11s/it]

VAE train ep16:  55%|█████▍    | 90/165 [11:51<10:10,  8.14s/it]

VAE train ep16:  55%|█████▌    | 91/165 [12:00<10:04,  8.17s/it]

VAE train ep16:  56%|█████▌    | 92/165 [12:08<09:54,  8.15s/it]

VAE train ep16:  56%|█████▋    | 93/165 [12:16<09:42,  8.09s/it]

VAE train ep16:  57%|█████▋    | 94/165 [12:23<09:25,  7.97s/it]

VAE train ep16:  58%|█████▊    | 95/165 [12:31<09:13,  7.91s/it]

VAE train ep16:  58%|█████▊    | 96/165 [12:39<09:04,  7.89s/it]

VAE train ep16:  59%|█████▉    | 97/165 [12:47<09:00,  7.94s/it]

VAE train ep16:  59%|█████▉    | 98/165 [12:55<08:55,  7.99s/it]

VAE train ep16:  60%|██████    | 99/165 [13:03<08:42,  7.92s/it]

VAE train ep16:  61%|██████    | 100/165 [13:11<08:30,  7.85s/it]

VAE train ep16:  61%|██████    | 101/165 [13:18<08:23,  7.86s/it]

VAE train ep16:  62%|██████▏   | 102/165 [13:26<08:14,  7.85s/it]

VAE train ep16:  62%|██████▏   | 103/165 [13:34<08:01,  7.77s/it]

VAE train ep16:  63%|██████▎   | 104/165 [13:42<07:54,  7.77s/it]

VAE train ep16:  64%|██████▎   | 105/165 [13:49<07:45,  7.76s/it]

VAE train ep16:  64%|██████▍   | 106/165 [13:57<07:34,  7.71s/it]

VAE train ep16:  65%|██████▍   | 107/165 [14:05<07:31,  7.78s/it]

VAE train ep16:  65%|██████▌   | 108/165 [14:13<07:23,  7.78s/it]

VAE train ep16:  66%|██████▌   | 109/165 [14:20<07:13,  7.75s/it]

VAE train ep16:  67%|██████▋   | 110/165 [14:28<07:05,  7.73s/it]

VAE train ep16:  67%|██████▋   | 111/165 [14:36<06:58,  7.75s/it]

VAE train ep16:  68%|██████▊   | 112/165 [14:43<06:48,  7.71s/it]

VAE train ep16:  68%|██████▊   | 113/165 [14:51<06:40,  7.71s/it]

VAE train ep16:  69%|██████▉   | 114/165 [14:59<06:31,  7.67s/it]

VAE train ep16:  70%|██████▉   | 115/165 [15:06<06:22,  7.66s/it]

VAE train ep16:  70%|███████   | 116/165 [15:14<06:14,  7.65s/it]

VAE train ep16:  71%|███████   | 117/165 [15:22<06:05,  7.62s/it]

VAE train ep16:  72%|███████▏  | 118/165 [15:29<05:56,  7.59s/it]

VAE train ep16:  72%|███████▏  | 119/165 [15:37<05:48,  7.58s/it]

VAE train ep16:  73%|███████▎  | 120/165 [15:44<05:44,  7.65s/it]

VAE train ep16:  73%|███████▎  | 121/165 [15:52<05:37,  7.68s/it]

VAE train ep16:  74%|███████▍  | 122/165 [16:00<05:30,  7.68s/it]

VAE train ep16:  75%|███████▍  | 123/165 [16:08<05:22,  7.69s/it]

VAE train ep16:  75%|███████▌  | 124/165 [16:15<05:13,  7.65s/it]

VAE train ep16:  76%|███████▌  | 125/165 [16:23<05:08,  7.72s/it]

VAE train ep16:  76%|███████▋  | 126/165 [16:31<05:00,  7.70s/it]

VAE train ep16:  77%|███████▋  | 127/165 [16:38<04:50,  7.66s/it]

VAE train ep16:  78%|███████▊  | 128/165 [16:46<04:43,  7.66s/it]

VAE train ep16:  78%|███████▊  | 129/165 [16:53<04:35,  7.64s/it]

VAE train ep16:  79%|███████▉  | 130/165 [17:01<04:29,  7.69s/it]

VAE train ep16:  79%|███████▉  | 131/165 [17:09<04:20,  7.67s/it]

VAE train ep16:  80%|████████  | 132/165 [17:16<04:10,  7.61s/it]

VAE train ep16:  81%|████████  | 133/165 [17:24<04:04,  7.63s/it]

VAE train ep16:  81%|████████  | 134/165 [17:32<03:56,  7.63s/it]

VAE train ep16:  82%|████████▏ | 135/165 [17:39<03:50,  7.67s/it]

VAE train ep16:  82%|████████▏ | 136/165 [17:47<03:42,  7.66s/it]

VAE train ep16:  83%|████████▎ | 137/165 [17:55<03:34,  7.67s/it]

VAE train ep16:  84%|████████▎ | 138/165 [18:03<03:27,  7.69s/it]

VAE train ep16:  84%|████████▍ | 139/165 [18:10<03:20,  7.71s/it]

VAE train ep16:  85%|████████▍ | 140/165 [18:18<03:11,  7.67s/it]

VAE train ep16:  85%|████████▌ | 141/165 [18:26<03:04,  7.69s/it]

VAE train ep16:  86%|████████▌ | 142/165 [18:33<02:56,  7.66s/it]

VAE train ep16:  87%|████████▋ | 143/165 [18:41<02:49,  7.70s/it]

VAE train ep16:  87%|████████▋ | 144/165 [18:49<02:42,  7.76s/it]

VAE train ep16:  88%|████████▊ | 145/165 [18:57<02:34,  7.73s/it]

VAE train ep16:  88%|████████▊ | 146/165 [19:04<02:26,  7.69s/it]

VAE train ep16:  89%|████████▉ | 147/165 [19:12<02:18,  7.68s/it]

VAE train ep16:  90%|████████▉ | 148/165 [19:19<02:10,  7.67s/it]

VAE train ep16:  90%|█████████ | 149/165 [19:27<02:02,  7.68s/it]

VAE train ep16:  91%|█████████ | 150/165 [19:35<01:54,  7.66s/it]

VAE train ep16:  92%|█████████▏| 151/165 [19:42<01:47,  7.65s/it]

VAE train ep16:  92%|█████████▏| 152/165 [19:50<01:39,  7.69s/it]

VAE train ep16:  93%|█████████▎| 153/165 [19:58<01:32,  7.69s/it]

VAE train ep16:  93%|█████████▎| 154/165 [20:06<01:25,  7.77s/it]

VAE train ep16:  94%|█████████▍| 155/165 [20:13<01:17,  7.75s/it]

VAE train ep16:  95%|█████████▍| 156/165 [20:21<01:09,  7.75s/it]

VAE train ep16:  95%|█████████▌| 157/165 [20:29<01:01,  7.73s/it]

VAE train ep16:  96%|█████████▌| 158/165 [20:37<00:53,  7.69s/it]

VAE train ep16:  96%|█████████▋| 159/165 [20:44<00:46,  7.68s/it]

VAE train ep16:  97%|█████████▋| 160/165 [20:52<00:38,  7.69s/it]

VAE train ep16:  98%|█████████▊| 161/165 [21:00<00:30,  7.71s/it]

VAE train ep16:  98%|█████████▊| 162/165 [21:07<00:22,  7.67s/it]

VAE train ep16:  99%|█████████▉| 163/165 [21:15<00:15,  7.67s/it]

VAE train ep16:  99%|█████████▉| 164/165 [21:22<00:07,  7.64s/it]

VAE train ep16: 100%|██████████| 165/165 [21:23<00:00,  5.51s/it]

VAE val ep16:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep16:   3%|▎         | 1/29 [00:02<00:58,  2.09s/it]

VAE val ep16:   7%|▋         | 2/29 [00:04<00:56,  2.09s/it]

VAE val ep16:  10%|█         | 3/29 [00:06<00:54,  2.10s/it]

VAE val ep16:  14%|█▍        | 4/29 [00:08<00:51,  2.08s/it]

VAE val ep16:  17%|█▋        | 5/29 [00:10<00:49,  2.07s/it]

VAE val ep16:  21%|██        | 6/29 [00:12<00:47,  2.05s/it]

VAE val ep16:  24%|██▍       | 7/29 [00:14<00:44,  2.04s/it]

VAE val ep16:  28%|██▊       | 8/29 [00:16<00:42,  2.05s/it]

VAE val ep16:  31%|███       | 9/29 [00:18<00:40,  2.04s/it]

VAE val ep16:  34%|███▍      | 10/29 [00:20<00:38,  2.04s/it]

VAE val ep16:  38%|███▊      | 11/29 [00:22<00:36,  2.05s/it]

VAE val ep16:  41%|████▏     | 12/29 [00:24<00:34,  2.05s/it]

VAE val ep16:  45%|████▍     | 13/29 [00:26<00:32,  2.05s/it]

VAE val ep16:  48%|████▊     | 14/29 [00:28<00:30,  2.05s/it]

VAE val ep16:  52%|█████▏    | 15/29 [00:30<00:28,  2.04s/it]

VAE val ep16:  55%|█████▌    | 16/29 [00:32<00:26,  2.05s/it]

VAE val ep16:  59%|█████▊    | 17/29 [00:34<00:24,  2.06s/it]

VAE val ep16:  62%|██████▏   | 18/29 [00:37<00:22,  2.07s/it]

VAE val ep16:  66%|██████▌   | 19/29 [00:39<00:20,  2.09s/it]

VAE val ep16:  69%|██████▉   | 20/29 [00:41<00:18,  2.09s/it]

VAE val ep16:  72%|███████▏  | 21/29 [00:43<00:16,  2.10s/it]

VAE val ep16:  76%|███████▌  | 22/29 [00:45<00:14,  2.10s/it]

VAE val ep16:  79%|███████▉  | 23/29 [00:47<00:12,  2.09s/it]

VAE val ep16:  83%|████████▎ | 24/29 [00:49<00:10,  2.07s/it]

VAE val ep16:  86%|████████▌ | 25/29 [00:51<00:08,  2.07s/it]

VAE val ep16:  90%|████████▉ | 26/29 [00:53<00:06,  2.09s/it]

VAE val ep16:  93%|█████████▎| 27/29 [00:55<00:04,  2.12s/it]

VAE val ep16:  97%|█████████▋| 28/29 [00:58<00:02,  2.11s/it]

VAE val ep16: 100%|██████████| 29/29 [00:58<00:00,  1.56s/it]

VAE train ep17:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep17:   1%|          | 1/165 [00:08<21:59,  8.04s/it]

VAE train ep17:   1%|          | 2/165 [00:15<21:38,  7.97s/it]

VAE train ep17:   2%|▏         | 3/165 [00:23<21:17,  7.89s/it]

VAE train ep17:   2%|▏         | 4/165 [00:31<20:55,  7.80s/it]

VAE train ep17:   3%|▎         | 5/165 [00:39<20:51,  7.82s/it]

VAE train ep17:   4%|▎         | 6/165 [00:47<20:49,  7.86s/it]

VAE train ep17:   4%|▍         | 7/165 [00:54<20:29,  7.78s/it]

VAE train ep17:   5%|▍         | 8/165 [01:02<20:20,  7.78s/it]

VAE train ep17:   5%|▌         | 9/165 [01:10<20:22,  7.83s/it]

VAE train ep17:   6%|▌         | 10/165 [01:18<20:16,  7.85s/it]

VAE train ep17:   7%|▋         | 11/165 [01:26<20:10,  7.86s/it]

VAE train ep17:   7%|▋         | 12/165 [01:34<20:10,  7.91s/it]

VAE train ep17:   8%|▊         | 13/165 [01:42<20:04,  7.93s/it]

VAE train ep17:   8%|▊         | 14/165 [01:50<19:54,  7.91s/it]

VAE train ep17:   9%|▉         | 15/165 [01:58<19:45,  7.90s/it]

VAE train ep17:  10%|▉         | 16/165 [02:05<19:31,  7.86s/it]

VAE train ep17:  10%|█         | 17/165 [02:13<19:21,  7.85s/it]

VAE train ep17:  11%|█         | 18/165 [02:21<19:15,  7.86s/it]

VAE train ep17:  12%|█▏        | 19/165 [02:29<19:01,  7.82s/it]

VAE train ep17:  12%|█▏        | 20/165 [02:36<18:45,  7.77s/it]

VAE train ep17:  13%|█▎        | 21/165 [02:44<18:37,  7.76s/it]

VAE train ep17:  13%|█▎        | 22/165 [02:52<18:25,  7.73s/it]

VAE train ep17:  14%|█▍        | 23/165 [03:00<18:21,  7.76s/it]

VAE train ep17:  15%|█▍        | 24/165 [03:07<18:05,  7.70s/it]

VAE train ep17:  15%|█▌        | 25/165 [03:15<17:49,  7.64s/it]

VAE train ep17:  16%|█▌        | 26/165 [03:22<17:41,  7.64s/it]

VAE train ep17:  16%|█▋        | 27/165 [03:30<17:37,  7.67s/it]

VAE train ep17:  17%|█▋        | 28/165 [03:38<17:30,  7.66s/it]

VAE train ep17:  18%|█▊        | 29/165 [03:45<17:25,  7.69s/it]

VAE train ep17:  18%|█▊        | 30/165 [03:53<17:20,  7.70s/it]

VAE train ep17:  19%|█▉        | 31/165 [04:01<17:21,  7.77s/it]

VAE train ep17:  19%|█▉        | 32/165 [04:09<17:16,  7.80s/it]

VAE train ep17:  20%|██        | 33/165 [04:17<17:10,  7.81s/it]

VAE train ep17:  21%|██        | 34/165 [04:25<17:01,  7.80s/it]

VAE train ep17:  21%|██        | 35/165 [04:32<16:50,  7.77s/it]

VAE train ep17:  22%|██▏       | 36/165 [04:40<16:44,  7.78s/it]

VAE train ep17:  22%|██▏       | 37/165 [04:48<16:35,  7.78s/it]

VAE train ep17:  23%|██▎       | 38/165 [04:56<16:25,  7.76s/it]

VAE train ep17:  24%|██▎       | 39/165 [05:03<16:19,  7.78s/it]

VAE train ep17:  24%|██▍       | 40/165 [05:11<16:12,  7.78s/it]

VAE train ep17:  25%|██▍       | 41/165 [05:19<16:01,  7.76s/it]

VAE train ep17:  25%|██▌       | 42/165 [05:27<15:52,  7.74s/it]

VAE train ep17:  26%|██▌       | 43/165 [05:34<15:41,  7.72s/it]

VAE train ep17:  27%|██▋       | 44/165 [05:42<15:41,  7.78s/it]

VAE train ep17:  27%|██▋       | 45/165 [05:50<15:35,  7.79s/it]

VAE train ep17:  28%|██▊       | 46/165 [05:58<15:30,  7.82s/it]

VAE train ep17:  28%|██▊       | 47/165 [06:06<15:19,  7.79s/it]

VAE train ep17:  29%|██▉       | 48/165 [06:14<15:14,  7.81s/it]

VAE train ep17:  30%|██▉       | 49/165 [06:21<15:07,  7.82s/it]

VAE train ep17:  30%|███       | 50/165 [06:29<15:07,  7.89s/it]

VAE train ep17:  31%|███       | 51/165 [06:37<14:54,  7.84s/it]

VAE train ep17:  32%|███▏      | 52/165 [06:45<14:44,  7.83s/it]

VAE train ep17:  32%|███▏      | 53/165 [06:53<14:35,  7.82s/it]

VAE train ep17:  33%|███▎      | 54/165 [07:01<14:34,  7.88s/it]

VAE train ep17:  33%|███▎      | 55/165 [07:08<14:18,  7.81s/it]

VAE train ep17:  34%|███▍      | 56/165 [07:16<14:07,  7.77s/it]

VAE train ep17:  35%|███▍      | 57/165 [07:24<14:03,  7.81s/it]

VAE train ep17:  35%|███▌      | 58/165 [07:32<13:54,  7.80s/it]

VAE train ep17:  36%|███▌      | 59/165 [07:40<13:53,  7.86s/it]

VAE train ep17:  36%|███▋      | 60/165 [07:48<13:50,  7.91s/it]

VAE train ep17:  37%|███▋      | 61/165 [07:56<13:38,  7.87s/it]

VAE train ep17:  38%|███▊      | 62/165 [08:04<13:33,  7.90s/it]

VAE train ep17:  38%|███▊      | 63/165 [08:11<13:18,  7.83s/it]

VAE train ep17:  39%|███▉      | 64/165 [08:19<13:04,  7.77s/it]

VAE train ep17:  39%|███▉      | 65/165 [08:26<12:52,  7.73s/it]

VAE train ep17:  40%|████      | 66/165 [08:34<12:45,  7.73s/it]

VAE train ep17:  41%|████      | 67/165 [08:42<12:38,  7.74s/it]

VAE train ep17:  41%|████      | 68/165 [08:50<12:26,  7.70s/it]

VAE train ep17:  42%|████▏     | 69/165 [08:57<12:21,  7.73s/it]

VAE train ep17:  42%|████▏     | 70/165 [09:05<12:16,  7.76s/it]

VAE train ep17:  43%|████▎     | 71/165 [09:13<12:07,  7.74s/it]

VAE train ep17:  44%|████▎     | 72/165 [09:21<12:04,  7.79s/it]

VAE train ep17:  44%|████▍     | 73/165 [09:28<11:53,  7.75s/it]

VAE train ep17:  45%|████▍     | 74/165 [09:36<11:48,  7.78s/it]

VAE train ep17:  45%|████▌     | 75/165 [09:44<11:38,  7.76s/it]

VAE train ep17:  46%|████▌     | 76/165 [09:52<11:32,  7.78s/it]

VAE train ep17:  47%|████▋     | 77/165 [10:00<11:27,  7.81s/it]

VAE train ep17:  47%|████▋     | 78/165 [10:08<11:21,  7.84s/it]

VAE train ep17:  48%|████▊     | 79/165 [10:15<11:08,  7.78s/it]

VAE train ep17:  48%|████▊     | 80/165 [10:23<11:01,  7.78s/it]

VAE train ep17:  49%|████▉     | 81/165 [10:31<10:54,  7.79s/it]

VAE train ep17:  50%|████▉     | 82/165 [10:39<10:50,  7.83s/it]

VAE train ep17:  50%|█████     | 83/165 [10:47<10:40,  7.82s/it]

VAE train ep17:  51%|█████     | 84/165 [10:54<10:30,  7.79s/it]

VAE train ep17:  52%|█████▏    | 85/165 [11:02<10:27,  7.84s/it]

VAE train ep17:  52%|█████▏    | 86/165 [11:10<10:24,  7.91s/it]

VAE train ep17:  53%|█████▎    | 87/165 [11:19<10:23,  8.00s/it]

VAE train ep17:  53%|█████▎    | 88/165 [11:27<10:19,  8.04s/it]

VAE train ep17:  54%|█████▍    | 89/165 [11:35<10:07,  8.00s/it]

VAE train ep17:  55%|█████▍    | 90/165 [11:43<10:01,  8.02s/it]

VAE train ep17:  55%|█████▌    | 91/165 [11:51<09:56,  8.06s/it]

VAE train ep17:  56%|█████▌    | 92/165 [11:59<09:48,  8.07s/it]

VAE train ep17:  56%|█████▋    | 93/165 [12:07<09:40,  8.06s/it]

VAE train ep17:  57%|█████▋    | 94/165 [12:15<09:35,  8.10s/it]

VAE train ep17:  58%|█████▊    | 95/165 [12:23<09:30,  8.14s/it]

VAE train ep17:  58%|█████▊    | 96/165 [12:31<09:21,  8.14s/it]

VAE train ep17:  59%|█████▉    | 97/165 [12:40<09:16,  8.18s/it]

VAE train ep17:  59%|█████▉    | 98/165 [12:48<09:03,  8.11s/it]

VAE train ep17:  60%|██████    | 99/165 [12:56<08:53,  8.08s/it]

VAE train ep17:  61%|██████    | 100/165 [13:04<08:43,  8.06s/it]

VAE train ep17:  61%|██████    | 101/165 [13:12<08:31,  8.00s/it]

VAE train ep17:  62%|██████▏   | 102/165 [13:19<08:21,  7.96s/it]

VAE train ep17:  62%|██████▏   | 103/165 [13:27<08:09,  7.89s/it]

VAE train ep17:  63%|██████▎   | 104/165 [13:35<07:57,  7.83s/it]

VAE train ep17:  64%|██████▎   | 105/165 [13:43<07:49,  7.82s/it]

VAE train ep17:  64%|██████▍   | 106/165 [13:50<07:39,  7.79s/it]

VAE train ep17:  65%|██████▍   | 107/165 [13:58<07:32,  7.80s/it]

VAE train ep17:  65%|██████▌   | 108/165 [14:06<07:26,  7.83s/it]

VAE train ep17:  66%|██████▌   | 109/165 [14:14<07:19,  7.84s/it]

VAE train ep17:  67%|██████▋   | 110/165 [14:22<07:11,  7.84s/it]

VAE train ep17:  67%|██████▋   | 111/165 [14:30<07:04,  7.86s/it]

VAE train ep17:  68%|██████▊   | 112/165 [14:38<06:55,  7.85s/it]

VAE train ep17:  68%|██████▊   | 113/165 [14:45<06:47,  7.83s/it]

VAE train ep17:  69%|██████▉   | 114/165 [14:53<06:39,  7.83s/it]

VAE train ep17:  70%|██████▉   | 115/165 [15:01<06:31,  7.82s/it]

VAE train ep17:  70%|███████   | 116/165 [15:09<06:24,  7.85s/it]

VAE train ep17:  71%|███████   | 117/165 [15:17<06:14,  7.80s/it]

VAE train ep17:  72%|███████▏  | 118/165 [15:24<06:08,  7.83s/it]

VAE train ep17:  72%|███████▏  | 119/165 [15:32<05:58,  7.79s/it]

VAE train ep17:  73%|███████▎  | 120/165 [15:40<05:55,  7.89s/it]

VAE train ep17:  73%|███████▎  | 121/165 [15:48<05:46,  7.87s/it]

VAE train ep17:  74%|███████▍  | 122/165 [15:56<05:37,  7.85s/it]

VAE train ep17:  75%|███████▍  | 123/165 [16:04<05:27,  7.79s/it]

VAE train ep17:  75%|███████▌  | 124/165 [16:11<05:18,  7.77s/it]

VAE train ep17:  76%|███████▌  | 125/165 [16:19<05:09,  7.75s/it]

VAE train ep17:  76%|███████▋  | 126/165 [16:27<05:02,  7.76s/it]

VAE train ep17:  77%|███████▋  | 127/165 [16:34<04:52,  7.70s/it]

VAE train ep17:  78%|███████▊  | 128/165 [16:42<04:43,  7.67s/it]

VAE train ep17:  78%|███████▊  | 129/165 [16:50<04:35,  7.65s/it]

VAE train ep17:  79%|███████▉  | 130/165 [16:57<04:29,  7.71s/it]

VAE train ep17:  79%|███████▉  | 131/165 [17:05<04:22,  7.71s/it]

VAE train ep17:  80%|████████  | 132/165 [17:13<04:13,  7.69s/it]

VAE train ep17:  81%|████████  | 133/165 [17:21<04:07,  7.72s/it]

VAE train ep17:  81%|████████  | 134/165 [17:28<04:00,  7.75s/it]

VAE train ep17:  82%|████████▏ | 135/165 [17:36<03:53,  7.80s/it]

VAE train ep17:  82%|████████▏ | 136/165 [17:44<03:45,  7.78s/it]

VAE train ep17:  83%|████████▎ | 137/165 [17:52<03:38,  7.81s/it]

VAE train ep17:  84%|████████▎ | 138/165 [18:00<03:31,  7.84s/it]

VAE train ep17:  84%|████████▍ | 139/165 [18:08<03:24,  7.88s/it]

VAE train ep17:  85%|████████▍ | 140/165 [18:16<03:16,  7.84s/it]

VAE train ep17:  85%|████████▌ | 141/165 [18:23<03:08,  7.84s/it]

VAE train ep17:  86%|████████▌ | 142/165 [18:31<03:01,  7.91s/it]

VAE train ep17:  87%|████████▋ | 143/165 [18:40<02:56,  8.02s/it]

VAE train ep17:  87%|████████▋ | 144/165 [18:48<02:51,  8.17s/it]

VAE train ep17:  88%|████████▊ | 145/165 [18:57<02:46,  8.34s/it]

VAE train ep17:  88%|████████▊ | 146/165 [19:06<02:40,  8.44s/it]

VAE train ep17:  89%|████████▉ | 147/165 [19:14<02:31,  8.42s/it]

VAE train ep17:  90%|████████▉ | 148/165 [19:22<02:21,  8.30s/it]

VAE train ep17:  90%|█████████ | 149/165 [19:30<02:10,  8.18s/it]

VAE train ep17:  91%|█████████ | 150/165 [19:38<02:02,  8.15s/it]

VAE train ep17:  92%|█████████▏| 151/165 [19:46<01:54,  8.17s/it]

VAE train ep17:  92%|█████████▏| 152/165 [19:54<01:45,  8.08s/it]

VAE train ep17:  93%|█████████▎| 153/165 [20:02<01:36,  8.05s/it]

VAE train ep17:  93%|█████████▎| 154/165 [20:10<01:28,  8.03s/it]

VAE train ep17:  94%|█████████▍| 155/165 [20:18<01:20,  8.03s/it]

VAE train ep17:  95%|█████████▍| 156/165 [20:26<01:12,  8.02s/it]

VAE train ep17:  95%|█████████▌| 157/165 [20:34<01:03,  7.93s/it]

VAE train ep17:  96%|█████████▌| 158/165 [20:42<00:55,  7.91s/it]

VAE train ep17:  96%|█████████▋| 159/165 [20:49<00:47,  7.86s/it]

VAE train ep17:  97%|█████████▋| 160/165 [20:57<00:39,  7.84s/it]

VAE train ep17:  98%|█████████▊| 161/165 [21:05<00:31,  7.80s/it]

VAE train ep17:  98%|█████████▊| 162/165 [21:13<00:23,  7.84s/it]

VAE train ep17:  99%|█████████▉| 163/165 [21:21<00:15,  7.84s/it]

VAE train ep17:  99%|█████████▉| 164/165 [21:28<00:07,  7.81s/it]

VAE train ep17: 100%|██████████| 165/165 [21:29<00:00,  5.60s/it]

VAE val ep17:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep17:   3%|▎         | 1/29 [00:02<00:58,  2.11s/it]

VAE val ep17:   7%|▋         | 2/29 [00:04<00:56,  2.10s/it]

VAE val ep17:  10%|█         | 3/29 [00:06<00:54,  2.08s/it]

VAE val ep17:  14%|█▍        | 4/29 [00:08<00:52,  2.11s/it]

VAE val ep17:  17%|█▋        | 5/29 [00:10<00:51,  2.13s/it]

VAE val ep17:  21%|██        | 6/29 [00:12<00:48,  2.13s/it]

VAE val ep17:  24%|██▍       | 7/29 [00:14<00:47,  2.14s/it]

VAE val ep17:  28%|██▊       | 8/29 [00:17<00:45,  2.17s/it]

VAE val ep17:  31%|███       | 9/29 [00:19<00:43,  2.16s/it]

VAE val ep17:  34%|███▍      | 10/29 [00:21<00:40,  2.14s/it]

VAE val ep17:  38%|███▊      | 11/29 [00:23<00:38,  2.12s/it]

VAE val ep17:  41%|████▏     | 12/29 [00:25<00:35,  2.11s/it]

VAE val ep17:  45%|████▍     | 13/29 [00:27<00:33,  2.12s/it]

VAE val ep17:  48%|████▊     | 14/29 [00:29<00:32,  2.13s/it]

VAE val ep17:  52%|█████▏    | 15/29 [00:31<00:29,  2.13s/it]

VAE val ep17:  55%|█████▌    | 16/29 [00:34<00:27,  2.12s/it]

VAE val ep17:  59%|█████▊    | 17/29 [00:36<00:25,  2.10s/it]

VAE val ep17:  62%|██████▏   | 18/29 [00:38<00:23,  2.10s/it]

VAE val ep17:  66%|██████▌   | 19/29 [00:40<00:20,  2.10s/it]

VAE val ep17:  69%|██████▉   | 20/29 [00:42<00:18,  2.09s/it]

VAE val ep17:  72%|███████▏  | 21/29 [00:44<00:16,  2.08s/it]

VAE val ep17:  76%|███████▌  | 22/29 [00:46<00:14,  2.08s/it]

VAE val ep17:  79%|███████▉  | 23/29 [00:48<00:12,  2.09s/it]

VAE val ep17:  83%|████████▎ | 24/29 [00:50<00:10,  2.07s/it]

VAE val ep17:  86%|████████▌ | 25/29 [00:52<00:08,  2.06s/it]

VAE val ep17:  90%|████████▉ | 26/29 [00:54<00:06,  2.06s/it]

VAE val ep17:  93%|█████████▎| 27/29 [00:56<00:04,  2.05s/it]

VAE val ep17:  97%|█████████▋| 28/29 [00:58<00:02,  2.06s/it]

VAE val ep17: 100%|██████████| 29/29 [00:59<00:00,  1.52s/it]

VAE train ep18:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep18:   1%|          | 1/165 [00:08<22:33,  8.25s/it]

VAE train ep18:   1%|          | 2/165 [00:16<22:11,  8.17s/it]

VAE train ep18:   2%|▏         | 3/165 [00:24<21:45,  8.06s/it]

VAE train ep18:   2%|▏         | 4/165 [00:32<21:24,  7.98s/it]

VAE train ep18:   3%|▎         | 5/165 [00:39<20:59,  7.87s/it]

VAE train ep18:   4%|▎         | 6/165 [00:47<20:41,  7.81s/it]

VAE train ep18:   4%|▍         | 7/165 [00:55<20:29,  7.78s/it]

VAE train ep18:   5%|▍         | 8/165 [01:02<20:14,  7.74s/it]

VAE train ep18:   5%|▌         | 9/165 [01:10<19:56,  7.67s/it]

VAE train ep18:   6%|▌         | 10/165 [01:18<19:49,  7.67s/it]

VAE train ep18:   7%|▋         | 11/165 [01:25<19:36,  7.64s/it]

VAE train ep18:   7%|▋         | 12/165 [01:33<19:25,  7.62s/it]

VAE train ep18:   8%|▊         | 13/165 [01:40<19:11,  7.57s/it]

VAE train ep18:   8%|▊         | 14/165 [01:48<19:05,  7.59s/it]

VAE train ep18:   9%|▉         | 15/165 [01:55<19:01,  7.61s/it]

VAE train ep18:  10%|▉         | 16/165 [02:03<18:55,  7.62s/it]

VAE train ep18:  10%|█         | 17/165 [02:11<18:43,  7.59s/it]

VAE train ep18:  11%|█         | 18/165 [02:18<18:38,  7.61s/it]

VAE train ep18:  12%|█▏        | 19/165 [02:26<18:33,  7.62s/it]

VAE train ep18:  12%|█▏        | 20/165 [02:33<18:21,  7.60s/it]

VAE train ep18:  13%|█▎        | 21/165 [02:41<18:10,  7.58s/it]

VAE train ep18:  13%|█▎        | 22/165 [02:49<18:03,  7.58s/it]

VAE train ep18:  14%|█▍        | 23/165 [02:56<17:46,  7.51s/it]

VAE train ep18:  15%|█▍        | 24/165 [03:04<17:41,  7.53s/it]

VAE train ep18:  15%|█▌        | 25/165 [03:11<17:37,  7.56s/it]

VAE train ep18:  16%|█▌        | 26/165 [03:19<17:33,  7.58s/it]

VAE train ep18:  16%|█▋        | 27/165 [03:26<17:22,  7.55s/it]

VAE train ep18:  17%|█▋        | 28/165 [03:34<17:27,  7.65s/it]

VAE train ep18:  18%|█▊        | 29/165 [03:42<17:28,  7.71s/it]

VAE train ep18:  18%|█▊        | 30/165 [03:50<17:26,  7.75s/it]

VAE train ep18:  19%|█▉        | 31/165 [03:58<17:15,  7.72s/it]

VAE train ep18:  19%|█▉        | 32/165 [04:05<17:04,  7.70s/it]

VAE train ep18:  20%|██        | 33/165 [04:13<16:49,  7.65s/it]

VAE train ep18:  21%|██        | 34/165 [04:20<16:47,  7.69s/it]

VAE train ep18:  21%|██        | 35/165 [04:28<16:36,  7.67s/it]

VAE train ep18:  22%|██▏       | 36/165 [04:36<16:32,  7.69s/it]

VAE train ep18:  22%|██▏       | 37/165 [04:44<16:27,  7.72s/it]

VAE train ep18:  23%|██▎       | 38/165 [04:52<16:30,  7.80s/it]

VAE train ep18:  24%|██▎       | 39/165 [05:00<16:38,  7.93s/it]

VAE train ep18:  24%|██▍       | 40/165 [05:08<16:32,  7.94s/it]

VAE train ep18:  25%|██▍       | 41/165 [05:15<16:14,  7.86s/it]

VAE train ep18:  25%|██▌       | 42/165 [05:23<15:57,  7.78s/it]

VAE train ep18:  26%|██▌       | 43/165 [05:30<15:34,  7.66s/it]

VAE train ep18:  27%|██▋       | 44/165 [05:38<15:26,  7.66s/it]

VAE train ep18:  27%|██▋       | 45/165 [05:46<15:12,  7.61s/it]

VAE train ep18:  28%|██▊       | 46/165 [05:53<15:03,  7.59s/it]

VAE train ep18:  28%|██▊       | 47/165 [06:01<14:53,  7.57s/it]

VAE train ep18:  29%|██▉       | 48/165 [06:08<14:50,  7.61s/it]

VAE train ep18:  30%|██▉       | 49/165 [06:16<14:44,  7.62s/it]

VAE train ep18:  30%|███       | 50/165 [06:24<14:35,  7.61s/it]

VAE train ep18:  31%|███       | 51/165 [06:31<14:30,  7.63s/it]

VAE train ep18:  32%|███▏      | 52/165 [06:39<14:24,  7.65s/it]

VAE train ep18:  32%|███▏      | 53/165 [06:47<14:28,  7.76s/it]

VAE train ep18:  33%|███▎      | 54/165 [06:55<14:25,  7.80s/it]

VAE train ep18:  33%|███▎      | 55/165 [07:03<14:26,  7.88s/it]

VAE train ep18:  34%|███▍      | 56/165 [07:11<14:27,  7.95s/it]

VAE train ep18:  35%|███▍      | 57/165 [07:19<14:25,  8.01s/it]

VAE train ep18:  35%|███▌      | 58/165 [07:27<14:18,  8.02s/it]

VAE train ep18:  36%|███▌      | 59/165 [07:35<14:07,  8.00s/it]

VAE train ep18:  36%|███▋      | 60/165 [07:43<13:58,  7.98s/it]

VAE train ep18:  37%|███▋      | 61/165 [07:51<13:51,  7.99s/it]

VAE train ep18:  38%|███▊      | 62/165 [07:59<13:42,  7.99s/it]

VAE train ep18:  38%|███▊      | 63/165 [08:07<13:28,  7.93s/it]

VAE train ep18:  39%|███▉      | 64/165 [08:15<13:15,  7.88s/it]

VAE train ep18:  39%|███▉      | 65/165 [08:22<12:59,  7.80s/it]

VAE train ep18:  40%|████      | 66/165 [08:30<12:46,  7.75s/it]

VAE train ep18:  41%|████      | 67/165 [08:38<12:41,  7.77s/it]

VAE train ep18:  41%|████      | 68/165 [08:45<12:31,  7.75s/it]

VAE train ep18:  42%|████▏     | 69/165 [08:53<12:24,  7.75s/it]

VAE train ep18:  42%|████▏     | 70/165 [09:01<12:18,  7.77s/it]

VAE train ep18:  43%|████▎     | 71/165 [09:09<12:05,  7.71s/it]

VAE train ep18:  44%|████▎     | 72/165 [09:16<12:00,  7.74s/it]

VAE train ep18:  44%|████▍     | 73/165 [09:24<11:50,  7.73s/it]

VAE train ep18:  45%|████▍     | 74/165 [09:32<11:37,  7.66s/it]

VAE train ep18:  45%|████▌     | 75/165 [09:39<11:31,  7.68s/it]

VAE train ep18:  46%|████▌     | 76/165 [09:47<11:23,  7.68s/it]

VAE train ep18:  47%|████▋     | 77/165 [09:55<11:14,  7.67s/it]

VAE train ep18:  47%|████▋     | 78/165 [10:02<11:08,  7.69s/it]

VAE train ep18:  48%|████▊     | 79/165 [10:10<10:56,  7.64s/it]

VAE train ep18:  48%|████▊     | 80/165 [10:18<10:49,  7.65s/it]

VAE train ep18:  49%|████▉     | 81/165 [10:25<10:40,  7.63s/it]

VAE train ep18:  50%|████▉     | 82/165 [10:33<10:32,  7.62s/it]

VAE train ep18:  50%|█████     | 83/165 [10:40<10:23,  7.61s/it]

VAE train ep18:  51%|█████     | 84/165 [10:48<10:13,  7.58s/it]

VAE train ep18:  52%|█████▏    | 85/165 [10:55<10:05,  7.57s/it]

VAE train ep18:  52%|█████▏    | 86/165 [11:03<09:56,  7.55s/it]

VAE train ep18:  53%|█████▎    | 87/165 [11:11<09:52,  7.60s/it]

VAE train ep18:  53%|█████▎    | 88/165 [11:18<09:45,  7.61s/it]

VAE train ep18:  54%|█████▍    | 89/165 [11:26<09:34,  7.56s/it]

VAE train ep18:  55%|█████▍    | 90/165 [11:33<09:29,  7.59s/it]

VAE train ep18:  55%|█████▌    | 91/165 [11:41<09:19,  7.56s/it]

VAE train ep18:  56%|█████▌    | 92/165 [11:49<09:20,  7.67s/it]

VAE train ep18:  56%|█████▋    | 93/165 [11:57<09:16,  7.73s/it]

VAE train ep18:  57%|█████▋    | 94/165 [12:04<09:09,  7.74s/it]

VAE train ep18:  58%|█████▊    | 95/165 [12:12<08:57,  7.67s/it]

VAE train ep18:  58%|█████▊    | 96/165 [12:20<08:47,  7.65s/it]

VAE train ep18:  59%|█████▉    | 97/165 [12:27<08:38,  7.62s/it]

VAE train ep18:  59%|█████▉    | 98/165 [12:35<08:28,  7.59s/it]

VAE train ep18:  60%|██████    | 99/165 [12:42<08:20,  7.58s/it]

VAE train ep18:  61%|██████    | 100/165 [12:50<08:14,  7.61s/it]

VAE train ep18:  61%|██████    | 101/165 [12:57<08:06,  7.60s/it]

VAE train ep18:  62%|██████▏   | 102/165 [13:05<08:00,  7.63s/it]

VAE train ep18:  62%|██████▏   | 103/165 [13:13<07:55,  7.67s/it]

VAE train ep18:  63%|██████▎   | 104/165 [13:21<07:47,  7.66s/it]

VAE train ep18:  64%|██████▎   | 105/165 [13:28<07:39,  7.66s/it]

VAE train ep18:  64%|██████▍   | 106/165 [13:36<07:31,  7.65s/it]

VAE train ep18:  65%|██████▍   | 107/165 [13:43<07:21,  7.61s/it]

VAE train ep18:  65%|██████▌   | 108/165 [13:51<07:15,  7.65s/it]

VAE train ep18:  66%|██████▌   | 109/165 [13:59<07:12,  7.72s/it]

VAE train ep18:  67%|██████▋   | 110/165 [14:07<07:06,  7.76s/it]

VAE train ep18:  67%|██████▋   | 111/165 [14:15<07:01,  7.81s/it]

VAE train ep18:  68%|██████▊   | 112/165 [14:23<06:55,  7.85s/it]

VAE train ep18:  68%|██████▊   | 113/165 [14:30<06:47,  7.83s/it]

VAE train ep18:  69%|██████▉   | 114/165 [14:38<06:42,  7.89s/it]

VAE train ep18:  70%|██████▉   | 115/165 [14:47<06:37,  7.95s/it]

VAE train ep18:  70%|███████   | 116/165 [14:55<06:32,  8.02s/it]

VAE train ep18:  71%|███████   | 117/165 [15:03<06:26,  8.05s/it]

VAE train ep18:  72%|███████▏  | 118/165 [15:11<06:20,  8.09s/it]

VAE train ep18:  72%|███████▏  | 119/165 [15:19<06:14,  8.13s/it]

VAE train ep18:  73%|███████▎  | 120/165 [15:27<06:05,  8.13s/it]

VAE train ep18:  73%|███████▎  | 121/165 [15:35<05:55,  8.07s/it]

VAE train ep18:  74%|███████▍  | 122/165 [15:43<05:46,  8.07s/it]

VAE train ep18:  75%|███████▍  | 123/165 [15:51<05:38,  8.07s/it]

VAE train ep18:  75%|███████▌  | 124/165 [16:00<05:30,  8.06s/it]

VAE train ep18:  76%|███████▌  | 125/165 [16:08<05:23,  8.08s/it]

VAE train ep18:  76%|███████▋  | 126/165 [16:16<05:15,  8.08s/it]

VAE train ep18:  77%|███████▋  | 127/165 [16:24<05:04,  8.02s/it]

VAE train ep18:  78%|███████▊  | 128/165 [16:31<04:53,  7.93s/it]

VAE train ep18:  78%|███████▊  | 129/165 [16:39<04:41,  7.82s/it]

VAE train ep18:  79%|███████▉  | 130/165 [16:46<04:31,  7.75s/it]

VAE train ep18:  79%|███████▉  | 131/165 [16:54<04:23,  7.74s/it]

VAE train ep18:  80%|████████  | 132/165 [17:02<04:16,  7.78s/it]

VAE train ep18:  81%|████████  | 133/165 [17:10<04:09,  7.79s/it]

VAE train ep18:  81%|████████  | 134/165 [17:18<04:01,  7.80s/it]

VAE train ep18:  82%|████████▏ | 135/165 [17:26<03:53,  7.80s/it]

VAE train ep18:  82%|████████▏ | 136/165 [17:33<03:46,  7.81s/it]

VAE train ep18:  83%|████████▎ | 137/165 [17:41<03:38,  7.80s/it]

VAE train ep18:  84%|████████▎ | 138/165 [17:49<03:30,  7.78s/it]

VAE train ep18:  84%|████████▍ | 139/165 [17:57<03:22,  7.77s/it]

VAE train ep18:  85%|████████▍ | 140/165 [18:05<03:16,  7.84s/it]

VAE train ep18:  85%|████████▌ | 141/165 [18:12<03:07,  7.81s/it]

VAE train ep18:  86%|████████▌ | 142/165 [18:20<02:58,  7.76s/it]

VAE train ep18:  87%|████████▋ | 143/165 [18:28<02:49,  7.71s/it]

VAE train ep18:  87%|████████▋ | 144/165 [18:35<02:42,  7.74s/it]

VAE train ep18:  88%|████████▊ | 145/165 [18:43<02:34,  7.71s/it]

VAE train ep18:  88%|████████▊ | 146/165 [18:50<02:24,  7.63s/it]

VAE train ep18:  89%|████████▉ | 147/165 [18:58<02:16,  7.57s/it]

VAE train ep18:  90%|████████▉ | 148/165 [19:06<02:09,  7.62s/it]

VAE train ep18:  90%|█████████ | 149/165 [19:13<02:02,  7.64s/it]

VAE train ep18:  91%|█████████ | 150/165 [19:21<01:54,  7.61s/it]

VAE train ep18:  92%|█████████▏| 151/165 [19:28<01:46,  7.57s/it]

VAE train ep18:  92%|█████████▏| 152/165 [19:36<01:38,  7.58s/it]

VAE train ep18:  93%|█████████▎| 153/165 [19:44<01:30,  7.58s/it]

VAE train ep18:  93%|█████████▎| 154/165 [19:52<01:25,  7.76s/it]

VAE train ep18:  94%|█████████▍| 155/165 [19:59<01:17,  7.74s/it]

VAE train ep18:  95%|█████████▍| 156/165 [20:07<01:09,  7.75s/it]

VAE train ep18:  95%|█████████▌| 157/165 [20:15<01:01,  7.71s/it]

VAE train ep18:  96%|█████████▌| 158/165 [20:22<00:53,  7.68s/it]

VAE train ep18:  96%|█████████▋| 159/165 [20:30<00:45,  7.66s/it]

VAE train ep18:  97%|█████████▋| 160/165 [20:38<00:38,  7.62s/it]

VAE train ep18:  98%|█████████▊| 161/165 [20:45<00:30,  7.61s/it]

VAE train ep18:  98%|█████████▊| 162/165 [20:53<00:22,  7.66s/it]

VAE train ep18:  99%|█████████▉| 163/165 [21:01<00:15,  7.67s/it]

VAE train ep18:  99%|█████████▉| 164/165 [21:08<00:07,  7.65s/it]

VAE train ep18: 100%|██████████| 165/165 [21:09<00:00,  5.50s/it]

VAE val ep18:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep18:   3%|▎         | 1/29 [00:02<00:57,  2.07s/it]

VAE val ep18:   7%|▋         | 2/29 [00:04<00:55,  2.04s/it]

VAE val ep18:  10%|█         | 3/29 [00:06<00:52,  2.03s/it]

VAE val ep18:  14%|█▍        | 4/29 [00:08<00:51,  2.04s/it]

VAE val ep18:  17%|█▋        | 5/29 [00:10<00:49,  2.07s/it]

VAE val ep18:  21%|██        | 6/29 [00:12<00:47,  2.07s/it]

VAE val ep18:  24%|██▍       | 7/29 [00:14<00:45,  2.06s/it]

VAE val ep18:  28%|██▊       | 8/29 [00:16<00:43,  2.08s/it]

VAE val ep18:  31%|███       | 9/29 [00:18<00:42,  2.10s/it]

VAE val ep18:  34%|███▍      | 10/29 [00:20<00:39,  2.10s/it]

VAE val ep18:  38%|███▊      | 11/29 [00:22<00:37,  2.09s/it]

VAE val ep18:  41%|████▏     | 12/29 [00:24<00:35,  2.10s/it]

VAE val ep18:  45%|████▍     | 13/29 [00:27<00:33,  2.10s/it]

VAE val ep18:  48%|████▊     | 14/29 [00:29<00:31,  2.10s/it]

VAE val ep18:  52%|█████▏    | 15/29 [00:31<00:29,  2.08s/it]

VAE val ep18:  55%|█████▌    | 16/29 [00:33<00:26,  2.07s/it]

VAE val ep18:  59%|█████▊    | 17/29 [00:35<00:24,  2.07s/it]

VAE val ep18:  62%|██████▏   | 18/29 [00:37<00:22,  2.06s/it]

VAE val ep18:  66%|██████▌   | 19/29 [00:39<00:20,  2.06s/it]

VAE val ep18:  69%|██████▉   | 20/29 [00:41<00:18,  2.05s/it]

VAE val ep18:  72%|███████▏  | 21/29 [00:43<00:16,  2.04s/it]

VAE val ep18:  76%|███████▌  | 22/29 [00:45<00:14,  2.05s/it]

VAE val ep18:  79%|███████▉  | 23/29 [00:47<00:12,  2.05s/it]

VAE val ep18:  83%|████████▎ | 24/29 [00:49<00:10,  2.05s/it]

VAE val ep18:  86%|████████▌ | 25/29 [00:51<00:08,  2.05s/it]

VAE val ep18:  90%|████████▉ | 26/29 [00:53<00:06,  2.08s/it]

VAE val ep18:  93%|█████████▎| 27/29 [00:56<00:04,  2.12s/it]

VAE val ep18:  97%|█████████▋| 28/29 [00:58<00:02,  2.09s/it]

VAE val ep18: 100%|██████████| 29/29 [00:58<00:00,  1.55s/it]

VAE train ep19:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep19:   1%|          | 1/165 [00:07<21:49,  7.99s/it]

VAE train ep19:   1%|          | 2/165 [00:16<21:50,  8.04s/it]

VAE train ep19:   2%|▏         | 3/165 [00:24<21:38,  8.01s/it]

VAE train ep19:   2%|▏         | 4/165 [00:31<21:23,  7.97s/it]

VAE train ep19:   3%|▎         | 5/165 [00:40<21:29,  8.06s/it]

VAE train ep19:   4%|▎         | 6/165 [00:48<21:22,  8.06s/it]

VAE train ep19:   4%|▍         | 7/165 [00:56<20:58,  7.97s/it]

VAE train ep19:   5%|▍         | 8/165 [01:03<20:41,  7.91s/it]

VAE train ep19:   5%|▌         | 9/165 [01:11<20:34,  7.91s/it]

VAE train ep19:   6%|▌         | 10/165 [01:19<20:19,  7.87s/it]

VAE train ep19:   7%|▋         | 11/165 [01:27<20:16,  7.90s/it]

VAE train ep19:   7%|▋         | 12/165 [01:35<20:02,  7.86s/it]

VAE train ep19:   8%|▊         | 13/165 [01:43<19:51,  7.84s/it]

VAE train ep19:   8%|▊         | 14/165 [01:51<19:56,  7.93s/it]

VAE train ep19:   9%|▉         | 15/165 [01:59<19:46,  7.91s/it]

VAE train ep19:  10%|▉         | 16/165 [02:06<19:37,  7.90s/it]

VAE train ep19:  10%|█         | 17/165 [02:14<19:22,  7.86s/it]

VAE train ep19:  11%|█         | 18/165 [02:22<19:07,  7.81s/it]

VAE train ep19:  12%|█▏        | 19/165 [02:30<18:54,  7.77s/it]

VAE train ep19:  12%|█▏        | 20/165 [02:37<18:38,  7.71s/it]

VAE train ep19:  13%|█▎        | 21/165 [02:45<18:32,  7.72s/it]

VAE train ep19:  13%|█▎        | 22/165 [02:53<18:23,  7.72s/it]

VAE train ep19:  14%|█▍        | 23/165 [03:00<18:15,  7.71s/it]

VAE train ep19:  15%|█▍        | 24/165 [03:08<18:11,  7.74s/it]

VAE train ep19:  15%|█▌        | 25/165 [03:16<18:04,  7.74s/it]

VAE train ep19:  16%|█▌        | 26/165 [03:23<17:50,  7.70s/it]

VAE train ep19:  16%|█▋        | 27/165 [03:31<17:39,  7.68s/it]

VAE train ep19:  17%|█▋        | 28/165 [03:39<17:42,  7.76s/it]

VAE train ep19:  18%|█▊        | 29/165 [03:47<17:43,  7.82s/it]

VAE train ep19:  18%|█▊        | 30/165 [03:55<17:31,  7.79s/it]

VAE train ep19:  19%|█▉        | 31/165 [04:02<17:15,  7.73s/it]

VAE train ep19:  19%|█▉        | 32/165 [04:10<17:04,  7.70s/it]

VAE train ep19:  20%|██        | 33/165 [04:18<16:54,  7.68s/it]

VAE train ep19:  21%|██        | 34/165 [04:25<16:47,  7.69s/it]

VAE train ep19:  21%|██        | 35/165 [04:33<16:39,  7.69s/it]

VAE train ep19:  22%|██▏       | 36/165 [04:41<16:28,  7.66s/it]

VAE train ep19:  22%|██▏       | 37/165 [04:48<16:24,  7.69s/it]

VAE train ep19:  23%|██▎       | 38/165 [04:56<16:18,  7.70s/it]

VAE train ep19:  24%|██▎       | 39/165 [05:04<16:11,  7.71s/it]

VAE train ep19:  24%|██▍       | 40/165 [05:11<16:00,  7.68s/it]

VAE train ep19:  25%|██▍       | 41/165 [05:19<15:55,  7.71s/it]

VAE train ep19:  25%|██▌       | 42/165 [05:27<15:47,  7.70s/it]

VAE train ep19:  26%|██▌       | 43/165 [05:35<15:48,  7.78s/it]

VAE train ep19:  27%|██▋       | 44/165 [05:42<15:39,  7.76s/it]

VAE train ep19:  27%|██▋       | 45/165 [05:50<15:31,  7.76s/it]

VAE train ep19:  28%|██▊       | 46/165 [05:58<15:16,  7.70s/it]

VAE train ep19:  28%|██▊       | 47/165 [06:05<15:07,  7.69s/it]

VAE train ep19:  29%|██▉       | 48/165 [06:13<14:55,  7.65s/it]

VAE train ep19:  30%|██▉       | 49/165 [06:21<14:43,  7.62s/it]

VAE train ep19:  30%|███       | 50/165 [06:28<14:32,  7.59s/it]

VAE train ep19:  31%|███       | 51/165 [06:36<14:25,  7.59s/it]

VAE train ep19:  32%|███▏      | 52/165 [06:43<14:17,  7.59s/it]

VAE train ep19:  32%|███▏      | 53/165 [06:51<14:16,  7.64s/it]

VAE train ep19:  33%|███▎      | 54/165 [06:59<14:11,  7.67s/it]

VAE train ep19:  33%|███▎      | 55/165 [07:06<14:03,  7.67s/it]

VAE train ep19:  34%|███▍      | 56/165 [07:14<13:56,  7.67s/it]

VAE train ep19:  35%|███▍      | 57/165 [07:22<13:45,  7.64s/it]

VAE train ep19:  35%|███▌      | 58/165 [07:29<13:34,  7.62s/it]

VAE train ep19:  36%|███▌      | 59/165 [07:37<13:28,  7.62s/it]

VAE train ep19:  36%|███▋      | 60/165 [07:44<13:19,  7.61s/it]

VAE train ep19:  37%|███▋      | 61/165 [07:52<13:11,  7.61s/it]

VAE train ep19:  38%|███▊      | 62/165 [08:00<13:03,  7.61s/it]

VAE train ep19:  38%|███▊      | 63/165 [08:07<12:53,  7.58s/it]

VAE train ep19:  39%|███▉      | 64/165 [08:15<12:44,  7.57s/it]

VAE train ep19:  39%|███▉      | 65/165 [08:22<12:39,  7.60s/it]

VAE train ep19:  40%|████      | 66/165 [08:30<12:32,  7.60s/it]

VAE train ep19:  41%|████      | 67/165 [08:38<12:24,  7.59s/it]

VAE train ep19:  41%|████      | 68/165 [08:45<12:15,  7.58s/it]

VAE train ep19:  42%|████▏     | 69/165 [08:53<12:05,  7.56s/it]

VAE train ep19:  42%|████▏     | 70/165 [09:00<12:02,  7.61s/it]

VAE train ep19:  43%|████▎     | 71/165 [09:08<11:49,  7.55s/it]

VAE train ep19:  44%|████▎     | 72/165 [09:15<11:41,  7.54s/it]

VAE train ep19:  44%|████▍     | 73/165 [09:23<11:38,  7.60s/it]

VAE train ep19:  45%|████▍     | 74/165 [09:31<11:30,  7.59s/it]

VAE train ep19:  45%|████▌     | 75/165 [09:38<11:22,  7.59s/it]

VAE train ep19:  46%|████▌     | 76/165 [09:46<11:13,  7.57s/it]

VAE train ep19:  47%|████▋     | 77/165 [09:53<11:07,  7.59s/it]

VAE train ep19:  47%|████▋     | 78/165 [10:01<10:58,  7.56s/it]

VAE train ep19:  48%|████▊     | 79/165 [10:08<10:51,  7.58s/it]

VAE train ep19:  48%|████▊     | 80/165 [10:16<10:41,  7.55s/it]

VAE train ep19:  49%|████▉     | 81/165 [10:24<10:33,  7.55s/it]

VAE train ep19:  50%|████▉     | 82/165 [10:31<10:24,  7.53s/it]

VAE train ep19:  50%|█████     | 83/165 [10:39<10:18,  7.54s/it]

VAE train ep19:  51%|█████     | 84/165 [10:46<10:11,  7.55s/it]

VAE train ep19:  52%|█████▏    | 85/165 [10:54<10:05,  7.56s/it]

VAE train ep19:  52%|█████▏    | 86/165 [11:01<10:00,  7.60s/it]

VAE train ep19:  53%|█████▎    | 87/165 [11:09<09:58,  7.67s/it]

VAE train ep19:  53%|█████▎    | 88/165 [11:17<09:51,  7.68s/it]

VAE train ep19:  54%|█████▍    | 89/165 [11:25<09:43,  7.68s/it]

VAE train ep19:  55%|█████▍    | 90/165 [11:32<09:31,  7.63s/it]

VAE train ep19:  55%|█████▌    | 91/165 [11:40<09:26,  7.66s/it]

VAE train ep19:  56%|█████▌    | 92/165 [11:47<09:15,  7.61s/it]

VAE train ep19:  56%|█████▋    | 93/165 [11:55<09:07,  7.60s/it]

VAE train ep19:  57%|█████▋    | 94/165 [12:03<08:58,  7.59s/it]

VAE train ep19:  58%|█████▊    | 95/165 [12:10<08:53,  7.62s/it]

VAE train ep19:  58%|█████▊    | 96/165 [12:18<08:49,  7.68s/it]

VAE train ep19:  59%|█████▉    | 97/165 [12:26<08:41,  7.66s/it]

VAE train ep19:  59%|█████▉    | 98/165 [12:33<08:36,  7.71s/it]

VAE train ep19:  60%|██████    | 99/165 [12:41<08:27,  7.69s/it]

VAE train ep19:  61%|██████    | 100/165 [12:49<08:18,  7.67s/it]

VAE train ep19:  61%|██████    | 101/165 [12:56<08:11,  7.67s/it]

VAE train ep19:  62%|██████▏   | 102/165 [13:04<08:03,  7.67s/it]

VAE train ep19:  62%|██████▏   | 103/165 [13:12<07:54,  7.65s/it]

VAE train ep19:  63%|██████▎   | 104/165 [13:19<07:42,  7.59s/it]

VAE train ep19:  64%|██████▎   | 105/165 [13:27<07:32,  7.54s/it]

VAE train ep19:  64%|██████▍   | 106/165 [13:34<07:24,  7.53s/it]

VAE train ep19:  65%|██████▍   | 107/165 [13:42<07:16,  7.53s/it]

VAE train ep19:  65%|██████▌   | 108/165 [13:49<07:13,  7.60s/it]

VAE train ep19:  66%|██████▌   | 109/165 [13:57<07:08,  7.65s/it]

VAE train ep19:  67%|██████▋   | 110/165 [14:05<07:01,  7.66s/it]

VAE train ep19:  67%|██████▋   | 111/165 [14:13<06:55,  7.69s/it]

VAE train ep19:  68%|██████▊   | 112/165 [14:20<06:44,  7.64s/it]

VAE train ep19:  68%|██████▊   | 113/165 [14:28<06:36,  7.62s/it]

VAE train ep19:  69%|██████▉   | 114/165 [14:35<06:28,  7.61s/it]

VAE train ep19:  70%|██████▉   | 115/165 [14:43<06:22,  7.65s/it]

VAE train ep19:  70%|███████   | 116/165 [14:51<06:18,  7.72s/it]

VAE train ep19:  71%|███████   | 117/165 [14:58<06:08,  7.68s/it]

VAE train ep19:  72%|███████▏  | 118/165 [15:06<06:00,  7.68s/it]

VAE train ep19:  72%|███████▏  | 119/165 [15:14<05:54,  7.71s/it]

VAE train ep19:  73%|███████▎  | 120/165 [15:22<05:48,  7.74s/it]

VAE train ep19:  73%|███████▎  | 121/165 [15:29<05:38,  7.70s/it]

VAE train ep19:  74%|███████▍  | 122/165 [15:37<05:32,  7.73s/it]

VAE train ep19:  75%|███████▍  | 123/165 [15:45<05:24,  7.73s/it]

VAE train ep19:  75%|███████▌  | 124/165 [15:53<05:17,  7.73s/it]

VAE train ep19:  76%|███████▌  | 125/165 [16:00<05:07,  7.69s/it]

VAE train ep19:  76%|███████▋  | 126/165 [16:08<04:57,  7.63s/it]

VAE train ep19:  77%|███████▋  | 127/165 [16:15<04:50,  7.65s/it]

VAE train ep19:  78%|███████▊  | 128/165 [16:23<04:43,  7.66s/it]

VAE train ep19:  78%|███████▊  | 129/165 [16:31<04:34,  7.63s/it]

VAE train ep19:  79%|███████▉  | 130/165 [16:38<04:27,  7.63s/it]

VAE train ep19:  79%|███████▉  | 131/165 [16:46<04:19,  7.63s/it]

VAE train ep19:  80%|████████  | 132/165 [16:54<04:13,  7.69s/it]

VAE train ep19:  81%|████████  | 133/165 [17:01<04:05,  7.66s/it]

VAE train ep19:  81%|████████  | 134/165 [17:09<03:57,  7.67s/it]

VAE train ep19:  82%|████████▏ | 135/165 [17:17<03:49,  7.65s/it]

VAE train ep19:  82%|████████▏ | 136/165 [17:24<03:42,  7.68s/it]

VAE train ep19:  83%|████████▎ | 137/165 [17:32<03:35,  7.71s/it]

VAE train ep19:  84%|████████▎ | 138/165 [17:40<03:27,  7.68s/it]

VAE train ep19:  84%|████████▍ | 139/165 [17:47<03:19,  7.68s/it]

VAE train ep19:  85%|████████▍ | 140/165 [17:55<03:11,  7.67s/it]

VAE train ep19:  85%|████████▌ | 141/165 [18:03<03:04,  7.68s/it]

VAE train ep19:  86%|████████▌ | 142/165 [18:10<02:57,  7.70s/it]

VAE train ep19:  87%|████████▋ | 143/165 [18:18<02:49,  7.68s/it]

VAE train ep19:  87%|████████▋ | 144/165 [18:26<02:40,  7.65s/it]

VAE train ep19:  88%|████████▊ | 145/165 [18:34<02:33,  7.70s/it]

VAE train ep19:  88%|████████▊ | 146/165 [18:41<02:26,  7.70s/it]

VAE train ep19:  89%|████████▉ | 147/165 [18:49<02:19,  7.73s/it]

VAE train ep19:  90%|████████▉ | 148/165 [18:57<02:11,  7.74s/it]

VAE train ep19:  90%|█████████ | 149/165 [19:04<02:03,  7.70s/it]

VAE train ep19:  91%|█████████ | 150/165 [19:12<01:56,  7.75s/it]

VAE train ep19:  92%|█████████▏| 151/165 [19:20<01:49,  7.82s/it]

VAE train ep19:  92%|█████████▏| 152/165 [19:28<01:41,  7.78s/it]

VAE train ep19:  93%|█████████▎| 153/165 [19:36<01:33,  7.76s/it]

VAE train ep19:  93%|█████████▎| 154/165 [19:43<01:25,  7.75s/it]

VAE train ep19:  94%|█████████▍| 155/165 [19:51<01:17,  7.73s/it]

VAE train ep19:  95%|█████████▍| 156/165 [19:59<01:10,  7.80s/it]

VAE train ep19:  95%|█████████▌| 157/165 [20:07<01:03,  7.88s/it]

VAE train ep19:  96%|█████████▌| 158/165 [20:15<00:55,  7.93s/it]

VAE train ep19:  96%|█████████▋| 159/165 [20:23<00:47,  7.99s/it]

VAE train ep19:  97%|█████████▋| 160/165 [20:31<00:40,  8.04s/it]

VAE train ep19:  98%|█████████▊| 161/165 [20:39<00:32,  8.05s/it]

VAE train ep19:  98%|█████████▊| 162/165 [20:47<00:23,  7.99s/it]

VAE train ep19:  99%|█████████▉| 163/165 [20:55<00:15,  7.93s/it]

VAE train ep19:  99%|█████████▉| 164/165 [21:03<00:07,  7.93s/it]

VAE train ep19: 100%|██████████| 165/165 [21:04<00:00,  5.70s/it]

VAE val ep19:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep19:   3%|▎         | 1/29 [00:02<00:58,  2.09s/it]

VAE val ep19:   7%|▋         | 2/29 [00:04<00:56,  2.10s/it]

VAE val ep19:  10%|█         | 3/29 [00:06<00:55,  2.12s/it]

VAE val ep19:  14%|█▍        | 4/29 [00:08<00:52,  2.11s/it]

VAE val ep19:  17%|█▋        | 5/29 [00:10<00:50,  2.10s/it]

VAE val ep19:  21%|██        | 6/29 [00:12<00:48,  2.09s/it]

VAE val ep19:  24%|██▍       | 7/29 [00:14<00:45,  2.08s/it]

VAE val ep19:  28%|██▊       | 8/29 [00:16<00:43,  2.08s/it]

VAE val ep19:  31%|███       | 9/29 [00:18<00:41,  2.08s/it]

VAE val ep19:  34%|███▍      | 10/29 [00:20<00:39,  2.08s/it]

VAE val ep19:  38%|███▊      | 11/29 [00:23<00:37,  2.09s/it]

VAE val ep19:  41%|████▏     | 12/29 [00:25<00:35,  2.10s/it]

VAE val ep19:  45%|████▍     | 13/29 [00:27<00:33,  2.11s/it]

VAE val ep19:  48%|████▊     | 14/29 [00:29<00:31,  2.10s/it]

VAE val ep19:  52%|█████▏    | 15/29 [00:31<00:29,  2.09s/it]

VAE val ep19:  55%|█████▌    | 16/29 [00:33<00:27,  2.08s/it]

VAE val ep19:  59%|█████▊    | 17/29 [00:35<00:24,  2.08s/it]

VAE val ep19:  62%|██████▏   | 18/29 [00:37<00:23,  2.09s/it]

VAE val ep19:  66%|██████▌   | 19/29 [00:39<00:20,  2.09s/it]

VAE val ep19:  69%|██████▉   | 20/29 [00:41<00:18,  2.09s/it]

VAE val ep19:  72%|███████▏  | 21/29 [00:43<00:16,  2.08s/it]

VAE val ep19:  76%|███████▌  | 22/29 [00:45<00:14,  2.08s/it]

VAE val ep19:  79%|███████▉  | 23/29 [00:48<00:12,  2.08s/it]

VAE val ep19:  83%|████████▎ | 24/29 [00:50<00:10,  2.08s/it]

VAE val ep19:  86%|████████▌ | 25/29 [00:52<00:08,  2.09s/it]

VAE val ep19:  90%|████████▉ | 26/29 [00:54<00:06,  2.08s/it]

VAE val ep19:  93%|█████████▎| 27/29 [00:56<00:04,  2.10s/it]

VAE val ep19:  97%|█████████▋| 28/29 [00:58<00:02,  2.09s/it]

VAE val ep19: 100%|██████████| 29/29 [00:58<00:00,  1.55s/it]

VAE train ep20:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep20:   1%|          | 1/165 [00:08<22:36,  8.27s/it]

VAE train ep20:   1%|          | 2/165 [00:16<21:50,  8.04s/it]

VAE train ep20:   2%|▏         | 3/165 [00:24<21:52,  8.10s/it]

VAE train ep20:   2%|▏         | 4/165 [00:32<21:23,  7.97s/it]

VAE train ep20:   3%|▎         | 5/165 [00:39<21:07,  7.92s/it]

VAE train ep20:   4%|▎         | 6/165 [00:47<20:51,  7.87s/it]

VAE train ep20:   4%|▍         | 7/165 [00:55<20:35,  7.82s/it]

VAE train ep20:   5%|▍         | 8/165 [01:03<20:24,  7.80s/it]

VAE train ep20:   5%|▌         | 9/165 [01:11<20:22,  7.84s/it]

VAE train ep20:   6%|▌         | 10/165 [01:18<20:15,  7.84s/it]

VAE train ep20:   7%|▋         | 11/165 [01:26<20:04,  7.82s/it]

VAE train ep20:   7%|▋         | 12/165 [01:34<20:01,  7.86s/it]

VAE train ep20:   8%|▊         | 13/165 [01:42<19:53,  7.85s/it]

VAE train ep20:   8%|▊         | 14/165 [01:50<19:35,  7.79s/it]

VAE train ep20:   9%|▉         | 15/165 [01:58<19:33,  7.82s/it]

VAE train ep20:  10%|▉         | 16/165 [02:05<19:24,  7.82s/it]

VAE train ep20:  10%|█         | 17/165 [02:13<19:22,  7.85s/it]

VAE train ep20:  11%|█         | 18/165 [02:21<19:04,  7.78s/it]

VAE train ep20:  12%|█▏        | 19/165 [02:29<18:50,  7.74s/it]

VAE train ep20:  12%|█▏        | 20/165 [02:36<18:42,  7.74s/it]

VAE train ep20:  13%|█▎        | 21/165 [02:44<18:36,  7.75s/it]

VAE train ep20:  13%|█▎        | 22/165 [02:52<18:28,  7.75s/it]

VAE train ep20:  14%|█▍        | 23/165 [02:59<18:16,  7.72s/it]

VAE train ep20:  15%|█▍        | 24/165 [03:07<18:12,  7.75s/it]

VAE train ep20:  15%|█▌        | 25/165 [03:15<18:06,  7.76s/it]

VAE train ep20:  16%|█▌        | 26/165 [03:23<17:56,  7.75s/it]

VAE train ep20:  16%|█▋        | 27/165 [03:31<17:51,  7.76s/it]

VAE train ep20:  17%|█▋        | 28/165 [03:38<17:45,  7.77s/it]

VAE train ep20:  18%|█▊        | 29/165 [03:46<17:43,  7.82s/it]

VAE train ep20:  18%|█▊        | 30/165 [03:54<17:31,  7.79s/it]

VAE train ep20:  19%|█▉        | 31/165 [04:02<17:22,  7.78s/it]

VAE train ep20:  19%|█▉        | 32/165 [04:10<17:13,  7.77s/it]

VAE train ep20:  20%|██        | 33/165 [04:17<17:08,  7.79s/it]

VAE train ep20:  21%|██        | 34/165 [04:25<16:56,  7.76s/it]

VAE train ep20:  21%|██        | 35/165 [04:33<16:42,  7.72s/it]

VAE train ep20:  22%|██▏       | 36/165 [04:40<16:36,  7.73s/it]

VAE train ep20:  22%|██▏       | 37/165 [04:48<16:32,  7.75s/it]

VAE train ep20:  23%|██▎       | 38/165 [04:56<16:22,  7.73s/it]

VAE train ep20:  24%|██▎       | 39/165 [05:04<16:14,  7.73s/it]

VAE train ep20:  24%|██▍       | 40/165 [05:11<16:03,  7.71s/it]

VAE train ep20:  25%|██▍       | 41/165 [05:19<15:57,  7.72s/it]

VAE train ep20:  25%|██▌       | 42/165 [05:27<15:44,  7.68s/it]

VAE train ep20:  26%|██▌       | 43/165 [05:34<15:39,  7.70s/it]

VAE train ep20:  27%|██▋       | 44/165 [05:42<15:32,  7.71s/it]

VAE train ep20:  27%|██▋       | 45/165 [05:50<15:28,  7.73s/it]

VAE train ep20:  28%|██▊       | 46/165 [05:58<15:20,  7.73s/it]

VAE train ep20:  28%|██▊       | 47/165 [06:05<15:04,  7.67s/it]

VAE train ep20:  29%|██▉       | 48/165 [06:13<14:57,  7.67s/it]

VAE train ep20:  30%|██▉       | 49/165 [06:21<14:50,  7.67s/it]

VAE train ep20:  30%|███       | 50/165 [06:28<14:38,  7.64s/it]

VAE train ep20:  31%|███       | 51/165 [06:36<14:29,  7.63s/it]

VAE train ep20:  32%|███▏      | 52/165 [06:43<14:18,  7.60s/it]

VAE train ep20:  32%|███▏      | 53/165 [06:51<14:13,  7.62s/it]

VAE train ep20:  33%|███▎      | 54/165 [06:59<14:10,  7.66s/it]

VAE train ep20:  33%|███▎      | 55/165 [07:07<14:10,  7.73s/it]

VAE train ep20:  34%|███▍      | 56/165 [07:15<14:13,  7.83s/it]

VAE train ep20:  35%|███▍      | 57/165 [07:22<14:08,  7.86s/it]

VAE train ep20:  35%|███▌      | 58/165 [07:31<14:05,  7.91s/it]

VAE train ep20:  36%|███▌      | 59/165 [07:39<14:01,  7.94s/it]

VAE train ep20:  36%|███▋      | 60/165 [07:46<13:49,  7.90s/it]

VAE train ep20:  37%|███▋      | 61/165 [07:54<13:39,  7.88s/it]

VAE train ep20:  38%|███▊      | 62/165 [08:02<13:30,  7.87s/it]

VAE train ep20:  38%|███▊      | 63/165 [08:10<13:27,  7.91s/it]

VAE train ep20:  39%|███▉      | 64/165 [08:18<13:17,  7.90s/it]

VAE train ep20:  39%|███▉      | 65/165 [08:26<13:12,  7.92s/it]

VAE train ep20:  40%|████      | 66/165 [08:34<12:59,  7.87s/it]

VAE train ep20:  41%|████      | 67/165 [08:41<12:48,  7.84s/it]

VAE train ep20:  41%|████      | 68/165 [08:49<12:40,  7.84s/it]

VAE train ep20:  42%|████▏     | 69/165 [08:57<12:36,  7.88s/it]

VAE train ep20:  42%|████▏     | 70/165 [09:05<12:27,  7.87s/it]

VAE train ep20:  43%|████▎     | 71/165 [09:13<12:17,  7.85s/it]

VAE train ep20:  44%|████▎     | 72/165 [09:21<12:13,  7.88s/it]

VAE train ep20:  44%|████▍     | 73/165 [09:29<12:04,  7.87s/it]

VAE train ep20:  45%|████▍     | 74/165 [09:36<11:52,  7.83s/it]

VAE train ep20:  45%|████▌     | 75/165 [09:44<11:36,  7.74s/it]

VAE train ep20:  46%|████▌     | 76/165 [09:52<11:28,  7.74s/it]

VAE train ep20:  47%|████▋     | 77/165 [09:59<11:16,  7.69s/it]

VAE train ep20:  47%|████▋     | 78/165 [10:07<11:08,  7.68s/it]

VAE train ep20:  48%|████▊     | 79/165 [10:15<10:58,  7.65s/it]

VAE train ep20:  48%|████▊     | 80/165 [10:22<10:54,  7.70s/it]

VAE train ep20:  49%|████▉     | 81/165 [10:30<10:48,  7.73s/it]

VAE train ep20:  50%|████▉     | 82/165 [10:38<10:40,  7.71s/it]

VAE train ep20:  50%|█████     | 83/165 [10:46<10:33,  7.72s/it]

VAE train ep20:  51%|█████     | 84/165 [10:53<10:28,  7.76s/it]

VAE train ep20:  52%|█████▏    | 85/165 [11:01<10:24,  7.80s/it]

VAE train ep20:  52%|█████▏    | 86/165 [11:09<10:15,  7.78s/it]

VAE train ep20:  53%|█████▎    | 87/165 [11:17<10:05,  7.77s/it]

VAE train ep20:  53%|█████▎    | 88/165 [11:25<10:00,  7.80s/it]

VAE train ep20:  54%|█████▍    | 89/165 [11:32<09:51,  7.78s/it]

VAE train ep20:  55%|█████▍    | 90/165 [11:40<09:38,  7.71s/it]

VAE train ep20:  55%|█████▌    | 91/165 [11:48<09:28,  7.68s/it]

VAE train ep20:  56%|█████▌    | 92/165 [11:55<09:22,  7.70s/it]

VAE train ep20:  56%|█████▋    | 93/165 [12:03<09:17,  7.75s/it]

VAE train ep20:  57%|█████▋    | 94/165 [12:11<09:10,  7.75s/it]

VAE train ep20:  58%|█████▊    | 95/165 [12:19<09:04,  7.78s/it]

VAE train ep20:  58%|█████▊    | 96/165 [12:26<08:55,  7.76s/it]

VAE train ep20:  59%|█████▉    | 97/165 [12:34<08:49,  7.79s/it]

VAE train ep20:  59%|█████▉    | 98/165 [12:42<08:42,  7.79s/it]

VAE train ep20:  60%|██████    | 99/165 [12:50<08:40,  7.89s/it]

VAE train ep20:  61%|██████    | 100/165 [12:58<08:32,  7.88s/it]

VAE train ep20:  61%|██████    | 101/165 [13:06<08:25,  7.90s/it]

VAE train ep20:  62%|██████▏   | 102/165 [13:14<08:18,  7.92s/it]

VAE train ep20:  62%|██████▏   | 103/165 [13:22<08:09,  7.90s/it]

VAE train ep20:  63%|██████▎   | 104/165 [13:30<08:03,  7.93s/it]

VAE train ep20:  64%|██████▎   | 105/165 [13:38<07:54,  7.91s/it]

VAE train ep20:  64%|██████▍   | 106/165 [13:46<07:46,  7.91s/it]

VAE train ep20:  65%|██████▍   | 107/165 [13:53<07:37,  7.88s/it]

VAE train ep20:  65%|██████▌   | 108/165 [14:01<07:30,  7.91s/it]

VAE train ep20:  66%|██████▌   | 109/165 [14:09<07:24,  7.93s/it]

VAE train ep20:  67%|██████▋   | 110/165 [14:17<07:15,  7.92s/it]

VAE train ep20:  67%|██████▋   | 111/165 [14:25<07:06,  7.89s/it]

VAE train ep20:  68%|██████▊   | 112/165 [14:33<06:55,  7.85s/it]

VAE train ep20:  68%|██████▊   | 113/165 [14:41<06:49,  7.88s/it]

VAE train ep20:  69%|██████▉   | 114/165 [14:49<06:42,  7.90s/it]

VAE train ep20:  70%|██████▉   | 115/165 [14:57<06:35,  7.92s/it]

VAE train ep20:  70%|███████   | 116/165 [15:05<06:26,  7.88s/it]

VAE train ep20:  71%|███████   | 117/165 [15:12<06:19,  7.90s/it]

VAE train ep20:  72%|███████▏  | 118/165 [15:20<06:11,  7.91s/it]

VAE train ep20:  72%|███████▏  | 119/165 [15:28<06:04,  7.92s/it]

VAE train ep20:  73%|███████▎  | 120/165 [15:36<05:56,  7.91s/it]

VAE train ep20:  73%|███████▎  | 121/165 [15:44<05:49,  7.93s/it]

VAE train ep20:  74%|███████▍  | 122/165 [15:52<05:41,  7.93s/it]

VAE train ep20:  75%|███████▍  | 123/165 [16:00<05:32,  7.91s/it]

VAE train ep20:  75%|███████▌  | 124/165 [16:08<05:23,  7.89s/it]

VAE train ep20:  76%|███████▌  | 125/165 [16:16<05:16,  7.91s/it]

VAE train ep20:  76%|███████▋  | 126/165 [16:24<05:07,  7.87s/it]

VAE train ep20:  77%|███████▋  | 127/165 [16:31<04:57,  7.83s/it]

VAE train ep20:  78%|███████▊  | 128/165 [16:39<04:49,  7.81s/it]

VAE train ep20:  78%|███████▊  | 129/165 [16:47<04:40,  7.80s/it]

VAE train ep20:  79%|███████▉  | 130/165 [16:55<04:33,  7.81s/it]

VAE train ep20:  79%|███████▉  | 131/165 [17:03<04:27,  7.86s/it]

VAE train ep20:  80%|████████  | 132/165 [17:11<04:19,  7.86s/it]

VAE train ep20:  81%|████████  | 133/165 [17:19<04:13,  7.93s/it]

VAE train ep20:  81%|████████  | 134/165 [17:26<04:03,  7.86s/it]

VAE train ep20:  82%|████████▏ | 135/165 [17:34<03:55,  7.84s/it]

VAE train ep20:  82%|████████▏ | 136/165 [17:42<03:46,  7.80s/it]

VAE train ep20:  83%|████████▎ | 137/165 [17:50<03:39,  7.85s/it]

VAE train ep20:  84%|████████▎ | 138/165 [17:58<03:32,  7.86s/it]

VAE train ep20:  84%|████████▍ | 139/165 [18:05<03:23,  7.82s/it]

VAE train ep20:  85%|████████▍ | 140/165 [18:14<03:18,  7.94s/it]

VAE train ep20:  85%|████████▌ | 141/165 [18:22<03:13,  8.06s/it]

VAE train ep20:  86%|████████▌ | 142/165 [18:31<03:09,  8.24s/it]

VAE train ep20:  87%|████████▋ | 143/165 [18:39<03:03,  8.35s/it]

VAE train ep20:  87%|████████▋ | 144/165 [18:48<02:57,  8.46s/it]

VAE train ep20:  88%|████████▊ | 145/165 [18:56<02:49,  8.46s/it]

VAE train ep20:  88%|████████▊ | 146/165 [19:05<02:39,  8.42s/it]

VAE train ep20:  89%|████████▉ | 147/165 [19:13<02:29,  8.28s/it]

VAE train ep20:  90%|████████▉ | 148/165 [19:21<02:20,  8.25s/it]

VAE train ep20:  90%|█████████ | 149/165 [19:29<02:11,  8.24s/it]

VAE train ep20:  91%|█████████ | 150/165 [19:37<02:03,  8.20s/it]

VAE train ep20:  92%|█████████▏| 151/165 [19:45<01:54,  8.19s/it]

VAE train ep20:  92%|█████████▏| 152/165 [19:53<01:46,  8.16s/it]

VAE train ep20:  93%|█████████▎| 153/165 [20:02<01:37,  8.17s/it]

VAE train ep20:  93%|█████████▎| 154/165 [20:10<01:30,  8.19s/it]

VAE train ep20:  94%|█████████▍| 155/165 [20:18<01:21,  8.18s/it]

VAE train ep20:  95%|█████████▍| 156/165 [20:26<01:12,  8.09s/it]

VAE train ep20:  95%|█████████▌| 157/165 [20:34<01:04,  8.06s/it]

VAE train ep20:  96%|█████████▌| 158/165 [20:42<00:56,  8.05s/it]

VAE train ep20:  96%|█████████▋| 159/165 [20:50<00:48,  8.15s/it]

VAE train ep20:  97%|█████████▋| 160/165 [20:59<00:41,  8.22s/it]

VAE train ep20:  98%|█████████▊| 161/165 [21:07<00:32,  8.24s/it]

VAE train ep20:  98%|█████████▊| 162/165 [21:15<00:24,  8.19s/it]

VAE train ep20:  99%|█████████▉| 163/165 [21:23<00:16,  8.16s/it]

VAE train ep20:  99%|█████████▉| 164/165 [21:31<00:08,  8.18s/it]

VAE train ep20: 100%|██████████| 165/165 [21:32<00:00,  5.91s/it]

VAE val ep20:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep20:   3%|▎         | 1/29 [00:02<01:02,  2.23s/it]

VAE val ep20:   7%|▋         | 2/29 [00:04<00:59,  2.20s/it]

VAE val ep20:  10%|█         | 3/29 [00:06<00:57,  2.19s/it]

VAE val ep20:  14%|█▍        | 4/29 [00:08<00:54,  2.17s/it]

VAE val ep20:  17%|█▋        | 5/29 [00:10<00:51,  2.15s/it]

VAE val ep20:  21%|██        | 6/29 [00:12<00:49,  2.15s/it]

VAE val ep20:  24%|██▍       | 7/29 [00:15<00:47,  2.15s/it]

VAE val ep20:  28%|██▊       | 8/29 [00:17<00:44,  2.14s/it]

VAE val ep20:  31%|███       | 9/29 [00:19<00:42,  2.13s/it]

VAE val ep20:  34%|███▍      | 10/29 [00:21<00:40,  2.12s/it]

VAE val ep20:  38%|███▊      | 11/29 [00:23<00:37,  2.10s/it]

VAE val ep20:  41%|████▏     | 12/29 [00:25<00:36,  2.12s/it]

VAE val ep20:  45%|████▍     | 13/29 [00:27<00:33,  2.12s/it]

VAE val ep20:  48%|████▊     | 14/29 [00:29<00:31,  2.13s/it]

VAE val ep20:  52%|█████▏    | 15/29 [00:32<00:30,  2.15s/it]

VAE val ep20:  55%|█████▌    | 16/29 [00:34<00:27,  2.14s/it]

VAE val ep20:  59%|█████▊    | 17/29 [00:36<00:25,  2.16s/it]

VAE val ep20:  62%|██████▏   | 18/29 [00:38<00:23,  2.16s/it]

VAE val ep20:  66%|██████▌   | 19/29 [00:40<00:21,  2.16s/it]

VAE val ep20:  69%|██████▉   | 20/29 [00:42<00:19,  2.16s/it]

VAE val ep20:  72%|███████▏  | 21/29 [00:45<00:17,  2.17s/it]

VAE val ep20:  76%|███████▌  | 22/29 [00:47<00:15,  2.16s/it]

VAE val ep20:  79%|███████▉  | 23/29 [00:49<00:12,  2.15s/it]

VAE val ep20:  83%|████████▎ | 24/29 [00:51<00:10,  2.15s/it]

VAE val ep20:  86%|████████▌ | 25/29 [00:53<00:08,  2.14s/it]

VAE val ep20:  90%|████████▉ | 26/29 [00:55<00:06,  2.14s/it]

VAE val ep20:  93%|█████████▎| 27/29 [00:57<00:04,  2.14s/it]

VAE val ep20:  97%|█████████▋| 28/29 [01:00<00:02,  2.14s/it]

VAE val ep20: 100%|██████████| 29/29 [01:00<00:00,  1.59s/it]

VAE train ep21:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep21:   1%|          | 1/165 [00:08<23:01,  8.42s/it]

VAE train ep21:   1%|          | 2/165 [00:16<22:35,  8.32s/it]

VAE train ep21:   2%|▏         | 3/165 [00:24<22:13,  8.23s/it]

VAE train ep21:   2%|▏         | 4/165 [00:32<21:57,  8.18s/it]

VAE train ep21:   3%|▎         | 5/165 [00:40<21:34,  8.09s/it]

VAE train ep21:   4%|▎         | 6/165 [00:48<21:22,  8.07s/it]

VAE train ep21:   4%|▍         | 7/165 [00:56<20:57,  7.96s/it]

VAE train ep21:   5%|▍         | 8/165 [01:04<20:49,  7.96s/it]

VAE train ep21:   5%|▌         | 9/165 [01:12<20:44,  7.98s/it]

VAE train ep21:   6%|▌         | 10/165 [01:20<20:41,  8.01s/it]

VAE train ep21:   7%|▋         | 11/165 [01:28<20:32,  8.00s/it]

VAE train ep21:   7%|▋         | 12/165 [01:36<20:21,  7.98s/it]

VAE train ep21:   8%|▊         | 13/165 [01:44<20:11,  7.97s/it]

VAE train ep21:   8%|▊         | 14/165 [01:52<20:04,  7.97s/it]

VAE train ep21:   9%|▉         | 15/165 [02:00<19:52,  7.95s/it]

VAE train ep21:  10%|▉         | 16/165 [02:08<19:37,  7.91s/it]

VAE train ep21:  10%|█         | 17/165 [02:16<19:37,  7.96s/it]

VAE train ep21:  11%|█         | 18/165 [02:24<19:24,  7.92s/it]

VAE train ep21:  12%|█▏        | 19/165 [02:32<19:16,  7.92s/it]

VAE train ep21:  12%|█▏        | 20/165 [02:40<19:12,  7.95s/it]

VAE train ep21:  13%|█▎        | 21/165 [02:48<19:08,  7.98s/it]

VAE train ep21:  13%|█▎        | 22/165 [02:55<18:53,  7.93s/it]

VAE train ep21:  14%|█▍        | 23/165 [03:03<18:41,  7.90s/it]

VAE train ep21:  15%|█▍        | 24/165 [03:11<18:32,  7.89s/it]

VAE train ep21:  15%|█▌        | 25/165 [03:19<18:28,  7.92s/it]

VAE train ep21:  16%|█▌        | 26/165 [03:27<18:25,  7.95s/it]

VAE train ep21:  16%|█▋        | 27/165 [03:35<18:16,  7.95s/it]

VAE train ep21:  17%|█▋        | 28/165 [03:43<18:06,  7.93s/it]

VAE train ep21:  18%|█▊        | 29/165 [03:51<18:06,  7.99s/it]

VAE train ep21:  18%|█▊        | 30/165 [03:59<17:53,  7.95s/it]

VAE train ep21:  19%|█▉        | 31/165 [04:07<17:37,  7.89s/it]

VAE train ep21:  19%|█▉        | 32/165 [04:15<17:31,  7.91s/it]

VAE train ep21:  20%|██        | 33/165 [04:23<17:26,  7.93s/it]

VAE train ep21:  21%|██        | 34/165 [04:31<17:22,  7.96s/it]

VAE train ep21:  21%|██        | 35/165 [04:39<17:22,  8.02s/it]

VAE train ep21:  22%|██▏       | 36/165 [04:47<17:18,  8.05s/it]

VAE train ep21:  22%|██▏       | 37/165 [04:55<17:13,  8.07s/it]

VAE train ep21:  23%|██▎       | 38/165 [05:03<17:06,  8.08s/it]

VAE train ep21:  24%|██▎       | 39/165 [05:11<16:52,  8.03s/it]

VAE train ep21:  24%|██▍       | 40/165 [05:19<16:40,  8.00s/it]

VAE train ep21:  25%|██▍       | 41/165 [05:27<16:28,  7.97s/it]

VAE train ep21:  25%|██▌       | 42/165 [05:35<16:19,  7.96s/it]

VAE train ep21:  26%|██▌       | 43/165 [05:43<16:12,  7.97s/it]

VAE train ep21:  27%|██▋       | 44/165 [05:51<16:07,  8.00s/it]

VAE train ep21:  27%|██▋       | 45/165 [05:59<16:04,  8.04s/it]

VAE train ep21:  28%|██▊       | 46/165 [06:07<16:02,  8.09s/it]

VAE train ep21:  28%|██▊       | 47/165 [06:15<16:00,  8.14s/it]

VAE train ep21:  29%|██▉       | 48/165 [06:24<16:00,  8.21s/it]

VAE train ep21:  30%|██▉       | 49/165 [06:32<15:58,  8.26s/it]

VAE train ep21:  30%|███       | 50/165 [06:40<15:39,  8.17s/it]

VAE train ep21:  31%|███       | 51/165 [06:48<15:27,  8.14s/it]

VAE train ep21:  32%|███▏      | 52/165 [06:56<15:13,  8.08s/it]

VAE train ep21:  32%|███▏      | 53/165 [07:04<15:02,  8.06s/it]

VAE train ep21:  33%|███▎      | 54/165 [07:12<14:57,  8.09s/it]

VAE train ep21:  33%|███▎      | 55/165 [07:20<14:45,  8.05s/it]

VAE train ep21:  34%|███▍      | 56/165 [07:28<14:39,  8.07s/it]

VAE train ep21:  35%|███▍      | 57/165 [07:36<14:31,  8.07s/it]

VAE train ep21:  35%|███▌      | 58/165 [07:45<14:26,  8.10s/it]

VAE train ep21:  36%|███▌      | 59/165 [07:52<14:08,  8.00s/it]

VAE train ep21:  36%|███▋      | 60/165 [08:00<14:00,  8.00s/it]

VAE train ep21:  37%|███▋      | 61/165 [08:08<13:51,  8.00s/it]

VAE train ep21:  38%|███▊      | 62/165 [08:16<13:44,  8.01s/it]

VAE train ep21:  38%|███▊      | 63/165 [08:25<13:40,  8.04s/it]

VAE train ep21:  39%|███▉      | 64/165 [08:33<13:29,  8.01s/it]

VAE train ep21:  39%|███▉      | 65/165 [08:40<13:19,  8.00s/it]

VAE train ep21:  40%|████      | 66/165 [08:48<13:11,  8.00s/it]

VAE train ep21:  41%|████      | 67/165 [08:56<12:59,  7.95s/it]

VAE train ep21:  41%|████      | 68/165 [09:04<12:48,  7.92s/it]

VAE train ep21:  42%|████▏     | 69/165 [09:12<12:40,  7.93s/it]

VAE train ep21:  42%|████▏     | 70/165 [09:20<12:31,  7.91s/it]

VAE train ep21:  43%|████▎     | 71/165 [09:28<12:28,  7.96s/it]

VAE train ep21:  44%|████▎     | 72/165 [09:36<12:23,  8.00s/it]

VAE train ep21:  44%|████▍     | 73/165 [09:44<12:17,  8.01s/it]

VAE train ep21:  45%|████▍     | 74/165 [09:52<12:04,  7.96s/it]

VAE train ep21:  45%|████▌     | 75/165 [10:00<11:54,  7.93s/it]

VAE train ep21:  46%|████▌     | 76/165 [10:08<11:46,  7.94s/it]

VAE train ep21:  47%|████▋     | 77/165 [10:16<11:42,  7.99s/it]

VAE train ep21:  47%|████▋     | 78/165 [10:24<11:32,  7.96s/it]

VAE train ep21:  48%|████▊     | 79/165 [10:32<11:27,  7.99s/it]

VAE train ep21:  48%|████▊     | 80/165 [10:40<11:22,  8.02s/it]

VAE train ep21:  49%|████▉     | 81/165 [10:48<11:15,  8.04s/it]

VAE train ep21:  50%|████▉     | 82/165 [10:56<11:05,  8.02s/it]

VAE train ep21:  50%|█████     | 83/165 [11:04<10:59,  8.04s/it]

VAE train ep21:  51%|█████     | 84/165 [11:12<10:45,  7.97s/it]

VAE train ep21:  52%|█████▏    | 85/165 [11:20<10:37,  7.96s/it]

VAE train ep21:  52%|█████▏    | 86/165 [11:28<10:28,  7.96s/it]

VAE train ep21:  53%|█████▎    | 87/165 [11:36<10:14,  7.88s/it]

VAE train ep21:  53%|█████▎    | 88/165 [11:43<10:05,  7.86s/it]

VAE train ep21:  54%|█████▍    | 89/165 [11:51<09:59,  7.88s/it]

VAE train ep21:  55%|█████▍    | 90/165 [11:59<09:47,  7.84s/it]

VAE train ep21:  55%|█████▌    | 91/165 [12:07<09:40,  7.84s/it]

VAE train ep21:  56%|█████▌    | 92/165 [12:15<09:34,  7.88s/it]

VAE train ep21:  56%|█████▋    | 93/165 [12:23<09:28,  7.90s/it]

VAE train ep21:  57%|█████▋    | 94/165 [12:31<09:21,  7.90s/it]

VAE train ep21:  58%|█████▊    | 95/165 [12:39<09:12,  7.89s/it]

VAE train ep21:  58%|█████▊    | 96/165 [12:47<09:12,  8.00s/it]

VAE train ep21:  59%|█████▉    | 97/165 [12:55<09:06,  8.04s/it]

VAE train ep21:  59%|█████▉    | 98/165 [13:03<08:54,  7.98s/it]

VAE train ep21:  60%|██████    | 99/165 [13:11<08:45,  7.96s/it]

VAE train ep21:  61%|██████    | 100/165 [13:19<08:40,  8.00s/it]

VAE train ep21:  61%|██████    | 101/165 [13:27<08:32,  8.00s/it]

VAE train ep21:  62%|██████▏   | 102/165 [13:35<08:27,  8.05s/it]

VAE train ep21:  62%|██████▏   | 103/165 [13:43<08:19,  8.05s/it]

VAE train ep21:  63%|██████▎   | 104/165 [13:51<08:08,  8.02s/it]

VAE train ep21:  64%|██████▎   | 105/165 [13:59<07:56,  7.94s/it]

VAE train ep21:  64%|██████▍   | 106/165 [14:07<07:46,  7.90s/it]

VAE train ep21:  65%|██████▍   | 107/165 [14:14<07:36,  7.87s/it]

VAE train ep21:  65%|██████▌   | 108/165 [14:22<07:30,  7.91s/it]

VAE train ep21:  66%|██████▌   | 109/165 [14:30<07:25,  7.96s/it]

VAE train ep21:  67%|██████▋   | 110/165 [14:38<07:18,  7.97s/it]

VAE train ep21:  67%|██████▋   | 111/165 [14:46<07:06,  7.90s/it]

VAE train ep21:  68%|██████▊   | 112/165 [14:54<06:56,  7.85s/it]

VAE train ep21:  68%|██████▊   | 113/165 [15:02<06:48,  7.85s/it]

VAE train ep21:  69%|██████▉   | 114/165 [15:09<06:38,  7.81s/it]

VAE train ep21:  70%|██████▉   | 115/165 [15:17<06:31,  7.84s/it]

VAE train ep21:  70%|███████   | 116/165 [15:25<06:23,  7.83s/it]

VAE train ep21:  71%|███████   | 117/165 [15:33<06:15,  7.82s/it]

VAE train ep21:  72%|███████▏  | 118/165 [15:41<06:05,  7.78s/it]

VAE train ep21:  72%|███████▏  | 119/165 [15:48<05:58,  7.79s/it]

VAE train ep21:  73%|███████▎  | 120/165 [15:56<05:50,  7.80s/it]

VAE train ep21:  73%|███████▎  | 121/165 [16:04<05:44,  7.82s/it]

VAE train ep21:  74%|███████▍  | 122/165 [16:12<05:33,  7.75s/it]

VAE train ep21:  75%|███████▍  | 123/165 [16:20<05:25,  7.76s/it]

VAE train ep21:  75%|███████▌  | 124/165 [16:27<05:17,  7.75s/it]

VAE train ep21:  76%|███████▌  | 125/165 [16:35<05:12,  7.82s/it]

VAE train ep21:  76%|███████▋  | 126/165 [16:43<05:05,  7.82s/it]

VAE train ep21:  77%|███████▋  | 127/165 [16:51<04:58,  7.84s/it]

VAE train ep21:  78%|███████▊  | 128/165 [16:59<04:51,  7.87s/it]

VAE train ep21:  78%|███████▊  | 129/165 [17:07<04:45,  7.94s/it]

VAE train ep21:  79%|███████▉  | 130/165 [17:15<04:39,  7.99s/it]

VAE train ep21:  79%|███████▉  | 131/165 [17:23<04:34,  8.08s/it]

VAE train ep21:  80%|████████  | 132/165 [17:32<04:31,  8.22s/it]

VAE train ep21:  81%|████████  | 133/165 [17:41<04:26,  8.34s/it]

VAE train ep21:  81%|████████  | 134/165 [17:49<04:18,  8.35s/it]

VAE train ep21:  82%|████████▏ | 135/165 [17:57<04:10,  8.36s/it]

VAE train ep21:  82%|████████▏ | 136/165 [18:06<04:04,  8.43s/it]

VAE train ep21:  83%|████████▎ | 137/165 [18:15<03:59,  8.54s/it]

VAE train ep21:  84%|████████▎ | 138/165 [18:23<03:49,  8.49s/it]

VAE train ep21:  84%|████████▍ | 139/165 [18:31<03:38,  8.39s/it]

VAE train ep21:  85%|████████▍ | 140/165 [18:39<03:28,  8.33s/it]

VAE train ep21:  85%|████████▌ | 141/165 [18:48<03:21,  8.40s/it]

VAE train ep21:  86%|████████▌ | 142/165 [18:56<03:11,  8.34s/it]

VAE train ep21:  87%|████████▋ | 143/165 [19:04<03:03,  8.32s/it]

VAE train ep21:  87%|████████▋ | 144/165 [19:13<02:53,  8.24s/it]

VAE train ep21:  88%|████████▊ | 145/165 [19:21<02:45,  8.26s/it]

VAE train ep21:  88%|████████▊ | 146/165 [19:29<02:36,  8.21s/it]

VAE train ep21:  89%|████████▉ | 147/165 [19:37<02:27,  8.18s/it]

VAE train ep21:  90%|████████▉ | 148/165 [19:45<02:20,  8.26s/it]

VAE train ep21:  90%|█████████ | 149/165 [19:54<02:11,  8.24s/it]

VAE train ep21:  91%|█████████ | 150/165 [20:02<02:02,  8.18s/it]

VAE train ep21:  92%|█████████▏| 151/165 [20:10<01:54,  8.17s/it]

VAE train ep21:  92%|█████████▏| 152/165 [20:18<01:46,  8.17s/it]

VAE train ep21:  93%|█████████▎| 153/165 [20:26<01:38,  8.22s/it]

VAE train ep21:  93%|█████████▎| 154/165 [20:34<01:29,  8.18s/it]

VAE train ep21:  94%|█████████▍| 155/165 [20:43<01:21,  8.17s/it]

VAE train ep21:  95%|█████████▍| 156/165 [20:51<01:13,  8.13s/it]

VAE train ep21:  95%|█████████▌| 157/165 [20:59<01:05,  8.20s/it]

VAE train ep21:  96%|█████████▌| 158/165 [21:07<00:57,  8.22s/it]

VAE train ep21:  96%|█████████▋| 159/165 [21:15<00:49,  8.20s/it]

VAE train ep21:  97%|█████████▋| 160/165 [21:23<00:40,  8.15s/it]

VAE train ep21:  98%|█████████▊| 161/165 [21:32<00:32,  8.18s/it]

VAE train ep21:  98%|█████████▊| 162/165 [21:40<00:24,  8.17s/it]

VAE train ep21:  99%|█████████▉| 163/165 [21:48<00:16,  8.14s/it]

VAE train ep21:  99%|█████████▉| 164/165 [21:56<00:08,  8.11s/it]

VAE train ep21: 100%|██████████| 165/165 [21:56<00:00,  5.84s/it]

VAE val ep21:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep21:   3%|▎         | 1/29 [00:02<01:01,  2.19s/it]

VAE val ep21:   7%|▋         | 2/29 [00:04<00:58,  2.18s/it]

VAE val ep21:  10%|█         | 3/29 [00:06<00:57,  2.20s/it]

VAE val ep21:  14%|█▍        | 4/29 [00:08<00:55,  2.21s/it]

VAE val ep21:  17%|█▋        | 5/29 [00:10<00:52,  2.18s/it]

VAE val ep21:  21%|██        | 6/29 [00:13<00:50,  2.18s/it]

VAE val ep21:  24%|██▍       | 7/29 [00:15<00:47,  2.17s/it]

VAE val ep21:  28%|██▊       | 8/29 [00:17<00:45,  2.19s/it]

VAE val ep21:  31%|███       | 9/29 [00:19<00:44,  2.20s/it]

VAE val ep21:  34%|███▍      | 10/29 [00:21<00:42,  2.22s/it]

VAE val ep21:  38%|███▊      | 11/29 [00:24<00:39,  2.21s/it]

VAE val ep21:  41%|████▏     | 12/29 [00:26<00:37,  2.20s/it]

VAE val ep21:  45%|████▍     | 13/29 [00:28<00:35,  2.20s/it]

VAE val ep21:  48%|████▊     | 14/29 [00:30<00:32,  2.19s/it]

VAE val ep21:  52%|█████▏    | 15/29 [00:32<00:30,  2.21s/it]

VAE val ep21:  55%|█████▌    | 16/29 [00:35<00:28,  2.20s/it]

VAE val ep21:  59%|█████▊    | 17/29 [00:37<00:26,  2.19s/it]

VAE val ep21:  62%|██████▏   | 18/29 [00:39<00:24,  2.20s/it]

VAE val ep21:  66%|██████▌   | 19/29 [00:41<00:21,  2.18s/it]

VAE val ep21:  69%|██████▉   | 20/29 [00:43<00:19,  2.17s/it]

VAE val ep21:  72%|███████▏  | 21/29 [00:46<00:17,  2.18s/it]

VAE val ep21:  76%|███████▌  | 22/29 [00:48<00:15,  2.17s/it]

VAE val ep21:  79%|███████▉  | 23/29 [00:50<00:12,  2.16s/it]

VAE val ep21:  83%|████████▎ | 24/29 [00:52<00:10,  2.14s/it]

VAE val ep21:  86%|████████▌ | 25/29 [00:54<00:08,  2.14s/it]

VAE val ep21:  90%|████████▉ | 26/29 [00:56<00:06,  2.15s/it]

VAE val ep21:  93%|█████████▎| 27/29 [00:58<00:04,  2.17s/it]

VAE val ep21:  97%|█████████▋| 28/29 [01:01<00:02,  2.18s/it]

VAE val ep21: 100%|██████████| 29/29 [01:01<00:00,  1.64s/it]

VAE train ep22:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep22:   1%|          | 1/165 [00:08<23:03,  8.44s/it]

VAE train ep22:   1%|          | 2/165 [00:16<22:48,  8.40s/it]

VAE train ep22:   2%|▏         | 3/165 [00:25<22:34,  8.36s/it]

VAE train ep22:   2%|▏         | 4/165 [00:33<22:18,  8.31s/it]

VAE train ep22:   3%|▎         | 5/165 [00:41<22:14,  8.34s/it]

VAE train ep22:   4%|▎         | 6/165 [00:49<21:58,  8.29s/it]

VAE train ep22:   4%|▍         | 7/165 [00:57<21:33,  8.19s/it]

VAE train ep22:   5%|▍         | 8/165 [01:05<21:12,  8.11s/it]

VAE train ep22:   5%|▌         | 9/165 [01:14<21:06,  8.12s/it]

VAE train ep22:   6%|▌         | 10/165 [01:22<21:08,  8.19s/it]

VAE train ep22:   7%|▋         | 11/165 [01:30<21:00,  8.18s/it]

VAE train ep22:   7%|▋         | 12/165 [01:38<20:40,  8.11s/it]

VAE train ep22:   8%|▊         | 13/165 [01:46<20:32,  8.11s/it]

VAE train ep22:   8%|▊         | 14/165 [01:54<20:16,  8.06s/it]

VAE train ep22:   9%|▉         | 15/165 [02:02<20:15,  8.11s/it]

VAE train ep22:  10%|▉         | 16/165 [02:10<20:06,  8.10s/it]

VAE train ep22:  10%|█         | 17/165 [02:18<19:55,  8.08s/it]

VAE train ep22:  11%|█         | 18/165 [02:26<19:42,  8.05s/it]

VAE train ep22:  12%|█▏        | 19/165 [02:34<19:30,  8.02s/it]

VAE train ep22:  12%|█▏        | 20/165 [02:42<19:27,  8.05s/it]

VAE train ep22:  13%|█▎        | 21/165 [02:50<19:12,  8.00s/it]

VAE train ep22:  13%|█▎        | 22/165 [02:58<19:00,  7.98s/it]

VAE train ep22:  14%|█▍        | 23/165 [03:06<18:46,  7.94s/it]

VAE train ep22:  15%|█▍        | 24/165 [03:14<18:45,  7.98s/it]

VAE train ep22:  15%|█▌        | 25/165 [03:22<18:52,  8.09s/it]

VAE train ep22:  16%|█▌        | 26/165 [03:31<18:57,  8.18s/it]

VAE train ep22:  16%|█▋        | 27/165 [03:39<18:51,  8.20s/it]

VAE train ep22:  17%|█▋        | 28/165 [03:47<18:45,  8.22s/it]

VAE train ep22:  18%|█▊        | 29/165 [03:56<18:42,  8.26s/it]

VAE train ep22:  18%|█▊        | 30/165 [04:04<18:27,  8.20s/it]

VAE train ep22:  19%|█▉        | 31/165 [04:12<18:10,  8.14s/it]

VAE train ep22:  19%|█▉        | 32/165 [04:20<17:54,  8.08s/it]

VAE train ep22:  20%|██        | 33/165 [04:28<17:54,  8.14s/it]

VAE train ep22:  21%|██        | 34/165 [04:36<17:49,  8.16s/it]

VAE train ep22:  21%|██        | 35/165 [04:44<17:39,  8.15s/it]

VAE train ep22:  22%|██▏       | 36/165 [04:52<17:23,  8.09s/it]

VAE train ep22:  22%|██▏       | 37/165 [05:00<17:09,  8.05s/it]

VAE train ep22:  23%|██▎       | 38/165 [05:09<17:11,  8.12s/it]

VAE train ep22:  24%|██▎       | 39/165 [05:17<17:01,  8.10s/it]

VAE train ep22:  24%|██▍       | 40/165 [05:25<16:54,  8.12s/it]

VAE train ep22:  25%|██▍       | 41/165 [05:33<16:50,  8.15s/it]

VAE train ep22:  25%|██▌       | 42/165 [05:41<16:47,  8.19s/it]

VAE train ep22:  26%|██▌       | 43/165 [05:50<16:45,  8.24s/it]

VAE train ep22:  27%|██▋       | 44/165 [05:58<16:45,  8.31s/it]

VAE train ep22:  27%|██▋       | 45/165 [06:06<16:30,  8.25s/it]

VAE train ep22:  28%|██▊       | 46/165 [06:14<16:10,  8.16s/it]

VAE train ep22:  28%|██▊       | 47/165 [06:22<15:56,  8.10s/it]

VAE train ep22:  29%|██▉       | 48/165 [06:30<15:45,  8.08s/it]

VAE train ep22:  30%|██▉       | 49/165 [06:38<15:46,  8.16s/it]

VAE train ep22:  30%|███       | 50/165 [06:47<15:45,  8.22s/it]

VAE train ep22:  31%|███       | 51/165 [06:55<15:46,  8.30s/it]

VAE train ep22:  32%|███▏      | 52/165 [07:04<15:35,  8.28s/it]

VAE train ep22:  32%|███▏      | 53/165 [07:12<15:26,  8.27s/it]

VAE train ep22:  33%|███▎      | 54/165 [07:20<15:18,  8.27s/it]

VAE train ep22:  33%|███▎      | 55/165 [07:29<15:14,  8.32s/it]

VAE train ep22:  34%|███▍      | 56/165 [07:37<15:09,  8.35s/it]

VAE train ep22:  35%|███▍      | 57/165 [07:45<15:02,  8.35s/it]

VAE train ep22:  35%|███▌      | 58/165 [07:54<14:49,  8.32s/it]

VAE train ep22:  36%|███▌      | 59/165 [08:02<14:39,  8.29s/it]

VAE train ep22:  36%|███▋      | 60/165 [08:10<14:29,  8.28s/it]

VAE train ep22:  37%|███▋      | 61/165 [08:18<14:17,  8.24s/it]

VAE train ep22:  38%|███▊      | 62/165 [08:27<14:16,  8.31s/it]

VAE train ep22:  38%|███▊      | 63/165 [08:35<14:19,  8.43s/it]

VAE train ep22:  39%|███▉      | 64/165 [08:44<14:10,  8.42s/it]

VAE train ep22:  39%|███▉      | 65/165 [08:52<14:09,  8.50s/it]

VAE train ep22:  40%|████      | 66/165 [09:01<13:59,  8.48s/it]

VAE train ep22:  41%|████      | 67/165 [09:09<13:43,  8.41s/it]

VAE train ep22:  41%|████      | 68/165 [09:17<13:25,  8.30s/it]

VAE train ep22:  42%|████▏     | 69/165 [09:25<13:12,  8.26s/it]

VAE train ep22:  42%|████▏     | 70/165 [09:34<13:08,  8.30s/it]

VAE train ep22:  43%|████▎     | 71/165 [09:42<13:00,  8.30s/it]

VAE train ep22:  44%|████▎     | 72/165 [09:50<12:52,  8.30s/it]

VAE train ep22:  44%|████▍     | 73/165 [09:59<12:42,  8.29s/it]

VAE train ep22:  45%|████▍     | 74/165 [10:07<12:29,  8.23s/it]

VAE train ep22:  45%|████▌     | 75/165 [10:15<12:15,  8.17s/it]

VAE train ep22:  46%|████▌     | 76/165 [10:23<12:13,  8.24s/it]

VAE train ep22:  47%|████▋     | 77/165 [10:31<12:04,  8.24s/it]

VAE train ep22:  47%|████▋     | 78/165 [10:40<11:57,  8.24s/it]

VAE train ep22:  48%|████▊     | 79/165 [10:48<11:58,  8.35s/it]

VAE train ep22:  48%|████▊     | 80/165 [10:57<11:53,  8.40s/it]

VAE train ep22:  49%|████▉     | 81/165 [11:05<11:46,  8.41s/it]

VAE train ep22:  50%|████▉     | 82/165 [11:14<11:38,  8.42s/it]

VAE train ep22:  50%|█████     | 83/165 [11:22<11:26,  8.38s/it]

VAE train ep22:  51%|█████     | 84/165 [11:30<11:22,  8.42s/it]

VAE train ep22:  52%|█████▏    | 85/165 [11:39<11:21,  8.52s/it]

VAE train ep22:  52%|█████▏    | 86/165 [11:48<11:11,  8.51s/it]

VAE train ep22:  53%|█████▎    | 87/165 [11:56<11:01,  8.48s/it]

VAE train ep22:  53%|█████▎    | 88/165 [12:04<10:47,  8.40s/it]

VAE train ep22:  54%|█████▍    | 89/165 [12:13<10:39,  8.42s/it]

VAE train ep22:  55%|█████▍    | 90/165 [12:21<10:30,  8.41s/it]

VAE train ep22:  55%|█████▌    | 91/165 [12:30<10:26,  8.46s/it]

VAE train ep22:  56%|█████▌    | 92/165 [12:38<10:22,  8.53s/it]

VAE train ep22:  56%|█████▋    | 93/165 [12:47<10:14,  8.53s/it]

VAE train ep22:  57%|█████▋    | 94/165 [12:56<10:10,  8.60s/it]

VAE train ep22:  58%|█████▊    | 95/165 [13:04<09:55,  8.50s/it]

VAE train ep22:  58%|█████▊    | 96/165 [13:12<09:40,  8.42s/it]

VAE train ep22:  59%|█████▉    | 97/165 [13:21<09:31,  8.40s/it]

VAE train ep22:  59%|█████▉    | 98/165 [13:29<09:26,  8.46s/it]

VAE train ep22:  60%|██████    | 99/165 [13:38<09:23,  8.54s/it]

VAE train ep22:  61%|██████    | 100/165 [13:46<09:14,  8.53s/it]

VAE train ep22:  61%|██████    | 101/165 [13:55<09:04,  8.50s/it]

VAE train ep22:  62%|██████▏   | 102/165 [14:03<08:55,  8.51s/it]

VAE train ep22:  62%|██████▏   | 103/165 [14:12<08:44,  8.46s/it]

VAE train ep22:  63%|██████▎   | 104/165 [14:20<08:38,  8.49s/it]

VAE train ep22:  64%|██████▎   | 105/165 [14:29<08:29,  8.50s/it]

VAE train ep22:  64%|██████▍   | 106/165 [14:37<08:21,  8.49s/it]

VAE train ep22:  65%|██████▍   | 107/165 [14:46<08:12,  8.49s/it]

VAE train ep22:  65%|██████▌   | 108/165 [14:54<08:01,  8.45s/it]

VAE train ep22:  66%|██████▌   | 109/165 [15:03<07:53,  8.46s/it]

VAE train ep22:  67%|██████▋   | 110/165 [15:11<07:44,  8.44s/it]

VAE train ep22:  67%|██████▋   | 111/165 [15:19<07:34,  8.41s/it]

VAE train ep22:  68%|██████▊   | 112/165 [15:28<07:29,  8.48s/it]

VAE train ep22:  68%|██████▊   | 113/165 [15:37<07:23,  8.54s/it]

VAE train ep22:  69%|██████▉   | 114/165 [15:45<07:14,  8.52s/it]

VAE train ep22:  70%|██████▉   | 115/165 [15:53<07:03,  8.48s/it]

VAE train ep22:  70%|███████   | 116/165 [16:02<06:54,  8.46s/it]

VAE train ep22:  71%|███████   | 117/165 [16:10<06:47,  8.48s/it]

VAE train ep22:  72%|███████▏  | 118/165 [16:19<06:40,  8.51s/it]

VAE train ep22:  72%|███████▏  | 119/165 [16:28<06:32,  8.54s/it]

VAE train ep22:  73%|███████▎  | 120/165 [16:36<06:22,  8.50s/it]

VAE train ep22:  73%|███████▎  | 121/165 [16:45<06:15,  8.53s/it]

VAE train ep22:  74%|███████▍  | 122/165 [16:53<06:05,  8.49s/it]

VAE train ep22:  75%|███████▍  | 123/165 [17:01<05:54,  8.44s/it]

VAE train ep22:  75%|███████▌  | 124/165 [17:10<05:45,  8.42s/it]

VAE train ep22:  76%|███████▌  | 125/165 [17:18<05:37,  8.44s/it]

VAE train ep22:  76%|███████▋  | 126/165 [17:27<05:30,  8.47s/it]

VAE train ep22:  77%|███████▋  | 127/165 [17:35<05:22,  8.48s/it]

VAE train ep22:  78%|███████▊  | 128/165 [17:44<05:12,  8.44s/it]

VAE train ep22:  78%|███████▊  | 129/165 [17:52<05:05,  8.49s/it]

VAE train ep22:  79%|███████▉  | 130/165 [18:01<04:55,  8.45s/it]

VAE train ep22:  79%|███████▉  | 131/165 [18:09<04:48,  8.48s/it]

VAE train ep22:  80%|████████  | 132/165 [18:18<04:39,  8.48s/it]

VAE train ep22:  81%|████████  | 133/165 [18:26<04:32,  8.51s/it]

VAE train ep22:  81%|████████  | 134/165 [18:35<04:23,  8.49s/it]

VAE train ep22:  82%|████████▏ | 135/165 [18:43<04:14,  8.50s/it]

VAE train ep22:  82%|████████▏ | 136/165 [18:52<04:07,  8.54s/it]

VAE train ep22:  83%|████████▎ | 137/165 [19:00<03:59,  8.57s/it]

VAE train ep22:  84%|████████▎ | 138/165 [19:09<03:49,  8.50s/it]

VAE train ep22:  84%|████████▍ | 139/165 [19:17<03:41,  8.53s/it]

VAE train ep22:  85%|████████▍ | 140/165 [19:26<03:34,  8.57s/it]

VAE train ep22:  85%|████████▌ | 141/165 [19:35<03:25,  8.57s/it]

VAE train ep22:  86%|████████▌ | 142/165 [19:43<03:15,  8.50s/it]

VAE train ep22:  87%|████████▋ | 143/165 [19:51<03:05,  8.44s/it]

VAE train ep22:  87%|████████▋ | 144/165 [20:00<02:57,  8.47s/it]

VAE train ep22:  88%|████████▊ | 145/165 [20:08<02:49,  8.50s/it]

VAE train ep22:  88%|████████▊ | 146/165 [20:17<02:40,  8.45s/it]

VAE train ep22:  89%|████████▉ | 147/165 [20:25<02:31,  8.40s/it]

VAE train ep22:  90%|████████▉ | 148/165 [20:33<02:22,  8.40s/it]

VAE train ep22:  90%|█████████ | 149/165 [20:42<02:16,  8.51s/it]

VAE train ep22:  91%|█████████ | 150/165 [20:50<02:06,  8.42s/it]

VAE train ep22:  92%|█████████▏| 151/165 [20:59<01:57,  8.38s/it]

VAE train ep22:  92%|█████████▏| 152/165 [21:07<01:49,  8.40s/it]

VAE train ep22:  93%|█████████▎| 153/165 [21:16<01:41,  8.48s/it]

VAE train ep22:  93%|█████████▎| 154/165 [21:24<01:33,  8.53s/it]

VAE train ep22:  94%|█████████▍| 155/165 [21:33<01:25,  8.58s/it]

VAE train ep22:  95%|█████████▍| 156/165 [21:42<01:17,  8.59s/it]

VAE train ep22:  95%|█████████▌| 157/165 [21:50<01:08,  8.58s/it]

VAE train ep22:  96%|█████████▌| 158/165 [21:58<00:59,  8.49s/it]

VAE train ep22:  96%|█████████▋| 159/165 [22:07<00:50,  8.42s/it]

VAE train ep22:  97%|█████████▋| 160/165 [22:15<00:42,  8.40s/it]

VAE train ep22:  98%|█████████▊| 161/165 [22:24<00:33,  8.45s/it]

VAE train ep22:  98%|█████████▊| 162/165 [22:32<00:25,  8.42s/it]

VAE train ep22:  99%|█████████▉| 163/165 [22:41<00:16,  8.44s/it]

VAE train ep22:  99%|█████████▉| 164/165 [22:49<00:08,  8.46s/it]

VAE train ep22: 100%|██████████| 165/165 [22:50<00:00,  6.11s/it]

VAE val ep22:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep22:   3%|▎         | 1/29 [00:02<01:04,  2.31s/it]

VAE val ep22:   7%|▋         | 2/29 [00:04<01:01,  2.28s/it]

VAE val ep22:  10%|█         | 3/29 [00:06<00:59,  2.29s/it]

VAE val ep22:  14%|█▍        | 4/29 [00:09<00:56,  2.28s/it]

VAE val ep22:  17%|█▋        | 5/29 [00:11<00:54,  2.27s/it]

VAE val ep22:  21%|██        | 6/29 [00:13<00:51,  2.26s/it]

VAE val ep22:  24%|██▍       | 7/29 [00:15<00:49,  2.26s/it]

VAE val ep22:  28%|██▊       | 8/29 [00:18<00:47,  2.26s/it]

VAE val ep22:  31%|███       | 9/29 [00:20<00:45,  2.26s/it]

VAE val ep22:  34%|███▍      | 10/29 [00:22<00:42,  2.26s/it]

VAE val ep22:  38%|███▊      | 11/29 [00:24<00:40,  2.26s/it]

VAE val ep22:  41%|████▏     | 12/29 [00:27<00:38,  2.28s/it]

VAE val ep22:  45%|████▍     | 13/29 [00:29<00:36,  2.27s/it]

VAE val ep22:  48%|████▊     | 14/29 [00:31<00:33,  2.26s/it]

VAE val ep22:  52%|█████▏    | 15/29 [00:34<00:31,  2.28s/it]

VAE val ep22:  55%|█████▌    | 16/29 [00:36<00:29,  2.28s/it]

VAE val ep22:  59%|█████▊    | 17/29 [00:38<00:27,  2.28s/it]

VAE val ep22:  62%|██████▏   | 18/29 [00:40<00:25,  2.29s/it]

VAE val ep22:  66%|██████▌   | 19/29 [00:43<00:22,  2.28s/it]

VAE val ep22:  69%|██████▉   | 20/29 [00:45<00:20,  2.28s/it]

VAE val ep22:  72%|███████▏  | 21/29 [00:47<00:18,  2.29s/it]

VAE val ep22:  76%|███████▌  | 22/29 [00:50<00:15,  2.28s/it]

VAE val ep22:  79%|███████▉  | 23/29 [00:52<00:13,  2.27s/it]

VAE val ep22:  83%|████████▎ | 24/29 [00:54<00:11,  2.28s/it]

VAE val ep22:  86%|████████▌ | 25/29 [00:56<00:09,  2.30s/it]

VAE val ep22:  90%|████████▉ | 26/29 [00:59<00:06,  2.30s/it]

VAE val ep22:  93%|█████████▎| 27/29 [01:01<00:04,  2.32s/it]

VAE val ep22:  97%|█████████▋| 28/29 [01:03<00:02,  2.34s/it]

VAE val ep22: 100%|██████████| 29/29 [01:04<00:00,  1.76s/it]

VAE train ep23:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep23:   1%|          | 1/165 [00:08<24:29,  8.96s/it]

VAE train ep23:   1%|          | 2/165 [00:17<23:39,  8.71s/it]

VAE train ep23:   2%|▏         | 3/165 [00:25<23:11,  8.59s/it]

VAE train ep23:   2%|▏         | 4/165 [00:34<23:08,  8.62s/it]

VAE train ep23:   3%|▎         | 5/165 [00:43<23:08,  8.68s/it]

VAE train ep23:   4%|▎         | 6/165 [00:51<22:50,  8.62s/it]

VAE train ep23:   4%|▍         | 7/165 [01:00<22:33,  8.57s/it]

VAE train ep23:   5%|▍         | 8/165 [01:08<22:20,  8.54s/it]

VAE train ep23:   5%|▌         | 9/165 [01:17<22:26,  8.63s/it]

VAE train ep23:   6%|▌         | 10/165 [01:26<22:19,  8.64s/it]

VAE train ep23:   7%|▋         | 11/165 [01:35<22:13,  8.66s/it]

VAE train ep23:   7%|▋         | 12/165 [01:43<22:02,  8.64s/it]

VAE train ep23:   8%|▊         | 13/165 [01:52<21:46,  8.60s/it]

VAE train ep23:   8%|▊         | 14/165 [02:00<21:41,  8.62s/it]

VAE train ep23:   9%|▉         | 15/165 [02:09<21:23,  8.55s/it]

VAE train ep23:  10%|▉         | 16/165 [02:17<21:12,  8.54s/it]

VAE train ep23:  10%|█         | 17/165 [02:26<21:00,  8.52s/it]

VAE train ep23:  11%|█         | 18/165 [02:34<20:47,  8.48s/it]

VAE train ep23:  12%|█▏        | 19/165 [02:43<20:45,  8.53s/it]

VAE train ep23:  12%|█▏        | 20/165 [02:51<20:36,  8.52s/it]

VAE train ep23:  13%|█▎        | 21/165 [03:00<20:35,  8.58s/it]

VAE train ep23:  13%|█▎        | 22/165 [03:08<20:21,  8.54s/it]

VAE train ep23:  14%|█▍        | 23/165 [03:17<20:09,  8.52s/it]

VAE train ep23:  15%|█▍        | 24/165 [03:26<20:06,  8.56s/it]

VAE train ep23:  15%|█▌        | 25/165 [03:34<19:58,  8.56s/it]

VAE train ep23:  16%|█▌        | 26/165 [03:43<19:45,  8.53s/it]

VAE train ep23:  16%|█▋        | 27/165 [03:51<19:29,  8.48s/it]

VAE train ep23:  17%|█▋        | 28/165 [03:59<19:23,  8.49s/it]

VAE train ep23:  18%|█▊        | 29/165 [04:08<19:18,  8.52s/it]

VAE train ep23:  18%|█▊        | 30/165 [04:16<19:02,  8.46s/it]

VAE train ep23:  19%|█▉        | 31/165 [04:25<18:44,  8.39s/it]

VAE train ep23:  19%|█▉        | 32/165 [04:33<18:31,  8.36s/it]

VAE train ep23:  20%|██        | 33/165 [04:41<18:25,  8.37s/it]

VAE train ep23:  21%|██        | 34/165 [04:49<18:11,  8.34s/it]

VAE train ep23:  21%|██        | 35/165 [04:58<18:06,  8.36s/it]

VAE train ep23:  22%|██▏       | 36/165 [05:06<18:04,  8.41s/it]

VAE train ep23:  22%|██▏       | 37/165 [05:15<18:08,  8.50s/it]

VAE train ep23:  23%|██▎       | 38/165 [05:24<17:59,  8.50s/it]

VAE train ep23:  24%|██▎       | 39/165 [05:32<17:45,  8.46s/it]

VAE train ep23:  24%|██▍       | 40/165 [05:40<17:36,  8.45s/it]

VAE train ep23:  25%|██▍       | 41/165 [05:49<17:27,  8.45s/it]

VAE train ep23:  25%|██▌       | 42/165 [05:57<17:17,  8.43s/it]

VAE train ep23:  26%|██▌       | 43/165 [06:06<17:02,  8.38s/it]

VAE train ep23:  27%|██▋       | 44/165 [06:14<16:49,  8.34s/it]

VAE train ep23:  27%|██▋       | 45/165 [06:22<16:44,  8.37s/it]

VAE train ep23:  28%|██▊       | 46/165 [06:31<16:35,  8.37s/it]

VAE train ep23:  28%|██▊       | 47/165 [06:39<16:28,  8.37s/it]

VAE train ep23:  29%|██▉       | 48/165 [06:47<16:19,  8.37s/it]

VAE train ep23:  30%|██▉       | 49/165 [06:56<16:10,  8.36s/it]

VAE train ep23:  30%|███       | 50/165 [07:04<16:00,  8.35s/it]

VAE train ep23:  31%|███       | 51/165 [07:12<15:53,  8.36s/it]

VAE train ep23:  32%|███▏      | 52/165 [07:21<15:42,  8.34s/it]

VAE train ep23:  32%|███▏      | 53/165 [07:29<15:32,  8.33s/it]

VAE train ep23:  33%|███▎      | 54/165 [07:37<15:25,  8.33s/it]

VAE train ep23:  33%|███▎      | 55/165 [07:46<15:26,  8.42s/it]

VAE train ep23:  34%|███▍      | 56/165 [07:55<15:23,  8.47s/it]

VAE train ep23:  35%|███▍      | 57/165 [08:03<15:13,  8.46s/it]

VAE train ep23:  35%|███▌      | 58/165 [08:11<15:03,  8.45s/it]

VAE train ep23:  36%|███▌      | 59/165 [08:20<14:54,  8.44s/it]

VAE train ep23:  36%|███▋      | 60/165 [08:28<14:44,  8.42s/it]

VAE train ep23:  37%|███▋      | 61/165 [08:36<14:31,  8.38s/it]

VAE train ep23:  38%|███▊      | 62/165 [08:45<14:27,  8.42s/it]

VAE train ep23:  38%|███▊      | 63/165 [08:53<14:09,  8.33s/it]

VAE train ep23:  39%|███▉      | 64/165 [09:01<13:59,  8.31s/it]

VAE train ep23:  39%|███▉      | 65/165 [09:10<13:55,  8.36s/it]

VAE train ep23:  40%|████      | 66/165 [09:18<13:50,  8.38s/it]

VAE train ep23:  41%|████      | 67/165 [09:27<13:42,  8.39s/it]

VAE train ep23:  41%|████      | 68/165 [09:35<13:34,  8.40s/it]

VAE train ep23:  42%|████▏     | 69/165 [09:44<13:28,  8.43s/it]

VAE train ep23:  42%|████▏     | 70/165 [09:52<13:17,  8.39s/it]

VAE train ep23:  43%|████▎     | 71/165 [10:00<13:08,  8.39s/it]

VAE train ep23:  44%|████▎     | 72/165 [10:08<12:52,  8.31s/it]

VAE train ep23:  44%|████▍     | 73/165 [10:17<12:45,  8.32s/it]

VAE train ep23:  45%|████▍     | 74/165 [10:25<12:36,  8.32s/it]

VAE train ep23:  45%|████▌     | 75/165 [10:33<12:28,  8.31s/it]

VAE train ep23:  46%|████▌     | 76/165 [10:42<12:20,  8.32s/it]

VAE train ep23:  47%|████▋     | 77/165 [10:50<12:16,  8.37s/it]

VAE train ep23:  47%|████▋     | 78/165 [10:59<12:09,  8.38s/it]

VAE train ep23:  48%|████▊     | 79/165 [11:07<11:58,  8.35s/it]

VAE train ep23:  48%|████▊     | 80/165 [11:15<11:49,  8.35s/it]

VAE train ep23:  49%|████▉     | 81/165 [11:24<11:42,  8.36s/it]

VAE train ep23:  50%|████▉     | 82/165 [11:32<11:33,  8.36s/it]

VAE train ep23:  50%|█████     | 83/165 [11:40<11:25,  8.37s/it]

VAE train ep23:  51%|█████     | 84/165 [11:49<11:15,  8.34s/it]

VAE train ep23:  52%|█████▏    | 85/165 [11:57<11:02,  8.28s/it]

VAE train ep23:  52%|█████▏    | 86/165 [12:05<10:54,  8.28s/it]

VAE train ep23:  53%|█████▎    | 87/165 [12:14<10:50,  8.34s/it]

VAE train ep23:  53%|█████▎    | 88/165 [12:22<10:49,  8.43s/it]

VAE train ep23:  54%|█████▍    | 89/165 [12:31<10:47,  8.51s/it]

VAE train ep23:  55%|█████▍    | 90/165 [12:39<10:38,  8.51s/it]

VAE train ep23:  55%|█████▌    | 91/165 [12:48<10:30,  8.52s/it]

VAE train ep23:  56%|█████▌    | 92/165 [12:56<10:18,  8.48s/it]

VAE train ep23:  56%|█████▋    | 93/165 [13:04<09:59,  8.33s/it]

VAE train ep23:  57%|█████▋    | 94/165 [13:12<09:45,  8.24s/it]

VAE train ep23:  58%|█████▊    | 95/165 [13:20<09:35,  8.22s/it]

VAE train ep23:  58%|█████▊    | 96/165 [13:29<09:22,  8.16s/it]

VAE train ep23:  59%|█████▉    | 97/165 [13:37<09:15,  8.18s/it]

VAE train ep23:  59%|█████▉    | 98/165 [13:45<09:00,  8.07s/it]

VAE train ep23:  60%|██████    | 99/165 [13:52<08:50,  8.04s/it]

VAE train ep23:  61%|██████    | 100/165 [14:00<08:39,  7.99s/it]

VAE train ep23:  61%|██████    | 101/165 [14:08<08:32,  8.00s/it]

VAE train ep23:  62%|██████▏   | 102/165 [14:16<08:20,  7.95s/it]

VAE train ep23:  62%|██████▏   | 103/165 [14:24<08:11,  7.93s/it]

VAE train ep23:  63%|██████▎   | 104/165 [14:32<08:05,  7.96s/it]

VAE train ep23:  64%|██████▎   | 105/165 [14:40<07:58,  7.98s/it]

VAE train ep23:  64%|██████▍   | 106/165 [14:48<07:51,  7.99s/it]

VAE train ep23:  65%|██████▍   | 107/165 [14:56<07:42,  7.97s/it]

VAE train ep23:  65%|██████▌   | 108/165 [15:04<07:33,  7.96s/it]

VAE train ep23:  66%|██████▌   | 109/165 [15:12<07:24,  7.94s/it]

VAE train ep23:  67%|██████▋   | 110/165 [15:20<07:16,  7.93s/it]

VAE train ep23:  67%|██████▋   | 111/165 [15:28<07:08,  7.94s/it]

VAE train ep23:  68%|██████▊   | 112/165 [15:36<07:03,  8.00s/it]

VAE train ep23:  68%|██████▊   | 113/165 [15:44<06:56,  8.01s/it]

VAE train ep23:  69%|██████▉   | 114/165 [15:52<06:46,  7.97s/it]

VAE train ep23:  70%|██████▉   | 115/165 [16:00<06:39,  8.00s/it]

VAE train ep23:  70%|███████   | 116/165 [16:08<06:32,  8.00s/it]

VAE train ep23:  71%|███████   | 117/165 [16:16<06:25,  8.04s/it]

VAE train ep23:  72%|███████▏  | 118/165 [16:24<06:16,  8.00s/it]

VAE train ep23:  72%|███████▏  | 119/165 [16:32<06:07,  7.98s/it]

VAE train ep23:  73%|███████▎  | 120/165 [16:40<05:59,  7.98s/it]

VAE train ep23:  73%|███████▎  | 121/165 [16:48<05:49,  7.94s/it]

VAE train ep23:  74%|███████▍  | 122/165 [16:56<05:41,  7.94s/it]

VAE train ep23:  75%|███████▍  | 123/165 [17:04<05:34,  7.98s/it]

VAE train ep23:  75%|███████▌  | 124/165 [17:12<05:28,  8.01s/it]

VAE train ep23:  76%|███████▌  | 125/165 [17:20<05:20,  8.02s/it]

VAE train ep23:  76%|███████▋  | 126/165 [17:28<05:10,  7.95s/it]

VAE train ep23:  77%|███████▋  | 127/165 [17:36<05:02,  7.95s/it]

VAE train ep23:  78%|███████▊  | 128/165 [17:43<04:53,  7.92s/it]

VAE train ep23:  78%|███████▊  | 129/165 [17:51<04:45,  7.92s/it]

VAE train ep23:  79%|███████▉  | 130/165 [17:59<04:37,  7.93s/it]

VAE train ep23:  79%|███████▉  | 131/165 [18:07<04:27,  7.87s/it]

VAE train ep23:  80%|████████  | 132/165 [18:15<04:19,  7.88s/it]

VAE train ep23:  81%|████████  | 133/165 [18:23<04:13,  7.92s/it]

VAE train ep23:  81%|████████  | 134/165 [18:31<04:05,  7.91s/it]

VAE train ep23:  82%|████████▏ | 135/165 [18:39<03:57,  7.92s/it]

VAE train ep23:  82%|████████▏ | 136/165 [18:47<03:50,  7.93s/it]

VAE train ep23:  83%|████████▎ | 137/165 [18:55<03:42,  7.96s/it]

VAE train ep23:  84%|████████▎ | 138/165 [19:03<03:34,  7.95s/it]

VAE train ep23:  84%|████████▍ | 139/165 [19:11<03:26,  7.93s/it]

VAE train ep23:  85%|████████▍ | 140/165 [19:18<03:17,  7.90s/it]

VAE train ep23:  85%|████████▌ | 141/165 [19:26<03:10,  7.95s/it]

VAE train ep23:  86%|████████▌ | 142/165 [19:35<03:03,  7.99s/it]

VAE train ep23:  87%|████████▋ | 143/165 [19:43<02:56,  8.01s/it]

VAE train ep23:  87%|████████▋ | 144/165 [19:51<02:48,  8.04s/it]

VAE train ep23:  88%|████████▊ | 145/165 [19:59<02:40,  8.05s/it]

VAE train ep23:  88%|████████▊ | 146/165 [20:07<02:31,  7.98s/it]

VAE train ep23:  89%|████████▉ | 147/165 [20:14<02:22,  7.94s/it]

VAE train ep23:  90%|████████▉ | 148/165 [20:22<02:15,  7.95s/it]

VAE train ep23:  90%|█████████ | 149/165 [20:30<02:07,  7.94s/it]

VAE train ep23:  91%|█████████ | 150/165 [20:38<01:59,  7.99s/it]

VAE train ep23:  92%|█████████▏| 151/165 [20:46<01:51,  7.98s/it]

VAE train ep23:  92%|█████████▏| 152/165 [20:54<01:43,  7.94s/it]

VAE train ep23:  93%|█████████▎| 153/165 [21:02<01:35,  7.99s/it]

VAE train ep23:  93%|█████████▎| 154/165 [21:10<01:27,  7.96s/it]

VAE train ep23:  94%|█████████▍| 155/165 [21:18<01:20,  8.00s/it]

VAE train ep23:  95%|█████████▍| 156/165 [21:26<01:11,  7.99s/it]

VAE train ep23:  95%|█████████▌| 157/165 [21:34<01:03,  7.96s/it]

VAE train ep23:  96%|█████████▌| 158/165 [21:42<00:55,  7.95s/it]

VAE train ep23:  96%|█████████▋| 159/165 [21:50<00:47,  7.94s/it]

VAE train ep23:  97%|█████████▋| 160/165 [21:58<00:39,  7.98s/it]

VAE train ep23:  98%|█████████▊| 161/165 [22:06<00:32,  8.05s/it]

VAE train ep23:  98%|█████████▊| 162/165 [22:14<00:24,  8.04s/it]

VAE train ep23:  99%|█████████▉| 163/165 [22:22<00:16,  8.01s/it]

VAE train ep23:  99%|█████████▉| 164/165 [22:30<00:07,  7.95s/it]

VAE train ep23: 100%|██████████| 165/165 [22:31<00:00,  5.73s/it]

VAE val ep23:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep23:   3%|▎         | 1/29 [00:02<01:01,  2.19s/it]

VAE val ep23:   7%|▋         | 2/29 [00:04<00:58,  2.18s/it]

VAE val ep23:  10%|█         | 3/29 [00:06<00:56,  2.18s/it]

VAE val ep23:  14%|█▍        | 4/29 [00:08<00:54,  2.17s/it]

VAE val ep23:  17%|█▋        | 5/29 [00:10<00:52,  2.18s/it]

VAE val ep23:  21%|██        | 6/29 [00:13<00:49,  2.17s/it]

VAE val ep23:  24%|██▍       | 7/29 [00:15<00:47,  2.14s/it]

VAE val ep23:  28%|██▊       | 8/29 [00:17<00:45,  2.15s/it]

VAE val ep23:  31%|███       | 9/29 [00:19<00:42,  2.14s/it]

VAE val ep23:  34%|███▍      | 10/29 [00:21<00:40,  2.14s/it]

VAE val ep23:  38%|███▊      | 11/29 [00:23<00:38,  2.13s/it]

VAE val ep23:  41%|████▏     | 12/29 [00:25<00:36,  2.13s/it]

VAE val ep23:  45%|████▍     | 13/29 [00:27<00:34,  2.13s/it]

VAE val ep23:  48%|████▊     | 14/29 [00:30<00:32,  2.14s/it]

VAE val ep23:  52%|█████▏    | 15/29 [00:32<00:30,  2.16s/it]

VAE val ep23:  55%|█████▌    | 16/29 [00:34<00:27,  2.15s/it]

VAE val ep23:  59%|█████▊    | 17/29 [00:36<00:25,  2.14s/it]

VAE val ep23:  62%|██████▏   | 18/29 [00:38<00:23,  2.14s/it]

VAE val ep23:  66%|██████▌   | 19/29 [00:40<00:21,  2.15s/it]

VAE val ep23:  69%|██████▉   | 20/29 [00:42<00:19,  2.15s/it]

VAE val ep23:  72%|███████▏  | 21/29 [00:45<00:17,  2.16s/it]

VAE val ep23:  76%|███████▌  | 22/29 [00:47<00:15,  2.17s/it]

VAE val ep23:  79%|███████▉  | 23/29 [00:49<00:13,  2.18s/it]

VAE val ep23:  83%|████████▎ | 24/29 [00:51<00:10,  2.19s/it]

VAE val ep23:  86%|████████▌ | 25/29 [00:53<00:08,  2.18s/it]

VAE val ep23:  90%|████████▉ | 26/29 [00:56<00:06,  2.20s/it]

VAE val ep23:  93%|█████████▎| 27/29 [00:58<00:04,  2.22s/it]

VAE val ep23:  97%|█████████▋| 28/29 [01:00<00:02,  2.25s/it]

VAE val ep23: 100%|██████████| 29/29 [01:01<00:00,  1.69s/it]

VAE train ep24:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep24:   1%|          | 1/165 [00:08<24:23,  8.92s/it]

VAE train ep24:   1%|          | 2/165 [00:17<24:07,  8.88s/it]

VAE train ep24:   2%|▏         | 3/165 [00:26<23:52,  8.84s/it]

VAE train ep24:   2%|▏         | 4/165 [00:35<23:17,  8.68s/it]

VAE train ep24:   3%|▎         | 5/165 [00:43<22:59,  8.62s/it]

VAE train ep24:   4%|▎         | 6/165 [00:52<22:45,  8.59s/it]

VAE train ep24:   4%|▍         | 7/165 [01:00<22:33,  8.57s/it]

VAE train ep24:   5%|▍         | 8/165 [01:08<22:18,  8.52s/it]

VAE train ep24:   5%|▌         | 9/165 [01:17<22:05,  8.49s/it]

VAE train ep24:   6%|▌         | 10/165 [01:25<21:49,  8.45s/it]

VAE train ep24:   7%|▋         | 11/165 [01:34<21:34,  8.41s/it]

VAE train ep24:   7%|▋         | 12/165 [01:42<21:23,  8.39s/it]

VAE train ep24:   8%|▊         | 13/165 [01:50<21:14,  8.38s/it]

VAE train ep24:   8%|▊         | 14/165 [01:59<21:11,  8.42s/it]

VAE train ep24:   9%|▉         | 15/165 [02:07<21:05,  8.44s/it]

VAE train ep24:  10%|▉         | 16/165 [02:16<20:54,  8.42s/it]

VAE train ep24:  10%|█         | 17/165 [02:24<20:47,  8.43s/it]

VAE train ep24:  11%|█         | 18/165 [02:32<20:36,  8.41s/it]

VAE train ep24:  12%|█▏        | 19/165 [02:41<20:25,  8.39s/it]

VAE train ep24:  12%|█▏        | 20/165 [02:49<20:11,  8.36s/it]

VAE train ep24:  13%|█▎        | 21/165 [02:57<20:01,  8.34s/it]

VAE train ep24:  13%|█▎        | 22/165 [03:06<19:52,  8.34s/it]

VAE train ep24:  14%|█▍        | 23/165 [03:14<19:43,  8.34s/it]

VAE train ep24:  15%|█▍        | 24/165 [03:22<19:31,  8.31s/it]

VAE train ep24:  15%|█▌        | 25/165 [03:31<19:26,  8.34s/it]

VAE train ep24:  16%|█▌        | 26/165 [03:39<19:13,  8.30s/it]

VAE train ep24:  16%|█▋        | 27/165 [03:47<18:56,  8.23s/it]

VAE train ep24:  17%|█▋        | 28/165 [03:55<18:52,  8.27s/it]

VAE train ep24:  18%|█▊        | 29/165 [04:04<18:41,  8.25s/it]

VAE train ep24:  18%|█▊        | 30/165 [04:12<18:33,  8.25s/it]

VAE train ep24:  19%|█▉        | 31/165 [04:20<18:27,  8.26s/it]

VAE train ep24:  19%|█▉        | 32/165 [04:28<18:19,  8.27s/it]

VAE train ep24:  20%|██        | 33/165 [04:37<18:16,  8.31s/it]

VAE train ep24:  21%|██        | 34/165 [04:45<18:02,  8.26s/it]

VAE train ep24:  21%|██        | 35/165 [04:53<17:54,  8.26s/it]

VAE train ep24:  22%|██▏       | 36/165 [05:01<17:41,  8.23s/it]

VAE train ep24:  22%|██▏       | 37/165 [05:10<17:38,  8.27s/it]

VAE train ep24:  23%|██▎       | 38/165 [05:18<17:25,  8.23s/it]

VAE train ep24:  24%|██▎       | 39/165 [05:26<17:12,  8.19s/it]

VAE train ep24:  24%|██▍       | 40/165 [05:34<17:05,  8.20s/it]

VAE train ep24:  25%|██▍       | 41/165 [05:43<17:04,  8.26s/it]

VAE train ep24:  25%|██▌       | 42/165 [05:51<17:02,  8.31s/it]

VAE train ep24:  26%|██▌       | 43/165 [05:59<16:53,  8.31s/it]

VAE train ep24:  27%|██▋       | 44/165 [06:07<16:38,  8.25s/it]

VAE train ep24:  27%|██▋       | 45/165 [06:16<16:29,  8.25s/it]

VAE train ep24:  28%|██▊       | 46/165 [06:24<16:20,  8.24s/it]

VAE train ep24:  28%|██▊       | 47/165 [06:32<16:12,  8.24s/it]

VAE train ep24:  29%|██▉       | 48/165 [06:40<16:00,  8.21s/it]

VAE train ep24:  30%|██▉       | 49/165 [06:48<15:50,  8.19s/it]

VAE train ep24:  30%|███       | 50/165 [06:57<15:38,  8.16s/it]

VAE train ep24:  31%|███       | 51/165 [07:05<15:30,  8.16s/it]

VAE train ep24:  32%|███▏      | 52/165 [07:13<15:24,  8.18s/it]

VAE train ep24:  32%|███▏      | 53/165 [07:21<15:11,  8.14s/it]

VAE train ep24:  33%|███▎      | 54/165 [07:29<15:00,  8.11s/it]

VAE train ep24:  33%|███▎      | 55/165 [07:37<14:49,  8.09s/it]

VAE train ep24:  34%|███▍      | 56/165 [07:45<14:40,  8.08s/it]

VAE train ep24:  35%|███▍      | 57/165 [07:53<14:35,  8.11s/it]

VAE train ep24:  35%|███▌      | 58/165 [08:01<14:29,  8.13s/it]

VAE train ep24:  36%|███▌      | 59/165 [08:10<14:24,  8.15s/it]

VAE train ep24:  36%|███▋      | 60/165 [08:18<14:15,  8.15s/it]

VAE train ep24:  37%|███▋      | 61/165 [08:26<14:05,  8.13s/it]

VAE train ep24:  38%|███▊      | 62/165 [08:34<13:56,  8.12s/it]

VAE train ep24:  38%|███▊      | 63/165 [08:42<13:43,  8.08s/it]

VAE train ep24:  39%|███▉      | 64/165 [08:50<13:37,  8.09s/it]

VAE train ep24:  39%|███▉      | 65/165 [08:58<13:31,  8.12s/it]

VAE train ep24:  40%|████      | 66/165 [09:06<13:17,  8.06s/it]

VAE train ep24:  41%|████      | 67/165 [09:14<13:11,  8.08s/it]

VAE train ep24:  41%|████      | 68/165 [09:22<13:01,  8.06s/it]

VAE train ep24:  42%|████▏     | 69/165 [09:30<12:55,  8.08s/it]

VAE train ep24:  42%|████▏     | 70/165 [09:39<12:49,  8.10s/it]

VAE train ep24:  43%|████▎     | 71/165 [09:47<12:45,  8.14s/it]

VAE train ep24:  44%|████▎     | 72/165 [09:55<12:40,  8.18s/it]

VAE train ep24:  44%|████▍     | 73/165 [10:03<12:31,  8.17s/it]

VAE train ep24:  45%|████▍     | 74/165 [10:11<12:19,  8.13s/it]

VAE train ep24:  45%|████▌     | 75/165 [10:19<12:08,  8.10s/it]

VAE train ep24:  46%|████▌     | 76/165 [10:27<12:02,  8.12s/it]

VAE train ep24:  47%|████▋     | 77/165 [10:36<11:56,  8.14s/it]

VAE train ep24:  47%|████▋     | 78/165 [10:44<11:50,  8.16s/it]

VAE train ep24:  48%|████▊     | 79/165 [10:52<11:48,  8.23s/it]

VAE train ep24:  48%|████▊     | 80/165 [11:01<11:40,  8.25s/it]

VAE train ep24:  49%|████▉     | 81/165 [11:09<11:34,  8.26s/it]

VAE train ep24:  50%|████▉     | 82/165 [11:17<11:24,  8.25s/it]

VAE train ep24:  50%|█████     | 83/165 [11:25<11:16,  8.25s/it]

VAE train ep24:  51%|█████     | 84/165 [11:33<11:05,  8.21s/it]

VAE train ep24:  52%|█████▏    | 85/165 [11:42<10:56,  8.21s/it]

VAE train ep24:  52%|█████▏    | 86/165 [11:50<10:45,  8.17s/it]

VAE train ep24:  53%|█████▎    | 87/165 [11:58<10:35,  8.15s/it]

VAE train ep24:  53%|█████▎    | 88/165 [12:06<10:27,  8.15s/it]

VAE train ep24:  54%|█████▍    | 89/165 [12:14<10:20,  8.16s/it]

VAE train ep24:  55%|█████▍    | 90/165 [12:22<10:09,  8.13s/it]

VAE train ep24:  55%|█████▌    | 91/165 [12:30<09:58,  8.09s/it]

VAE train ep24:  56%|█████▌    | 92/165 [12:38<09:50,  8.08s/it]

VAE train ep24:  56%|█████▋    | 93/165 [12:47<09:47,  8.15s/it]

VAE train ep24:  57%|█████▋    | 94/165 [12:55<09:37,  8.13s/it]

VAE train ep24:  58%|█████▊    | 95/165 [13:03<09:30,  8.15s/it]

VAE train ep24:  58%|█████▊    | 96/165 [13:11<09:22,  8.15s/it]

VAE train ep24:  59%|█████▉    | 97/165 [13:19<09:16,  8.18s/it]

VAE train ep24:  59%|█████▉    | 98/165 [13:27<09:03,  8.11s/it]

VAE train ep24:  60%|██████    | 99/165 [13:35<08:55,  8.11s/it]

VAE train ep24:  61%|██████    | 100/165 [13:43<08:45,  8.08s/it]

VAE train ep24:  61%|██████    | 101/165 [13:51<08:37,  8.09s/it]

VAE train ep24:  62%|██████▏   | 102/165 [13:59<08:27,  8.05s/it]

VAE train ep24:  62%|██████▏   | 103/165 [14:08<08:22,  8.10s/it]

VAE train ep24:  63%|██████▎   | 104/165 [14:16<08:15,  8.13s/it]

VAE train ep24:  64%|██████▎   | 105/165 [14:24<08:12,  8.21s/it]

VAE train ep24:  64%|██████▍   | 106/165 [14:33<08:10,  8.31s/it]

VAE train ep24:  65%|██████▍   | 107/165 [14:41<08:00,  8.29s/it]

VAE train ep24:  65%|██████▌   | 108/165 [14:49<07:51,  8.28s/it]

VAE train ep24:  66%|██████▌   | 109/165 [14:57<07:41,  8.23s/it]

VAE train ep24:  67%|██████▋   | 110/165 [15:06<07:31,  8.21s/it]

VAE train ep24:  67%|██████▋   | 111/165 [15:14<07:25,  8.24s/it]

VAE train ep24:  68%|██████▊   | 112/165 [15:22<07:14,  8.19s/it]

VAE train ep24:  68%|██████▊   | 113/165 [15:30<07:05,  8.19s/it]

VAE train ep24:  69%|██████▉   | 114/165 [15:38<06:56,  8.16s/it]

VAE train ep24:  70%|██████▉   | 115/165 [15:46<06:49,  8.19s/it]

VAE train ep24:  70%|███████   | 116/165 [15:55<06:42,  8.22s/it]

VAE train ep24:  71%|███████   | 117/165 [16:03<06:38,  8.29s/it]

VAE train ep24:  72%|███████▏  | 118/165 [16:12<06:31,  8.34s/it]

VAE train ep24:  72%|███████▏  | 119/165 [16:20<06:22,  8.32s/it]

VAE train ep24:  73%|███████▎  | 120/165 [16:28<06:13,  8.29s/it]

VAE train ep24:  73%|███████▎  | 121/165 [16:36<06:04,  8.29s/it]

VAE train ep24:  74%|███████▍  | 122/165 [16:44<05:51,  8.17s/it]

VAE train ep24:  75%|███████▍  | 123/165 [16:53<05:42,  8.16s/it]

VAE train ep24:  75%|███████▌  | 124/165 [17:01<05:33,  8.14s/it]

VAE train ep24:  76%|███████▌  | 125/165 [17:09<05:25,  8.15s/it]

VAE train ep24:  76%|███████▋  | 126/165 [17:17<05:16,  8.13s/it]

VAE train ep24:  77%|███████▋  | 127/165 [17:25<05:07,  8.10s/it]

VAE train ep24:  78%|███████▊  | 128/165 [17:33<04:59,  8.09s/it]

VAE train ep24:  78%|███████▊  | 129/165 [17:41<04:51,  8.08s/it]

VAE train ep24:  79%|███████▉  | 130/165 [17:49<04:44,  8.12s/it]

VAE train ep24:  79%|███████▉  | 131/165 [17:57<04:36,  8.12s/it]

VAE train ep24:  80%|████████  | 132/165 [18:05<04:26,  8.08s/it]

VAE train ep24:  81%|████████  | 133/165 [18:14<04:19,  8.11s/it]

VAE train ep24:  81%|████████  | 134/165 [18:21<04:09,  8.05s/it]

VAE train ep24:  82%|████████▏ | 135/165 [18:29<04:01,  8.04s/it]

VAE train ep24:  82%|████████▏ | 136/165 [18:37<03:51,  7.99s/it]

VAE train ep24:  83%|████████▎ | 137/165 [18:45<03:44,  8.00s/it]

VAE train ep24:  84%|████████▎ | 138/165 [18:53<03:36,  8.04s/it]

VAE train ep24:  84%|████████▍ | 139/165 [19:02<03:29,  8.07s/it]

VAE train ep24:  85%|████████▍ | 140/165 [19:10<03:22,  8.10s/it]

VAE train ep24:  85%|████████▌ | 141/165 [19:18<03:14,  8.10s/it]

VAE train ep24:  86%|████████▌ | 142/165 [19:26<03:05,  8.06s/it]

VAE train ep24:  87%|████████▋ | 143/165 [19:34<02:56,  8.04s/it]

VAE train ep24:  87%|████████▋ | 144/165 [19:42<02:47,  7.99s/it]

VAE train ep24:  88%|████████▊ | 145/165 [19:50<02:39,  7.99s/it]

VAE train ep24:  88%|████████▊ | 146/165 [19:58<02:31,  7.96s/it]

VAE train ep24:  89%|████████▉ | 147/165 [20:06<02:23,  7.96s/it]

VAE train ep24:  90%|████████▉ | 148/165 [20:14<02:15,  7.98s/it]

VAE train ep24:  90%|█████████ | 149/165 [20:22<02:09,  8.07s/it]

VAE train ep24:  91%|█████████ | 150/165 [20:30<02:01,  8.07s/it]

VAE train ep24:  92%|█████████▏| 151/165 [20:38<01:52,  8.04s/it]

VAE train ep24:  92%|█████████▏| 152/165 [20:46<01:44,  8.03s/it]

VAE train ep24:  93%|█████████▎| 153/165 [20:54<01:36,  8.01s/it]

VAE train ep24:  93%|█████████▎| 154/165 [21:02<01:28,  8.02s/it]

VAE train ep24:  94%|█████████▍| 155/165 [21:10<01:20,  8.01s/it]

VAE train ep24:  95%|█████████▍| 156/165 [21:18<01:11,  7.94s/it]

VAE train ep24:  95%|█████████▌| 157/165 [21:26<01:04,  8.03s/it]

VAE train ep24:  96%|█████████▌| 158/165 [21:34<00:56,  8.01s/it]

VAE train ep24:  96%|█████████▋| 159/165 [21:42<00:47,  7.97s/it]

VAE train ep24:  97%|█████████▋| 160/165 [21:50<00:40,  8.03s/it]

VAE train ep24:  98%|█████████▊| 161/165 [21:58<00:32,  8.10s/it]

VAE train ep24:  98%|█████████▊| 162/165 [22:06<00:24,  8.08s/it]

VAE train ep24:  99%|█████████▉| 163/165 [22:14<00:15,  7.98s/it]

VAE train ep24:  99%|█████████▉| 164/165 [22:22<00:07,  7.97s/it]

VAE train ep24: 100%|██████████| 165/165 [22:23<00:00,  5.78s/it]

VAE val ep24:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep24:   3%|▎         | 1/29 [00:02<01:02,  2.24s/it]

VAE val ep24:   7%|▋         | 2/29 [00:04<00:59,  2.20s/it]

VAE val ep24:  10%|█         | 3/29 [00:06<00:56,  2.18s/it]

VAE val ep24:  14%|█▍        | 4/29 [00:08<00:54,  2.17s/it]

VAE val ep24:  17%|█▋        | 5/29 [00:10<00:51,  2.16s/it]

VAE val ep24:  21%|██        | 6/29 [00:13<00:49,  2.15s/it]

VAE val ep24:  24%|██▍       | 7/29 [00:15<00:47,  2.15s/it]

VAE val ep24:  28%|██▊       | 8/29 [00:17<00:45,  2.16s/it]

VAE val ep24:  31%|███       | 9/29 [00:19<00:42,  2.15s/it]

VAE val ep24:  34%|███▍      | 10/29 [00:21<00:40,  2.14s/it]

VAE val ep24:  38%|███▊      | 11/29 [00:23<00:38,  2.14s/it]

VAE val ep24:  41%|████▏     | 12/29 [00:25<00:36,  2.14s/it]

VAE val ep24:  45%|████▍     | 13/29 [00:27<00:34,  2.14s/it]

VAE val ep24:  48%|████▊     | 14/29 [00:30<00:32,  2.14s/it]

VAE val ep24:  52%|█████▏    | 15/29 [00:32<00:30,  2.16s/it]

VAE val ep24:  55%|█████▌    | 16/29 [00:34<00:27,  2.15s/it]

VAE val ep24:  59%|█████▊    | 17/29 [00:36<00:25,  2.16s/it]

VAE val ep24:  62%|██████▏   | 18/29 [00:38<00:23,  2.16s/it]

VAE val ep24:  66%|██████▌   | 19/29 [00:40<00:21,  2.15s/it]

VAE val ep24:  69%|██████▉   | 20/29 [00:43<00:19,  2.14s/it]

VAE val ep24:  72%|███████▏  | 21/29 [00:45<00:17,  2.15s/it]

VAE val ep24:  76%|███████▌  | 22/29 [00:47<00:15,  2.16s/it]

VAE val ep24:  79%|███████▉  | 23/29 [00:49<00:12,  2.15s/it]

VAE val ep24:  83%|████████▎ | 24/29 [00:51<00:10,  2.14s/it]

VAE val ep24:  86%|████████▌ | 25/29 [00:53<00:08,  2.15s/it]

VAE val ep24:  90%|████████▉ | 26/29 [00:55<00:06,  2.15s/it]

VAE val ep24:  93%|█████████▎| 27/29 [00:58<00:04,  2.15s/it]

VAE val ep24:  97%|█████████▋| 28/29 [01:00<00:02,  2.14s/it]

VAE val ep24: 100%|██████████| 29/29 [01:00<00:00,  1.58s/it]

VAE train ep25:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep25:   1%|          | 1/165 [00:08<22:46,  8.33s/it]

VAE train ep25:   1%|          | 2/165 [00:16<22:24,  8.25s/it]

VAE train ep25:   2%|▏         | 3/165 [00:24<22:02,  8.16s/it]

VAE train ep25:   2%|▏         | 4/165 [00:32<21:49,  8.13s/it]

VAE train ep25:   3%|▎         | 5/165 [00:40<21:34,  8.09s/it]

VAE train ep25:   4%|▎         | 6/165 [00:48<21:20,  8.06s/it]

VAE train ep25:   4%|▍         | 7/165 [00:56<21:04,  8.00s/it]

VAE train ep25:   5%|▍         | 8/165 [01:04<20:50,  7.97s/it]

VAE train ep25:   5%|▌         | 9/165 [01:12<20:49,  8.01s/it]

VAE train ep25:   6%|▌         | 10/165 [01:20<20:41,  8.01s/it]

VAE train ep25:   7%|▋         | 11/165 [01:28<20:27,  7.97s/it]

VAE train ep25:   7%|▋         | 12/165 [01:36<20:19,  7.97s/it]

VAE train ep25:   8%|▊         | 13/165 [01:44<20:04,  7.92s/it]

VAE train ep25:   8%|▊         | 14/165 [01:52<19:58,  7.94s/it]

VAE train ep25:   9%|▉         | 15/165 [02:00<19:49,  7.93s/it]

VAE train ep25:  10%|▉         | 16/165 [02:08<19:46,  7.96s/it]

VAE train ep25:  10%|█         | 17/165 [02:16<19:42,  7.99s/it]

VAE train ep25:  11%|█         | 18/165 [02:24<19:31,  7.97s/it]

VAE train ep25:  12%|█▏        | 19/165 [02:32<19:36,  8.06s/it]

VAE train ep25:  12%|█▏        | 20/165 [02:40<19:29,  8.06s/it]

VAE train ep25:  13%|█▎        | 21/165 [02:48<19:27,  8.11s/it]

VAE train ep25:  13%|█▎        | 22/165 [02:56<19:17,  8.10s/it]

VAE train ep25:  14%|█▍        | 23/165 [03:04<19:03,  8.05s/it]

VAE train ep25:  15%|█▍        | 24/165 [03:12<19:03,  8.11s/it]

VAE train ep25:  15%|█▌        | 25/165 [03:21<19:06,  8.19s/it]

VAE train ep25:  16%|█▌        | 26/165 [03:29<19:09,  8.27s/it]

VAE train ep25:  16%|█▋        | 27/165 [03:37<18:57,  8.24s/it]

VAE train ep25:  17%|█▋        | 28/165 [03:46<18:49,  8.24s/it]

VAE train ep25:  18%|█▊        | 29/165 [03:54<18:39,  8.23s/it]

VAE train ep25:  18%|█▊        | 30/165 [04:02<18:26,  8.20s/it]

VAE train ep25:  19%|█▉        | 31/165 [04:10<18:20,  8.21s/it]

VAE train ep25:  19%|█▉        | 32/165 [04:18<18:04,  8.15s/it]

VAE train ep25:  20%|██        | 33/165 [04:26<17:51,  8.12s/it]

VAE train ep25:  21%|██        | 34/165 [04:34<17:40,  8.10s/it]

VAE train ep25:  21%|██        | 35/165 [04:42<17:33,  8.10s/it]

VAE train ep25:  22%|██▏       | 36/165 [04:50<17:19,  8.06s/it]

VAE train ep25:  22%|██▏       | 37/165 [04:59<17:12,  8.07s/it]

VAE train ep25:  23%|██▎       | 38/165 [05:07<17:03,  8.06s/it]

VAE train ep25:  24%|██▎       | 39/165 [05:15<16:55,  8.06s/it]

VAE train ep25:  24%|██▍       | 40/165 [05:23<16:45,  8.05s/it]

VAE train ep25:  25%|██▍       | 41/165 [05:31<16:39,  8.06s/it]

VAE train ep25:  25%|██▌       | 42/165 [05:39<16:30,  8.05s/it]

VAE train ep25:  26%|██▌       | 43/165 [05:47<16:24,  8.07s/it]

VAE train ep25:  27%|██▋       | 44/165 [05:55<16:18,  8.09s/it]

VAE train ep25:  27%|██▋       | 45/165 [06:03<16:15,  8.13s/it]

VAE train ep25:  28%|██▊       | 46/165 [06:11<15:57,  8.04s/it]

VAE train ep25:  28%|██▊       | 47/165 [06:19<15:49,  8.05s/it]

VAE train ep25:  29%|██▉       | 48/165 [06:27<15:42,  8.05s/it]

VAE train ep25:  30%|██▉       | 49/165 [06:35<15:37,  8.08s/it]

VAE train ep25:  30%|███       | 50/165 [06:43<15:23,  8.03s/it]

VAE train ep25:  31%|███       | 51/165 [06:51<15:16,  8.04s/it]

VAE train ep25:  32%|███▏      | 52/165 [06:59<15:00,  7.97s/it]

VAE train ep25:  32%|███▏      | 53/165 [07:07<14:59,  8.03s/it]

VAE train ep25:  33%|███▎      | 54/165 [07:16<15:02,  8.13s/it]

VAE train ep25:  33%|███▎      | 55/165 [07:24<14:54,  8.13s/it]

VAE train ep25:  34%|███▍      | 56/165 [07:32<14:45,  8.13s/it]

VAE train ep25:  35%|███▍      | 57/165 [07:40<14:43,  8.18s/it]

VAE train ep25:  35%|███▌      | 58/165 [07:48<14:35,  8.18s/it]

VAE train ep25:  36%|███▌      | 59/165 [07:57<14:34,  8.25s/it]

VAE train ep25:  36%|███▋      | 60/165 [08:05<14:22,  8.22s/it]

VAE train ep25:  37%|███▋      | 61/165 [08:13<14:15,  8.22s/it]

VAE train ep25:  38%|███▊      | 62/165 [08:21<14:08,  8.23s/it]

VAE train ep25:  38%|███▊      | 63/165 [08:30<14:03,  8.27s/it]

VAE train ep25:  39%|███▉      | 64/165 [08:38<13:50,  8.23s/it]

VAE train ep25:  39%|███▉      | 65/165 [08:46<13:44,  8.25s/it]

VAE train ep25:  40%|████      | 66/165 [08:54<13:30,  8.19s/it]

VAE train ep25:  41%|████      | 67/165 [09:03<13:23,  8.20s/it]

VAE train ep25:  41%|████      | 68/165 [09:11<13:13,  8.18s/it]

VAE train ep25:  42%|████▏     | 69/165 [09:19<13:01,  8.14s/it]

VAE train ep25:  42%|████▏     | 70/165 [09:27<12:55,  8.16s/it]

VAE train ep25:  43%|████▎     | 71/165 [09:35<12:47,  8.17s/it]

VAE train ep25:  44%|████▎     | 72/165 [09:43<12:39,  8.16s/it]

VAE train ep25:  44%|████▍     | 73/165 [09:51<12:30,  8.16s/it]

VAE train ep25:  45%|████▍     | 74/165 [09:59<12:20,  8.14s/it]

VAE train ep25:  45%|████▌     | 75/165 [10:08<12:11,  8.12s/it]

VAE train ep25:  46%|████▌     | 76/165 [10:16<12:03,  8.13s/it]

VAE train ep25:  47%|████▋     | 77/165 [10:24<11:50,  8.08s/it]

VAE train ep25:  47%|████▋     | 78/165 [10:32<11:39,  8.04s/it]

VAE train ep25:  48%|████▊     | 79/165 [10:40<11:32,  8.05s/it]

VAE train ep25:  48%|████▊     | 80/165 [10:48<11:25,  8.07s/it]

VAE train ep25:  49%|████▉     | 81/165 [10:56<11:18,  8.08s/it]

VAE train ep25:  50%|████▉     | 82/165 [11:04<11:07,  8.05s/it]

VAE train ep25:  50%|█████     | 83/165 [11:12<11:01,  8.07s/it]

VAE train ep25:  51%|█████     | 84/165 [11:20<10:53,  8.07s/it]

VAE train ep25:  52%|█████▏    | 85/165 [11:28<10:48,  8.11s/it]

VAE train ep25:  52%|█████▏    | 86/165 [11:36<10:38,  8.08s/it]

VAE train ep25:  53%|█████▎    | 87/165 [11:44<10:31,  8.10s/it]

VAE train ep25:  53%|█████▎    | 88/165 [11:52<10:20,  8.05s/it]

VAE train ep25:  54%|█████▍    | 89/165 [12:01<10:14,  8.09s/it]

VAE train ep25:  55%|█████▍    | 90/165 [12:09<10:06,  8.09s/it]

VAE train ep25:  55%|█████▌    | 91/165 [12:17<09:56,  8.06s/it]

VAE train ep25:  56%|█████▌    | 92/165 [12:25<09:50,  8.10s/it]

VAE train ep25:  56%|█████▋    | 93/165 [12:33<09:44,  8.11s/it]

VAE train ep25:  57%|█████▋    | 94/165 [12:41<09:40,  8.17s/it]

VAE train ep25:  58%|█████▊    | 95/165 [12:49<09:30,  8.15s/it]

VAE train ep25:  58%|█████▊    | 96/165 [12:57<09:20,  8.12s/it]

VAE train ep25:  59%|█████▉    | 97/165 [13:06<09:14,  8.15s/it]

VAE train ep25:  59%|█████▉    | 98/165 [13:14<09:05,  8.14s/it]

VAE train ep25:  60%|██████    | 99/165 [13:22<08:53,  8.08s/it]

VAE train ep25:  61%|██████    | 100/165 [13:30<08:45,  8.08s/it]

VAE train ep25:  61%|██████    | 101/165 [13:38<08:38,  8.10s/it]

VAE train ep25:  62%|██████▏   | 102/165 [13:46<08:28,  8.08s/it]

VAE train ep25:  62%|██████▏   | 103/165 [13:54<08:20,  8.07s/it]

VAE train ep25:  63%|██████▎   | 104/165 [14:02<08:10,  8.05s/it]

VAE train ep25:  64%|██████▎   | 105/165 [14:10<08:04,  8.08s/it]

VAE train ep25:  64%|██████▍   | 106/165 [14:18<07:54,  8.05s/it]

VAE train ep25:  65%|██████▍   | 107/165 [14:26<07:45,  8.02s/it]

VAE train ep25:  65%|██████▌   | 108/165 [14:34<07:36,  8.00s/it]

VAE train ep25:  66%|██████▌   | 109/165 [14:42<07:30,  8.04s/it]

VAE train ep25:  67%|██████▋   | 110/165 [14:50<07:22,  8.04s/it]

VAE train ep25:  67%|██████▋   | 111/165 [14:58<07:15,  8.07s/it]

VAE train ep25:  68%|██████▊   | 112/165 [15:06<07:07,  8.06s/it]

VAE train ep25:  68%|██████▊   | 113/165 [15:14<06:59,  8.07s/it]

VAE train ep25:  69%|██████▉   | 114/165 [15:22<06:49,  8.03s/it]

VAE train ep25:  70%|██████▉   | 115/165 [15:30<06:39,  8.00s/it]

VAE train ep25:  70%|███████   | 116/165 [15:38<06:32,  8.00s/it]

VAE train ep25:  71%|███████   | 117/165 [15:46<06:22,  7.97s/it]

VAE train ep25:  72%|███████▏  | 118/165 [15:54<06:12,  7.93s/it]

VAE train ep25:  72%|███████▏  | 119/165 [16:02<06:06,  7.98s/it]

VAE train ep25:  73%|███████▎  | 120/165 [16:10<05:59,  8.00s/it]

VAE train ep25:  73%|███████▎  | 121/165 [16:18<05:54,  8.05s/it]

VAE train ep25:  74%|███████▍  | 122/165 [16:27<05:48,  8.11s/it]

VAE train ep25:  75%|███████▍  | 123/165 [16:35<05:41,  8.14s/it]

VAE train ep25:  75%|███████▌  | 124/165 [16:43<05:37,  8.23s/it]

VAE train ep25:  76%|███████▌  | 125/165 [16:52<05:36,  8.41s/it]

VAE train ep25:  76%|███████▋  | 126/165 [17:00<05:25,  8.35s/it]

VAE train ep25:  77%|███████▋  | 127/165 [17:09<05:15,  8.31s/it]

VAE train ep25:  78%|███████▊  | 128/165 [17:17<05:06,  8.27s/it]

VAE train ep25:  78%|███████▊  | 129/165 [17:25<04:57,  8.26s/it]

VAE train ep25:  79%|███████▉  | 130/165 [17:33<04:49,  8.26s/it]

VAE train ep25:  79%|███████▉  | 131/165 [17:41<04:40,  8.25s/it]

VAE train ep25:  80%|████████  | 132/165 [17:49<04:29,  8.18s/it]

VAE train ep25:  81%|████████  | 133/165 [17:58<04:22,  8.19s/it]

VAE train ep25:  81%|████████  | 134/165 [18:06<04:13,  8.17s/it]

VAE train ep25:  82%|████████▏ | 135/165 [18:14<04:02,  8.07s/it]

VAE train ep25:  82%|████████▏ | 136/165 [18:22<03:53,  8.06s/it]

VAE train ep25:  83%|████████▎ | 137/165 [18:30<03:46,  8.08s/it]

VAE train ep25:  84%|████████▎ | 138/165 [18:38<03:38,  8.09s/it]

VAE train ep25:  84%|████████▍ | 139/165 [18:46<03:31,  8.12s/it]

VAE train ep25:  85%|████████▍ | 140/165 [18:54<03:21,  8.06s/it]

VAE train ep25:  85%|████████▌ | 141/165 [19:02<03:14,  8.12s/it]

VAE train ep25:  86%|████████▌ | 142/165 [19:10<03:06,  8.10s/it]

VAE train ep25:  87%|████████▋ | 143/165 [19:19<02:59,  8.14s/it]

VAE train ep25:  87%|████████▋ | 144/165 [19:27<02:51,  8.17s/it]

VAE train ep25:  88%|████████▊ | 145/165 [19:35<02:44,  8.21s/it]

VAE train ep25:  88%|████████▊ | 146/165 [19:44<02:37,  8.27s/it]

VAE train ep25:  89%|████████▉ | 147/165 [19:52<02:29,  8.31s/it]

VAE train ep25:  90%|████████▉ | 148/165 [20:00<02:21,  8.33s/it]

VAE train ep25:  90%|█████████ | 149/165 [20:09<02:12,  8.31s/it]

VAE train ep25:  91%|█████████ | 150/165 [20:17<02:04,  8.31s/it]

VAE train ep25:  92%|█████████▏| 151/165 [20:25<01:56,  8.35s/it]

VAE train ep25:  92%|█████████▏| 152/165 [20:34<01:49,  8.39s/it]

VAE train ep25:  93%|█████████▎| 153/165 [20:42<01:40,  8.35s/it]

VAE train ep25:  93%|█████████▎| 154/165 [20:50<01:31,  8.33s/it]

VAE train ep25:  94%|█████████▍| 155/165 [20:58<01:22,  8.28s/it]

VAE train ep25:  95%|█████████▍| 156/165 [21:07<01:14,  8.28s/it]

VAE train ep25:  95%|█████████▌| 157/165 [21:15<01:06,  8.25s/it]

VAE train ep25:  96%|█████████▌| 158/165 [21:23<00:57,  8.21s/it]

VAE train ep25:  96%|█████████▋| 159/165 [21:31<00:49,  8.20s/it]

VAE train ep25:  97%|█████████▋| 160/165 [21:40<00:41,  8.22s/it]

VAE train ep25:  98%|█████████▊| 161/165 [21:48<00:32,  8.25s/it]

VAE train ep25:  98%|█████████▊| 162/165 [21:56<00:24,  8.22s/it]

VAE train ep25:  99%|█████████▉| 163/165 [22:04<00:16,  8.19s/it]

VAE train ep25:  99%|█████████▉| 164/165 [22:12<00:08,  8.15s/it]

VAE train ep25: 100%|██████████| 165/165 [22:13<00:00,  5.87s/it]

VAE val ep25:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep25:   3%|▎         | 1/29 [00:02<01:01,  2.21s/it]

VAE val ep25:   7%|▋         | 2/29 [00:04<01:00,  2.23s/it]

VAE val ep25:  10%|█         | 3/29 [00:06<00:57,  2.23s/it]

VAE val ep25:  14%|█▍        | 4/29 [00:08<00:55,  2.22s/it]

VAE val ep25:  17%|█▋        | 5/29 [00:11<00:53,  2.21s/it]

VAE val ep25:  21%|██        | 6/29 [00:13<00:51,  2.22s/it]

VAE val ep25:  24%|██▍       | 7/29 [00:15<00:48,  2.21s/it]

VAE val ep25:  28%|██▊       | 8/29 [00:17<00:46,  2.20s/it]

VAE val ep25:  31%|███       | 9/29 [00:19<00:43,  2.19s/it]

VAE val ep25:  34%|███▍      | 10/29 [00:22<00:41,  2.19s/it]

VAE val ep25:  38%|███▊      | 11/29 [00:24<00:39,  2.18s/it]

VAE val ep25:  41%|████▏     | 12/29 [00:26<00:37,  2.18s/it]

VAE val ep25:  45%|████▍     | 13/29 [00:28<00:34,  2.18s/it]

VAE val ep25:  48%|████▊     | 14/29 [00:30<00:32,  2.17s/it]

VAE val ep25:  52%|█████▏    | 15/29 [00:33<00:31,  2.22s/it]

VAE val ep25:  55%|█████▌    | 16/29 [00:35<00:28,  2.20s/it]

VAE val ep25:  59%|█████▊    | 17/29 [00:37<00:26,  2.20s/it]

VAE val ep25:  62%|██████▏   | 18/29 [00:39<00:24,  2.20s/it]

VAE val ep25:  66%|██████▌   | 19/29 [00:41<00:22,  2.20s/it]

VAE val ep25:  69%|██████▉   | 20/29 [00:44<00:19,  2.21s/it]

VAE val ep25:  72%|███████▏  | 21/29 [00:46<00:17,  2.21s/it]

VAE val ep25:  76%|███████▌  | 22/29 [00:48<00:15,  2.21s/it]

VAE val ep25:  79%|███████▉  | 23/29 [00:50<00:13,  2.20s/it]

VAE val ep25:  83%|████████▎ | 24/29 [00:52<00:10,  2.19s/it]

VAE val ep25:  86%|████████▌ | 25/29 [00:54<00:08,  2.19s/it]

VAE val ep25:  90%|████████▉ | 26/29 [00:57<00:06,  2.20s/it]

VAE val ep25:  93%|█████████▎| 27/29 [00:59<00:04,  2.20s/it]

VAE val ep25:  97%|█████████▋| 28/29 [01:01<00:02,  2.20s/it]

VAE val ep25: 100%|██████████| 29/29 [01:02<00:00,  1.67s/it]

VAE train ep26:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep26:   1%|          | 1/165 [00:08<21:52,  8.00s/it]

VAE train ep26:   1%|          | 2/165 [00:16<22:09,  8.16s/it]

VAE train ep26:   2%|▏         | 3/165 [00:24<22:07,  8.20s/it]

VAE train ep26:   2%|▏         | 4/165 [00:32<21:53,  8.16s/it]

VAE train ep26:   3%|▎         | 5/165 [00:40<21:49,  8.18s/it]

VAE train ep26:   4%|▎         | 6/165 [00:48<21:35,  8.15s/it]

VAE train ep26:   4%|▍         | 7/165 [00:57<21:29,  8.16s/it]

VAE train ep26:   5%|▍         | 8/165 [01:05<21:12,  8.11s/it]

VAE train ep26:   5%|▌         | 9/165 [01:13<21:03,  8.10s/it]

VAE train ep26:   6%|▌         | 10/165 [01:21<20:58,  8.12s/it]

VAE train ep26:   7%|▋         | 11/165 [01:29<20:50,  8.12s/it]

VAE train ep26:   7%|▋         | 12/165 [01:37<20:48,  8.16s/it]

VAE train ep26:   8%|▊         | 13/165 [01:45<20:40,  8.16s/it]

VAE train ep26:   8%|▊         | 14/165 [01:54<20:37,  8.20s/it]

VAE train ep26:   9%|▉         | 15/165 [02:02<20:21,  8.15s/it]

VAE train ep26:  10%|▉         | 16/165 [02:10<20:06,  8.10s/it]

VAE train ep26:  10%|█         | 17/165 [02:18<19:56,  8.09s/it]

VAE train ep26:  11%|█         | 18/165 [02:26<19:48,  8.09s/it]

VAE train ep26:  12%|█▏        | 19/165 [02:34<19:41,  8.09s/it]

VAE train ep26:  12%|█▏        | 20/165 [02:42<19:37,  8.12s/it]

VAE train ep26:  13%|█▎        | 21/165 [02:50<19:32,  8.14s/it]

VAE train ep26:  13%|█▎        | 22/165 [02:59<19:33,  8.20s/it]

VAE train ep26:  14%|█▍        | 23/165 [03:07<19:22,  8.19s/it]

VAE train ep26:  15%|█▍        | 24/165 [03:15<19:13,  8.18s/it]

VAE train ep26:  15%|█▌        | 25/165 [03:23<19:02,  8.16s/it]

VAE train ep26:  16%|█▌        | 26/165 [03:31<18:55,  8.17s/it]

VAE train ep26:  16%|█▋        | 27/165 [03:39<18:40,  8.12s/it]

VAE train ep26:  17%|█▋        | 28/165 [03:47<18:27,  8.08s/it]

VAE train ep26:  18%|█▊        | 29/165 [03:55<18:18,  8.07s/it]

VAE train ep26:  18%|█▊        | 30/165 [04:04<18:19,  8.14s/it]

VAE train ep26:  19%|█▉        | 31/165 [04:12<18:09,  8.13s/it]

VAE train ep26:  19%|█▉        | 32/165 [04:20<18:02,  8.14s/it]

VAE train ep26:  20%|██        | 33/165 [04:28<17:57,  8.16s/it]

VAE train ep26:  21%|██        | 34/165 [04:36<17:43,  8.12s/it]

VAE train ep26:  21%|██        | 35/165 [04:44<17:28,  8.07s/it]

VAE train ep26:  22%|██▏       | 36/165 [04:52<17:16,  8.03s/it]

VAE train ep26:  22%|██▏       | 37/165 [05:00<17:11,  8.06s/it]

VAE train ep26:  23%|██▎       | 38/165 [05:08<17:01,  8.04s/it]

VAE train ep26:  24%|██▎       | 39/165 [05:16<16:52,  8.04s/it]

VAE train ep26:  24%|██▍       | 40/165 [05:24<16:46,  8.05s/it]

VAE train ep26:  25%|██▍       | 41/165 [05:32<16:39,  8.06s/it]

VAE train ep26:  25%|██▌       | 42/165 [05:40<16:25,  8.01s/it]

VAE train ep26:  26%|██▌       | 43/165 [05:48<16:16,  8.00s/it]

VAE train ep26:  27%|██▋       | 44/165 [05:56<16:17,  8.07s/it]

VAE train ep26:  27%|██▋       | 45/165 [06:05<16:10,  8.09s/it]

VAE train ep26:  28%|██▊       | 46/165 [06:13<16:07,  8.13s/it]

VAE train ep26:  28%|██▊       | 47/165 [06:21<15:58,  8.13s/it]

VAE train ep26:  29%|██▉       | 48/165 [06:29<15:45,  8.08s/it]

VAE train ep26:  30%|██▉       | 49/165 [06:37<15:35,  8.07s/it]

VAE train ep26:  30%|███       | 50/165 [06:45<15:24,  8.04s/it]

VAE train ep26:  31%|███       | 51/165 [06:53<15:14,  8.02s/it]

VAE train ep26:  32%|███▏      | 52/165 [07:01<15:11,  8.07s/it]

VAE train ep26:  32%|███▏      | 53/165 [07:09<15:08,  8.11s/it]

VAE train ep26:  33%|███▎      | 54/165 [07:17<14:55,  8.06s/it]

VAE train ep26:  33%|███▎      | 55/165 [07:25<14:42,  8.02s/it]

VAE train ep26:  34%|███▍      | 56/165 [07:33<14:36,  8.04s/it]

VAE train ep26:  35%|███▍      | 57/165 [07:42<14:37,  8.13s/it]

VAE train ep26:  35%|███▌      | 58/165 [07:50<14:36,  8.19s/it]

VAE train ep26:  36%|███▌      | 59/165 [07:58<14:36,  8.27s/it]

VAE train ep26:  36%|███▋      | 60/165 [08:07<14:33,  8.32s/it]

VAE train ep26:  37%|███▋      | 61/165 [08:15<14:31,  8.38s/it]

VAE train ep26:  38%|███▊      | 62/165 [08:24<14:18,  8.33s/it]

VAE train ep26:  38%|███▊      | 63/165 [08:32<14:04,  8.28s/it]

VAE train ep26:  39%|███▉      | 64/165 [08:40<13:53,  8.25s/it]

VAE train ep26:  39%|███▉      | 65/165 [08:48<13:43,  8.24s/it]

VAE train ep26:  40%|████      | 66/165 [08:56<13:33,  8.21s/it]

VAE train ep26:  41%|████      | 67/165 [09:04<13:22,  8.19s/it]

VAE train ep26:  41%|████      | 68/165 [09:12<13:09,  8.14s/it]

VAE train ep26:  42%|████▏     | 69/165 [09:21<13:00,  8.13s/it]

VAE train ep26:  42%|████▏     | 70/165 [09:29<12:54,  8.15s/it]

VAE train ep26:  43%|████▎     | 71/165 [09:37<13:00,  8.30s/it]

VAE train ep26:  44%|████▎     | 72/165 [09:46<12:58,  8.37s/it]

VAE train ep26:  44%|████▍     | 73/165 [09:54<12:54,  8.42s/it]

VAE train ep26:  45%|████▍     | 74/165 [10:03<12:44,  8.41s/it]

VAE train ep26:  45%|████▌     | 75/165 [10:11<12:38,  8.43s/it]

VAE train ep26:  46%|████▌     | 76/165 [10:20<12:30,  8.43s/it]

VAE train ep26:  47%|████▋     | 77/165 [10:28<12:21,  8.42s/it]

VAE train ep26:  47%|████▋     | 78/165 [10:36<12:10,  8.39s/it]

VAE train ep26:  48%|████▊     | 79/165 [10:45<12:03,  8.41s/it]

VAE train ep26:  48%|████▊     | 80/165 [10:54<12:00,  8.48s/it]

VAE train ep26:  49%|████▉     | 81/165 [11:02<11:52,  8.48s/it]

VAE train ep26:  50%|████▉     | 82/165 [11:10<11:39,  8.43s/it]

VAE train ep26:  50%|█████     | 83/165 [11:19<11:36,  8.49s/it]

VAE train ep26:  51%|█████     | 84/165 [11:27<11:23,  8.44s/it]

VAE train ep26:  52%|█████▏    | 85/165 [11:36<11:19,  8.50s/it]

VAE train ep26:  52%|█████▏    | 86/165 [11:44<11:03,  8.40s/it]

VAE train ep26:  53%|█████▎    | 87/165 [11:52<10:50,  8.35s/it]

VAE train ep26:  53%|█████▎    | 88/165 [12:00<10:37,  8.28s/it]

VAE train ep26:  54%|█████▍    | 89/165 [12:09<10:30,  8.30s/it]

VAE train ep26:  55%|█████▍    | 90/165 [12:17<10:21,  8.28s/it]

VAE train ep26:  55%|█████▌    | 91/165 [12:25<10:08,  8.22s/it]

VAE train ep26:  56%|█████▌    | 92/165 [12:33<09:55,  8.15s/it]

VAE train ep26:  56%|█████▋    | 93/165 [12:41<09:47,  8.15s/it]

VAE train ep26:  57%|█████▋    | 94/165 [12:49<09:37,  8.13s/it]

VAE train ep26:  58%|█████▊    | 95/165 [12:57<09:26,  8.09s/it]

VAE train ep26:  58%|█████▊    | 96/165 [13:05<09:16,  8.06s/it]

VAE train ep26:  59%|█████▉    | 97/165 [13:13<09:05,  8.02s/it]

VAE train ep26:  59%|█████▉    | 98/165 [13:21<08:56,  8.01s/it]

VAE train ep26:  60%|██████    | 99/165 [13:29<08:53,  8.08s/it]

VAE train ep26:  61%|██████    | 100/165 [13:37<08:42,  8.03s/it]

VAE train ep26:  61%|██████    | 101/165 [13:46<08:36,  8.06s/it]

VAE train ep26:  62%|██████▏   | 102/165 [13:53<08:23,  7.99s/it]

VAE train ep26:  62%|██████▏   | 103/165 [14:01<08:15,  7.99s/it]

VAE train ep26:  63%|██████▎   | 104/165 [14:09<08:08,  8.00s/it]

VAE train ep26:  64%|██████▎   | 105/165 [14:18<08:04,  8.08s/it]

VAE train ep26:  64%|██████▍   | 106/165 [14:26<07:56,  8.07s/it]

VAE train ep26:  65%|██████▍   | 107/165 [14:34<07:46,  8.05s/it]

VAE train ep26:  65%|██████▌   | 108/165 [14:42<07:37,  8.02s/it]

VAE train ep26:  66%|██████▌   | 109/165 [14:50<07:29,  8.03s/it]

VAE train ep26:  67%|██████▋   | 110/165 [14:58<07:19,  7.98s/it]

VAE train ep26:  67%|██████▋   | 111/165 [15:05<07:05,  7.88s/it]

VAE train ep26:  68%|██████▊   | 112/165 [15:13<06:54,  7.81s/it]

VAE train ep26:  68%|██████▊   | 113/165 [15:21<06:49,  7.88s/it]

VAE train ep26:  69%|██████▉   | 114/165 [15:29<06:42,  7.89s/it]

VAE train ep26:  70%|██████▉   | 115/165 [15:37<06:38,  7.97s/it]

VAE train ep26:  70%|███████   | 116/165 [15:45<06:30,  7.97s/it]

VAE train ep26:  71%|███████   | 117/165 [15:53<06:25,  8.04s/it]

VAE train ep26:  72%|███████▏  | 118/165 [16:01<06:19,  8.07s/it]

VAE train ep26:  72%|███████▏  | 119/165 [16:09<06:11,  8.07s/it]

VAE train ep26:  73%|███████▎  | 120/165 [16:17<06:00,  8.02s/it]

VAE train ep26:  73%|███████▎  | 121/165 [16:25<05:55,  8.08s/it]

VAE train ep26:  74%|███████▍  | 122/165 [16:34<05:48,  8.11s/it]

VAE train ep26:  75%|███████▍  | 123/165 [16:42<05:41,  8.12s/it]

VAE train ep26:  75%|███████▌  | 124/165 [16:50<05:37,  8.22s/it]

VAE train ep26:  76%|███████▌  | 125/165 [16:58<05:29,  8.23s/it]

VAE train ep26:  76%|███████▋  | 126/165 [17:07<05:20,  8.22s/it]

VAE train ep26:  77%|███████▋  | 127/165 [17:15<05:13,  8.25s/it]

VAE train ep26:  78%|███████▊  | 128/165 [17:23<05:02,  8.19s/it]

VAE train ep26:  78%|███████▊  | 129/165 [17:31<04:57,  8.26s/it]

VAE train ep26:  79%|███████▉  | 130/165 [17:40<04:47,  8.22s/it]

VAE train ep26:  79%|███████▉  | 131/165 [17:48<04:39,  8.21s/it]

VAE train ep26:  80%|████████  | 132/165 [17:56<04:29,  8.16s/it]

VAE train ep26:  81%|████████  | 133/165 [18:04<04:22,  8.20s/it]

VAE train ep26:  81%|████████  | 134/165 [18:12<04:15,  8.25s/it]

VAE train ep26:  82%|████████▏ | 135/165 [18:21<04:09,  8.30s/it]

VAE train ep26:  82%|████████▏ | 136/165 [18:30<04:04,  8.42s/it]

VAE train ep26:  83%|████████▎ | 137/165 [18:38<03:58,  8.52s/it]

VAE train ep26:  84%|████████▎ | 138/165 [18:47<03:50,  8.54s/it]

VAE train ep26:  84%|████████▍ | 139/165 [18:55<03:42,  8.54s/it]

VAE train ep26:  85%|████████▍ | 140/165 [19:04<03:32,  8.51s/it]

VAE train ep26:  85%|████████▌ | 141/165 [19:12<03:22,  8.45s/it]

VAE train ep26:  86%|████████▌ | 142/165 [19:20<03:11,  8.31s/it]

VAE train ep26:  87%|████████▋ | 143/165 [19:28<03:01,  8.25s/it]

VAE train ep26:  87%|████████▋ | 144/165 [19:36<02:51,  8.15s/it]

VAE train ep26:  88%|████████▊ | 145/165 [19:44<02:41,  8.07s/it]

VAE train ep26:  88%|████████▊ | 146/165 [19:52<02:31,  7.98s/it]

VAE train ep26:  89%|████████▉ | 147/165 [20:00<02:24,  8.01s/it]

VAE train ep26:  90%|████████▉ | 148/165 [20:08<02:15,  7.98s/it]

VAE train ep26:  90%|█████████ | 149/165 [20:16<02:08,  8.01s/it]

VAE train ep26:  91%|█████████ | 150/165 [20:24<01:59,  7.99s/it]

VAE train ep26:  92%|█████████▏| 151/165 [20:32<01:51,  7.97s/it]

VAE train ep26:  92%|█████████▏| 152/165 [20:40<01:43,  7.99s/it]

VAE train ep26:  93%|█████████▎| 153/165 [20:48<01:35,  7.97s/it]

VAE train ep26:  93%|█████████▎| 154/165 [20:56<01:27,  7.93s/it]

VAE train ep26:  94%|█████████▍| 155/165 [21:04<01:19,  7.96s/it]

VAE train ep26:  95%|█████████▍| 156/165 [21:12<01:12,  8.03s/it]

VAE train ep26:  95%|█████████▌| 157/165 [21:20<01:04,  8.03s/it]

VAE train ep26:  96%|█████████▌| 158/165 [21:28<00:55,  7.95s/it]

VAE train ep26:  96%|█████████▋| 159/165 [21:35<00:47,  7.91s/it]

VAE train ep26:  97%|█████████▋| 160/165 [21:43<00:39,  7.94s/it]

VAE train ep26:  98%|█████████▊| 161/165 [21:52<00:31,  7.99s/it]

VAE train ep26:  98%|█████████▊| 162/165 [22:00<00:24,  8.03s/it]

VAE train ep26:  99%|█████████▉| 163/165 [22:08<00:16,  8.06s/it]

VAE train ep26:  99%|█████████▉| 164/165 [22:16<00:08,  8.02s/it]

VAE train ep26: 100%|██████████| 165/165 [22:16<00:00,  5.79s/it]

VAE val ep26:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep26:   3%|▎         | 1/29 [00:02<01:00,  2.17s/it]

VAE val ep26:   7%|▋         | 2/29 [00:04<00:58,  2.16s/it]

VAE val ep26:  10%|█         | 3/29 [00:06<00:56,  2.17s/it]

VAE val ep26:  14%|█▍        | 4/29 [00:08<00:53,  2.16s/it]

VAE val ep26:  17%|█▋        | 5/29 [00:10<00:51,  2.15s/it]

VAE val ep26:  21%|██        | 6/29 [00:12<00:49,  2.15s/it]

VAE val ep26:  24%|██▍       | 7/29 [00:15<00:47,  2.14s/it]

VAE val ep26:  28%|██▊       | 8/29 [00:17<00:44,  2.14s/it]

VAE val ep26:  31%|███       | 9/29 [00:19<00:42,  2.13s/it]

VAE val ep26:  34%|███▍      | 10/29 [00:21<00:40,  2.14s/it]

VAE val ep26:  38%|███▊      | 11/29 [00:23<00:38,  2.14s/it]

VAE val ep26:  41%|████▏     | 12/29 [00:25<00:36,  2.13s/it]

VAE val ep26:  45%|████▍     | 13/29 [00:27<00:34,  2.13s/it]

VAE val ep26:  48%|████▊     | 14/29 [00:29<00:32,  2.14s/it]

VAE val ep26:  52%|█████▏    | 15/29 [00:32<00:30,  2.16s/it]

VAE val ep26:  55%|█████▌    | 16/29 [00:34<00:28,  2.17s/it]

VAE val ep26:  59%|█████▊    | 17/29 [00:36<00:25,  2.17s/it]

VAE val ep26:  62%|██████▏   | 18/29 [00:38<00:23,  2.16s/it]

VAE val ep26:  66%|██████▌   | 19/29 [00:40<00:21,  2.15s/it]

VAE val ep26:  69%|██████▉   | 20/29 [00:43<00:19,  2.16s/it]

VAE val ep26:  72%|███████▏  | 21/29 [00:45<00:17,  2.16s/it]

VAE val ep26:  76%|███████▌  | 22/29 [00:47<00:15,  2.16s/it]

VAE val ep26:  79%|███████▉  | 23/29 [00:49<00:13,  2.18s/it]

VAE val ep26:  83%|████████▎ | 24/29 [00:51<00:10,  2.19s/it]

VAE val ep26:  86%|████████▌ | 25/29 [00:54<00:08,  2.20s/it]

VAE val ep26:  90%|████████▉ | 26/29 [00:56<00:06,  2.19s/it]

VAE val ep26:  93%|█████████▎| 27/29 [00:58<00:04,  2.18s/it]

VAE val ep26:  97%|█████████▋| 28/29 [01:00<00:02,  2.17s/it]

VAE val ep26: 100%|██████████| 29/29 [01:00<00:00,  1.63s/it]

VAE train ep27:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep27:   1%|          | 1/165 [00:08<23:07,  8.46s/it]

VAE train ep27:   1%|          | 2/165 [00:16<22:27,  8.27s/it]

VAE train ep27:   2%|▏         | 3/165 [00:24<22:09,  8.21s/it]

VAE train ep27:   2%|▏         | 4/165 [00:32<21:49,  8.13s/it]

VAE train ep27:   3%|▎         | 5/165 [00:40<21:36,  8.10s/it]

VAE train ep27:   4%|▎         | 6/165 [00:48<21:15,  8.02s/it]

VAE train ep27:   4%|▍         | 7/165 [00:56<20:56,  7.95s/it]

VAE train ep27:   5%|▍         | 8/165 [01:04<20:45,  7.93s/it]

VAE train ep27:   5%|▌         | 9/165 [01:12<20:40,  7.95s/it]

VAE train ep27:   6%|▌         | 10/165 [01:20<20:29,  7.93s/it]

VAE train ep27:   7%|▋         | 11/165 [01:28<20:21,  7.93s/it]

VAE train ep27:   7%|▋         | 12/165 [01:36<20:12,  7.92s/it]

VAE train ep27:   8%|▊         | 13/165 [01:44<20:05,  7.93s/it]

VAE train ep27:   8%|▊         | 14/165 [01:51<19:51,  7.89s/it]

VAE train ep27:   9%|▉         | 15/165 [01:59<19:46,  7.91s/it]

VAE train ep27:  10%|▉         | 16/165 [02:07<19:35,  7.89s/it]

VAE train ep27:  10%|█         | 17/165 [02:15<19:27,  7.89s/it]

VAE train ep27:  11%|█         | 18/165 [02:23<19:16,  7.87s/it]

VAE train ep27:  12%|█▏        | 19/165 [02:31<19:04,  7.84s/it]

VAE train ep27:  12%|█▏        | 20/165 [02:38<18:52,  7.81s/it]

VAE train ep27:  13%|█▎        | 21/165 [02:46<18:45,  7.81s/it]

VAE train ep27:  13%|█▎        | 22/165 [02:54<18:37,  7.82s/it]

VAE train ep27:  14%|█▍        | 23/165 [03:02<18:32,  7.83s/it]

VAE train ep27:  15%|█▍        | 24/165 [03:10<18:17,  7.79s/it]

VAE train ep27:  15%|█▌        | 25/165 [03:17<18:09,  7.78s/it]

VAE train ep27:  16%|█▌        | 26/165 [03:25<17:50,  7.70s/it]

VAE train ep27:  16%|█▋        | 27/165 [03:32<17:34,  7.64s/it]

VAE train ep27:  17%|█▋        | 28/165 [03:40<17:28,  7.65s/it]

VAE train ep27:  18%|█▊        | 29/165 [03:48<17:26,  7.69s/it]

VAE train ep27:  18%|█▊        | 30/165 [03:56<17:28,  7.77s/it]

VAE train ep27:  19%|█▉        | 31/165 [04:04<17:23,  7.79s/it]

VAE train ep27:  19%|█▉        | 32/165 [04:11<17:08,  7.74s/it]

VAE train ep27:  20%|██        | 33/165 [04:19<17:07,  7.79s/it]

VAE train ep27:  21%|██        | 34/165 [04:27<17:05,  7.83s/it]

VAE train ep27:  21%|██        | 35/165 [04:35<16:55,  7.81s/it]

VAE train ep27:  22%|██▏       | 36/165 [04:43<16:50,  7.83s/it]

VAE train ep27:  22%|██▏       | 37/165 [04:51<16:54,  7.93s/it]

VAE train ep27:  23%|██▎       | 38/165 [04:59<16:42,  7.90s/it]

VAE train ep27:  24%|██▎       | 39/165 [05:06<16:30,  7.86s/it]

VAE train ep27:  24%|██▍       | 40/165 [05:14<16:23,  7.86s/it]

VAE train ep27:  25%|██▍       | 41/165 [05:22<16:13,  7.85s/it]

VAE train ep27:  25%|██▌       | 42/165 [05:30<16:01,  7.82s/it]

VAE train ep27:  26%|██▌       | 43/165 [05:38<15:53,  7.82s/it]

VAE train ep27:  27%|██▋       | 44/165 [05:45<15:45,  7.82s/it]

VAE train ep27:  27%|██▋       | 45/165 [05:53<15:43,  7.86s/it]

VAE train ep27:  28%|██▊       | 46/165 [06:01<15:29,  7.81s/it]

VAE train ep27:  28%|██▊       | 47/165 [06:09<15:31,  7.89s/it]

VAE train ep27:  29%|██▉       | 48/165 [06:17<15:28,  7.93s/it]

VAE train ep27:  30%|██▉       | 49/165 [06:25<15:20,  7.93s/it]

VAE train ep27:  30%|███       | 50/165 [06:33<15:12,  7.94s/it]

VAE train ep27:  31%|███       | 51/165 [06:41<15:05,  7.95s/it]

VAE train ep27:  32%|███▏      | 52/165 [06:49<14:57,  7.94s/it]

VAE train ep27:  32%|███▏      | 53/165 [06:57<14:52,  7.97s/it]

VAE train ep27:  33%|███▎      | 54/165 [07:05<14:43,  7.96s/it]

VAE train ep27:  33%|███▎      | 55/165 [07:13<14:34,  7.95s/it]

VAE train ep27:  34%|███▍      | 56/165 [07:21<14:28,  7.97s/it]

VAE train ep27:  35%|███▍      | 57/165 [07:29<14:27,  8.04s/it]

VAE train ep27:  35%|███▌      | 58/165 [07:37<14:18,  8.02s/it]

VAE train ep27:  36%|███▌      | 59/165 [07:45<14:12,  8.04s/it]

VAE train ep27:  36%|███▋      | 60/165 [07:53<14:09,  8.09s/it]

VAE train ep27:  37%|███▋      | 61/165 [08:02<14:05,  8.13s/it]

VAE train ep27:  38%|███▊      | 62/165 [08:10<13:56,  8.12s/it]

VAE train ep27:  38%|███▊      | 63/165 [08:18<13:41,  8.05s/it]

VAE train ep27:  39%|███▉      | 64/165 [08:25<13:26,  7.99s/it]

VAE train ep27:  39%|███▉      | 65/165 [08:34<13:26,  8.06s/it]

VAE train ep27:  40%|████      | 66/165 [08:42<13:28,  8.16s/it]

VAE train ep27:  41%|████      | 67/165 [08:51<13:30,  8.27s/it]

VAE train ep27:  41%|████      | 68/165 [08:59<13:35,  8.41s/it]

VAE train ep27:  42%|████▏     | 69/165 [09:08<13:28,  8.42s/it]

VAE train ep27:  42%|████▏     | 70/165 [09:16<13:16,  8.38s/it]

VAE train ep27:  43%|████▎     | 71/165 [09:24<13:08,  8.38s/it]

VAE train ep27:  44%|████▎     | 72/165 [09:33<12:58,  8.37s/it]

VAE train ep27:  44%|████▍     | 73/165 [09:41<12:54,  8.42s/it]

VAE train ep27:  45%|████▍     | 74/165 [09:50<12:40,  8.36s/it]

VAE train ep27:  45%|████▌     | 75/165 [09:58<12:35,  8.39s/it]

VAE train ep27:  46%|████▌     | 76/165 [10:06<12:28,  8.41s/it]

VAE train ep27:  47%|████▋     | 77/165 [10:15<12:26,  8.48s/it]

VAE train ep27:  47%|████▋     | 78/165 [10:24<12:18,  8.48s/it]

VAE train ep27:  48%|████▊     | 79/165 [10:32<12:06,  8.45s/it]

VAE train ep27:  48%|████▊     | 80/165 [10:40<11:58,  8.45s/it]

VAE train ep27:  49%|████▉     | 81/165 [10:49<11:49,  8.45s/it]

VAE train ep27:  50%|████▉     | 82/165 [10:58<11:45,  8.50s/it]

VAE train ep27:  50%|█████     | 83/165 [11:06<11:40,  8.54s/it]

VAE train ep27:  51%|█████     | 84/165 [11:15<11:31,  8.54s/it]

VAE train ep27:  52%|█████▏    | 85/165 [11:23<11:25,  8.57s/it]

VAE train ep27:  52%|█████▏    | 86/165 [11:32<11:15,  8.55s/it]

VAE train ep27:  53%|█████▎    | 87/165 [11:40<11:03,  8.50s/it]

VAE train ep27:  53%|█████▎    | 88/165 [11:49<10:53,  8.49s/it]

VAE train ep27:  54%|█████▍    | 89/165 [11:57<10:46,  8.51s/it]

VAE train ep27:  55%|█████▍    | 90/165 [12:06<10:34,  8.47s/it]

VAE train ep27:  55%|█████▌    | 91/165 [12:14<10:24,  8.44s/it]

VAE train ep27:  56%|█████▌    | 92/165 [12:22<10:16,  8.45s/it]

VAE train ep27:  56%|█████▋    | 93/165 [12:31<10:08,  8.45s/it]

VAE train ep27:  57%|█████▋    | 94/165 [12:39<09:58,  8.43s/it]

VAE train ep27:  58%|█████▊    | 95/165 [12:48<09:51,  8.44s/it]

VAE train ep27:  58%|█████▊    | 96/165 [12:56<09:38,  8.38s/it]

VAE train ep27:  59%|█████▉    | 97/165 [13:04<09:29,  8.38s/it]

VAE train ep27:  59%|█████▉    | 98/165 [13:13<09:18,  8.34s/it]

VAE train ep27:  60%|██████    | 99/165 [13:21<09:06,  8.27s/it]

VAE train ep27:  61%|██████    | 100/165 [13:29<08:52,  8.19s/it]

VAE train ep27:  61%|██████    | 101/165 [13:37<08:44,  8.20s/it]

VAE train ep27:  62%|██████▏   | 102/165 [13:45<08:33,  8.15s/it]

VAE train ep27:  62%|██████▏   | 103/165 [13:53<08:23,  8.12s/it]

VAE train ep27:  63%|██████▎   | 104/165 [14:01<08:12,  8.07s/it]

VAE train ep27:  64%|██████▎   | 105/165 [14:09<08:07,  8.13s/it]

VAE train ep27:  64%|██████▍   | 106/165 [14:17<08:00,  8.14s/it]

VAE train ep27:  65%|██████▍   | 107/165 [14:26<07:54,  8.18s/it]

VAE train ep27:  65%|██████▌   | 108/165 [14:34<07:48,  8.22s/it]

VAE train ep27:  66%|██████▌   | 109/165 [14:42<07:40,  8.22s/it]

VAE train ep27:  67%|██████▋   | 110/165 [14:50<07:30,  8.20s/it]

VAE train ep27:  67%|██████▋   | 111/165 [14:59<07:26,  8.27s/it]

VAE train ep27:  68%|██████▊   | 112/165 [15:07<07:19,  8.29s/it]

VAE train ep27:  68%|██████▊   | 113/165 [15:15<07:08,  8.24s/it]

VAE train ep27:  69%|██████▉   | 114/165 [15:23<06:54,  8.13s/it]

VAE train ep27:  70%|██████▉   | 115/165 [15:31<06:46,  8.12s/it]

VAE train ep27:  70%|███████   | 116/165 [15:39<06:39,  8.15s/it]

VAE train ep27:  71%|███████   | 117/165 [15:48<06:32,  8.18s/it]

VAE train ep27:  72%|███████▏  | 118/165 [15:56<06:22,  8.13s/it]

VAE train ep27:  72%|███████▏  | 119/165 [16:04<06:15,  8.16s/it]

VAE train ep27:  73%|███████▎  | 120/165 [16:12<06:09,  8.20s/it]

VAE train ep27:  73%|███████▎  | 121/165 [16:21<06:01,  8.23s/it]

VAE train ep27:  74%|███████▍  | 122/165 [16:29<05:53,  8.21s/it]

VAE train ep27:  75%|███████▍  | 123/165 [16:37<05:43,  8.18s/it]

VAE train ep27:  75%|███████▌  | 124/165 [16:45<05:34,  8.16s/it]

VAE train ep27:  76%|███████▌  | 125/165 [16:53<05:25,  8.15s/it]

VAE train ep27:  76%|███████▋  | 126/165 [17:01<05:13,  8.04s/it]

VAE train ep27:  77%|███████▋  | 127/165 [17:09<05:05,  8.03s/it]

VAE train ep27:  78%|███████▊  | 128/165 [17:17<04:55,  7.99s/it]

VAE train ep27:  78%|███████▊  | 129/165 [17:25<04:49,  8.05s/it]

VAE train ep27:  79%|███████▉  | 130/165 [17:33<04:42,  8.07s/it]

VAE train ep27:  79%|███████▉  | 131/165 [17:41<04:34,  8.06s/it]

VAE train ep27:  80%|████████  | 132/165 [17:49<04:25,  8.04s/it]

VAE train ep27:  81%|████████  | 133/165 [17:57<04:19,  8.12s/it]

VAE train ep27:  81%|████████  | 134/165 [18:05<04:11,  8.11s/it]

VAE train ep27:  82%|████████▏ | 135/165 [18:14<04:03,  8.13s/it]

VAE train ep27:  82%|████████▏ | 136/165 [18:22<03:56,  8.14s/it]

VAE train ep27:  83%|████████▎ | 137/165 [18:30<03:46,  8.10s/it]

VAE train ep27:  84%|████████▎ | 138/165 [18:38<03:38,  8.10s/it]

VAE train ep27:  84%|████████▍ | 139/165 [18:46<03:32,  8.16s/it]

VAE train ep27:  85%|████████▍ | 140/165 [18:54<03:23,  8.12s/it]

VAE train ep27:  85%|████████▌ | 141/165 [19:02<03:15,  8.14s/it]

VAE train ep27:  86%|████████▌ | 142/165 [19:10<03:06,  8.11s/it]

VAE train ep27:  87%|████████▋ | 143/165 [19:19<02:57,  8.08s/it]

VAE train ep27:  87%|████████▋ | 144/165 [19:27<02:50,  8.10s/it]

VAE train ep27:  88%|████████▊ | 145/165 [19:35<02:43,  8.16s/it]

VAE train ep27:  88%|████████▊ | 146/165 [19:43<02:34,  8.13s/it]

VAE train ep27:  89%|████████▉ | 147/165 [19:51<02:26,  8.16s/it]

VAE train ep27:  90%|████████▉ | 148/165 [20:00<02:19,  8.22s/it]

VAE train ep27:  90%|█████████ | 149/165 [20:08<02:11,  8.25s/it]

VAE train ep27:  91%|█████████ | 150/165 [20:16<02:03,  8.21s/it]

VAE train ep27:  92%|█████████▏| 151/165 [20:24<01:54,  8.17s/it]

VAE train ep27:  92%|█████████▏| 152/165 [20:32<01:45,  8.13s/it]

VAE train ep27:  93%|█████████▎| 153/165 [20:40<01:36,  8.07s/it]

VAE train ep27:  93%|█████████▎| 154/165 [20:48<01:28,  8.07s/it]

VAE train ep27:  94%|█████████▍| 155/165 [20:56<01:20,  8.05s/it]

VAE train ep27:  95%|█████████▍| 156/165 [21:04<01:12,  8.07s/it]

VAE train ep27:  95%|█████████▌| 157/165 [21:13<01:05,  8.16s/it]

VAE train ep27:  96%|█████████▌| 158/165 [21:21<00:56,  8.13s/it]

VAE train ep27:  96%|█████████▋| 159/165 [21:29<00:48,  8.12s/it]

VAE train ep27:  97%|█████████▋| 160/165 [21:37<00:40,  8.12s/it]

VAE train ep27:  98%|█████████▊| 161/165 [21:45<00:32,  8.14s/it]

VAE train ep27:  98%|█████████▊| 162/165 [21:53<00:24,  8.10s/it]

VAE train ep27:  99%|█████████▉| 163/165 [22:01<00:16,  8.10s/it]

VAE train ep27:  99%|█████████▉| 164/165 [22:09<00:08,  8.09s/it]

VAE train ep27: 100%|██████████| 165/165 [22:10<00:00,  5.84s/it]

VAE val ep27:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep27:   3%|▎         | 1/29 [00:02<01:00,  2.17s/it]

VAE val ep27:   7%|▋         | 2/29 [00:04<00:58,  2.15s/it]

VAE val ep27:  10%|█         | 3/29 [00:06<00:56,  2.16s/it]

VAE val ep27:  14%|█▍        | 4/29 [00:08<00:54,  2.16s/it]

VAE val ep27:  17%|█▋        | 5/29 [00:10<00:52,  2.17s/it]

VAE val ep27:  21%|██        | 6/29 [00:13<00:50,  2.18s/it]

VAE val ep27:  24%|██▍       | 7/29 [00:15<00:47,  2.17s/it]

VAE val ep27:  28%|██▊       | 8/29 [00:17<00:45,  2.17s/it]

VAE val ep27:  31%|███       | 9/29 [00:19<00:43,  2.16s/it]

VAE val ep27:  34%|███▍      | 10/29 [00:21<00:41,  2.16s/it]

VAE val ep27:  38%|███▊      | 11/29 [00:23<00:38,  2.16s/it]

VAE val ep27:  41%|████▏     | 12/29 [00:25<00:36,  2.16s/it]

VAE val ep27:  45%|████▍     | 13/29 [00:28<00:34,  2.17s/it]

VAE val ep27:  48%|████▊     | 14/29 [00:30<00:32,  2.17s/it]

VAE val ep27:  52%|█████▏    | 15/29 [00:32<00:30,  2.20s/it]

VAE val ep27:  55%|█████▌    | 16/29 [00:34<00:28,  2.18s/it]

VAE val ep27:  59%|█████▊    | 17/29 [00:36<00:26,  2.17s/it]

VAE val ep27:  62%|██████▏   | 18/29 [00:39<00:23,  2.16s/it]

VAE val ep27:  66%|██████▌   | 19/29 [00:41<00:21,  2.16s/it]

VAE val ep27:  69%|██████▉   | 20/29 [00:43<00:19,  2.16s/it]

VAE val ep27:  72%|███████▏  | 21/29 [00:45<00:17,  2.16s/it]

VAE val ep27:  76%|███████▌  | 22/29 [00:47<00:15,  2.16s/it]

VAE val ep27:  79%|███████▉  | 23/29 [00:49<00:12,  2.16s/it]

VAE val ep27:  83%|████████▎ | 24/29 [00:51<00:10,  2.16s/it]

VAE val ep27:  86%|████████▌ | 25/29 [00:54<00:08,  2.15s/it]

VAE val ep27:  90%|████████▉ | 26/29 [00:56<00:06,  2.15s/it]

VAE val ep27:  93%|█████████▎| 27/29 [00:58<00:04,  2.14s/it]

VAE val ep27:  97%|█████████▋| 28/29 [01:00<00:02,  2.15s/it]

VAE val ep27: 100%|██████████| 29/29 [01:00<00:00,  1.59s/it]

VAE train ep28:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep28:   1%|          | 1/165 [00:08<23:51,  8.73s/it]

VAE train ep28:   1%|          | 2/165 [00:17<23:04,  8.50s/it]

VAE train ep28:   2%|▏         | 3/165 [00:25<22:36,  8.37s/it]

VAE train ep28:   2%|▏         | 4/165 [00:33<22:11,  8.27s/it]

VAE train ep28:   3%|▎         | 5/165 [00:41<21:52,  8.20s/it]

VAE train ep28:   4%|▎         | 6/165 [00:49<21:38,  8.17s/it]

VAE train ep28:   4%|▍         | 7/165 [00:57<21:24,  8.13s/it]

VAE train ep28:   5%|▍         | 8/165 [01:05<21:13,  8.11s/it]

VAE train ep28:   5%|▌         | 9/165 [01:13<21:04,  8.11s/it]

VAE train ep28:   6%|▌         | 10/165 [01:21<20:54,  8.10s/it]

VAE train ep28:   7%|▋         | 11/165 [01:29<20:36,  8.03s/it]

VAE train ep28:   7%|▋         | 12/165 [01:37<20:26,  8.02s/it]

VAE train ep28:   8%|▊         | 13/165 [01:45<20:26,  8.07s/it]

VAE train ep28:   8%|▊         | 14/165 [01:54<20:25,  8.12s/it]

VAE train ep28:   9%|▉         | 15/165 [02:02<20:15,  8.11s/it]

VAE train ep28:  10%|▉         | 16/165 [02:10<20:06,  8.10s/it]

VAE train ep28:  10%|█         | 17/165 [02:18<20:07,  8.16s/it]

VAE train ep28:  11%|█         | 18/165 [02:26<19:49,  8.09s/it]

VAE train ep28:  12%|█▏        | 19/165 [02:34<19:34,  8.04s/it]

VAE train ep28:  12%|█▏        | 20/165 [02:42<19:22,  8.01s/it]

VAE train ep28:  13%|█▎        | 21/165 [02:50<19:20,  8.06s/it]

VAE train ep28:  13%|█▎        | 22/165 [02:58<19:20,  8.12s/it]

VAE train ep28:  14%|█▍        | 23/165 [03:07<19:20,  8.17s/it]

VAE train ep28:  15%|█▍        | 24/165 [03:15<19:23,  8.25s/it]

VAE train ep28:  15%|█▌        | 25/165 [03:24<19:24,  8.32s/it]

VAE train ep28:  16%|█▌        | 26/165 [03:32<19:16,  8.32s/it]

VAE train ep28:  16%|█▋        | 27/165 [03:40<19:01,  8.28s/it]

VAE train ep28:  17%|█▋        | 28/165 [03:48<18:45,  8.22s/it]

VAE train ep28:  18%|█▊        | 29/165 [03:57<18:46,  8.29s/it]

VAE train ep28:  18%|█▊        | 30/165 [04:05<18:33,  8.24s/it]

VAE train ep28:  19%|█▉        | 31/165 [04:13<18:23,  8.24s/it]

VAE train ep28:  19%|█▉        | 32/165 [04:21<18:10,  8.20s/it]

VAE train ep28:  20%|██        | 33/165 [04:29<18:07,  8.24s/it]

VAE train ep28:  21%|██        | 34/165 [04:38<18:00,  8.25s/it]

VAE train ep28:  21%|██        | 35/165 [04:46<17:52,  8.25s/it]

VAE train ep28:  22%|██▏       | 36/165 [04:54<17:46,  8.26s/it]

VAE train ep28:  22%|██▏       | 37/165 [05:02<17:35,  8.25s/it]

VAE train ep28:  23%|██▎       | 38/165 [05:11<17:21,  8.20s/it]

VAE train ep28:  24%|██▎       | 39/165 [05:19<17:11,  8.19s/it]

VAE train ep28:  24%|██▍       | 40/165 [05:27<17:03,  8.19s/it]

VAE train ep28:  25%|██▍       | 41/165 [05:35<16:57,  8.21s/it]

VAE train ep28:  25%|██▌       | 42/165 [05:43<16:49,  8.21s/it]

VAE train ep28:  26%|██▌       | 43/165 [05:51<16:39,  8.19s/it]

VAE train ep28:  27%|██▋       | 44/165 [06:00<16:35,  8.23s/it]

VAE train ep28:  27%|██▋       | 45/165 [06:08<16:27,  8.23s/it]

VAE train ep28:  28%|██▊       | 46/165 [06:16<16:13,  8.18s/it]

VAE train ep28:  28%|██▊       | 47/165 [06:24<16:01,  8.14s/it]

VAE train ep28:  29%|██▉       | 48/165 [06:32<15:54,  8.16s/it]

VAE train ep28:  30%|██▉       | 49/165 [06:41<16:01,  8.29s/it]

VAE train ep28:  30%|███       | 50/165 [06:49<15:55,  8.31s/it]

VAE train ep28:  31%|███       | 51/165 [06:57<15:43,  8.28s/it]

VAE train ep28:  32%|███▏      | 52/165 [07:06<15:33,  8.26s/it]

VAE train ep28:  32%|███▏      | 53/165 [07:14<15:35,  8.35s/it]

VAE train ep28:  33%|███▎      | 54/165 [07:23<15:24,  8.33s/it]

VAE train ep28:  33%|███▎      | 55/165 [07:31<15:05,  8.24s/it]

VAE train ep28:  34%|███▍      | 56/165 [07:39<14:54,  8.20s/it]

VAE train ep28:  35%|███▍      | 57/165 [07:47<14:49,  8.24s/it]

VAE train ep28:  35%|███▌      | 58/165 [07:55<14:41,  8.24s/it]

VAE train ep28:  36%|███▌      | 59/165 [08:03<14:28,  8.19s/it]

VAE train ep28:  36%|███▋      | 60/165 [08:11<14:16,  8.15s/it]

VAE train ep28:  37%|███▋      | 61/165 [08:20<14:08,  8.16s/it]

VAE train ep28:  38%|███▊      | 62/165 [08:28<14:02,  8.18s/it]

VAE train ep28:  38%|███▊      | 63/165 [08:36<13:52,  8.16s/it]

VAE train ep28:  39%|███▉      | 64/165 [08:44<13:43,  8.15s/it]

VAE train ep28:  39%|███▉      | 65/165 [08:52<13:42,  8.23s/it]

VAE train ep28:  40%|████      | 66/165 [09:01<13:34,  8.23s/it]

VAE train ep28:  41%|████      | 67/165 [09:09<13:25,  8.21s/it]

VAE train ep28:  41%|████      | 68/165 [09:17<13:17,  8.22s/it]

VAE train ep28:  42%|████▏     | 69/165 [09:25<13:07,  8.20s/it]

VAE train ep28:  42%|████▏     | 70/165 [09:33<12:55,  8.16s/it]

VAE train ep28:  43%|████▎     | 71/165 [09:42<12:49,  8.19s/it]

VAE train ep28:  44%|████▎     | 72/165 [09:50<12:40,  8.18s/it]

VAE train ep28:  44%|████▍     | 73/165 [09:58<12:37,  8.23s/it]

VAE train ep28:  45%|████▍     | 74/165 [10:06<12:32,  8.27s/it]

VAE train ep28:  45%|████▌     | 75/165 [10:15<12:19,  8.22s/it]

VAE train ep28:  46%|████▌     | 76/165 [10:23<12:10,  8.21s/it]

VAE train ep28:  47%|████▋     | 77/165 [10:31<11:55,  8.14s/it]

VAE train ep28:  47%|████▋     | 78/165 [10:39<11:43,  8.08s/it]

VAE train ep28:  48%|████▊     | 79/165 [10:47<11:37,  8.11s/it]

VAE train ep28:  48%|████▊     | 80/165 [10:55<11:31,  8.13s/it]

VAE train ep28:  49%|████▉     | 81/165 [11:03<11:23,  8.14s/it]

VAE train ep28:  50%|████▉     | 82/165 [11:11<11:15,  8.14s/it]

VAE train ep28:  50%|█████     | 83/165 [11:19<11:07,  8.15s/it]

VAE train ep28:  51%|█████     | 84/165 [11:27<10:56,  8.10s/it]

VAE train ep28:  52%|█████▏    | 85/165 [11:36<10:47,  8.10s/it]

VAE train ep28:  52%|█████▏    | 86/165 [11:44<10:38,  8.08s/it]

VAE train ep28:  53%|█████▎    | 87/165 [11:52<10:28,  8.06s/it]

VAE train ep28:  53%|█████▎    | 88/165 [12:00<10:19,  8.04s/it]

VAE train ep28:  54%|█████▍    | 89/165 [12:08<10:14,  8.08s/it]

VAE train ep28:  55%|█████▍    | 90/165 [12:16<10:08,  8.12s/it]

VAE train ep28:  55%|█████▌    | 91/165 [12:24<10:04,  8.17s/it]

VAE train ep28:  56%|█████▌    | 92/165 [12:32<09:54,  8.15s/it]

VAE train ep28:  56%|█████▋    | 93/165 [12:41<09:46,  8.15s/it]

VAE train ep28:  57%|█████▋    | 94/165 [12:49<09:38,  8.15s/it]

VAE train ep28:  58%|█████▊    | 95/165 [12:57<09:28,  8.12s/it]

VAE train ep28:  58%|█████▊    | 96/165 [13:05<09:17,  8.07s/it]

VAE train ep28:  59%|█████▉    | 97/165 [13:13<09:11,  8.11s/it]

VAE train ep28:  59%|█████▉    | 98/165 [13:21<09:05,  8.14s/it]

VAE train ep28:  60%|██████    | 99/165 [13:29<08:55,  8.12s/it]

VAE train ep28:  61%|██████    | 100/165 [13:37<08:46,  8.10s/it]

VAE train ep28:  61%|██████    | 101/165 [13:45<08:35,  8.06s/it]

VAE train ep28:  62%|██████▏   | 102/165 [13:53<08:24,  8.00s/it]

VAE train ep28:  62%|██████▏   | 103/165 [14:01<08:14,  7.97s/it]

VAE train ep28:  63%|██████▎   | 104/165 [14:09<08:06,  7.97s/it]

VAE train ep28:  64%|██████▎   | 105/165 [14:17<07:57,  7.96s/it]

VAE train ep28:  64%|██████▍   | 106/165 [14:25<07:51,  7.99s/it]

VAE train ep28:  65%|██████▍   | 107/165 [14:33<07:48,  8.08s/it]

VAE train ep28:  65%|██████▌   | 108/165 [14:41<07:43,  8.14s/it]

VAE train ep28:  66%|██████▌   | 109/165 [14:50<07:39,  8.20s/it]

VAE train ep28:  67%|██████▋   | 110/165 [14:58<07:29,  8.17s/it]

VAE train ep28:  67%|██████▋   | 111/165 [15:06<07:20,  8.16s/it]

VAE train ep28:  68%|██████▊   | 112/165 [15:14<07:13,  8.18s/it]

VAE train ep28:  68%|██████▊   | 113/165 [15:22<07:04,  8.17s/it]

VAE train ep28:  69%|██████▉   | 114/165 [15:31<06:55,  8.15s/it]

VAE train ep28:  70%|██████▉   | 115/165 [15:38<06:44,  8.08s/it]

VAE train ep28:  70%|███████   | 116/165 [15:47<06:39,  8.15s/it]

VAE train ep28:  71%|███████   | 117/165 [15:55<06:35,  8.23s/it]

VAE train ep28:  72%|███████▏  | 118/165 [16:03<06:24,  8.18s/it]

VAE train ep28:  72%|███████▏  | 119/165 [16:11<06:15,  8.16s/it]

VAE train ep28:  73%|███████▎  | 120/165 [16:19<06:05,  8.12s/it]

VAE train ep28:  73%|███████▎  | 121/165 [16:28<05:58,  8.14s/it]

VAE train ep28:  74%|███████▍  | 122/165 [16:36<05:49,  8.12s/it]

VAE train ep28:  75%|███████▍  | 123/165 [16:44<05:39,  8.09s/it]

VAE train ep28:  75%|███████▌  | 124/165 [16:52<05:31,  8.07s/it]

VAE train ep28:  76%|███████▌  | 125/165 [17:00<05:25,  8.14s/it]

VAE train ep28:  76%|███████▋  | 126/165 [17:08<05:18,  8.17s/it]

VAE train ep28:  77%|███████▋  | 127/165 [17:16<05:10,  8.18s/it]

VAE train ep28:  78%|███████▊  | 128/165 [17:25<05:04,  8.23s/it]

VAE train ep28:  78%|███████▊  | 129/165 [17:33<05:00,  8.34s/it]

VAE train ep28:  79%|███████▉  | 130/165 [17:42<04:55,  8.45s/it]

VAE train ep28:  79%|███████▉  | 131/165 [17:51<04:48,  8.49s/it]

VAE train ep28:  80%|████████  | 132/165 [17:59<04:38,  8.45s/it]

VAE train ep28:  81%|████████  | 133/165 [18:07<04:30,  8.44s/it]

VAE train ep28:  81%|████████  | 134/165 [18:16<04:21,  8.45s/it]

VAE train ep28:  82%|████████▏ | 135/165 [18:24<04:13,  8.46s/it]

VAE train ep28:  82%|████████▏ | 136/165 [18:33<04:04,  8.42s/it]

VAE train ep28:  83%|████████▎ | 137/165 [18:41<03:56,  8.44s/it]

VAE train ep28:  84%|████████▎ | 138/165 [18:49<03:46,  8.38s/it]

VAE train ep28:  84%|████████▍ | 139/165 [18:58<03:36,  8.34s/it]

VAE train ep28:  85%|████████▍ | 140/165 [19:06<03:26,  8.28s/it]

VAE train ep28:  85%|████████▌ | 141/165 [19:14<03:19,  8.31s/it]

VAE train ep28:  86%|████████▌ | 142/165 [19:22<03:10,  8.27s/it]

VAE train ep28:  87%|████████▋ | 143/165 [19:31<03:02,  8.28s/it]

VAE train ep28:  87%|████████▋ | 144/165 [19:39<02:53,  8.28s/it]

VAE train ep28:  88%|████████▊ | 145/165 [19:48<02:47,  8.36s/it]

VAE train ep28:  88%|████████▊ | 146/165 [19:56<02:38,  8.35s/it]

VAE train ep28:  89%|████████▉ | 147/165 [20:04<02:29,  8.32s/it]

VAE train ep28:  90%|████████▉ | 148/165 [20:12<02:21,  8.34s/it]

VAE train ep28:  90%|█████████ | 149/165 [20:21<02:12,  8.29s/it]

VAE train ep28:  91%|█████████ | 150/165 [20:29<02:03,  8.26s/it]

VAE train ep28:  92%|█████████▏| 151/165 [20:37<01:54,  8.18s/it]

VAE train ep28:  92%|█████████▏| 152/165 [20:45<01:45,  8.12s/it]

VAE train ep28:  93%|█████████▎| 153/165 [20:53<01:37,  8.12s/it]

VAE train ep28:  93%|█████████▎| 154/165 [21:01<01:29,  8.14s/it]

VAE train ep28:  94%|█████████▍| 155/165 [21:09<01:21,  8.12s/it]

VAE train ep28:  95%|█████████▍| 156/165 [21:17<01:12,  8.10s/it]

VAE train ep28:  95%|█████████▌| 157/165 [21:26<01:05,  8.15s/it]

VAE train ep28:  96%|█████████▌| 158/165 [21:34<00:56,  8.13s/it]

VAE train ep28:  96%|█████████▋| 159/165 [21:42<00:48,  8.12s/it]

VAE train ep28:  97%|█████████▋| 160/165 [21:50<00:40,  8.12s/it]

VAE train ep28:  98%|█████████▊| 161/165 [21:58<00:32,  8.18s/it]

VAE train ep28:  98%|█████████▊| 162/165 [22:06<00:24,  8.19s/it]

VAE train ep28:  99%|█████████▉| 163/165 [22:15<00:16,  8.21s/it]

VAE train ep28:  99%|█████████▉| 164/165 [22:23<00:08,  8.22s/it]

VAE train ep28: 100%|██████████| 165/165 [22:23<00:00,  5.94s/it]

VAE val ep28:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep28:   3%|▎         | 1/29 [00:02<01:00,  2.18s/it]

VAE val ep28:   7%|▋         | 2/29 [00:04<00:58,  2.16s/it]

VAE val ep28:  10%|█         | 3/29 [00:06<00:56,  2.16s/it]

VAE val ep28:  14%|█▍        | 4/29 [00:08<00:54,  2.18s/it]

VAE val ep28:  17%|█▋        | 5/29 [00:10<00:52,  2.18s/it]

VAE val ep28:  21%|██        | 6/29 [00:13<00:50,  2.19s/it]

VAE val ep28:  24%|██▍       | 7/29 [00:15<00:48,  2.21s/it]

VAE val ep28:  28%|██▊       | 8/29 [00:17<00:46,  2.23s/it]

VAE val ep28:  31%|███       | 9/29 [00:19<00:44,  2.22s/it]

VAE val ep28:  34%|███▍      | 10/29 [00:21<00:41,  2.21s/it]

VAE val ep28:  38%|███▊      | 11/29 [00:24<00:39,  2.20s/it]

VAE val ep28:  41%|████▏     | 12/29 [00:26<00:37,  2.20s/it]

VAE val ep28:  45%|████▍     | 13/29 [00:28<00:35,  2.20s/it]

VAE val ep28:  48%|████▊     | 14/29 [00:30<00:33,  2.20s/it]

VAE val ep28:  52%|█████▏    | 15/29 [00:33<00:31,  2.23s/it]

VAE val ep28:  55%|█████▌    | 16/29 [00:35<00:28,  2.20s/it]

VAE val ep28:  59%|█████▊    | 17/29 [00:37<00:26,  2.20s/it]

VAE val ep28:  62%|██████▏   | 18/29 [00:39<00:24,  2.19s/it]

VAE val ep28:  66%|██████▌   | 19/29 [00:41<00:21,  2.18s/it]

VAE val ep28:  69%|██████▉   | 20/29 [00:43<00:19,  2.18s/it]

VAE val ep28:  72%|███████▏  | 21/29 [00:46<00:17,  2.17s/it]

VAE val ep28:  76%|███████▌  | 22/29 [00:48<00:15,  2.19s/it]

VAE val ep28:  79%|███████▉  | 23/29 [00:50<00:13,  2.19s/it]

VAE val ep28:  83%|████████▎ | 24/29 [00:52<00:11,  2.21s/it]

VAE val ep28:  86%|████████▌ | 25/29 [00:54<00:08,  2.20s/it]

VAE val ep28:  90%|████████▉ | 26/29 [00:57<00:06,  2.20s/it]

VAE val ep28:  93%|█████████▎| 27/29 [00:59<00:04,  2.19s/it]

VAE val ep28:  97%|█████████▋| 28/29 [01:01<00:02,  2.19s/it]

VAE val ep28: 100%|██████████| 29/29 [01:01<00:00,  1.64s/it]

VAE train ep29:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep29:   1%|          | 1/165 [00:08<23:12,  8.49s/it]

VAE train ep29:   1%|          | 2/165 [00:16<22:55,  8.44s/it]

VAE train ep29:   2%|▏         | 3/165 [00:25<22:41,  8.40s/it]

VAE train ep29:   2%|▏         | 4/165 [00:33<22:14,  8.29s/it]

VAE train ep29:   3%|▎         | 5/165 [00:41<21:56,  8.23s/it]

VAE train ep29:   4%|▎         | 6/165 [00:49<21:47,  8.22s/it]

VAE train ep29:   4%|▍         | 7/165 [00:57<21:40,  8.23s/it]

VAE train ep29:   5%|▍         | 8/165 [01:06<21:32,  8.23s/it]

VAE train ep29:   5%|▌         | 9/165 [01:14<21:40,  8.33s/it]

VAE train ep29:   6%|▌         | 10/165 [01:23<21:36,  8.36s/it]

VAE train ep29:   7%|▋         | 11/165 [01:31<21:27,  8.36s/it]

VAE train ep29:   7%|▋         | 12/165 [01:39<21:20,  8.37s/it]

VAE train ep29:   8%|▊         | 13/165 [01:48<21:06,  8.33s/it]

VAE train ep29:   8%|▊         | 14/165 [01:56<20:51,  8.29s/it]

VAE train ep29:   9%|▉         | 15/165 [02:04<20:33,  8.23s/it]

VAE train ep29:  10%|▉         | 16/165 [02:12<20:25,  8.22s/it]

VAE train ep29:  10%|█         | 17/165 [02:20<20:18,  8.23s/it]

VAE train ep29:  11%|█         | 18/165 [02:29<20:04,  8.20s/it]

VAE train ep29:  12%|█▏        | 19/165 [02:37<19:58,  8.21s/it]

VAE train ep29:  12%|█▏        | 20/165 [02:45<19:46,  8.18s/it]

VAE train ep29:  13%|█▎        | 21/165 [02:53<19:35,  8.16s/it]

VAE train ep29:  13%|█▎        | 22/165 [03:01<19:19,  8.11s/it]

VAE train ep29:  14%|█▍        | 23/165 [03:09<19:14,  8.13s/it]

VAE train ep29:  15%|█▍        | 24/165 [03:17<19:06,  8.13s/it]

VAE train ep29:  15%|█▌        | 25/165 [03:25<19:01,  8.15s/it]

VAE train ep29:  16%|█▌        | 26/165 [03:34<18:58,  8.19s/it]

VAE train ep29:  16%|█▋        | 27/165 [03:42<18:42,  8.13s/it]

VAE train ep29:  17%|█▋        | 28/165 [03:50<18:25,  8.07s/it]

VAE train ep29:  18%|█▊        | 29/165 [03:58<18:17,  8.07s/it]

VAE train ep29:  18%|█▊        | 30/165 [04:06<18:03,  8.03s/it]

VAE train ep29:  19%|█▉        | 31/165 [04:14<17:53,  8.01s/it]

VAE train ep29:  19%|█▉        | 32/165 [04:22<17:49,  8.04s/it]

VAE train ep29:  20%|██        | 33/165 [04:30<17:48,  8.10s/it]

VAE train ep29:  21%|██        | 34/165 [04:38<17:38,  8.08s/it]

VAE train ep29:  21%|██        | 35/165 [04:46<17:32,  8.10s/it]

VAE train ep29:  22%|██▏       | 36/165 [04:54<17:25,  8.10s/it]

VAE train ep29:  22%|██▏       | 37/165 [05:02<17:15,  8.09s/it]

VAE train ep29:  23%|██▎       | 38/165 [05:10<17:04,  8.07s/it]

VAE train ep29:  24%|██▎       | 39/165 [05:18<16:56,  8.07s/it]

VAE train ep29:  24%|██▍       | 40/165 [05:26<16:41,  8.01s/it]

VAE train ep29:  25%|██▍       | 41/165 [05:34<16:38,  8.05s/it]

VAE train ep29:  25%|██▌       | 42/165 [05:42<16:27,  8.03s/it]

VAE train ep29:  26%|██▌       | 43/165 [05:50<16:17,  8.01s/it]

VAE train ep29:  27%|██▋       | 44/165 [05:58<16:09,  8.01s/it]

VAE train ep29:  27%|██▋       | 45/165 [06:07<16:06,  8.06s/it]

VAE train ep29:  28%|██▊       | 46/165 [06:15<16:00,  8.07s/it]

VAE train ep29:  28%|██▊       | 47/165 [06:23<15:52,  8.07s/it]

VAE train ep29:  29%|██▉       | 48/165 [06:31<15:41,  8.05s/it]

VAE train ep29:  30%|██▉       | 49/165 [06:39<15:40,  8.11s/it]

VAE train ep29:  30%|███       | 50/165 [06:47<15:34,  8.12s/it]

VAE train ep29:  31%|███       | 51/165 [06:55<15:31,  8.17s/it]

VAE train ep29:  32%|███▏      | 52/165 [07:04<15:33,  8.26s/it]

VAE train ep29:  32%|███▏      | 53/165 [07:12<15:32,  8.33s/it]

VAE train ep29:  33%|███▎      | 54/165 [07:21<15:24,  8.33s/it]

VAE train ep29:  33%|███▎      | 55/165 [07:29<15:18,  8.35s/it]

VAE train ep29:  34%|███▍      | 56/165 [07:38<15:14,  8.39s/it]

VAE train ep29:  35%|███▍      | 57/165 [07:46<15:02,  8.36s/it]

VAE train ep29:  35%|███▌      | 58/165 [07:54<14:46,  8.29s/it]

VAE train ep29:  36%|███▌      | 59/165 [08:02<14:37,  8.28s/it]

VAE train ep29:  36%|███▋      | 60/165 [08:10<14:25,  8.25s/it]

VAE train ep29:  37%|███▋      | 61/165 [08:19<14:18,  8.25s/it]

VAE train ep29:  38%|███▊      | 62/165 [08:27<14:02,  8.18s/it]

VAE train ep29:  38%|███▊      | 63/165 [08:35<13:49,  8.13s/it]

VAE train ep29:  39%|███▉      | 64/165 [08:43<13:34,  8.06s/it]

VAE train ep29:  39%|███▉      | 65/165 [08:51<13:26,  8.06s/it]

VAE train ep29:  40%|████      | 66/165 [08:59<13:15,  8.04s/it]

VAE train ep29:  41%|████      | 67/165 [09:07<13:10,  8.07s/it]

VAE train ep29:  41%|████      | 68/165 [09:15<13:10,  8.15s/it]

VAE train ep29:  42%|████▏     | 69/165 [09:23<13:07,  8.20s/it]

VAE train ep29:  42%|████▏     | 70/165 [09:32<13:02,  8.23s/it]

VAE train ep29:  43%|████▎     | 71/165 [09:40<12:49,  8.19s/it]

VAE train ep29:  44%|████▎     | 72/165 [09:48<12:35,  8.12s/it]

VAE train ep29:  44%|████▍     | 73/165 [09:56<12:31,  8.17s/it]

VAE train ep29:  45%|████▍     | 74/165 [10:04<12:21,  8.14s/it]

VAE train ep29:  45%|████▌     | 75/165 [10:12<12:12,  8.13s/it]

VAE train ep29:  46%|████▌     | 76/165 [10:21<12:07,  8.18s/it]

VAE train ep29:  47%|████▋     | 77/165 [10:29<12:02,  8.21s/it]

VAE train ep29:  47%|████▋     | 78/165 [10:37<11:56,  8.23s/it]

VAE train ep29:  48%|████▊     | 79/165 [10:45<11:43,  8.18s/it]

VAE train ep29:  48%|████▊     | 80/165 [10:53<11:30,  8.12s/it]

VAE train ep29:  49%|████▉     | 81/165 [11:01<11:14,  8.03s/it]

VAE train ep29:  50%|████▉     | 82/165 [11:09<11:03,  7.99s/it]

VAE train ep29:  50%|█████     | 83/165 [11:17<10:54,  7.98s/it]

VAE train ep29:  51%|█████     | 84/165 [11:25<10:48,  8.00s/it]

VAE train ep29:  52%|█████▏    | 85/165 [11:33<10:43,  8.04s/it]

VAE train ep29:  52%|█████▏    | 86/165 [11:41<10:35,  8.04s/it]

VAE train ep29:  53%|█████▎    | 87/165 [11:49<10:29,  8.07s/it]

VAE train ep29:  53%|█████▎    | 88/165 [11:57<10:22,  8.09s/it]

VAE train ep29:  54%|█████▍    | 89/165 [12:06<10:19,  8.15s/it]

VAE train ep29:  55%|█████▍    | 90/165 [12:14<10:05,  8.08s/it]

VAE train ep29:  55%|█████▌    | 91/165 [12:22<09:55,  8.04s/it]

VAE train ep29:  56%|█████▌    | 92/165 [12:29<09:44,  8.00s/it]

VAE train ep29:  56%|█████▋    | 93/165 [12:38<09:39,  8.05s/it]

VAE train ep29:  57%|█████▋    | 94/165 [12:46<09:30,  8.04s/it]

VAE train ep29:  58%|█████▊    | 95/165 [12:53<09:18,  7.98s/it]

VAE train ep29:  58%|█████▊    | 96/165 [13:01<09:11,  8.00s/it]

VAE train ep29:  59%|█████▉    | 97/165 [13:10<09:08,  8.07s/it]

VAE train ep29:  59%|█████▉    | 98/165 [13:18<08:59,  8.05s/it]

VAE train ep29:  60%|██████    | 99/165 [13:26<08:51,  8.05s/it]

VAE train ep29:  61%|██████    | 100/165 [13:34<08:40,  8.00s/it]

VAE train ep29:  61%|██████    | 101/165 [13:42<08:32,  8.01s/it]

VAE train ep29:  62%|██████▏   | 102/165 [13:50<08:21,  7.96s/it]

VAE train ep29:  62%|██████▏   | 103/165 [13:57<08:09,  7.90s/it]

VAE train ep29:  63%|██████▎   | 104/165 [14:05<07:59,  7.86s/it]

VAE train ep29:  64%|██████▎   | 105/165 [14:13<07:51,  7.86s/it]

VAE train ep29:  64%|██████▍   | 106/165 [14:21<07:41,  7.82s/it]

VAE train ep29:  65%|██████▍   | 107/165 [14:28<07:32,  7.80s/it]

VAE train ep29:  65%|██████▌   | 108/165 [14:36<07:23,  7.77s/it]

VAE train ep29:  66%|██████▌   | 109/165 [14:44<07:16,  7.79s/it]

VAE train ep29:  67%|██████▋   | 110/165 [14:52<07:07,  7.78s/it]

VAE train ep29:  67%|██████▋   | 111/165 [15:00<07:01,  7.81s/it]

VAE train ep29:  68%|██████▊   | 112/165 [15:07<06:54,  7.83s/it]

VAE train ep29:  68%|██████▊   | 113/165 [15:15<06:48,  7.86s/it]

VAE train ep29:  69%|██████▉   | 114/165 [15:23<06:39,  7.84s/it]

VAE train ep29:  70%|██████▉   | 115/165 [15:31<06:31,  7.83s/it]

VAE train ep29:  70%|███████   | 116/165 [15:39<06:23,  7.82s/it]

VAE train ep29:  71%|███████   | 117/165 [15:47<06:16,  7.85s/it]

VAE train ep29:  72%|███████▏  | 118/165 [15:55<06:08,  7.84s/it]

VAE train ep29:  72%|███████▏  | 119/165 [16:02<06:00,  7.84s/it]

VAE train ep29:  73%|███████▎  | 120/165 [16:10<05:53,  7.85s/it]

VAE train ep29:  73%|███████▎  | 121/165 [16:18<05:49,  7.94s/it]

VAE train ep29:  74%|███████▍  | 122/165 [16:26<05:40,  7.93s/it]

VAE train ep29:  75%|███████▍  | 123/165 [16:34<05:30,  7.87s/it]

VAE train ep29:  75%|███████▌  | 124/165 [16:42<05:21,  7.84s/it]

VAE train ep29:  76%|███████▌  | 125/165 [16:50<05:14,  7.87s/it]

VAE train ep29:  76%|███████▋  | 126/165 [16:58<05:06,  7.86s/it]

VAE train ep29:  77%|███████▋  | 127/165 [17:05<04:57,  7.83s/it]

VAE train ep29:  78%|███████▊  | 128/165 [17:13<04:49,  7.83s/it]

VAE train ep29:  78%|███████▊  | 129/165 [17:21<04:44,  7.90s/it]

VAE train ep29:  79%|███████▉  | 130/165 [17:29<04:36,  7.90s/it]

VAE train ep29:  79%|███████▉  | 131/165 [17:37<04:27,  7.87s/it]

VAE train ep29:  80%|████████  | 132/165 [17:45<04:18,  7.82s/it]

VAE train ep29:  81%|████████  | 133/165 [17:53<04:11,  7.86s/it]

VAE train ep29:  81%|████████  | 134/165 [18:00<04:02,  7.84s/it]

VAE train ep29:  82%|████████▏ | 135/165 [18:08<03:55,  7.87s/it]

VAE train ep29:  82%|████████▏ | 136/165 [18:16<03:47,  7.86s/it]

VAE train ep29:  83%|████████▎ | 137/165 [18:24<03:41,  7.90s/it]

VAE train ep29:  84%|████████▎ | 138/165 [18:32<03:35,  7.97s/it]

VAE train ep29:  84%|████████▍ | 139/165 [18:40<03:27,  8.00s/it]

VAE train ep29:  85%|████████▍ | 140/165 [18:48<03:20,  8.01s/it]

VAE train ep29:  85%|████████▌ | 141/165 [18:56<03:12,  8.01s/it]

VAE train ep29:  86%|████████▌ | 142/165 [19:04<03:03,  7.98s/it]

VAE train ep29:  87%|████████▋ | 143/165 [19:12<02:56,  8.00s/it]

VAE train ep29:  87%|████████▋ | 144/165 [19:20<02:47,  7.97s/it]

VAE train ep29:  88%|████████▊ | 145/165 [19:28<02:40,  8.03s/it]

VAE train ep29:  88%|████████▊ | 146/165 [19:36<02:32,  8.02s/it]

VAE train ep29:  89%|████████▉ | 147/165 [19:45<02:25,  8.06s/it]

VAE train ep29:  90%|████████▉ | 148/165 [19:53<02:17,  8.06s/it]

VAE train ep29:  90%|█████████ | 149/165 [20:01<02:10,  8.14s/it]

VAE train ep29:  91%|█████████ | 150/165 [20:09<02:02,  8.17s/it]

VAE train ep29:  92%|█████████▏| 151/165 [20:18<01:54,  8.21s/it]

VAE train ep29:  92%|█████████▏| 152/165 [20:26<01:47,  8.24s/it]

VAE train ep29:  93%|█████████▎| 153/165 [20:34<01:39,  8.29s/it]

VAE train ep29:  93%|█████████▎| 154/165 [20:43<01:31,  8.29s/it]

VAE train ep29:  94%|█████████▍| 155/165 [20:51<01:22,  8.26s/it]

VAE train ep29:  95%|█████████▍| 156/165 [20:59<01:13,  8.16s/it]

VAE train ep29:  95%|█████████▌| 157/165 [21:07<01:04,  8.11s/it]

VAE train ep29:  96%|█████████▌| 158/165 [21:15<00:56,  8.13s/it]

VAE train ep29:  96%|█████████▋| 159/165 [21:23<00:49,  8.23s/it]

VAE train ep29:  97%|█████████▋| 160/165 [21:31<00:40,  8.20s/it]

VAE train ep29:  98%|█████████▊| 161/165 [21:40<00:32,  8.19s/it]

VAE train ep29:  98%|█████████▊| 162/165 [21:48<00:24,  8.12s/it]

VAE train ep29:  99%|█████████▉| 163/165 [21:56<00:16,  8.09s/it]

VAE train ep29:  99%|█████████▉| 164/165 [22:03<00:08,  8.01s/it]

VAE train ep29: 100%|██████████| 165/165 [22:04<00:00,  5.79s/it]

VAE val ep29:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep29:   3%|▎         | 1/29 [00:02<01:00,  2.17s/it]

VAE val ep29:   7%|▋         | 2/29 [00:04<00:58,  2.16s/it]

VAE val ep29:  10%|█         | 3/29 [00:06<00:55,  2.15s/it]

VAE val ep29:  14%|█▍        | 4/29 [00:08<00:53,  2.14s/it]

VAE val ep29:  17%|█▋        | 5/29 [00:10<00:51,  2.13s/it]

VAE val ep29:  21%|██        | 6/29 [00:12<00:49,  2.15s/it]

VAE val ep29:  24%|██▍       | 7/29 [00:15<00:47,  2.14s/it]

VAE val ep29:  28%|██▊       | 8/29 [00:17<00:44,  2.14s/it]

VAE val ep29:  31%|███       | 9/29 [00:19<00:42,  2.13s/it]

VAE val ep29:  34%|███▍      | 10/29 [00:21<00:40,  2.12s/it]

VAE val ep29:  38%|███▊      | 11/29 [00:23<00:38,  2.12s/it]

VAE val ep29:  41%|████▏     | 12/29 [00:25<00:36,  2.13s/it]

VAE val ep29:  45%|████▍     | 13/29 [00:27<00:34,  2.14s/it]

VAE val ep29:  48%|████▊     | 14/29 [00:29<00:32,  2.14s/it]

VAE val ep29:  52%|█████▏    | 15/29 [00:32<00:30,  2.17s/it]

VAE val ep29:  55%|█████▌    | 16/29 [00:34<00:27,  2.15s/it]

VAE val ep29:  59%|█████▊    | 17/29 [00:36<00:25,  2.14s/it]

VAE val ep29:  62%|██████▏   | 18/29 [00:38<00:23,  2.13s/it]

VAE val ep29:  66%|██████▌   | 19/29 [00:40<00:21,  2.13s/it]

VAE val ep29:  69%|██████▉   | 20/29 [00:42<00:19,  2.12s/it]

VAE val ep29:  72%|███████▏  | 21/29 [00:44<00:16,  2.11s/it]

VAE val ep29:  76%|███████▌  | 22/29 [00:46<00:14,  2.11s/it]

VAE val ep29:  79%|███████▉  | 23/29 [00:49<00:12,  2.10s/it]

VAE val ep29:  83%|████████▎ | 24/29 [00:51<00:10,  2.12s/it]

VAE val ep29:  86%|████████▌ | 25/29 [00:53<00:08,  2.13s/it]

VAE val ep29:  90%|████████▉ | 26/29 [00:55<00:06,  2.13s/it]

VAE val ep29:  93%|█████████▎| 27/29 [00:57<00:04,  2.13s/it]

VAE val ep29:  97%|█████████▋| 28/29 [00:59<00:02,  2.14s/it]

VAE val ep29: 100%|██████████| 29/29 [01:00<00:00,  1.59s/it]

VAE train ep30:   0%|          | 0/165 [00:00<?, ?it/s]

VAE train ep30:   1%|          | 1/165 [00:08<23:26,  8.58s/it]

VAE train ep30:   1%|          | 2/165 [00:16<22:52,  8.42s/it]

VAE train ep30:   2%|▏         | 3/165 [00:25<22:22,  8.28s/it]

VAE train ep30:   2%|▏         | 4/165 [00:32<21:49,  8.14s/it]

VAE train ep30:   3%|▎         | 5/165 [00:40<21:17,  7.98s/it]

VAE train ep30:   4%|▎         | 6/165 [00:48<20:59,  7.92s/it]

VAE train ep30:   4%|▍         | 7/165 [00:56<20:52,  7.92s/it]

VAE train ep30:   5%|▍         | 8/165 [01:04<20:40,  7.90s/it]

VAE train ep30:   5%|▌         | 9/165 [01:12<20:52,  8.03s/it]

VAE train ep30:   6%|▌         | 10/165 [01:20<20:46,  8.04s/it]

VAE train ep30:   7%|▋         | 11/165 [01:28<20:25,  7.96s/it]

VAE train ep30:   7%|▋         | 12/165 [01:36<20:10,  7.91s/it]

VAE train ep30:   8%|▊         | 13/165 [01:43<19:58,  7.88s/it]

VAE train ep30:   8%|▊         | 14/165 [01:51<19:55,  7.92s/it]

VAE train ep30:   9%|▉         | 15/165 [01:59<19:40,  7.87s/it]

VAE train ep30:  10%|▉         | 16/165 [02:07<19:26,  7.83s/it]

VAE train ep30:  10%|█         | 17/165 [02:15<19:19,  7.83s/it]

VAE train ep30:  11%|█         | 18/165 [02:23<19:21,  7.90s/it]

VAE train ep30:  12%|█▏        | 19/165 [02:31<19:20,  7.95s/it]

VAE train ep30:  12%|█▏        | 20/165 [02:39<19:14,  7.96s/it]

VAE train ep30:  13%|█▎        | 21/165 [02:47<19:09,  7.98s/it]

VAE train ep30:  13%|█▎        | 22/165 [02:55<18:57,  7.95s/it]

VAE train ep30:  14%|█▍        | 23/165 [03:03<18:41,  7.90s/it]

VAE train ep30:  15%|█▍        | 24/165 [03:10<18:27,  7.85s/it]

VAE train ep30:  15%|█▌        | 25/165 [03:18<18:16,  7.84s/it]

VAE train ep30:  16%|█▌        | 26/165 [03:26<18:15,  7.88s/it]

VAE train ep30:  16%|█▋        | 27/165 [03:34<18:01,  7.84s/it]

VAE train ep30:  17%|█▋        | 28/165 [03:42<17:52,  7.83s/it]

VAE train ep30:  18%|█▊        | 29/165 [03:49<17:40,  7.80s/it]

VAE train ep30:  18%|█▊        | 30/165 [03:57<17:40,  7.85s/it]

VAE train ep30:  19%|█▉        | 31/165 [04:05<17:34,  7.87s/it]

VAE train ep30:  19%|█▉        | 32/165 [04:13<17:27,  7.88s/it]

VAE train ep30:  20%|██        | 33/165 [04:21<17:14,  7.84s/it]

VAE train ep30:  21%|██        | 34/165 [04:29<17:06,  7.83s/it]

VAE train ep30:  21%|██        | 35/165 [04:36<16:52,  7.79s/it]

VAE train ep30:  22%|██▏       | 36/165 [04:44<16:52,  7.85s/it]

VAE train ep30:  22%|██▏       | 37/165 [04:52<16:49,  7.89s/it]

VAE train ep30:  23%|██▎       | 38/165 [05:00<16:43,  7.90s/it]

VAE train ep30:  24%|██▎       | 39/165 [05:08<16:32,  7.88s/it]

VAE train ep30:  24%|██▍       | 40/165 [05:16<16:30,  7.92s/it]

VAE train ep30:  25%|██▍       | 41/165 [05:24<16:26,  7.96s/it]

VAE train ep30:  25%|██▌       | 42/165 [05:33<16:43,  8.16s/it]

VAE train ep30:  26%|██▌       | 43/165 [05:41<16:46,  8.25s/it]

VAE train ep30:  27%|██▋       | 44/165 [05:49<16:30,  8.19s/it]

VAE train ep30:  27%|██▋       | 45/165 [05:57<16:14,  8.12s/it]

VAE train ep30:  28%|██▊       | 46/165 [06:05<16:03,  8.10s/it]

VAE train ep30:  28%|██▊       | 47/165 [06:13<15:48,  8.04s/it]

VAE train ep30:  29%|██▉       | 48/165 [06:22<15:47,  8.09s/it]

VAE train ep30:  30%|██▉       | 49/165 [06:30<15:40,  8.11s/it]

VAE train ep30:  30%|███       | 50/165 [06:38<15:27,  8.07s/it]

VAE train ep30:  31%|███       | 51/165 [06:46<15:22,  8.09s/it]

VAE train ep30:  32%|███▏      | 52/165 [06:54<15:19,  8.14s/it]

VAE train ep30:  32%|███▏      | 53/165 [07:02<15:11,  8.14s/it]

VAE train ep30:  33%|███▎      | 54/165 [07:10<14:59,  8.10s/it]

VAE train ep30:  33%|███▎      | 55/165 [07:18<14:47,  8.06s/it]

VAE train ep30:  34%|███▍      | 56/165 [07:26<14:35,  8.03s/it]

VAE train ep30:  35%|███▍      | 57/165 [07:34<14:21,  7.98s/it]

VAE train ep30:  35%|███▌      | 58/165 [07:42<14:16,  8.01s/it]

VAE train ep30:  36%|███▌      | 59/165 [07:50<14:03,  7.96s/it]

VAE train ep30:  36%|███▋      | 60/165 [07:58<13:52,  7.93s/it]

VAE train ep30:  37%|███▋      | 61/165 [08:06<13:43,  7.92s/it]

VAE train ep30:  38%|███▊      | 62/165 [08:14<13:38,  7.95s/it]

VAE train ep30:  38%|███▊      | 63/165 [08:22<13:28,  7.92s/it]

VAE train ep30:  39%|███▉      | 64/165 [08:29<13:17,  7.90s/it]

VAE train ep30:  39%|███▉      | 65/165 [08:37<13:09,  7.89s/it]

VAE train ep30:  40%|████      | 66/165 [08:45<13:04,  7.92s/it]

VAE train ep30:  41%|████      | 67/165 [08:53<12:53,  7.90s/it]

VAE train ep30:  41%|████      | 68/165 [09:01<12:41,  7.85s/it]

VAE train ep30:  42%|████▏     | 69/165 [09:09<12:33,  7.85s/it]

VAE train ep30:  42%|████▏     | 70/165 [09:17<12:29,  7.89s/it]

VAE train ep30:  43%|████▎     | 71/165 [09:24<12:19,  7.87s/it]

VAE train ep30:  44%|████▎     | 72/165 [09:32<12:08,  7.83s/it]

VAE train ep30:  44%|████▍     | 73/165 [09:40<11:52,  7.74s/it]

VAE train ep30:  45%|████▍     | 74/165 [09:48<11:45,  7.75s/it]

VAE train ep30:  45%|████▌     | 75/165 [09:55<11:35,  7.73s/it]

VAE train ep30:  46%|████▌     | 76/165 [10:03<11:31,  7.77s/it]

VAE train ep30:  47%|████▋     | 77/165 [10:11<11:21,  7.75s/it]

VAE train ep30:  47%|████▋     | 78/165 [10:19<11:21,  7.83s/it]

VAE train ep30:  48%|████▊     | 79/165 [10:27<11:12,  7.82s/it]

VAE train ep30:  48%|████▊     | 80/165 [10:34<11:01,  7.78s/it]

VAE train ep30:  49%|████▉     | 81/165 [10:42<10:52,  7.77s/it]

VAE train ep30:  50%|████▉     | 82/165 [10:50<10:43,  7.75s/it]

VAE train ep30:  50%|█████     | 83/165 [10:57<10:33,  7.73s/it]

VAE train ep30:  51%|█████     | 84/165 [11:05<10:26,  7.74s/it]

VAE train ep30:  52%|█████▏    | 85/165 [11:13<10:23,  7.79s/it]

VAE train ep30:  52%|█████▏    | 86/165 [11:21<10:18,  7.83s/it]

VAE train ep30:  53%|█████▎    | 87/165 [11:29<10:09,  7.81s/it]

VAE train ep30:  53%|█████▎    | 88/165 [11:36<09:59,  7.78s/it]

VAE train ep30:  54%|█████▍    | 89/165 [11:44<09:45,  7.71s/it]

VAE train ep30:  55%|█████▍    | 90/165 [11:52<09:41,  7.75s/it]

VAE train ep30:  55%|█████▌    | 91/165 [12:00<09:33,  7.75s/it]

VAE train ep30:  56%|█████▌    | 92/165 [12:07<09:25,  7.75s/it]

VAE train ep30:  56%|█████▋    | 93/165 [12:15<09:19,  7.77s/it]

VAE train ep30:  57%|█████▋    | 94/165 [12:23<09:15,  7.83s/it]

VAE train ep30:  58%|█████▊    | 95/165 [12:31<09:07,  7.82s/it]

VAE train ep30:  58%|█████▊    | 96/165 [12:39<08:59,  7.81s/it]

VAE train ep30:  59%|█████▉    | 97/165 [12:47<08:53,  7.85s/it]

VAE train ep30:  59%|█████▉    | 98/165 [12:55<08:47,  7.87s/it]

VAE train ep30:  60%|██████    | 99/165 [13:02<08:35,  7.81s/it]

VAE train ep30:  61%|██████    | 100/165 [13:10<08:26,  7.79s/it]

VAE train ep30:  61%|██████    | 101/165 [13:18<08:24,  7.88s/it]

VAE train ep30:  62%|██████▏   | 102/165 [13:26<08:20,  7.95s/it]

VAE train ep30:  62%|██████▏   | 103/165 [13:34<08:11,  7.93s/it]

VAE train ep30:  63%|██████▎   | 104/165 [13:42<08:05,  7.96s/it]

VAE train ep30:  64%|██████▎   | 105/165 [13:50<07:54,  7.90s/it]

VAE train ep30:  64%|██████▍   | 106/165 [13:58<07:44,  7.87s/it]

VAE train ep30:  65%|██████▍   | 107/165 [14:05<07:31,  7.79s/it]

VAE train ep30:  65%|██████▌   | 108/165 [14:13<07:27,  7.84s/it]

VAE train ep30:  66%|██████▌   | 109/165 [14:21<07:16,  7.80s/it]

VAE train ep30:  67%|██████▋   | 110/165 [14:29<07:07,  7.77s/it]

VAE train ep30:  67%|██████▋   | 111/165 [14:36<06:58,  7.75s/it]

VAE train ep30:  68%|██████▊   | 112/165 [14:44<06:50,  7.74s/it]

VAE train ep30:  68%|██████▊   | 113/165 [14:52<06:42,  7.73s/it]

VAE train ep30:  69%|██████▉   | 114/165 [14:59<06:33,  7.72s/it]

VAE train ep30:  70%|██████▉   | 115/165 [15:07<06:24,  7.70s/it]

VAE train ep30:  70%|███████   | 116/165 [15:15<06:17,  7.71s/it]

VAE train ep30:  71%|███████   | 117/165 [15:23<06:09,  7.70s/it]

VAE train ep30:  72%|███████▏  | 118/165 [15:30<06:03,  7.73s/it]

VAE train ep30:  72%|███████▏  | 119/165 [15:38<05:52,  7.66s/it]

VAE train ep30:  73%|███████▎  | 120/165 [15:45<05:41,  7.59s/it]

VAE train ep30:  73%|███████▎  | 121/165 [15:53<05:34,  7.60s/it]

VAE train ep30:  74%|███████▍  | 122/165 [16:00<05:25,  7.57s/it]

VAE train ep30:  75%|███████▍  | 123/165 [16:08<05:20,  7.64s/it]

VAE train ep30:  75%|███████▌  | 124/165 [16:16<05:15,  7.70s/it]

VAE train ep30:  76%|███████▌  | 125/165 [16:24<05:07,  7.70s/it]

VAE train ep30:  76%|███████▋  | 126/165 [16:32<05:01,  7.73s/it]

VAE train ep30:  77%|███████▋  | 127/165 [16:39<04:53,  7.72s/it]

VAE train ep30:  78%|███████▊  | 128/165 [16:47<04:47,  7.78s/it]

VAE train ep30:  78%|███████▊  | 129/165 [16:55<04:42,  7.85s/it]

VAE train ep30:  79%|███████▉  | 130/165 [17:03<04:36,  7.91s/it]

VAE train ep30:  79%|███████▉  | 131/165 [17:11<04:32,  8.01s/it]

VAE train ep30:  80%|████████  | 132/165 [17:20<04:25,  8.05s/it]

VAE train ep30:  81%|████████  | 133/165 [17:27<04:16,  8.00s/it]

VAE train ep30:  81%|████████  | 134/165 [17:35<04:06,  7.96s/it]

VAE train ep30:  82%|████████▏ | 135/165 [17:43<03:59,  7.99s/it]

VAE train ep30:  82%|████████▏ | 136/165 [17:51<03:50,  7.96s/it]

VAE train ep30:  83%|████████▎ | 137/165 [17:59<03:42,  7.95s/it]

VAE train ep30:  84%|████████▎ | 138/165 [18:07<03:35,  7.98s/it]

VAE train ep30:  84%|████████▍ | 139/165 [18:15<03:27,  8.00s/it]

VAE train ep30:  85%|████████▍ | 140/165 [18:23<03:19,  7.97s/it]

VAE train ep30:  85%|████████▌ | 141/165 [18:31<03:11,  7.97s/it]

VAE train ep30:  86%|████████▌ | 142/165 [18:39<03:04,  8.02s/it]

VAE train ep30:  87%|████████▋ | 143/165 [18:47<02:57,  8.08s/it]

VAE train ep30:  87%|████████▋ | 144/165 [18:55<02:47,  7.99s/it]

VAE train ep30:  88%|████████▊ | 145/165 [19:03<02:39,  7.97s/it]

VAE train ep30:  88%|████████▊ | 146/165 [19:11<02:32,  8.00s/it]

VAE train ep30:  89%|████████▉ | 147/165 [19:19<02:24,  8.02s/it]

VAE train ep30:  90%|████████▉ | 148/165 [19:27<02:16,  8.02s/it]

VAE train ep30:  90%|█████████ | 149/165 [19:35<02:07,  7.99s/it]

VAE train ep30:  91%|█████████ | 150/165 [19:44<02:01,  8.07s/it]

VAE train ep30:  92%|█████████▏| 151/165 [19:52<01:53,  8.11s/it]

VAE train ep30:  92%|█████████▏| 152/165 [20:00<01:44,  8.05s/it]

VAE train ep30:  93%|█████████▎| 153/165 [20:08<01:36,  8.02s/it]

VAE train ep30:  93%|█████████▎| 154/165 [20:16<01:28,  8.00s/it]

VAE train ep30:  94%|█████████▍| 155/165 [20:24<01:20,  8.09s/it]

VAE train ep30:  95%|█████████▍| 156/165 [20:32<01:12,  8.10s/it]

VAE train ep30:  95%|█████████▌| 157/165 [20:40<01:04,  8.05s/it]

VAE train ep30:  96%|█████████▌| 158/165 [20:48<00:56,  8.10s/it]

VAE train ep30:  96%|█████████▋| 159/165 [20:56<00:48,  8.13s/it]

VAE train ep30:  97%|█████████▋| 160/165 [21:04<00:40,  8.09s/it]

VAE train ep30:  98%|█████████▊| 161/165 [21:12<00:32,  8.09s/it]

VAE train ep30:  98%|█████████▊| 162/165 [21:20<00:24,  8.03s/it]

VAE train ep30:  99%|█████████▉| 163/165 [21:28<00:15,  7.98s/it]

VAE train ep30:  99%|█████████▉| 164/165 [21:36<00:07,  7.94s/it]

VAE train ep30: 100%|██████████| 165/165 [21:37<00:00,  5.71s/it]

VAE val ep30:   0%|          | 0/29 [00:00<?, ?it/s]

VAE val ep30:   3%|▎         | 1/29 [00:02<01:00,  2.16s/it]

VAE val ep30:   7%|▋         | 2/29 [00:04<00:59,  2.19s/it]

VAE val ep30:  10%|█         | 3/29 [00:06<00:56,  2.19s/it]

VAE val ep30:  14%|█▍        | 4/29 [00:08<00:54,  2.18s/it]

VAE val ep30:  17%|█▋        | 5/29 [00:10<00:52,  2.17s/it]

VAE val ep30:  21%|██        | 6/29 [00:13<00:49,  2.16s/it]

VAE val ep30:  24%|██▍       | 7/29 [00:15<00:47,  2.16s/it]

VAE val ep30:  28%|██▊       | 8/29 [00:17<00:46,  2.20s/it]

VAE val ep30:  31%|███       | 9/29 [00:19<00:43,  2.19s/it]

VAE val ep30:  34%|███▍      | 10/29 [00:21<00:41,  2.18s/it]

VAE val ep30:  38%|███▊      | 11/29 [00:23<00:39,  2.18s/it]

VAE val ep30:  41%|████▏     | 12/29 [00:26<00:37,  2.18s/it]

VAE val ep30:  45%|████▍     | 13/29 [00:28<00:34,  2.16s/it]

VAE val ep30:  48%|████▊     | 14/29 [00:30<00:32,  2.16s/it]

VAE val ep30:  52%|█████▏    | 15/29 [00:32<00:30,  2.15s/it]

VAE val ep30:  55%|█████▌    | 16/29 [00:34<00:28,  2.17s/it]

VAE val ep30:  59%|█████▊    | 17/29 [00:36<00:26,  2.18s/it]

VAE val ep30:  62%|██████▏   | 18/29 [00:39<00:23,  2.18s/it]

VAE val ep30:  66%|██████▌   | 19/29 [00:41<00:21,  2.18s/it]

VAE val ep30:  69%|██████▉   | 20/29 [00:43<00:19,  2.20s/it]

VAE val ep30:  72%|███████▏  | 21/29 [00:45<00:17,  2.20s/it]

VAE val ep30:  76%|███████▌  | 22/29 [00:48<00:15,  2.23s/it]

VAE val ep30:  79%|███████▉  | 23/29 [00:50<00:13,  2.21s/it]

VAE val ep30:  83%|████████▎ | 24/29 [00:52<00:10,  2.20s/it]

VAE val ep30:  86%|████████▌ | 25/29 [00:54<00:08,  2.21s/it]

VAE val ep30:  90%|████████▉ | 26/29 [00:56<00:06,  2.19s/it]

VAE val ep30:  93%|█████████▎| 27/29 [00:58<00:04,  2.17s/it]

VAE val ep30:  97%|█████████▋| 28/29 [01:01<00:02,  2.17s/it]

VAE val ep30: 100%|██████████| 29/29 [01:01<00:00,  1.61s/it]

encode split:   0%|          | 0/165 [00:00<?, ?it/s]

encode split:   1%|          | 1/165 [00:00<02:16,  1.20it/s]

encode split:   1%|          | 2/165 [00:01<02:18,  1.18it/s]

encode split:   2%|▏         | 3/165 [00:02<02:20,  1.15it/s]

encode split:   2%|▏         | 4/165 [00:03<02:18,  1.17it/s]

encode split:   3%|▎         | 5/165 [00:04<02:17,  1.17it/s]

encode split:   4%|▎         | 6/165 [00:05<02:16,  1.17it/s]

encode split:   4%|▍         | 7/165 [00:05<02:15,  1.17it/s]

encode split:   5%|▍         | 8/165 [00:06<02:13,  1.18it/s]

encode split:   5%|▌         | 9/165 [00:07<02:12,  1.18it/s]

encode split:   6%|▌         | 10/165 [00:08<02:10,  1.18it/s]

encode split:   7%|▋         | 11/165 [00:09<02:10,  1.18it/s]

encode split:   7%|▋         | 12/165 [00:10<02:08,  1.19it/s]

encode split:   8%|▊         | 13/165 [00:11<02:06,  1.20it/s]

encode split:   8%|▊         | 14/165 [00:11<02:08,  1.18it/s]

encode split:   9%|▉         | 15/165 [00:12<02:07,  1.18it/s]

encode split:  10%|▉         | 16/165 [00:13<02:06,  1.17it/s]

encode split:  10%|█         | 17/165 [00:14<02:06,  1.17it/s]

encode split:  11%|█         | 18/165 [00:15<02:04,  1.18it/s]

encode split:  12%|█▏        | 19/165 [00:16<02:07,  1.14it/s]

encode split:  12%|█▏        | 20/165 [00:17<02:04,  1.16it/s]

encode split:  13%|█▎        | 21/165 [00:17<02:03,  1.17it/s]

encode split:  13%|█▎        | 22/165 [00:18<02:03,  1.15it/s]

encode split:  14%|█▍        | 23/165 [00:19<02:03,  1.15it/s]

encode split:  15%|█▍        | 24/165 [00:20<02:02,  1.15it/s]

encode split:  15%|█▌        | 25/165 [00:21<02:00,  1.16it/s]

encode split:  16%|█▌        | 26/165 [00:22<02:01,  1.15it/s]

encode split:  16%|█▋        | 27/165 [00:23<01:59,  1.16it/s]

encode split:  17%|█▋        | 28/165 [00:23<01:57,  1.16it/s]

encode split:  18%|█▊        | 29/165 [00:24<01:56,  1.17it/s]

encode split:  18%|█▊        | 30/165 [00:25<01:55,  1.17it/s]

encode split:  19%|█▉        | 31/165 [00:26<01:54,  1.17it/s]

encode split:  19%|█▉        | 32/165 [00:27<01:52,  1.18it/s]

encode split:  20%|██        | 33/165 [00:28<01:51,  1.19it/s]

encode split:  21%|██        | 34/165 [00:29<01:50,  1.18it/s]

encode split:  21%|██        | 35/165 [00:29<01:49,  1.19it/s]

encode split:  22%|██▏       | 36/165 [00:30<01:48,  1.19it/s]

encode split:  22%|██▏       | 37/165 [00:31<01:48,  1.18it/s]

encode split:  23%|██▎       | 38/165 [00:32<01:50,  1.15it/s]

encode split:  24%|██▎       | 39/165 [00:33<01:49,  1.15it/s]

encode split:  24%|██▍       | 40/165 [00:34<01:48,  1.15it/s]

encode split:  25%|██▍       | 41/165 [00:35<01:46,  1.16it/s]

encode split:  25%|██▌       | 42/165 [00:35<01:44,  1.17it/s]

encode split:  26%|██▌       | 43/165 [00:36<01:42,  1.18it/s]

encode split:  27%|██▋       | 44/165 [00:37<01:42,  1.18it/s]

encode split:  27%|██▋       | 45/165 [00:38<01:41,  1.18it/s]

encode split:  28%|██▊       | 46/165 [00:39<01:40,  1.18it/s]

encode split:  28%|██▊       | 47/165 [00:40<01:39,  1.19it/s]

encode split:  29%|██▉       | 48/165 [00:40<01:39,  1.18it/s]

encode split:  30%|██▉       | 49/165 [00:41<01:40,  1.16it/s]

encode split:  30%|███       | 50/165 [00:42<01:38,  1.17it/s]

encode split:  31%|███       | 51/165 [00:43<01:36,  1.18it/s]

encode split:  32%|███▏      | 52/165 [00:44<01:36,  1.18it/s]

encode split:  32%|███▏      | 53/165 [00:45<01:35,  1.17it/s]

encode split:  33%|███▎      | 54/165 [00:46<01:34,  1.18it/s]

encode split:  33%|███▎      | 55/165 [00:47<01:36,  1.14it/s]

encode split:  34%|███▍      | 56/165 [00:47<01:33,  1.16it/s]

encode split:  35%|███▍      | 57/165 [00:48<01:32,  1.17it/s]

encode split:  35%|███▌      | 58/165 [00:49<01:30,  1.18it/s]

encode split:  36%|███▌      | 59/165 [00:50<01:29,  1.18it/s]

encode split:  36%|███▋      | 60/165 [00:51<01:28,  1.19it/s]

encode split:  37%|███▋      | 61/165 [00:52<01:29,  1.16it/s]

encode split:  38%|███▊      | 62/165 [00:52<01:27,  1.17it/s]

encode split:  38%|███▊      | 63/165 [00:53<01:26,  1.18it/s]

encode split:  39%|███▉      | 64/165 [00:54<01:25,  1.18it/s]

encode split:  39%|███▉      | 65/165 [00:55<01:24,  1.18it/s]

encode split:  40%|████      | 66/165 [00:56<01:23,  1.19it/s]

encode split:  41%|████      | 67/165 [00:57<01:22,  1.19it/s]

encode split:  41%|████      | 68/165 [00:57<01:21,  1.19it/s]

encode split:  42%|████▏     | 69/165 [00:58<01:21,  1.18it/s]

encode split:  42%|████▏     | 70/165 [00:59<01:20,  1.18it/s]

encode split:  43%|████▎     | 71/165 [01:00<01:19,  1.18it/s]

encode split:  44%|████▎     | 72/165 [01:01<01:18,  1.18it/s]

encode split:  44%|████▍     | 73/165 [01:02<01:19,  1.16it/s]

encode split:  45%|████▍     | 74/165 [01:03<01:18,  1.16it/s]

encode split:  45%|████▌     | 75/165 [01:03<01:16,  1.17it/s]

encode split:  46%|████▌     | 76/165 [01:04<01:16,  1.17it/s]

encode split:  47%|████▋     | 77/165 [01:05<01:15,  1.16it/s]

encode split:  47%|████▋     | 78/165 [01:06<01:14,  1.17it/s]

encode split:  48%|████▊     | 79/165 [01:07<01:13,  1.16it/s]

encode split:  48%|████▊     | 80/165 [01:08<01:13,  1.16it/s]

encode split:  49%|████▉     | 81/165 [01:09<01:11,  1.17it/s]

encode split:  50%|████▉     | 82/165 [01:09<01:10,  1.17it/s]

encode split:  50%|█████     | 83/165 [01:10<01:09,  1.17it/s]

encode split:  51%|█████     | 84/165 [01:11<01:08,  1.17it/s]

encode split:  52%|█████▏    | 85/165 [01:12<01:08,  1.17it/s]

encode split:  52%|█████▏    | 86/165 [01:13<01:07,  1.17it/s]

encode split:  53%|█████▎    | 87/165 [01:14<01:06,  1.18it/s]

encode split:  53%|█████▎    | 88/165 [01:15<01:05,  1.17it/s]

encode split:  54%|█████▍    | 89/165 [01:15<01:04,  1.17it/s]

encode split:  55%|█████▍    | 90/165 [01:16<01:03,  1.18it/s]

encode split:  55%|█████▌    | 91/165 [01:17<01:04,  1.15it/s]

encode split:  56%|█████▌    | 92/165 [01:18<01:02,  1.17it/s]

encode split:  56%|█████▋    | 93/165 [01:19<01:01,  1.18it/s]

encode split:  57%|█████▋    | 94/165 [01:20<01:00,  1.18it/s]

encode split:  58%|█████▊    | 95/165 [01:21<00:58,  1.19it/s]

encode split:  58%|█████▊    | 96/165 [01:21<00:58,  1.18it/s]

encode split:  59%|█████▉    | 97/165 [01:22<00:57,  1.18it/s]

encode split:  59%|█████▉    | 98/165 [01:23<00:56,  1.19it/s]

encode split:  60%|██████    | 99/165 [01:24<00:55,  1.19it/s]

encode split:  61%|██████    | 100/165 [01:25<00:54,  1.19it/s]

encode split:  61%|██████    | 101/165 [01:26<00:54,  1.18it/s]

encode split:  62%|██████▏   | 102/165 [01:26<00:53,  1.19it/s]

encode split:  62%|██████▏   | 103/165 [01:27<00:51,  1.20it/s]

encode split:  63%|██████▎   | 104/165 [01:28<00:50,  1.21it/s]

encode split:  64%|██████▎   | 105/165 [01:29<00:49,  1.21it/s]

encode split:  64%|██████▍   | 106/165 [01:30<00:48,  1.21it/s]

encode split:  65%|██████▍   | 107/165 [01:31<00:48,  1.20it/s]

encode split:  65%|██████▌   | 108/165 [01:31<00:47,  1.19it/s]

encode split:  66%|██████▌   | 109/165 [01:32<00:46,  1.20it/s]

encode split:  67%|██████▋   | 110/165 [01:33<00:46,  1.19it/s]

encode split:  67%|██████▋   | 111/165 [01:34<00:45,  1.20it/s]

encode split:  68%|██████▊   | 112/165 [01:35<00:44,  1.19it/s]

encode split:  68%|██████▊   | 113/165 [01:36<00:43,  1.19it/s]

encode split:  69%|██████▉   | 114/165 [01:36<00:42,  1.19it/s]

encode split:  70%|██████▉   | 115/165 [01:37<00:42,  1.19it/s]

encode split:  70%|███████   | 116/165 [01:38<00:41,  1.19it/s]

encode split:  71%|███████   | 117/165 [01:39<00:40,  1.18it/s]

encode split:  72%|███████▏  | 118/165 [01:40<00:39,  1.19it/s]

encode split:  72%|███████▏  | 119/165 [01:41<00:39,  1.18it/s]

encode split:  73%|███████▎  | 120/165 [01:42<00:38,  1.16it/s]

encode split:  73%|███████▎  | 121/165 [01:42<00:37,  1.16it/s]

encode split:  74%|███████▍  | 122/165 [01:43<00:36,  1.18it/s]

encode split:  75%|███████▍  | 123/165 [01:44<00:35,  1.18it/s]

encode split:  75%|███████▌  | 124/165 [01:45<00:34,  1.18it/s]

encode split:  76%|███████▌  | 125/165 [01:46<00:33,  1.18it/s]

encode split:  76%|███████▋  | 126/165 [01:47<00:32,  1.20it/s]

encode split:  77%|███████▋  | 127/165 [01:47<00:31,  1.21it/s]

encode split:  78%|███████▊  | 128/165 [01:48<00:31,  1.16it/s]

encode split:  78%|███████▊  | 129/165 [01:49<00:30,  1.18it/s]

encode split:  79%|███████▉  | 130/165 [01:50<00:29,  1.18it/s]

encode split:  79%|███████▉  | 131/165 [01:51<00:28,  1.18it/s]

encode split:  80%|████████  | 132/165 [01:52<00:28,  1.17it/s]

encode split:  81%|████████  | 133/165 [01:53<00:27,  1.18it/s]

encode split:  81%|████████  | 134/165 [01:53<00:26,  1.19it/s]

encode split:  82%|████████▏ | 135/165 [01:54<00:25,  1.20it/s]

encode split:  82%|████████▏ | 136/165 [01:55<00:24,  1.20it/s]

encode split:  83%|████████▎ | 137/165 [01:56<00:23,  1.21it/s]

encode split:  84%|████████▎ | 138/165 [01:57<00:22,  1.21it/s]

encode split:  84%|████████▍ | 139/165 [01:57<00:21,  1.22it/s]

encode split:  85%|████████▍ | 140/165 [01:58<00:20,  1.22it/s]

encode split:  85%|████████▌ | 141/165 [01:59<00:19,  1.22it/s]

encode split:  86%|████████▌ | 142/165 [02:00<00:18,  1.22it/s]

encode split:  87%|████████▋ | 143/165 [02:01<00:18,  1.21it/s]

encode split:  87%|████████▋ | 144/165 [02:02<00:17,  1.20it/s]

encode split:  88%|████████▊ | 145/165 [02:02<00:16,  1.20it/s]

encode split:  88%|████████▊ | 146/165 [02:03<00:15,  1.21it/s]

encode split:  89%|████████▉ | 147/165 [02:04<00:14,  1.20it/s]

encode split:  90%|████████▉ | 148/165 [02:05<00:14,  1.21it/s]

encode split:  90%|█████████ | 149/165 [02:06<00:13,  1.21it/s]

encode split:  91%|█████████ | 150/165 [02:07<00:12,  1.21it/s]

encode split:  92%|█████████▏| 151/165 [02:07<00:11,  1.21it/s]

encode split:  92%|█████████▏| 152/165 [02:08<00:10,  1.21it/s]

encode split:  93%|█████████▎| 153/165 [02:09<00:09,  1.21it/s]

encode split:  93%|█████████▎| 154/165 [02:10<00:09,  1.21it/s]

encode split:  94%|█████████▍| 155/165 [02:11<00:08,  1.21it/s]

encode split:  95%|█████████▍| 156/165 [02:12<00:07,  1.19it/s]

encode split:  95%|█████████▌| 157/165 [02:12<00:06,  1.20it/s]

encode split:  96%|█████████▌| 158/165 [02:13<00:05,  1.20it/s]

encode split:  96%|█████████▋| 159/165 [02:14<00:05,  1.20it/s]

encode split:  97%|█████████▋| 160/165 [02:15<00:04,  1.19it/s]

encode split:  98%|█████████▊| 161/165 [02:16<00:03,  1.19it/s]

encode split:  98%|█████████▊| 162/165 [02:17<00:02,  1.19it/s]

encode split:  99%|█████████▉| 163/165 [02:17<00:01,  1.19it/s]

encode split:  99%|█████████▉| 164/165 [02:18<00:00,  1.19it/s]

encode split:   0%|          | 0/29 [00:00<?, ?it/s]

encode split:   3%|▎         | 1/29 [00:00<00:25,  1.08it/s]

encode split:   7%|▋         | 2/29 [00:01<00:23,  1.14it/s]

encode split:  10%|█         | 3/29 [00:02<00:22,  1.17it/s]

encode split:  14%|█▍        | 4/29 [00:03<00:21,  1.16it/s]

encode split:  17%|█▋        | 5/29 [00:04<00:20,  1.17it/s]

encode split:  21%|██        | 6/29 [00:05<00:19,  1.19it/s]

encode split:  24%|██▍       | 7/29 [00:05<00:18,  1.20it/s]

encode split:  28%|██▊       | 8/29 [00:06<00:17,  1.20it/s]

encode split:  31%|███       | 9/29 [00:07<00:16,  1.20it/s]

encode split:  34%|███▍      | 10/29 [00:08<00:15,  1.21it/s]

encode split:  38%|███▊      | 11/29 [00:09<00:14,  1.22it/s]

encode split:  41%|████▏     | 12/29 [00:10<00:14,  1.21it/s]

encode split:  45%|████▍     | 13/29 [00:10<00:13,  1.21it/s]

encode split:  48%|████▊     | 14/29 [00:11<00:12,  1.20it/s]

encode split:  52%|█████▏    | 15/29 [00:12<00:11,  1.20it/s]

encode split:  55%|█████▌    | 16/29 [00:13<00:10,  1.20it/s]

encode split:  59%|█████▊    | 17/29 [00:14<00:09,  1.21it/s]

encode split:  62%|██████▏   | 18/29 [00:15<00:09,  1.21it/s]

encode split:  66%|██████▌   | 19/29 [00:15<00:08,  1.21it/s]

encode split:  69%|██████▉   | 20/29 [00:16<00:07,  1.20it/s]

encode split:  72%|███████▏  | 21/29 [00:17<00:06,  1.21it/s]

encode split:  76%|███████▌  | 22/29 [00:18<00:05,  1.21it/s]

encode split:  79%|███████▉  | 23/29 [00:19<00:04,  1.21it/s]

encode split:  83%|████████▎ | 24/29 [00:19<00:04,  1.22it/s]

encode split:  86%|████████▌ | 25/29 [00:20<00:03,  1.22it/s]

encode split:  90%|████████▉ | 26/29 [00:21<00:02,  1.22it/s]

encode split:  93%|█████████▎| 27/29 [00:22<00:01,  1.22it/s]

encode split:  97%|█████████▋| 28/29 [00:23<00:00,  1.20it/s]

encode split: 100%|██████████| 29/29 [00:23<00:00,  1.63it/s]

encode split:   0%|          | 0/38 [00:00<?, ?it/s]

encode split:   3%|▎         | 1/38 [00:00<00:30,  1.21it/s]

encode split:   5%|▌         | 2/38 [00:01<00:29,  1.21it/s]

encode split:   8%|▊         | 3/38 [00:02<00:29,  1.19it/s]

encode split:  11%|█         | 4/38 [00:03<00:28,  1.19it/s]

encode split:  13%|█▎        | 5/38 [00:04<00:27,  1.19it/s]

encode split:  16%|█▌        | 6/38 [00:05<00:26,  1.20it/s]

encode split:  18%|█▊        | 7/38 [00:05<00:25,  1.21it/s]

encode split:  21%|██        | 8/38 [00:06<00:24,  1.22it/s]

encode split:  24%|██▎       | 9/38 [00:07<00:23,  1.22it/s]

encode split:  26%|██▋       | 10/38 [00:08<00:23,  1.18it/s]

encode split:  29%|██▉       | 11/38 [00:09<00:22,  1.19it/s]

encode split:  32%|███▏      | 12/38 [00:10<00:22,  1.18it/s]

encode split:  34%|███▍      | 13/38 [00:10<00:21,  1.19it/s]

encode split:  37%|███▋      | 14/38 [00:11<00:19,  1.20it/s]

encode split:  39%|███▉      | 15/38 [00:12<00:18,  1.21it/s]

encode split:  42%|████▏     | 16/38 [00:13<00:18,  1.22it/s]

encode split:  45%|████▍     | 17/38 [00:14<00:17,  1.22it/s]

encode split:  47%|████▋     | 18/38 [00:14<00:16,  1.23it/s]

encode split:  50%|█████     | 19/38 [00:15<00:15,  1.23it/s]

encode split:  53%|█████▎    | 20/38 [00:16<00:14,  1.23it/s]

encode split:  55%|█████▌    | 21/38 [00:17<00:13,  1.22it/s]

encode split:  58%|█████▊    | 22/38 [00:18<00:13,  1.22it/s]

encode split:  61%|██████    | 23/38 [00:19<00:12,  1.21it/s]

encode split:  63%|██████▎   | 24/38 [00:19<00:11,  1.19it/s]

encode split:  66%|██████▌   | 25/38 [00:20<00:10,  1.19it/s]

encode split:  68%|██████▊   | 26/38 [00:21<00:10,  1.18it/s]

encode split:  71%|███████   | 27/38 [00:22<00:09,  1.18it/s]

encode split:  74%|███████▎  | 28/38 [00:23<00:08,  1.18it/s]

encode split:  76%|███████▋  | 29/38 [00:24<00:07,  1.19it/s]

encode split:  79%|███████▉  | 30/38 [00:24<00:06,  1.19it/s]

encode split:  82%|████████▏ | 31/38 [00:25<00:05,  1.19it/s]

encode split:  84%|████████▍ | 32/38 [00:26<00:05,  1.20it/s]

encode split:  87%|████████▋ | 33/38 [00:27<00:04,  1.20it/s]

encode split:  89%|████████▉ | 34/38 [00:28<00:03,  1.20it/s]

encode split:  92%|█████████▏| 35/38 [00:29<00:02,  1.21it/s]

encode split:  95%|█████████▍| 36/38 [00:29<00:01,  1.20it/s]

encode split:  97%|█████████▋| 37/38 [00:30<00:00,  1.21it/s]

encode split: 100%|██████████| 38/38 [00:31<00:00,  1.42it/s]

encode split:   0%|          | 0/38 [00:00<?, ?it/s]

encode split:   3%|▎         | 1/38 [00:00<00:30,  1.21it/s]

encode split:   5%|▌         | 2/38 [00:01<00:29,  1.21it/s]

encode split:   8%|▊         | 3/38 [00:02<00:28,  1.21it/s]

encode split:  11%|█         | 4/38 [00:03<00:28,  1.21it/s]

encode split:  13%|█▎        | 5/38 [00:04<00:27,  1.21it/s]

encode split:  16%|█▌        | 6/38 [00:04<00:26,  1.21it/s]

encode split:  18%|█▊        | 7/38 [00:05<00:25,  1.21it/s]

encode split:  21%|██        | 8/38 [00:06<00:24,  1.21it/s]

encode split:  24%|██▎       | 9/38 [00:07<00:24,  1.17it/s]

encode split:  26%|██▋       | 10/38 [00:08<00:24,  1.16it/s]

encode split:  29%|██▉       | 11/38 [00:09<00:23,  1.17it/s]

encode split:  32%|███▏      | 12/38 [00:10<00:22,  1.18it/s]

encode split:  34%|███▍      | 13/38 [00:10<00:21,  1.18it/s]

encode split:  37%|███▋      | 14/38 [00:11<00:20,  1.18it/s]

encode split:  39%|███▉      | 15/38 [00:12<00:19,  1.18it/s]

encode split:  42%|████▏     | 16/38 [00:13<00:18,  1.19it/s]

encode split:  45%|████▍     | 17/38 [00:14<00:17,  1.19it/s]

encode split:  47%|████▋     | 18/38 [00:15<00:16,  1.19it/s]

encode split:  50%|█████     | 19/38 [00:15<00:15,  1.19it/s]

encode split:  53%|█████▎    | 20/38 [00:16<00:15,  1.19it/s]

encode split:  55%|█████▌    | 21/38 [00:17<00:14,  1.19it/s]

encode split:  58%|█████▊    | 22/38 [00:18<00:13,  1.17it/s]

encode split:  61%|██████    | 23/38 [00:19<00:12,  1.18it/s]

encode split:  63%|██████▎   | 24/38 [00:20<00:11,  1.18it/s]

encode split:  66%|██████▌   | 25/38 [00:21<00:10,  1.18it/s]

encode split:  68%|██████▊   | 26/38 [00:21<00:10,  1.19it/s]

encode split:  71%|███████   | 27/38 [00:22<00:09,  1.19it/s]

encode split:  74%|███████▎  | 28/38 [00:23<00:08,  1.19it/s]

encode split:  76%|███████▋  | 29/38 [00:24<00:07,  1.19it/s]

encode split:  79%|███████▉  | 30/38 [00:25<00:06,  1.20it/s]

encode split:  82%|████████▏ | 31/38 [00:26<00:05,  1.20it/s]

encode split:  84%|████████▍ | 32/38 [00:26<00:04,  1.21it/s]

encode split:  87%|████████▋ | 33/38 [00:27<00:04,  1.21it/s]

encode split:  89%|████████▉ | 34/38 [00:28<00:03,  1.20it/s]

encode split:  92%|█████████▏| 35/38 [00:29<00:02,  1.20it/s]

encode split:  95%|█████████▍| 36/38 [00:30<00:01,  1.20it/s]

encode split:  97%|█████████▋| 37/38 [00:31<00:00,  1.20it/s]

encode split: 100%|██████████| 38/38 [00:31<00:00,  1.41it/s]

      split target       acc     n
0   id_test  shape  0.838125  4800
1  ood_test  shape  0.777500  4800
2   id_test  scale  0.517083  4800
3  ood_test  scale  0.524375  4800

fixed sweep [id_test]:   0%|          | 0/38 [00:00<?, ?it/s]

fixed sweep [id_test]:   3%|▎         | 1/38 [00:13<08:21, 13.54s/it]

fixed sweep [id_test]:   5%|▌         | 2/38 [00:26<08:00, 13.36s/it]

fixed sweep [id_test]:   8%|▊         | 3/38 [00:40<07:50, 13.43s/it]

fixed sweep [id_test]:  11%|█         | 4/38 [00:53<07:40, 13.54s/it]

fixed sweep [id_test]:  13%|█▎        | 5/38 [01:07<07:26, 13.52s/it]

fixed sweep [id_test]:  16%|█▌        | 6/38 [01:20<07:10, 13.47s/it]

fixed sweep [id_test]:  18%|█▊        | 7/38 [01:34<06:55, 13.42s/it]

fixed sweep [id_test]:  21%|██        | 8/38 [01:47<06:42, 13.41s/it]

fixed sweep [id_test]:  24%|██▎       | 9/38 [02:01<06:29, 13.43s/it]

fixed sweep [id_test]:  26%|██▋       | 10/38 [02:14<06:16, 13.43s/it]

fixed sweep [id_test]:  29%|██▉       | 11/38 [02:27<06:01, 13.40s/it]

fixed sweep [id_test]:  32%|███▏      | 12/38 [02:40<05:46, 13.33s/it]

fixed sweep [id_test]:  34%|███▍      | 13/38 [02:54<05:33, 13.33s/it]

fixed sweep [id_test]:  37%|███▋      | 14/38 [03:07<05:18, 13.29s/it]

fixed sweep [id_test]:  39%|███▉      | 15/38 [03:20<05:05, 13.28s/it]

fixed sweep [id_test]:  42%|████▏     | 16/38 [03:34<04:53, 13.33s/it]

fixed sweep [id_test]:  45%|████▍     | 17/38 [03:47<04:39, 13.30s/it]

fixed sweep [id_test]:  47%|████▋     | 18/38 [04:00<04:25, 13.26s/it]

fixed sweep [id_test]:  50%|█████     | 19/38 [04:13<04:11, 13.26s/it]

fixed sweep [id_test]:  53%|█████▎    | 20/38 [04:27<03:58, 13.24s/it]

fixed sweep [id_test]:  55%|█████▌    | 21/38 [04:40<03:44, 13.22s/it]

fixed sweep [id_test]:  58%|█████▊    | 22/38 [04:53<03:32, 13.26s/it]

fixed sweep [id_test]:  61%|██████    | 23/38 [05:06<03:18, 13.26s/it]

fixed sweep [id_test]:  63%|██████▎   | 24/38 [05:19<03:05, 13.23s/it]

fixed sweep [id_test]:  66%|██████▌   | 25/38 [05:33<02:52, 13.26s/it]

fixed sweep [id_test]:  68%|██████▊   | 26/38 [05:46<02:38, 13.24s/it]

fixed sweep [id_test]:  71%|███████   | 27/38 [05:59<02:25, 13.21s/it]

fixed sweep [id_test]:  74%|███████▎  | 28/38 [06:13<02:12, 13.26s/it]

fixed sweep [id_test]:  76%|███████▋  | 29/38 [06:26<01:59, 13.25s/it]

fixed sweep [id_test]:  79%|███████▉  | 30/38 [06:39<01:46, 13.37s/it]

fixed sweep [id_test]:  82%|████████▏ | 31/38 [06:53<01:34, 13.46s/it]

fixed sweep [id_test]:  84%|████████▍ | 32/38 [07:06<01:20, 13.42s/it]

fixed sweep [id_test]:  87%|████████▋ | 33/38 [07:20<01:06, 13.36s/it]

fixed sweep [id_test]:  89%|████████▉ | 34/38 [07:33<00:53, 13.37s/it]

fixed sweep [id_test]:  92%|█████████▏| 35/38 [07:46<00:40, 13.40s/it]

fixed sweep [id_test]:  95%|█████████▍| 36/38 [08:00<00:26, 13.40s/it]

fixed sweep [id_test]:  97%|█████████▋| 37/38 [08:13<00:13, 13.39s/it]

fixed sweep [id_test]: 100%|██████████| 38/38 [08:20<00:00, 11.40s/it]

fixed sweep [ood_test]:   0%|          | 0/38 [00:00<?, ?it/s]

fixed sweep [ood_test]:   3%|▎         | 1/38 [00:13<08:07, 13.18s/it]

fixed sweep [ood_test]:   5%|▌         | 2/38 [00:26<07:55, 13.21s/it]

fixed sweep [ood_test]:   8%|▊         | 3/38 [00:39<07:41, 13.18s/it]

fixed sweep [ood_test]:  11%|█         | 4/38 [00:52<07:29, 13.21s/it]

fixed sweep [ood_test]:  13%|█▎        | 5/38 [01:06<07:18, 13.29s/it]

fixed sweep [ood_test]:  16%|█▌        | 6/38 [01:19<07:04, 13.26s/it]

fixed sweep [ood_test]:  18%|█▊        | 7/38 [01:32<06:51, 13.26s/it]

fixed sweep [ood_test]:  21%|██        | 8/38 [01:46<06:38, 13.30s/it]

fixed sweep [ood_test]:  24%|██▎       | 9/38 [01:59<06:24, 13.27s/it]

fixed sweep [ood_test]:  26%|██▋       | 10/38 [02:12<06:11, 13.28s/it]

fixed sweep [ood_test]:  29%|██▉       | 11/38 [02:26<06:01, 13.38s/it]

fixed sweep [ood_test]:  32%|███▏      | 12/38 [02:39<05:46, 13.31s/it]

fixed sweep [ood_test]:  34%|███▍      | 13/38 [02:52<05:32, 13.31s/it]

fixed sweep [ood_test]:  37%|███▋      | 14/38 [03:06<05:20, 13.37s/it]

fixed sweep [ood_test]:  39%|███▉      | 15/38 [03:19<05:07, 13.37s/it]

fixed sweep [ood_test]:  42%|████▏     | 16/38 [03:33<04:55, 13.42s/it]

fixed sweep [ood_test]:  45%|████▍     | 17/38 [03:46<04:42, 13.43s/it]

fixed sweep [ood_test]:  47%|████▋     | 18/38 [03:59<04:28, 13.43s/it]

fixed sweep [ood_test]:  50%|█████     | 19/38 [04:13<04:13, 13.35s/it]

fixed sweep [ood_test]:  53%|█████▎    | 20/38 [04:26<04:00, 13.38s/it]

fixed sweep [ood_test]:  55%|█████▌    | 21/38 [04:40<03:48, 13.45s/it]

fixed sweep [ood_test]:  58%|█████▊    | 22/38 [04:53<03:35, 13.44s/it]

fixed sweep [ood_test]:  61%|██████    | 23/38 [05:07<03:21, 13.46s/it]

fixed sweep [ood_test]:  63%|██████▎   | 24/38 [05:20<03:08, 13.49s/it]

fixed sweep [ood_test]:  66%|██████▌   | 25/38 [05:34<02:55, 13.49s/it]

fixed sweep [ood_test]:  68%|██████▊   | 26/38 [05:47<02:42, 13.52s/it]

fixed sweep [ood_test]:  71%|███████   | 27/38 [06:01<02:27, 13.45s/it]

fixed sweep [ood_test]:  74%|███████▎  | 28/38 [06:14<02:13, 13.35s/it]

fixed sweep [ood_test]:  76%|███████▋  | 29/38 [06:27<02:00, 13.39s/it]

fixed sweep [ood_test]:  79%|███████▉  | 30/38 [06:41<01:47, 13.40s/it]

fixed sweep [ood_test]:  82%|████████▏ | 31/38 [06:54<01:33, 13.34s/it]

fixed sweep [ood_test]:  84%|████████▍ | 32/38 [07:07<01:20, 13.34s/it]

fixed sweep [ood_test]:  87%|████████▋ | 33/38 [07:20<01:06, 13.26s/it]

fixed sweep [ood_test]:  89%|████████▉ | 34/38 [07:34<00:53, 13.30s/it]

fixed sweep [ood_test]:  92%|█████████▏| 35/38 [07:47<00:39, 13.32s/it]

fixed sweep [ood_test]:  95%|█████████▍| 36/38 [08:00<00:26, 13.25s/it]

fixed sweep [ood_test]:  97%|█████████▋| 37/38 [08:13<00:13, 13.22s/it]

fixed sweep [ood_test]: 100%|██████████| 38/38 [08:20<00:00, 11.28s/it]

auto alpha [id_test]:   0%|          | 0/38 [00:00<?, ?it/s]

auto alpha [id_test]:   3%|▎         | 1/38 [00:32<19:47, 32.10s/it]

auto alpha [id_test]:   5%|▌         | 2/38 [01:04<19:13, 32.04s/it]

auto alpha [id_test]:   8%|▊         | 3/38 [01:36<18:40, 32.00s/it]

auto alpha [id_test]:  11%|█         | 4/38 [02:08<18:07, 32.00s/it]

auto alpha [id_test]:  13%|█▎        | 5/38 [02:39<17:30, 31.83s/it]

auto alpha [id_test]:  16%|█▌        | 6/38 [03:11<16:56, 31.76s/it]

auto alpha [id_test]:  18%|█▊        | 7/38 [03:42<16:24, 31.77s/it]

auto alpha [id_test]:  21%|██        | 8/38 [04:14<15:51, 31.71s/it]

auto alpha [id_test]:  24%|██▎       | 9/38 [04:46<15:17, 31.62s/it]

auto alpha [id_test]:  26%|██▋       | 10/38 [05:17<14:45, 31.61s/it]

auto alpha [id_test]:  29%|██▉       | 11/38 [05:49<14:14, 31.63s/it]

auto alpha [id_test]:  32%|███▏      | 12/38 [06:21<13:44, 31.71s/it]

auto alpha [id_test]:  34%|███▍      | 13/38 [06:52<13:13, 31.74s/it]

auto alpha [id_test]:  37%|███▋      | 14/38 [07:25<12:45, 31.91s/it]

auto alpha [id_test]:  39%|███▉      | 15/38 [07:56<12:11, 31.80s/it]

auto alpha [id_test]:  42%|████▏     | 16/38 [08:28<11:41, 31.88s/it]

auto alpha [id_test]:  45%|████▍     | 17/38 [09:01<11:13, 32.08s/it]

auto alpha [id_test]:  47%|████▋     | 18/38 [09:33<10:40, 32.03s/it]

auto alpha [id_test]:  50%|█████     | 19/38 [10:05<10:07, 32.00s/it]

auto alpha [id_test]:  53%|█████▎    | 20/38 [10:37<09:35, 31.99s/it]

auto alpha [id_test]:  55%|█████▌    | 21/38 [11:09<09:03, 31.99s/it]

auto alpha [id_test]:  58%|█████▊    | 22/38 [11:41<08:33, 32.07s/it]

auto alpha [id_test]:  61%|██████    | 23/38 [12:13<08:00, 32.01s/it]

auto alpha [id_test]:  63%|██████▎   | 24/38 [12:45<07:28, 32.01s/it]

auto alpha [id_test]:  66%|██████▌   | 25/38 [13:17<06:55, 31.98s/it]

auto alpha [id_test]:  68%|██████▊   | 26/38 [13:48<06:22, 31.89s/it]

auto alpha [id_test]:  71%|███████   | 27/38 [14:20<05:50, 31.89s/it]

auto alpha [id_test]:  74%|███████▎  | 28/38 [14:53<05:19, 31.98s/it]

auto alpha [id_test]:  76%|███████▋  | 29/38 [15:25<04:48, 32.04s/it]

In [ ]:
# quick preview of saved plots
plot_dir = Path(result["run_dir"]) / "plots"
for name in [
    "vae_curves.png",
    "head_curves.png",
    "fixed_tradeoff.png",
    "auto_tradeoff.png",
    "auto_alpha_hist.png",
    "preview_id.png",
    "preview_ood.png",
]:
    p = plot_dir / name
    if p.exists():
        print(name)
        display(Image(filename=str(p)))

In [ ]:
!zip -r output.zip /kaggle/working

So the VAE maybe not good at the encoding, but the steering is nice I think